### ISSUE TITLE
unable to connect localhost:8086 using influxdb 1.2.0

### ISSUE THREAD

**Issue by raghuvinayak** [influxdata/docs.influxdata.com#1000]

**Comment by 3fr61n** [comment]
Hi @raghuvinayak 

URL for relevant page?

--->  localhost:8086 is the default port for influxdb API, check this link and try some of the curl examples to that url

https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/

What products and version are you using?

---> We are using INFLUXDB_VERSION 1.0.2,  

Where did you look before opening the issue?

---> I'm sorry but not sure what you're trying to say

regards

**Comment by rkuchan** [comment]
@raghuvinayak, could you provide a little more context? We try to reserve this repo for docs-specific issue. I'm closing this for now but please feel free to re-open it if there is a docs issue!
