### ISSUE TITLE
Clarify "a point is the field set in the same series with the same timestamp."

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#1001]
At https://docs.influxdata.com/influxdb/v1.2/concepts/key_concepts/#point, what does "same" refer to in

> "Finally, a point is the field set in the same series with the same timestamp."

["fieldset"](https://docs.influxdata.com/influxdb/v1.2/concepts/key_concepts/#field-set) is defined beforehand as 

> the collection of field-key and field-value pairs make up a field set.

No mention of "the same timestamp" here. Can a field set come from two different "rows"? (apologies for the SQL terminology). If not, then even if pedantic, it might be be worth mentioning "with the same timestamp" since we're explaining concepts that many coming from the SQL words may have trouble adjusting to.

Finally, a note about the Key Concepts page overall: I've been using Influx for a while now, and "series" vs. "measurement" still doesn't come as an easy distinction. Also, even the author of the only sanctioned Node library had [trouble confusing the two!](https://github.com/node-influx/node-influx/pull/205). I'd love to see these concepts explained in a different way that might stick better.

**Comment by 3fr61n** [comment]
I'm totally agree that both terms (series/measurement) are usually used indifferently,  I'm not sure if this is deliberate or not, and I would like to know what influx team thinks about it.
