### ISSUE TITLE
Escaping backslash[present at the end] character  in field values which are string type

### ISSUE THREAD

**Issue by pushparajxa** [influxdata/docs.influxdata.com#1013]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/

###### What products and version are you using?
InfluxDB 1.0.2

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_tutorial/

<img width="976" alt="screen shot 2017-02-13 at 13 27 01" src="https://cloud.githubusercontent.com/assets/6145185/22883350/2910cbc6-f1f0-11e6-8c37-9ae65cb95ded.png">

If the field value is a string and ends with backslash then that backslash needs to be escaped otherwise influxdb thinks that it is escaping " [double-quote] character. 
 
For ex: 

No need to escape if backslash character is in the middle of the string

weather,location=us-midwest temperature="to\ee" 1465839830100400200

If backslash character is at the end of the string, as per present documentation we don't have to escape so it will look like below..

weather,location=us-midwest temperature="hello\\" 1465839830100400200

which fails at writing to InfluxDB by saying exception as incomplete quote. 

In those cases the backslash character at the end of the string needs to be escaped like below

weather,location=us-midwest temperature="hello\\\\" 1465839830100400200

**Comment by kelseiv** [comment]
Thank you, @pushparajxa! We've updated the [line protocol reference documentation](https://github.com/influxdata/docs.influxdata.com/commit/5943b51ff8e032054b2d781b77ab712c1b1bb86c) to reflect the escape backslash behavior.
