### ISSUE TITLE
Download links of Chronograph, InfluxDB and Kapacitor products are faulty.

### ISSUE THREAD

**Issue by FilotasSiskos** [influxdata/docs.influxdata.com#1014]
###### URL for relevant page?
https://portal.influxdata.com/downloads

**Problem Description:**
All download links are faulty for Chronograph, InfluxDB and Kapacitor products (but not Telegraf) and result in a 404 Not Found.

**Faulty Example:**
wget https://dl.influxdata.com/telegraf/releases/influxdb_1.2.0_amd64.deb

All product links are prefixed with the telegraf url which results into all download links for all other products being faulty except for the telegraf.

**Example Solution:**
Convert
wget https://dl.influxdata.com/telegraf/releases/influxdb_1.2.0_amd64.deb
To
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.2.0_amd64.deb
Probably by introducing a variable in the docs dependent on the product the user selected.

**Comment by kostasb** [comment]
@FilotasSiskos , thanks for reporting this.

We've very recently made some changes to our downloads page, due to which this bug was introduced. At the moment download links for all products refer to the telegraf uri.
The appropriate team has been notified and will resolve the issue as soon as possible.

**Comment by rkuchan** [comment]
@FilotasSiskos, thank you for letting us know. We're working on getting this fixed. This isn't handled by this repo but I'll keep this issue open until it gets fixed. 

For now, it looks like you were able to get around the issue. Were you able to get the download you needed?

For anyone else who is seeing this, here are the Ubuntu `.deb` packages for v1.2.0 of the products:

* InfluxDB
```
wget https://dl.influxdata.com/influxdb/releases/influxdb_1.2.0_amd64.deb
sudo dpkg -i influxdb_1.2.0_amd64.deb
```

* Kapacitor
```
wget https://dl.influxdata.com/kapacitor/releases/kapacitor_1.2.0_amd64.deb
sudo dpkg -i kapacitor_1.2.0_amd64.deb
```

* Telegraf
```
wget https://dl.influxdata.com/telegraf/releases/telegraf_1.2.0_amd64.deb
sudo dpkg -i telegraf_1.2.0_amd64.deb
```

* Chronograf
```
wget https://dl.influxdata.com/chronograf/releases/chronograf_1.2.0~beta2_amd64.deb
sudo dpkg -i chronograf_1.2.0~beta2_amd64.deb
```

**Comment by phemmer** [comment]
See also https://github.com/influxdata/influxdb/issues/7994 & https://github.com/influxdata/influxdb/issues/7993

**Comment by rkuchan** [comment]
OK! The download page now yields the proper links. Again, thank you for letting us know and we apologize for the confusion.
