### ISSUE TITLE
chronograf not showing any data in dashboad

### ISSUE THREAD

**Issue by kumar2000s** [influxdata/docs.influxdata.com#1024]
Hi 
I have setup the chronograf but not showing any data in dashboad
i can see the below in logs

INFO[2714] Request                                       component=server method=POST remote_addr=xx.xx.xx.xxx:62683 url=/chronograf/v1/sources/2/proxy
INFO[2714] Request                                       component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/chronograf/v1/mappings
INFO[2716] Request                                       component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/chronograf/v1/sources/2/kapacitors
INFO[2718] Request                                       component=server method=GET remote_addr=xx.xx.xx.xxx:62683 url=/chronograf/v1/mappings
INFO[2718] Request                                       component=server method=POST remote_addr=xx.xx.xx.xxx:62684 url=/chronograf/v1/sources/2/proxy
INFO[2718] Request                                       component=server method=POST remote_addr=xx.xx.xx.xxx:62682 url=/chronograf/v1/sources/2/proxy
INFO[2771] Request                                       component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/sources/2/hosts
INFO[2771] Serving assets                                component=server method=GET remote_addr=xx.xx.xx.xxx:62684 url=/sources/2/hosts
![chronograph](https://cloud.githubusercontent.com/assets/12763366/22975040/1b94609a-f3ab-11e6-80cf-0faf2a6bc8f9.PNG)

**Comment by rkuchan** [comment]
@kumar2000s, we generally try to reserve this repo for docs-specific issues. If it's not too much trouble would you mind opening this issue on the [Chronograf](https://github.com/influxdata/chronograf/issues/new) repo? I know someone will be able to help you out there!
