### ISSUE TITLE
[Enterprise] 1.2 configuration: retention-autocreate no longer used on meta nodes

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#1028]
The [current 1.2 configuration page](https://docs.influxdata.com/enterprise/v1.2/administration/configuration/) explains the `meta.retention-autocreate` section for meta node configuration, but that configuration is no longer used on meta nodes as of 1.2.

**Comment by rkuchan** [comment]
Thank you, @mark-rushakoff. I'd completely misread the changelog for that update.
