### ISSUE TITLE
docs do not show up on mobile (iphone / iOS / Chrome version 47.0.2526.70)

### ISSUE THREAD

**Issue by timschaaf** [influxdata/docs.influxdata.com#103]
iphone 6 / iOS / Chrome version 47.0.2526.70

When browsing in Chrome to docs (eg. https://docs.influxdata.com/influxdb/v0.9/introduction/overview/) returns a white screen / unable to navigate or view content.

**Comment by rkuchan** [comment]
We're having trouble reproducing the issue. Are you running any ad blockers?

**Comment by timschaaf** [comment]
Negative.

**Comment by beckettsean** [comment]
Cannot repro, not sure what to try and fix without a repro case.
