### ISSUE TITLE
[Kapacitor] Link Kapacitor's HoltWinters docs to InfluxDB's HoltWinters docs

### ISSUE THREAD

**Issue by Finkregh** [influxdata/docs.influxdata.com#1039]
###### URL for relevant page?
Everywhere describing holtWinters.

###### What products and version are you using?
Kapacitor, v1.2

###### Where did you look before opening the issue?
e.g. https://docs.influxdata.com/kapacitor/v1.0/nodes/influx_q_l_node/#holtwinters
https://github.com/influxdata/kapacitor/pull/606/files , but i am not fluent enough in go to understand what exactly is going on.

###### additional info
The documentation does not explain what the arguments the funktion uses do. There is an example in the CHANGELOG.md, which does only explain what timeframe is used for the forecast.

**Comment by rkuchan** [comment]
Hi @Finkregh, we describe the `HOLT_WINTERS()` and `HOLT_WINTERS_WITH_FIT()` functions in the InfluxDB documentation: https://docs.influxdata.com/influxdb/v1.2/query_language/functions/#holt-winters. Is that the information that you were looking for?

I agree that it's not obvious where to find the more detailed HoltWinters documentation in the Kapacitor docs. I'll keep this issue open until I can link the Kapacitor docs to that InfluxDB page.

**Comment by Finkregh** [comment]
oh my. i was really wondering as the rest of your documentation is really good.

Thanks!
