### ISSUE TITLE
Landing page CSS is broken for wide displays, hiding Enterprise section

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#1044]
###### URL for relevant page?

https://docs.influxdata.com/

On a "narrow" display all 6 items are visible:

![screen shot 2017-03-02 at 3 37 24 pm](https://cloud.githubusercontent.com/assets/290647/23532059/5932173a-ff5e-11e6-9b41-af1d31c51f3d.png)

On a "wide" display, Enterprise isn't visible, and it isn't particularly obvious that you have to scroll down to see it:

![screen shot 2017-03-02 at 3 37 49 pm](https://cloud.githubusercontent.com/assets/290647/23532075/6d3d5f1e-ff5e-11e6-82ce-ba9565a54cd7.png)

**Comment by rkuchan** [comment]
@alexpaxton - if you have a moment could you check this one out? I've added products to that page and I've disrupted the peace.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/1072
