### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bradclawsie** [influxdata/docs.influxdata.com#1045]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.2/introduction/getting_started/

"Conceptually you can think of a measurement as **an** SQL table"

(boldfaced from me to indicate error) should be 

"Conceptually you can think of a measurement as a SQL table"

**Comment by mark-rushakoff** [comment]
"An *ess queue ell* table" is grammatically correct. So is "a *sequel* table". I've read that the ISO and ANSI standards say it's pronounced *ess queue ell* in spite of many people pronouncing it *sequel*. I suppose this comes down to author preference.
