### ISSUE TITLE
Missing C in curl command 

### ISSUE THREAD

**Issue by Kaauw** [influxdata/docs.influxdata.com#1053]
Hi,

A 'C' is missing in Curl command for /ping section
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.2/troubleshooting/frequently-asked-questions/#how-can-i-identify-my-version-of-influxdb
###### What products and version are you using?
No need
###### Where did you look before opening the issue?
Some keyworkd in issues section link "missing" and "curl"

Problem : 
```
$ url -i 'http://localhost:8086/ping'

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 1e08aeb6-fec0-11e6-8486-000000000000
✨ X-Influxdb-Version: 1.2.0 ✨
Date: Wed, 01 Mar 2017 20:46:17 GMT
```

Should be 
```
$ curl -i 'http://localhost:8086/ping'

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 1e08aeb6-fec0-11e6-8486-000000000000
✨ X-Influxdb-Version: 1.2.0 ✨
Date: Wed, 01 Mar 2017 20:46:17 GMT
```

**Comment by timhallinflux** [comment]
Thanks @Kaauw -- fixed.
