### ISSUE TITLE
Warn users regarding passwords with shell special characters

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#1054]
When specifying a password from the CLI, for example:

```
influx -username myuser -password mypassword ...
```

We should warn users that if their password contains any special characters, their shell might attempt to inject variables into the password. For example:

```
influx -username myuser -password my$password ...
```

Will send the password as `my`. To fix, all passwords should be wrapped in single quotes:

```
influx -username myuser -password 'my$password' ...
```

**Comment by timhallinflux** [comment]
This should be expanded to include things like -- not using a <period> as part of the database name.  <periods> are used as a delimiter between database name and retention policy.
