### ISSUE TITLE
[InfluxDB] Document single and multiline comments

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1058]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/8062

###### What products and version are you using?
InfluxDB

**Comment by rkuchan** [comment]
Add a section about comments to the spec. Need help on the EBNF formatting.

Comments in InfluxQL

Use comments with InfluxQL statements to describe your queries.

* A single line comment begins with two hyphens (`--`) and ends where InfluxDB detects a line break. This comment type cannot span several lines.
* A multi-line comment begins with `/*` and ends with `*/`.
This comment type can span several lines.
Multi-line comments do not support nested multi-line comments.

**Comment by jsternberg** [comment]
I think, for the most part, you can avoid EBNF formatting for this. Comments are usually kept out of the parser and are removed before it ever gets there just like whitespace is ignored in the EBNF.

**Comment by rkuchan** [comment]
Thanks, @jsternberg! Would it be incorrect to add a `Comments` section to the spec or do you think that placement would be OK?

**Comment by jsternberg** [comment]
Hm... It might be worth adding it to the spec. At the very least (and maybe most), a section just describing the comments is probably all that's needed. For example, I don't see any specification of comments in the official Python grammar: https://docs.python.org/3/reference/grammar.html

I don't know where they mention it (I only looked for a total of 10 seconds), but it doesn't seem to be in the EBNF grammar.
