### ISSUE TITLE
influxdb-1.2.2.x86_64.rpm checksum verification fails

### ISSUE THREAD

**Issue by gsauthof** [influxdata/docs.influxdata.com#1059]
The download page https://portal.influxdata.com/downloads#influxdb currently lists the following MD5 checksum for the RedHat/CentOS rpm:

> RedHat & CentOS
> MD5: 78548b815f30dcb8c87e2c67f2b9b330
> wget https://dl.influxdata.com/influxdb/releases/influxdb-1.2.2.x86_64.rpm
> sudo yum localinstall influxdb-1.2.2.x86_64.rpm

This doesn't match the checksum of the downloaded file:

    $ curl -O https://dl.influxdata.com/influxdb/releases/influxdb-1.2.2.x86_64.rpm
    $ md5sum influxdb-1.2.2.x86_64.rpm 
    4d60a04055cb7a6780591f2a929f3283  influxdb-1.2.2.x86_64.rpm
    $ file influxdb-1.2.2.x86_64.rpm 
    influxdb-1.2.2.x86_64.rpm: RPM v3.0 bin i386/x86_64 influxdb-1.2.2-1

Btw, perhaps you also want to consider using something more state-of-the-art than MD5, e.g. SHA-256.

###### URL for relevant page?

https://portal.influxdata.com/downloads#influxdb

###### Where did you look before opening the issue?

Google

**Comment by rkuchan** [comment]
The issue has been fixed and the correct MD5s are now on the downloads page. Thank you again, @gsauthof for pointing this out. Sincerest apologies for the inconvenience this caused.
