### ISSUE TITLE
No Documentation for influx_stress or influx_tsm

### ISSUE THREAD

**Issue by dp1140a** [influxdata/docs.influxdata.com#1061]
###### URL for relevant page?
Unknown

###### What products and version are you using?
InfluxDb 1.2

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.2/tools/

There does not seem to be any documentation for influx_stress or influx_tsm commands

**Comment by stevebang** [comment]
The README for this tool is here https://github.com/influxdata/influx-stress/blob/master/README.md

**Comment by kelseiv** [comment]
We recommended using the inch tool for performance testing. [Doc for the inch tool ](https://github.com/influxdata/docs.influxdata.com/pull/2484) addresses this issue.
