### ISSUE TITLE
Add sha256 checksums for Enterprise package downloads

### ISSUE THREAD

**Issue by kostasb** [influxdata/docs.influxdata.com#1063]
We should add sha256 checksums for the meta and data packages wherever there are download links.

Enterprise specific, since these download links do not appear in the downloads page

E.g. 

```
root@ubuntu16:~# sha256sum influxdb-data_1.2.1-c1.2.2_amd64.deb 
86fb3fde585d67f8039c743a52a4fee765e0b2300341bdea76768c4539232264  influxdb-data_1.2.1-c1.2.2_amd64.deb
```

**Comment by phemmer** [comment]
Just curious, why? What's wrong with the current md5?

**Comment by kostasb** [comment]
@phemmer This is a request from a customer for the closed source packages.
