### ISSUE TITLE
New Doc Request -- Telegraf Kafka Consumer Plugin

### ISSUE THREAD

**Issue by dp1140a** [influxdata/docs.influxdata.com#1065]
Need documentation added for the Kafka Consumer Plugin.  There are docs for the output plugin but not the input plugin.

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kafka_consumer

**Comment by timhallinflux** [comment]
Doc for this is linked under the Service Inputs
see: 
<img width="1212" alt="screen shot 2017-09-12 at 12 13 45 am" src="https://user-images.githubusercontent.com/23535264/30285051-68e7d6b8-974f-11e7-9c19-b38d1d67f8d2.png">

Is this sufficient?

**Comment by dp1140a** [comment]
Perfect thank you.
