### ISSUE TITLE
[Enterprise InfluxDB] Document default config locations for influxd-meta

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1071]
###### What products and version are you using?
Will be introduced in influxd-meta 1.3.

The influxd-meta binary, if no configuration is specified, will check the `INFLUXDB_META_CONFIG_PATH`. If that environment variable is set, the path will be used as the configuration file. If unset, the binary will check the `~/.influxdb` and `/etc/influxdb` folder for an `influxdb-meta.conf` file. If it finds that file at either of the two locations, the first will be loaded as the configuration file automatically.

This matches a similar behavior that the open source and data node versions of InfluxDB already follow.

**Comment by rkuchan** [comment]
Add content to the `administration/configuration` page.

**Comment by timhallinflux** [comment]
done
