### ISSUE TITLE
[InfluxDB] Document INTEGRAL() aggregate function

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1076]
###### URL for relevant page?
influxdata/influxdb#8194

###### What products and version are you using?
InfluxDB 1.3

Description of the function is in the pull request.

**Comment by rkuchan** [comment]
* [ ] Add `INTEGRAL()` to the aggregations list
* [ ] Update the `INTEGRAL()` section with content:

## INTEGRAL()

Returns the area under the curve of [field values](link).

### Syntax

```
TK
```

No `fill()`.

### Description of Syntax

TK

### Examples

TK
