### ISSUE TITLE
if RPs=30m,how can i get data that before 1h or 1d's, is there some configuration about this?

### ISSUE THREAD

**Issue by hanjiabao** [influxdata/docs.influxdata.com#1078]

**Comment by timhallinflux** [comment]
@hanjiabao -- can you please explain this in more detail?  I have no idea what the subject line means.  

If you setup a retention policy of 30m -- that means the data will be dropped after 30m.  If you want to retain the data beyond 30m --- potentially at a lower precision, you use downsampling and write the less precise data into another retention policy.  https://docs.influxdata.com/influxdb/v1.3/query_language/continuous_queries/#downsampling-and-data-retention

A 30m retention policy is extraordinarily short -- I would advise against setting this up "tight" a window for your data.

**Comment by timhallinflux** [comment]
@hanjiabao -- any feedback?  otherwise, I'm going to close this issue.
