### ISSUE TITLE
Warnings should be added to 'remove-data', 'remove-meta', and 'leave' commands to clarify they are destructive

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#1081]
These commands are destructive, though it doesn't quite come across. I think we should add warnings around each section with a notice:

> **NOTE**: This command is destructive, and is only meant for _permanently_ removing nodes from a cluster. All data on the instance will be erased when removed from a cluster.

###### URL for relevant page?

https://docs.influxdata.com/enterprise/v1.2/features/cluster-commands/#remove-data
https://docs.influxdata.com/enterprise/v1.2/features/cluster-commands/#remove-meta
https://docs.influxdata.com/enterprise/v1.2/features/cluster-commands/#leave

###### What products and version are you using?

InfluxEnterprise, all versions.

**Comment by rkuchan** [comment]
@rossmcdonald - does this apply to `leave` as well?

**Comment by rossmcdonald** [comment]
@rkuchan Yes it does. I just updated the issue to reflect that.

**Comment by rkuchan** [comment]
Thanks, @rossmcdonald. All updated.
