### ISSUE TITLE
A bug with performing math functions? 

### ISSUE THREAD

**Issue by zmcpherson** [influxdata/docs.influxdata.com#1083]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.2/query_language/math_operators/

###### What products and version are you using?
4.1.1

###### Where did you look before opening the issue?
Across the web

I am seeing some weird behavior when trying to use the math function with influx/grafana, I'm curious if it's by design (in which case, how do I do it correctly) or if it's a bug.

So I am trying to do some math functions in a single stat panel - I have 3 queries like so.

![snip20170330_1](https://cloud.githubusercontent.com/assets/14893745/24529165/ffca5966-155e-11e7-8ac9-b71546a45f6e.png)
![snip20170330_3](https://cloud.githubusercontent.com/assets/14893745/24529168/04ff346a-155f-11e7-951e-d5b6ca82144c.png)
![snip20170330_5](https://cloud.githubusercontent.com/assets/14893745/24529171/0710174c-155f-11e7-8c2e-e213818f027f.png)

From what I was reading in the documentation,

`SELECT "A" + "B" From "add"` should return 36 (24+12)

But even weirder is when I do this - 

![snip20170330_6](https://cloud.githubusercontent.com/assets/14893745/24529505/e6a27962-1560-11e7-9e1e-2dbd34957f43.png)

I would expect this to be 34 (24 + 10)

Here is another example -

![snip20170330_7](https://cloud.githubusercontent.com/assets/14893745/24529560/302381bc-1561-11e7-9a2d-9ea036f70d64.png)

The expected result should be 22 (24 - 2) 

So is this expected behavior and or what am I doing wrong?

Thank you

**Comment by zmcpherson** [comment]
I just tried upgrading to Grafana v4.3.0-pre1 (commit: 6e304e6) and the issue still persists

**Comment by zmcpherson** [comment]
A few more examples of the weird math instances -

Here is 24/10 (which works)

![snip20170330_9](https://cloud.githubusercontent.com/assets/14893745/24530072/6c443d78-1564-11e7-96b8-a7d5e119df4f.png)

Here is 24 - 10 (which is a completely different calculation than the first post)

![snip20170330_11](https://cloud.githubusercontent.com/assets/14893745/24530085/811ad2c0-1564-11e7-8e55-720c612762c4.png)

Here is 24 - 100 

![snip20170330_12](https://cloud.githubusercontent.com/assets/14893745/24530097/8fed1d9e-1564-11e7-8482-4a579d221b22.png)

And here is 24 +100 

![snip20170330_13](https://cloud.githubusercontent.com/assets/14893745/24530105/98e52e64-1564-11e7-80e5-f33e01720d4d.png)

**Comment by zmcpherson** [comment]
Just realized I posted to influx instead of grafana.... it's been a long day....

**Comment by rkuchan** [comment]
No problem @zmcpherson, hope you get your answer!
