### ISSUE TITLE
Links broken for InfluxDB Nightly builds

### ISSUE THREAD

**Issue by weanjo** [influxdata/docs.influxdata.com#1087]
Only the Ubuntu & Debian link is working, the other links are broken.

The solution is to replace **releases** with **nightlies** in the Url.
This link works
https://dl.influxdata.com/influxdb/nightlies/influxdb-nightly_linux_armhf.tar.gz

This doesn't
https://dl.influxdata.com/influxdb/releases/influxdb-nightly_linux_armhf.tar.gz
###### URL for relevant page?
https://portal.influxdata.com/downloads (select InfluxDB Nightly)

###### Where did you look before opening the issue?
here

**Comment by rkuchan** [comment]
Thank you for pointing this out, @weanjo. I've notified the website team and they're working on getting it fixed. We apologize for the inconvenience!! I'll keep this open until the issue is resolved.

**Comment by rkuchan** [comment]
Fixed! Thank you again for letting us know.
