### ISSUE TITLE
[InfluxDB] Make mention that top() and bottom() cannot be used with other functions

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1091]
###### URL for relevant page?
influxdata/influxdb#8253

###### What products and version are you using?
InfluxDB 1.3

We're formally restricting `top()` and `bottom()` so they are exclusively selectors and cannot be used with other functions. You can still use them with other fields though so this is fine:

```
SELECT top(value, 2), host FROM cpu
```

This is not:

```
SELECT top(value, 2), max(value) FROM cpu
```

**Comment by rkuchan** [comment]
Add a note to the `Specify Multiple Functions in the SELECT Clause` section. Under the `Description of Syntax` header:

> The syntax applies to all InfluxQL functions except [`TOP()`](#top) and [`BOTTOM()`](#bottom).
The `SELECT` clause does not support specifying `TOP()` or `BOTTOM()` with another function.
