### ISSUE TITLE
Aggregation "difference" returns erratic values

### ISSUE THREAD

**Issue by jait-23** [influxdata/docs.influxdata.com#1101]
select difference(reading) from measurement_name
returns erratic values. some in negative and some in positive in v1.2.0 but works fine in v.1.1.0. how to solve it?

**Comment by timhallinflux** [comment]
@jait-23 this sounds like a potential query engine defect?  (as opposed to a documentation error/omission).  Seems like this should land as an issue in the influxdb GitHub repo.

It may have already been addressed by: https://github.com/influxdata/influxdb/pull/8214

Are you still running into this issue in v1.2.5 or v1.3.1?

**Comment by timhallinflux** [comment]
@jait-23 -- we haven't heard back from on this in over a year.  So, we are going to close this out.  But, if you are still running into this issue, please drop us a note here!  Thank you for your interest in InfluxDB!
