### ISSUE TITLE
[InfluxDB] top() and bottom() now returns the time for every point

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1103]
###### URL for relevant page?
influxdata/influxdb#8289

###### What products and version are you using?
InfluxDB 1.3.0

`top()` and `bottom()` are being modified so they return the actual time numbers always rather than following the standard time grouping rules. That also affects the ordering so they will not always be from greatest to least or least to greatest, they'll be organized by time and then the standard rules we use now.

**Comment by rkuchan** [comment]
### `TOP()`

* [ ] Update example 4:

```
> SELECT TOP("water_level",3),"location" FROM "h2o_feet" WHERE time >= '2015-08-18T00:00:00Z' AND time <= '2015-08-18T00:54:00Z' GROUP BY time(24m) ORDER BY time DESC
name: h2o_feet

time                 top   location
----                 ---   --------
2015-08-18T00:48:00Z 7.11  coyote_creek
2015-08-18T00:54:00Z 6.982 coyote_creek
2015-08-18T00:54:00Z 2.054 santa_monica
2015-08-18T00:24:00Z 7.635 coyote_creek
2015-08-18T00:30:00Z 7.5   coyote_creek
2015-08-18T00:36:00Z 7.372 coyote_creek
2015-08-18T00:00:00Z 8.12  coyote_creek
2015-08-18T00:06:00Z 8.005 coyote_creek
2015-08-18T00:12:00Z 7.887 coyote_creek
```
[...]
Notice that the [GROUP BY time() clause](/influxdb/v1.3/query_language/data_exploration/#group-by-time-intervals) does not override the points’ original timestamps. See [Issue 1](\#**TK **) in the section below for a more detailed explanation of that behavior.

* [ ] Update issue 1:

#### Issue 1: `TOP()` with a `GROUP BY time()` clause

Queries with `TOP()` and a `GROUP BY time()` clause return the specified
number of points per `GROUP BY time()` interval.
For
[most `GROUP BY time()` queries](/influxdb/v1.3/query_language/data_exploration/#group-by-time-intervals),
the returned timestamps mark the start of the `GROUP BY time()` interval.
`GROUP BY time()` queries with the `TOP()` function behave differently;
they maintain the timestamp of the original data point.

##### Example
<br>
The query below returns two points per 18-minute
`GROUP BY time()` interval.
Notice that the returned timestamps are the points' original timestamps; they
are not forced to match the start of the `GROUP BY time()` intervals.

```
> SELECT TOP("water_level",2) FROM "h2o_feet" WHERE time >= '2015-08-18T00:00:00Z' AND time <= '2015-08-18T00:30:00Z' AND "location" = 'santa_monica' GROUP BY time(18m)

name: h2o_feet
time                   top
----                   ------
                           __
2015-08-18T00:00:00Z  2.064 |
2015-08-18T00:06:00Z  2.116 | <------- Greatest points for the first time interval
                           --
                           __
2015-08-18T00:18:00Z  2.126 |
2015-08-18T00:30:00Z  2.051 | <------- Greatest points for the second time interval
                           --
```


### `BOTTOM()`

Waiting to hear about https://github.com/influxdata/influxdb/issues/8474 to update the `BOTTOM()` documentation.
