### ISSUE TITLE
Scroll selector hidden behind top nav bar

### ISSUE THREAD

**Issue by phemmer** [influxdata/docs.influxdata.com#1104]
The scroll bar draggy thingy on long pages is hidden behind the top nav bar and is inaccessible.

For example, in this screenshot, where's the scroll bar?
![image](https://cloud.githubusercontent.com/assets/1826947/25068758/1a62c62a-223c-11e7-94f8-0edba776de43.png)

But scroll down a bit (using mouse wheel) and it shows up:
![image](https://cloud.githubusercontent.com/assets/1826947/25068761/52983412-223c-11e7-8b4f-01db5e1ee00f.png)

###### URL for relevant page?
https://docs.influxdata.com

###### What products and version are you using?
Chrome 57.0.2987.133

###### Where did you look before opening the issue?
Here on github

**Comment by stevebang** [comment]
Fixed by Scott -- closing.
