### ISSUE TITLE
[InfluxDB] Update the admin UI documentation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1107]
###### URL for relevant page?
influxdata/influxdb#8306

###### What products and version are you using?
InfluxDB 1.3

**Comment by jwilder** [comment]
The admin code is removed in 1.3 and can no longer be re-enabled.  These docs https://docs.influxdata.com/influxdb/v1.2/tools/web_admin/ will be out of date for 1.3.

**Comment by rkuchan** [comment]
Add a note to the web admin page; something like:

> In version 1.3, we've removed the web admin interface from InfluxDB.
The system now ignores the `[admin]` section in the configuration file.
[Chronograf](/chronograf/v1.3/) replaces the web admin interface with improved tooling for querying data, writing data, and database management.
See [Chronograf's transition guide](/chronograf/v1.3/guides/transition-web-admin-interface/) for more information.

Also remove the deprecated notice and update the index page.
