### ISSUE TITLE
Alert at intervals, as well as on state change.

### ISSUE THREAD

**Issue by koushikpaul1** [influxdata/docs.influxdata.com#1109]
1.Our requirement is when ever the usage goes beyond 50 % , we should get the alert.
2.We should keep getting  this alert , at a certain interval, like 5 minutes.

But if we implement no 2, the usage check is executed every 5 minutes only.
So if the state changes in between this 5 minutes, we will get the alert only after the window( 5 minutes).

Can these( 1 & 2) be clubbed together ?

**Comment by phemmer** [comment]
See https://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#statechangesonly
