### ISSUE TITLE
9092 no connection could be made as the target machine actively refused it error

### ISSUE THREAD

**Issue by srik506** [influxdata/docs.influxdata.com#1112]
Hi,

I am following the getting started guide to setup Telegraph+InfluxDB+Kapacitor. Datapoints seem to be coming till InfluxDB but when I try to run:
'kapacitor record stream -name cpu_alert -duration 20s' command  
while kapacitord is running in the background, it throws the above mentioned error and also the running daemon exits. I could'nt find any information online pertainng to ths issue. I have checked using netstat that no other process is using that port. Also when I did 'show subscriptions' I can see the endpoint in InfluxDB.

https://docs.influxdata.com/kapacitor/v1.2/introduction/getting_started/
Kapacitor v1.2

**Comment by timhallinflux** [comment]
Have you used https://community.influxdata.com?  This feels more like a question for that forum -- as it is more troubleshooting related.
