### ISSUE TITLE
curl is misspelled 

### ISSUE THREAD

**Issue by jheerdegen** [influxdata/docs.influxdata.com#1113]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.2/troubleshooting/frequently-asked-questions/#what-words-and-characters-should-i-avoid-when-writing-data-to-influxdb

curl is misspelled here:
_curl the /ping endpoint:
$ url -i 'http://localhost:8086/ping'_

**Comment by rkuchan** [comment]
Thank you for pointing that out, @jheerdegen!
