### ISSUE TITLE
[Enterprise InfluxDB] Enterprise Web console deprecation

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1116]
###### URL for relevant page?
https://docs.influxdata.com/enterprise/v1.3/about-the-project/release-notes-changelog/

###### What products and version are you using?
InfluxEnterprise

###### Where did you look before opening the issue?

We need to announce the deprecation of the Enterprise Web console -- as part of 1.3.0 release of InfluxEnterprise.

**Comment by rkuchan** [comment]
### Deprecation warning
Pages that require the deprecation warning:

* [ ] /introduction/installation_guidelines/
* [ ] /introduction/getting_started/
* [ ] /quickstart_installation/web_console_installation/
* [ ] /production_installation/web_console_installation/
* [ ] /concepts/glossary/
* [ ] /features/web-console-features/
* [ ] /administration/configuration/#web-console-configuration

### Transition guide
The warning should link to a guide that transitions users from using the web console to using Chronograf. See https://docs.influxdata.com/chronograf/v1.3/guides/transition-web-admin-interface/ for an example. The table shows some possible content for the new guide:

| Feature  | Web Console  | Chronograf  |
| :--------- | :--------------- |:-------------- |
| Query Management       | Yes   | Yes, on the ADMIN page   |
| Database/Retention Policy Management |  Yes | Yes, on the ADMIN page |
| Monitoring | Yes, although rather minimal | Yes, but better, HOST LIST page and pre-created dashboards| 
| User Management | Yes | Yes, but *very* different from the web console |
| Visualization Tools | Yes (DATA EXPLORER) | Yes, there's an improved DATA EXPLORER with added write data and query template features. There's also a complete dashboarding solution. |  
| Kapacitor UI | No | Yes |
| Telegraf Requirement | No | Yes |

The guide should also go into detail about how to connect a cluster to Chronograf. There is already some content about this: https://docs.influxdata.com/chronograf/v1.3/guides/monitor-an-influxenterprise-cluster/ and https://docs.influxdata.com/chronograf/v1.3/troubleshooting/frequently-asked-questions/#how-do-i-connect-chronograf-to-an-influxenterprise-cluster.

### Other: The landing page
Finally, the landing page for the Enterprise InfluxDB docs (/enterprise_influxdb/v1.3/) is all about the web console. That'll need to be updated.

**Comment by timhallinflux** [comment]
done

**Comment by NateZimmer** [comment]
Seemed nifty when you had a webUI to configure/check on your database. Moving that to yet another tool is rather unfortunate for people getting started. A lot of tutorials on the web show this feature and now its gone. :/ Not making this ecosystem easier to use by breaking out a basic debug features into a separate clobber tools.
