### ISSUE TITLE
Dead link in docs.influxdata.com

### ISSUE THREAD

**Issue by MarijusBriedis** [influxdata/docs.influxdata.com#1120]
Hello,

I found one dead link in docs.influxdata.com.

https://docs.influxdata.com/influxdb/v1.2//troubleshooting/frequently-asked-questions/#what-is-the-relationship-between-shard-group-durations-and-retention-policies

It is for "ALTER RETENTION POLICY" it points to "localhost"

Best regards,
Marijus

**Comment by rkuchan** [comment]
Thank you, @MarijusBriedis! Fixed in https://github.com/influxdata/docs.influxdata.com/pull/1150.
