### ISSUE TITLE
[BUG] lacking documentation

### ISSUE THREAD

**Issue by PauloAugusto-Asos** [influxdata/docs.influxdata.com#1121]
Following the thread on community:
`https://community.influxdata.com/t/where-does-log-queries-after-writes-to/858`

I request that the following information:

>  It will write to the logs. The default position for those is /var/log/influxdb/influxdb.log. However on systems that use systemd (most modern linux distributions) those logs are output to journalctl. You should be able to view the InfluxDB logs with journalctl -u influxdb

Be added to the InfluxDB documentation at:
https://community.influxdata.com/clicks/track?url=https%3A%2F%2Fdocs.influxdata.com%2Finfluxdb%2Fv1.2%2Ftroubleshooting%2Fquery_management%2F%23log-queries-after&topic_id=858

**Comment by timhallinflux** [comment]
This is landing in the 1.3 docs.  Thanks @PauloAugusto-Asos !
