### ISSUE TITLE
[InfluxDB] Add nanosecond duration literal support documentation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1134]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/8406

###### What products and version are you using?
InfluxDB 1.3.0

If we have somewhere where we mention possible duration literals, the new `ns` literal should be included there. Previously, it was not possible to specify nanoseconds in places like `GROUP BY time(...)`.

It is still possible to use integers for duration math and the integers will be treated as nanoseconds. So these two are the same: `1d - 10` and `1d - 10ns`.

**Comment by rkuchan** [comment]
Add `ns` to the Duration units table in the spec and the crosswalk doc:

`ns | nanoseconds (1 billionth of a second)`
