### ISSUE TITLE
[InfluxDB] Document top() and bottom() divergent behavior when writing

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1135]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/8398

###### What products and version are you using?
InfluxDB 1.3.0

These functions will have strange behavior when writing that will need to be documented. Whenever a tag is included in the function, it will be passed to be written as a tag instead of a field. This behavior is weird and these are the only functions that will have this behavior.

**Comment by rkuchan** [comment]
* [ ] Add a sentence to the description of syntax sections for `TOP()` and `BOTTOM()`:
    `TOP()` and `BOTTOM()` differ from other InfluxQL functions when combined with an [`INTO` clause](/influxdb/v1.3/query_language/data_exploration/#the-into-clause). See the [Common Issues](\#**TK **) section for more information.
* [ ] Add a disclaimer to the `INTO` docs:
    [...] differentiated by a tag value. Note that this behavior does not apply to queries that use the [`TOP()`](/influxdb/v1.3/query_language/functions/#top) or [`BOTTOM()`](/influxdb/v1.3/query_language/functions/#bottom) functions.
* [ ] Update the FAQ entry about `INTO` queries:
    Note that this behavior does not apply to queries that use the [`TOP()`](/influxdb/v1.3/query_language/functions/#top) or [`BOTTOM()`](/influxdb/v1.3/query_language/functions/#bottom) functions.
    See the [`TOP()`](\#**Link to common issue**) and [`BOTTOM()`](\#**Link to common issue**) documentation for more information.
* [ ] Add a common issues to the `TOP()` and `BOTTOM()` sections:

TK
