### ISSUE TITLE
line protocol link 404

### ISSUE THREAD

**Issue by icco** [influxdata/docs.influxdata.com#1139]
on https://docs.influxdata.com/kapacitor/v1.3/, the line `Query data from InfluxDB on a schedule, and receive data via the line protocol and any other method InfluxDB supports.` links to https://docs.influxdata.com/influxdb/v1.3/write_protocols/line/ which does not exist.

###### URL for relevant page?

https://docs.influxdata.com/kapacitor/v1.3/

###### Where did you look before opening the issue?

**Comment by rkuchan** [comment]
Thank you for pointing this out, @icco! Fixed in  https://github.com/influxdata/docs.influxdata.com/pull/1147.
