### ISSUE TITLE
Click to tsm in glossary related entries don't scroll the page

### ISSUE THREAD

**Issue by kapsh** [influxdata/docs.influxdata.com#1146]
In glossary anchor links to `tsm` in "Related entries" point to `#tsm` but it should be `#tsm-time-structured-merge-tree`

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.2/concepts/glossary/#tsm

**Comment by rkuchan** [comment]
Thank you for pointing this out, @kapsh ! Fixed in  https://github.com/influxdata/docs.influxdata.com/pull/1147.
