### ISSUE TITLE
[InfluxDB] Document semi-breaking change around invalid duration literals

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#1159]
In 1.2, invalid duration literals were mistakenly treated as 0s  (see https://github.com/influxdata/influxdb/issues/8181). We've seen at least one case like this in the wild:

```
MALFORMED GROUP BY TIME:
> select mean(req) from httpd where time > now() - 1m group by time(10seconds)
name: httpd
-----------
time				mean
2017-06-06T14:35:14.552178758Z	5.666666666666667

CORRECTLY FORMED GROUP BY TIME:
> select mean(req) from httpd where time > now() - 1m group by time(10s)
name: httpd
-----------
time			mean
2017-06-06T14:35:10Z
2017-06-06T14:35:20Z	3
2017-06-06T14:35:30Z	4
2017-06-06T14:35:40Z	5
2017-06-06T14:35:50Z	6
2017-06-06T14:36:00Z	8
2017-06-06T14:36:10Z	8
```

Now in 1.3, the `10seconds` case is treated as a parse error, instead of returning results. Queries that were poorly formed in this way and that previously returned results in 1.2 will no longer be accepted in 1.3.

**Comment by rkuchan** [comment]
Thank you, @mark-rushakoff. I'll include this on the differences page.
