### ISSUE TITLE
Typo at using alert topics page

### ISSUE THREAD

**Issue by huangqiz** [influxdata/docs.influxdata.com#1170]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/guides/using_alert_topics/ 
###### Where did you look before opening the issue?
After "Finally confirm the topic is configured as expected:"
The example text should be:
`$ kapacitor show-topic cpu`
rather than 
`$ kapacitor show-topic slack`
![image](https://user-images.githubusercontent.com/7144380/27315063-094707d8-55aa-11e7-8906-7e26924e58e2.png)

**Comment by timhallinflux** [comment]
thanks @huangqiz -- fixed.
