### ISSUE TITLE
[Enterprise InfluxDB] Update version numbers

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#1174]
Update version numbers on the following pages:

* [x] administration/upgrading
* [x] features/cluster-commands
* [x] guides/migration
* [x] production_installation/data_node_installation
* [x] production_installation/meta_node_installation
* [x] quickstart_installation/cluster_installation
* [x] troubleshooting/reporting-issues

**Comment by timhallinflux** [comment]
done
