### ISSUE TITLE
[Enterprise InfluxDB]  Update InfluxEnterprise wording

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#1176]
`InfluxEnterise` could imply `Enterprise Kapacitor` or `Enterprise InfluxDB`. Currently, the Enterprise InfluxDB docs and the docs for the other products use `InfluxEnterprise` to indicate `Enterprise InfluxDB`. That wording requires updating.

**Comment by stevebang** [comment]
Done as part of major renaming and cleanup effort in November 2017. Names used based on discussion with Mark.
