### ISSUE TITLE
Add writeup on how to upgrade a license file on a running cluster

### ISSUE THREAD

**Issue by edbernier** [influxdata/docs.influxdata.com#1179]
In the docs there are a couple of brief descriptions of license-key and license-path but there is no description of how to install a new license on a running cluster.

Do I need to stop and start the cluster after?
Do I simply replace my current JSON license file?
Do I use the same license file on all my nodes?
Do I need to update the meta nodes and the data nodes?
Is there a command I should issue to signal InfluxDB to reread the license file?

We should add a section in the docs on the process to go through and highlight the fact that you can do this on a running cluster with no downtime.

**Comment by timhallinflux** [comment]
@edbernier -- added to 1.3 Enterprise docs.
