### ISSUE TITLE
[Enterprise InfluxDB] Remove other 1.2-specific mentions

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#1183]
The Enterprise InfluxDB docs contain unnecessary 1.2-specific content:

* In `/guides/backup-and-restore/`, remove the five warnings about versions 1.2.0 and 1.2.1. They start with `In versions 1.2.0 and 1.2.1`.
* In `/troubleshooting/frequently_asked_questions/`, remove the three known issues - they were all fixed in v1.2.5.
* In `/troubleshooting/frequently_asked_questions/`, remove the two warnings about versions 1.2.0 and 1.2.1. They start with `In versions 1.2.0 and 1.2.1`.
* In `/administration/configuration/`, remove the warning from:
  * `retention-autocreate` in the meta node's `[meta]` section
  * `retention-autocreate` in the data node's `[meta]` section
  * `max-row-limit` in the data node's `[http]` section

**Comment by timhallinflux** [comment]
Completed.
