### ISSUE TITLE
sample data docs incomplete

### ISSUE THREAD

**Issue by gravity-addiction** [influxdata/docs.influxdata.com#1188]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.2/query_language/data_download/

###### What products and version are you using?
InfluxDB 1.2.4

###### Where did you look before opening the issue?
this page of docs have no reference to setting the database for the sample data. No where where it uploaded this data to, and the other steps in the doc don't work without a prior `use <database>` command in influxdb

**Comment by timhallinflux** [comment]
Fair enough...we will look to update the example to explicitly call out the `use <database>` command....
