### ISSUE TITLE
Example output with HTTP headers will change

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/docs.influxdata.com#1190]
###### URL for relevant page?
example for /ping on :   https://docs.influxdata.com/influxdb/v1.3/tools/api/
###### What products and version are you using?
This is targeted for the Influxdb 1.4 release

The change adds a new value X-Influxdb-Build to the header.  It may have a value of 'OSS' or 'ENT'.  It is not a breaking change, and the doc is still valid, so this issue is not critical.

**Comment by stevebang** [comment]
Checked minor change directly into master for current 1.6 version -- closing.
