### ISSUE TITLE
Documentation on PagerDuty integration outdated?

### ISSUE THREAD

**Issue by whatthesunny** [influxdata/docs.influxdata.com#1191]
The documentation for integrating PagerDuty might be dated: 
   - No field 'Service Type' on 'Add a Service' page in PagerDuty. 'Integration Type' is there instead. 
   - Generic API not available as an 'Service Type'. 'InfluxDB' is available as an 'Integration Type'. 
      Is 'InfluxDB' more appopriate?
   - No 'Service Key' item on subsequent page. 'Integration Key' available instead. 

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/nodes/alert_node/#pagerduty

###### What products and version are you using?
InfluxDB V1.2
Kapacitor 

###### Where did you look before opening the issue?
https://docs.influxdata.com/kapacitor/v1.3/nodes/alert_node/#pagerduty
https://v2.developer.pagerduty.com/docs/events-api

**Comment by whatthesunny** [comment]
Is there anyone available to assist?

**Comment by timhallinflux** [comment]
Did you look at the docs relevant for your version?  The docs have been updated for the 1.3 release of Kapacitor.

I think you will find what you are looking for here:
https://docs.influxdata.com/kapacitor/v1.2/nodes/alert_node/#pagerduty
