### ISSUE TITLE
There was an error writing history file: open : The system cannot find the file specified.

### ISSUE THREAD

**Issue by hhhcj** [influxdata/docs.influxdata.com#1192]

**Comment by timhallinflux** [comment]
@hhhcj   This doesn't appear to be a documentation error/omission.  It could be a configuration error which is causing this.  Have you posted this to the https://community.influxdb.com site to see if anyone else has run into this issue?

I'm going to close this out here.

**Comment by honzajde** [comment]
This is a problem on Windows: https://groups.google.com/forum/#!msg/influxdb/4qxB1DLlCX4/L7CT2aOnAgAJ

**Comment by honzajde** [comment]
https://github.com/influxdata/influxdb/issues/6070
