### ISSUE TITLE
Bad link in alerts page

### ISSUE THREAD

**Issue by zunayed** [influxdata/docs.influxdata.com#1199]
A bad link (404 - https://docs.influxdata.com/kapacitor/guides/using_alert_topics)  is shown on the bottom of the alerts page  in the examples section.

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/alerts

**Comment by timhallinflux** [comment]
fixed.  Thank you for reporting this.

**Comment by zunayed** [comment]
@timhallinflux still seeing a 404 when clicking the link

**Comment by timhallinflux** [comment]
hmmm... the correct link is https://docs.influxdata.com/kapacitor/v1.3/guides/using_alert_topics/

I'll give it another shot.

**Comment by timhallinflux** [comment]
I think this is now fixed.  Thank you for cross-checking.
