### ISSUE TITLE
Document (or undocument) the behavior of HTTP pipelining

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1203]
influxdata/influxdb#8561

The HTTP service no longer will send the `Connection: close` header to force the query connection closed. This should help with reducing the number of `TIME_WAIT` connections for those who reuse HTTP connections.

It turns out the original reason why it was added doesn't appear to be needed anymore. More details are in the PR description.

###### URL for relevant page?
Not sure. If there is no relevant page, this may not need to be documented (unless we want to document this behavior). If there is a page that describes the current behavior, it needs to be modified or removed.

###### What products and version are you using?
InfluxDB 1.4.0

**Comment by kelseiv** [comment]
Thank you, @jsternberg!
I verified Connection: close header is not documented. Typically, we document behavior that exists, and keep these types of changes in Release Notes.  :yellow_heart:
