### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mqsquidy** [influxdata/docs.influxdata.com#1204]
https://docs.influxdata.com/enterprise_influxdb/v1.3/production_installation/data_node_installation/
###### URL for relevant page?
enterprise version 1.3.1
###### What products and version are you using?
just clicked on a link at bottom of page - no further investigation
###### Where did you look before opening the issue?

the last text on the page at the pasted URL is:
"the final step to set up the InfluxEnterprise web console." -> https://docs.influxdata.com/enterprise_influxdb/v1.3/production_installation/web_console_installation/

that link returns 404

**Comment by timhallinflux** [comment]
Got it!  Thanks...

We deprecated Enterprise Web....so the step should be...move on to installing Chronograf!

https://docs.influxdata.com/chronograf/v1.3/introduction/installation/

Thanks for catching this!
