### ISSUE TITLE
DOCUP - Getting Started - new users need to set precision

### ISSUE THREAD

**Issue by juggledad** [influxdata/docs.influxdata.com#1212]
For a new user going thru the 'Getting Started" examples, the date/time format does not match the example shown. To get them to match, the user needs to issue: 
`precision RFC3339`
This should be documented to avoid confusion for someone 'Getting Started' (grin)

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.3/introduction/getting_started/
###### What products and version are you using?
v1.3
###### Where did you look before opening the issue?
Did a search on the github repository

**Comment by timhallinflux** [comment]
Agreed... however, isn't that already covered at the very top?

Under Creating a Database....

The command listed to connect to the CLI is listed as:
```
$ influx -precision rfc3339
Connected to http://localhost:8086 version 1.3.x
InfluxDB shell 1.3.x
> 
```

Did you skim past that part?

**Comment by juggledad** [comment]
You are right, I did miss that. I had installed following a guide and when I went to the Getting Started, I missed that (embarrassed look on face). I have made a comment on the install guide page mentioning this to it's author.

tThis should be closed as a D.U.E. R.T.F.M.

**Comment by timhallinflux** [comment]
No worries.  I appreciate your interest....keep the requests for clarification coming!
