### ISSUE TITLE
1.2 -> 1.3 differences page problems

### ISSUE THREAD

**Issue by Ultimation** [influxdata/docs.influxdata.com#1213]
Just above where the URL below links too, the documentation goes all funky and is impossible to interpret
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.3/administration/differences/#tagkey
###### What products and version are you using?
Chrome Version 59.0.3071.115
###### Where did you look before opening the issue?
I searched the issues for differences to see if this had been opened already?

**Comment by Ultimation** [comment]
It seems to render fine in Githubs markdown parser: https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.3/administration/differences.md

but somewhere around line 130 causes the influx website to not parse the markdown in the same way.

**Comment by timhallinflux** [comment]
I'm also using Chrome 59.0.3071.115 ...but I see what you mean.  I'll attempt to clean this up.

**Comment by timhallinflux** [comment]
@Ultimation -- I believe I've slayed the markdown demons!  Have a look!
