### ISSUE TITLE
Working example for bind parameters

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#1220]
[This community post](https://community.influxdata.com/t/protection-against-query-injection/1750) was asking how to protect against query injection, which is the problem bind parameters solve.

The documentation for bind parameters explains the syntax but does not offer a working example.

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.3//tools/api/#bind-parameters

###### Where did you look before opening the issue?

Used the docs search bar for "bind parameters", searched for "parameters" on the InfluxDB FAQ page.

**Comment by timhallinflux** [comment]
@mark-rushakoff  -- there are now 3 example 4,5,6 that cover this.  Can you confirm that this meets your request?

**Comment by mark-rushakoff** [comment]
Those look good, thanks.
