### ISSUE TITLE
Relay link on influxdb/v1.3 docs page is broken

### ISSUE THREAD

**Issue by ericm-voicebox** [influxdata/docs.influxdata.com#1222]
###### URL for relevant page?

- **Documentation Page:** https://docs.influxdata.com/influxdb/v1.3/
- **Broken Link within Page:**  https://docs.influxdata.com/influxdb/v1.3/high_availability/relay/

###### What products and version are you using?

- influxdb/v1.3 Documentation Page

###### Where did you look before opening the issue?
- Searched Open Issues using [this search query](https://github.com/influxdata/docs.influxdata.com/issues?utf8=%E2%9C%93&q=is%3Aissue%20relay)

**Comment by timhallinflux** [comment]
Thanks @ericm-voicebox
