### ISSUE TITLE
Typo in query syntax

### ISSUE THREAD

**Issue by 4lfaBrav0** [influxdata/docs.influxdata.com#1235]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.3/query_language/data_download/

Hello, I saw a typo in the "Count the number of non-null values.." section; missed double quote on the field name, it should be:  `> SELECT COUNT("water_level") FROM h2o_feet`

Regards

**Comment by timhallinflux** [comment]
thanks @4lfaBrav0 -- fixed in tonight's build.
