### ISSUE TITLE
Initial documentation for explain plan

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1256]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/8776

###### What products and version are you using?
InfluxDB 1.4

###### Where did you look before opening the issue?
New feature.

Please contact me regarding the use of this feature. I can likely write up an initial explanation for the content and then someone can run through and ensure that it makes sense and fix any spelling or grammar mistakes I may make. I just need to know where I'm supposed to write the information.

**Comment by timhallinflux** [comment]
reconnect with @jsternberg re: changes in 1.5.x with regards to EXPLAIN

**Comment by stevebang** [comment]
There is a Google doc that explains details about EXPLAIN PLAN. I'll try to find the link and add it.

**Comment by kelseiv** [comment]
Explain docs are accurate per @jsternberg
