### ISSUE TITLE
[BUG]: Chronograf would not configure kapacitor - GET 'ping' fails with 204

### ISSUE THREAD

**Issue by varaga** [influxdata/docs.influxdata.com#1257]
###### URL for relevant page?
```
curl 'http://localhost:8888/chronograf/v1/sources/1/kapacitors/3/proxy?path=/kapacitor/v1/ping' -H 'Host: localhost:8888' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://localhost:8888/sources/1/kapacitors/3/edit' -H 'Content-Type: application/json;charset=utf-8' -H 'Connection: keep-alive'
```
returns 204 code
&&
```
curl 'http://localhost:8888/chronograf/v1/sources/1/kapacitors/3/proxy?path=%2Fkapacitor%2Fv1%2Fconfig%2Fslack%2F' -H 'Host: localhost:8888' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: http://localhost:8888/sources/1/kapacitors/3/edit' -H 'Content-Type: application/json' -H 'Content-Length: 54' -H 'Connection: keep-alive'
```
returns 204 error code

###### What products and version are you using?
InfuxDB 1.3.7 & Kapacitor 1.3.7 & Chronograf 1.3.7
On Ubuntu 17.04

###### Where did you look before opening the issue?
Looked through groups and github issues

Details:

I'm evaluating TICK stack without Telegraf agents. Basically I'm running prometheus scrappers with JMX exported agent. The prometheus server pushes data into influxdb. Kapacitor runs with subscriptions to influx db locally. Chronograf connects to influxdb fine and when it connects to kapacitor the UI says it is connected. However after integrating with slack, I see no alerts being notified in slack. When I debugged I could 204 errors on few requests.

**Comment by timhallinflux** [comment]
HTTP Status Code 204 is not an error -- it means: The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.

This repo is for documentation related issues.  It might be better if you logged this within the Chronograf project repo:  https://github.com/influxdata/chronograf/issues
