### ISSUE TITLE
'GROUP BY time' titles for example interval tables are unclear

### ISSUE THREAD

**Issue by valentinesd** [influxdata/docs.influxdata.com#1261]
https://docs.influxdata.com/influxdb/v1.3/query_language/data_exploration

Under GROUP BY time intervals -> Common Issues with Basic Syntax -> explanation, it says "InfluxDB uses preset round-number time boundaries for GROUP BY intervals that are independent of any time conditions in the WHERE clause."

In the tables that follow, 'Preset Time Boundary' and 'GROUP BY time() Interval' are separate columns with different data, when the above statement implies that they are the same.  I think it would make more sense reword those columns.  Perhaps something like 'GROUP BY Preset Time Boundary' and 'GROUP BY Time Condition'

**Comment by stevebang** [comment]
Changed table column tables as suggested. Thanks, @valentinesd !
