### ISSUE TITLE
Inadvertent spelling error

### ISSUE THREAD

**Issue by DaveBender** [influxdata/docs.influxdata.com#1269]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/tick/expr/

###### Where did you look before opening the issue?

The word inadvertent is misspelled in this section headline:

_Note on inadvertant type casting_
 
It should end with **e**nt, not **a**nt.

**Comment by timhallinflux** [comment]
Thanks.  Fixed...and will publish tonight at midnight PT.
