### ISSUE TITLE
"Completely" -- except for things that make it complete

### ISSUE THREAD

**Issue by DaveBender** [influxdata/docs.influxdata.com#1270]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/guides/template_tasks/

###### What products and version are you using?
Kapacitor 1.3

###### Where did you look before opening the issue?
Kapacitor documentation

The use of the work "completely" at the end of this paragraph is incorrect:

> Notice how everything about the task is a var **except for** the structure of the task pipeline itself. This allows you to customize the usage of the template **completely**.

If this allowed you to customize the template _completely_, there wouldn't be an exception for anything.  According to the first sentence, you can't customize the structure of the pipeline, so you can't customize the template completely.

I'd suggest replacing _completely_ with _substantially_, or some other impressive word. It is good functionality; I'm not knocking that.  Just looking for precision in the documentation.

**Comment by timhallinflux** [comment]
Fair enough.  Changed to: This allows substantial flexibility in customization of the template.
