### ISSUE TITLE
Document message pack response format

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1279]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/8897

###### What products and version are you using?
InfluxDB 1.4.x

Document that message pack can be used for responses with `application/x-msgpack` and that it is the recommended format going forward and is required for accurate responses with int64 and uint64 since JSON doesn't support integers above 2^53.

The method to use this format is by setting `application/x-msgpack` in the `Accept` header. For clients that may need to talk to versions of the server that do not support message pack, they should be prepared to receive `application/json` even if they requested `application/x-msgpack`.

**Comment by lovasoa** [comment]
@stevebang Any news ? That feature is almost two years old now and has never been documented.

**Comment by stevebang** [comment]
Closing for now.  I discussed with @jsternberg -- "uint64 never got actually enabled in 1.x unless built specially" and to avoid the "recommended format going forward"; he's not even sure how important it is to be documented.
