### ISSUE TITLE
HTTPS setup instructions out of date for systemd operating systems

### ISSUE THREAD

**Issue by jwflory** [influxdata/docs.influxdata.com#1281]
# Problem

The documentation incorrectly tells the user to set user:group to root on the TLS certificates, when the `influxdb.service` starts and runs as the user:group `influxdb`. Thus, InfluxDB is denied permission to read the TLS certificates.

# Explanation

This issue came up in [this forum thread](https://community.influxdata.com/t/cant-start-systemd-service-for-influxdb-because-of-tls-certs/2539). There is more context and discussion there. The correct solution to this is still unclear to me.

###### URL for relevant page?

* [On docs.influxdata.com](https://docs.influxdata.com/influxdb/v1.3/administration/https_setup/#setup-https-with-a-ca-signed-certificate)
* [On GitHub](https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.3/administration/https_setup.md#setup-https-with-a-ca-signed-certificate)

###### What products and version are you using?

* InfluxDB v0.13

###### Where did you look before opening the issue?

* Checked on the community forums, see [this thread](https://community.influxdata.com/t/cant-start-systemd-service-for-influxdb-because-of-tls-certs/2539)

**Comment by timhallinflux** [comment]
@tyauvil -- can you pair with @sanderson and run this down?  Thanks!

**Comment by sanderson** [comment]
@jflory7 We're looking at ways to adjust the documentation. We believe this is a permissions issues. Do you have any user-access logs or kernel auditing logs on your system?

**Comment by jflory7** [comment]
@sanderson It was a permissions issue. It's better explained in the detail [in this thread](https://community.influxdata.com/t/cant-start-systemd-service-for-influxdb-because-of-tls-certs/2539). Unfortunately, I no longer have access logs from the original permissions issue in October.

**Comment by stevebang** [comment]
@sanderson Note that the docs link above goes to InfluxDB 1.3, not the latest (1.5). I see more permissions included in the 1.5 page. Not sure if they're relevant here, but worth checking out.

**Comment by stevebang** [comment]
@sanderson Take a look at this too, which could need fixing too (or might provide more info): https://docs.influxdata.com/kapacitor/v1.4/administration/security/#kapacitor-and-influxdb-https

**Comment by sanderson** [comment]
Thanks @stevebang, I do believe the newer version of the docs resolve this issue. After talking through it with @tyauvil, we decided it was likely to do with permissions and ownership of the CA file. In the 1.3 docs, it instructs you to only `chown` and `chmod` the CA file and the private key file, but it neglects to mention the certificate itself. This prevented the full certificate chain of authority from being read.

A recent PR correct this. This was resolved in dd8c229261b38b78e614b270b878a9966f4b74f5

**Comment by cuu508** [comment]
Hi, I'm running into permissions issue with a self-signed certificate and don't quite understand how it is supposed to work: 

 * The certificate and the key in /etc/ssl belong to root. Key is only readable by root (600)
 * systemd runs influxdb as influxdb user
 * When systemd starts the service it quits with:

`run: open server: open service: open /etc/ssl/influxdb-selfsigned.key: permission denied`  

I followed the instructions in https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/
The OS is Ubuntu 18.04.2 LTS. What am I doing wrong? Thanks!

**Comment by timhallinflux** [comment]
I would assume that you'll need the key to be readable by the influxdb user....  try that.

**Comment by cuu508** [comment]
Yes, if I make "influxdb" the owner of the certificate files, it starts and works. But the documentation tells me these files should be owned by root.

**Comment by jwflory** [comment]
I think an extra `chown` step could be added to this block of documentation, e.g. `chown influxdb:influxdb /etc/ssl/influxdb-selfsigned.*`:

![Screenshot of relevant documentation, "Step 1: Generate a self-signed certificate"](https://user-images.githubusercontent.com/4721034/52880030-d5fe9a00-312e-11e9-882e-b7f869cf627d.png)

**Comment by timhallinflux** [comment]
@stevebang -- needs a rev based on the suggestion.

Thanks @jwflory and @cuu508 !

**Comment by stevebang** [comment]
@kelseiv I just went through the proposed change by @jwflory with @jsternberg and he thinks the proposed change is reasonable. So go ahead and make the change.

**Comment by kelseiv** [comment]
@jwflory @jsternberg please see [docs](https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/)..if updates look OK, I'll close this issue. Thank you!

**Comment by jsternberg** [comment]
You may want to mention that those instructions are for the debian package, but they look good. I think they probably work with the Red Hat package too but I've never used that.

**Comment by kelseiv** [comment]
Thank you, @jsternberg. 

We currently say "...instructions outline how to set up HTTPS w influxdb on Ubuntu 16.04. Steps may vary for other operating systems."

should we change "Unbuntu 16.04" to "Debian package"?

**Comment by kelseiv** [comment]
Also notable for those who've been following this issue:

Gentstr had added documentation for how to add CA certificate and HTTPS client certificate verification support for InfluxDB. These changes were intentionally rolled back because client certificates are not currently supported. 
Support for client certificates has been added to the proposed projects list @ https://github.com/orgs/influxdata/projects/3#card-14983244.

**Comment by jsternberg** [comment]
I did not see that. Then everything is good.

**Comment by kelseiv** [comment]
Excellent, thank you @jsternberg.

**Comment by jwflory** [comment]
This looks great to me, thanks for the improvement!

**Comment by timhallinflux** [comment]
thank you @jwflory and @cuu508!
