### ISSUE TITLE
Duplicate search results with extra slash for the second one

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#1284]
Searching for anything at https://docs.influxdata.com/influxdb/v1.3/ returns duplicate results:

![image](https://user-images.githubusercontent.com/33569/31115761-5abd6bd6-a7d8-11e7-8ff9-1babdcbdc809.png)

The second result turns out to contain an extra `/`:
https://docs.influxdata.com/influxdb/v1.3//query_language/data_exploration/#basic-group-by-time-syntax

**Comment by dandv** [comment]
Still in v1.4:

![image](https://user-images.githubusercontent.com/33569/34514419-3a28045c-f022-11e7-9eb1-c4353b0a97de.png)

**Comment by stevebang** [comment]
Fixed by Algolia.
