### ISSUE TITLE
InfluxQLNode links to itself

### ISSUE THREAD

**Issue by DaveBender** [influxdata/docs.influxdata.com#1286]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/nodes/influx_q_l_node/

###### What products and version are you using?
Kapacitor 1.3

###### Where did you look before opening the issue?
At the Kapacitor documentation

The second word of the text on this page is a boldly highlighted link that links to the same page.  This should not be a link.  Making it a link suggests to the reader there is something new or different, but there's not.  It just sows confusion.

**Comment by timhallinflux** [comment]
I've removed the hyperlink.  We are overhauling the Kapacitor docs -- stay tuned.
Thanks @DaveBender
