### ISSUE TITLE
Data Node Installation Docs.  Starts with Roman numerals then changes to "3.". 

### ISSUE THREAD

**Issue by dennisjbr** [influxdata/docs.influxdata.com#1293]
Data Node Installation Docs.  Under "Step 2: Set up, Configure, and start..." it starts with roman numerals for I. and II., then continues to normal number 3.

###### URL for relevant page?

http://docs.influxdata.com/enterprise_influxdb/v1.3/production_installation/data_node_installation/

**Comment by timhallinflux** [comment]
Fixed.  Will appear in next build.  Thanks @dennisjbr for the fine toothed comb!
