### ISSUE TITLE
Majority of v0.6 and v0.7 Documentation is Missing

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#130]
Original docs:

https://influxdb.com/docs/v0.7

New docs:

https://docs.influxdata.com/influxdb/v0.7/

**Comment by beckettsean** [comment]
Workaround is to use the old site, which is still live: https://influxdb.com/docs/v0.7/introduction/overview.html

**Comment by beckettsean** [comment]
I don't think we can power down influxdb.com/docs until this is fixed. It's not okay to remove 0.6 and 0.7 docs from the web.
