### ISSUE TITLE
kap cluster config value should be "cluster" ?

### ISSUE THREAD

**Issue by dennisjbr** [influxdata/docs.influxdata.com#1303]
###### URL for relevant page?

======
In section "influxDB Configuration" The configuration section for InfluxDB has a new option subscription-mode which should be set to **server** when running Enterprise Kapacitor as a cluster. This allows each server within the cluster to create its own subscriptions to InfluxDB so that each member receives all the data..   

I think this value should say subscription-mode should be set as **cluster** which is set by default, correct?

**Comment by karel-rehor** [comment]
Do you have the link to the specific page?

**Comment by karel-rehor** [comment]
The comments in the code `services/influxdb/config.go:26-28 are as follows: 

```
        // ClusterMode means that there will be one set of subscriptions per cluster.
        ClusterMode SubscriptionMode = iota
        // ServerMode means that there will be one set of subscriptions per server.
        ServerMode
```
So this implies that for _each_ server within the cluster to create its own subscription subscription-mode should be set to **server**.  However, I don't currently have a clustered deployment on which to verify this.

**Comment by nathanielc** [comment]
The quoted docs are correct, while running an Enterprise Kapacitor cluster you want to set the subscription mode to `server`. Otherwise there will only be one subscription for the entire cluster and only one of the nodes will receive the data.

**Comment by stevebang** [comment]
Closing based on @nathanielc comment.
