### ISSUE TITLE
Sensu documentation doesn't explain that destination must be a client

### ISSUE THREAD

**Issue by absolutejam** [influxdata/docs.influxdata.com#1306]
The documentation on the Sensu alert node does not specify that the Kapacitor server sends results to a Sensu **client**, not the API directly. @sstarcher has confirmed this.

This could be a big source of confusion and frustration as this requires Kapacitor to send to a client on port 3030 (Can be local), which is a standard thing to do, just not the only option.

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/nodes/alert_node/#sensu

###### What products and version are you using?
Kapacitor 1.3

**Comment by sstarcher** [comment]
Looks like the second `Example` uses the specific terminology.
```Send alerts to Sensu client. ```

**Comment by absolutejam** [comment]
Fair enough, just very easy to overlook.

**Comment by stevebang** [comment]
Clarified in description that the alert is sent to the Sensu client.
