### ISSUE TITLE
Document error message when attempting to kill a query multiple times

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1307]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/9020

###### What products and version are you using?
InfluxDB 1.4

**Comment by sanderson** [comment]
@jsternberg, just a few questions:

1. If they've tried to kill the query multiple times, does it mean the first kill signal is still in the process of stopping the query? i.e. What's the most common way to reproduce this error?
2. When getting the `error: already killed` message, is there anything the user needs to do?

**Comment by jsternberg** [comment]
Yes. Once you have killed the query the first time, it may not exit immediately. It will be in the killed state which means the signal has been sent, but the query itself hasn't hit an interrupt point.

On the second point, there is nothing useful the user can do.

**Comment by sanderson** [comment]
Resolved by 87c66d1d3c402849fd67eb00908fdb16419fb0cd
