### ISSUE TITLE
tik-docker-tutorial.zip example is not a zip

### ISSUE THREAD

**Issue by jcabillot** [influxdata/docs.influxdata.com#1308]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.3/introduction/install-docker/
and the link "this location" which point to : https://docs.influxdata.com/downloads/tik-docker-tutorial.zip

###### What products and version are you using?
N/A
###### Where did you look before opening the issue?
N/A

The file tik-docker-tutorial.zip is not a zip but a .tar.gz :
```
$ wget -q https://docs.influxdata.com/downloads/tik-docker-tutorial.zip
$ file tik-docker-tutorial.zip
tik-docker-tutorial.zip: gzip compressed data, last modified: Fri Aug 18 10:47:11 2017, from Unix
$ tar zxvf tik-docker-tutorial.zip
tik/docker-compose.yml
tik/etc/
[...]
```

**Comment by timhallinflux** [comment]
will go live tonight at midnight.  Thanks @jcabillot
