### ISSUE TITLE
move to semantic linefeeds

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#131]
As per https://github.com/influxdata/rfc/issues/3#issuecomment-169418400

**Comment by rossmcdonald** [comment]
@beckettsean Is that the correct link?

**Comment by beckettsean** [comment]
Not even close. Paste buffer FTL. Edited original comment. Thanks, @rossmcdonald!

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/149
