### ISSUE TITLE
Join Backfill Kapacitor Issues

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1314]
https://docs.influxdata.com/kapacitor/v1.3/guides/join_backfill/

Some things I had trouble with while going through the example:

- There are scripts to generate example data but they are only linked to at the bottom. They should be at the top so that users can follow along with their own
- The script to generate data are horribly out of date and do not work on influxdb 1.3.x. the influx_stress command is out of date and even when you update to use the `-config` option, it segfaults
- We should mention in the `groupBy` part of the description how join handles tags. I had issues with tag values not matching exactly and my join was not working.

**Comment by karel-rehor** [comment]
I've rewritten this document and have replaced the data generation with a python script.  However, this was done in a branch from kapa-1.4.  I was waiting for the 1.5 release before merging.  Which will be done in the next day or so. 

https://github.com/influxdata/docs.influxdata.com/tree/issue1314
