### ISSUE TITLE
`KILL QUERY` docs don't mention that in a cluster you have to specify the host

### ISSUE THREAD

**Issue by mupdt982** [influxdata/docs.influxdata.com#1326]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.3/troubleshooting/query_management/#stop-currently-running-queries-with-kill-query

###### What products and version are you using?

InfluxDB Enterprise 1.3.7

###### Where did you look before opening the issue?

The `KILL QUERY` documentation does not mention that in a cluster you have to specify the host.

```
KILL QUERY 12345 on "myhost:8088";
```

**Comment by stevebang** [comment]
Updated query management page with updated SHOW QUERIES and KILL QUERIES content. Also, updated the cluster-features page for InfluxEnterprise to point to the content here.
