### ISSUE TITLE
New arguments for OSS influxdb backup

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/docs.influxdata.com#1329]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.3/administration/backup_and_restore/

###### What products and version are you using?
influxdb future version 1.5

###### Where did you look before opening the issue?
new arguments to existing command.  Additive, all existing arguments + operations remain unchanged: 
-start <2015-12-24T08:12:23Z>::
  All points earlier than this time stamp will be excluded from the export. Not compatible with -since.
-end <2015-12-24T08:12:23Z>::
  All points later than this time stamp will be excluded from the export. Not compatible with -since.
-enterprise::
  Generate backup files in the format used for influxdb enterprise.

**Comment by aanthony1243** [comment]
@stevebang   let me know if this is enough to kick off a doc change.  This is my first time making a request; let me know what works for you.

**Comment by stevebang** [comment]
Closing as this was documented, with @aanthony1243 reviewing, for the InfluxDB 1.5 release.
