### ISSUE TITLE
auth: FGA for SHOW Queries

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1332]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.3/guides/fine-grained-authorization/

###### What products and version are you using?
In InfluxEnterprise 1.5, SHOW MEASUREMENTS AND SHOW TAGS are restricted via fine grained authorization.  This needs to be represented in the documentation.

https://github.com/influxdata/plutonium/pull/1546

**Comment by timhallinflux** [comment]
@chobbs just asked about this.  We need to update the FGA docs to highlight this --- as expected behavior.  Perhaps @pierwill can tackle this?

**Comment by pierwill** [comment]
Closed via https://github.com/influxdata/docs.influxdata.com/pull/2540
