### ISSUE TITLE
Handle redirects when pages don't exist

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#134]
Invalid links should ideally redirect to the node above the requested URL. For example, this page:

https://docs.influxdata.com/influxdb/v0.9/introduction/overview/

Is currently blank (due to a 404). It would be great if it would just automatically redirect to:

https://docs.influxdata.com/influxdb/v0.9/introduction/

**Comment by gunnaraasen** [comment]
There's no way to set multiple 404 pages using the S3 static site server we currently use. We'd have to switch to using a different server.

**Comment by rossmcdonald** [comment]
Ah, I didn't realize these were in S3. Please disregard then. :)
