### ISSUE TITLE
New arguments, features for OSS restore

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/docs.influxdata.com#1341]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.3/administration/backup_and_restore/

Below is the new man-page text for  "influxd restore" .   Highlights of the changes: 

1.  Previous functionality is all retained, so that nothing on above page is technically wrong but there are many improvements.  
2.  New flag   -online   will perform a DB restore of a single database with no downtime, and all existing DB's on the system remain unaffected.  
3.  New Flag/mode + alternate set of options  -enterprise.   When in this mode, the 'old' functionality is replaced with the new flags/functionality described below.  

influxd-restore(1)
==================

NAME
----
influxd-restore - Uses backups from the PATH to restore the metastore, databases, retention policies, or specific
 shards.  Default mode requires the instance to be stopped before running, and will wipe all databases from the
 system (e.g., for disaster recovery).  The improved online and enterprise modes requiresthe instance to be running,
 and the database name used must not already exist.

SYNOPSIS
--------
'influxd restore' [-enterprise] [flags] PATH

DESCRIPTION
-----------
Uses backups from the PATH to restore the metastore, databases, retention policies, or specific shards. The InfluxDB process must not be running during a restore.

OPTIONS
-------
The default mode consumes files in an OSS only file format. PATH is a directory containing the backup data

-metadir <path>::
            Optional. If set the metastore will be recovered to the given path.

-datadir <path>::
            Optional. If set the restore process will recover the specified
            destinationDatabase, retention policy or shard to the given directory.

-database <name>::
            Optional. Required if no metadir given. Will restore a single database's data.

-retention <name>::
            Optional. If given, -database is required. Will restore the retention policy's
            data.

-shard <id>::
            Optional. If given, -database and -retention are required. Will restore the shard's
            data.

-online::
	        Optional. If given, the restore will be done using the new process, detailed below.  All other arguments
	        above should be omitted.

The -enterprise restore mode consumes files in an improved format that includes a file manifest.  PATH should indicate
the manifest file.

Options:
-host <host:port>::
  The host to connect to and perform a snapshot of. Defaults to '127.0.0.1:8088'.

-db    <name>::
	        Identifies the database from the backup that will be restored.

-newdb <name>::
	        The name of the database into which the archived data will be imported on the target system.
	        If not given, then the value of -db is used.  The new database name must be unique to the target system.

-rp    <name>::
	        Identifies the retention policy from the backup that will be restored.  Requires that -db is set.

-newrp <name>::
	        The name of the retention policy that will be created on the target system. Requires that -rp is set.
	        If not given, the value of -rp is used.

-shard <id>::
	        Optional.  If given, -db and -rp are required.  Will restore the single shard's data.

**Comment by timhallinflux** [comment]
completed with 1.5
