### ISSUE TITLE
Kapacitor 1.4 documentation folder is missing spec.md

### ISSUE THREAD

**Issue by evaryont** [influxdata/docs.influxdata.com#1354]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.4/tick/ links to https://docs.influxdata.com/kapacitor/v1.4/tick/spec/ but that is a 404.

**Comment by timhallinflux** [comment]
This has been fixed.  https://docs.influxdata.com/kapacitor/v1.4/tick/reference/spec/
