### ISSUE TITLE
Recommendation: Batch / Stream 

### ISSUE THREAD

**Issue by alwaysrohit** [influxdata/docs.influxdata.com#1360]
###### What products and version are you using?
Kapacitor 1.4.0 (git: HEAD fcce3ee9e6abcee5595fd61066bfc904edb1e113)          

###### Where did you look before opening the issue?
Online search and local testing.

We would like a recommendation for our alerting solution.   Below are our requirements -
1. We have 300 Hosts to monitor 
2. For each of the host, we monitor host health, CPU utilization, Memory utilization, File system (5 nos) 
3. Memory allocated to Influx - 64 GB RAM [running as a Docker Image in OpenShift]  6 cores
4. Memory allocated to Kapacitor - 1GB / 1 core

Note that -
our period would  be 10 minutes
our every would be 1 minute
Influx has data for every 10 second interval

**Comment by timhallinflux** [comment]
This isn't a documentation issue.  I encourage you to use the online forums to post this question and get feedback/recommendations.   https://community.influxdata.com
