### ISSUE TITLE
Gitlab Oauth

### ISSUE THREAD

**Issue by trucaliber** [influxdata/docs.influxdata.com#1365]
Absolutely frustrating process

###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.3/administration/security-best-practices/

###### What products and version are you using?
1.3 of Chronograf and 10.3.1 of Gitlab

###### Where did you look before opening the issue?
All over the internet via google

1.)  GENERIC_NAME doesn't only change the name of the login provider on the login page, it also changes the callback URL  -- required Postman to see the exact redir url before being redirected to error page stating "The redirect URI included is not valid"

GENERIC_NAME=GitLab

changes:
https://influx.home.my:8888/oauth/generic/callback
to:
https://influx.home.my:8888/oauth/GitLab/callback

2.) after spending 8 hours trying to get OAuth to work I'm now successfully forwarding to GitLab, logging in and getting redirected to Chronograf login page.  I click "Login to Gitlab" and bounced right back to the Chronograf login page.

Please add documentation on setting up basic auth or fronting Chrongraf with nginx.   As of now I disabled auth just to be able to use it.  About to just ditch it and move on.

**Comment by stevebang** [comment]
Sorry, @trucaliber, for your frustrating experience -- clearly the GENERIC_NAME was not doc'ed correctly as also noted by @jcmcken (https://github.com/influxdata/chronograf/issues/2065).  I'm updating the docs for Chrono 1.4 and fixing it there.  

I'll also see about documenting basic authentication when using Chronograf with NGINX.  Stay tuned.

**Comment by stevebang** [comment]
@austinbutler was working with NGINX when he also encountered the same GENERIC_NAME issue (https://community.influxdata.com/t/oauth-with-internal-only-domain/1376).

**Comment by jaredscheib** [comment]
Hi @trucaliber, sorry to hear you've had a frustrating experience.

It sounds this is not an issue with Chronograf but rather more likely that your nginx config is not passing the required HTTP Authentication headers.

I don't know if the following is exactly what you'll need, but I believe it'll end up looking something like this:
```
proxy_set_header Authorization $http_authorization;
proxy_pass_header  Authorization;
```

I urge you to confirm that you're passing along the correct headers, and if you're absolutely sure that you are, let us know if you're still having issues. Thank you.

**Comment by jaredscheib** [comment]
Looks like generic may not be working currently: https://github.com/influxdata/chronograf/issues/2677

**Comment by bclermont** [comment]
@trucaliber you have some gist/hint on how to make oauth2 works on gitlab?

**Comment by bclermont** [comment]
Nevermind, it works now

**Comment by stevebang** [comment]
Closing due to changes in generic documentation. If any new issues, let us know.

**Comment by exabrial** [comment]
I ran into the same problem:

GENERIC_NAME=GitLab

changes:
https://influx.home.my:8888/oauth/generic/callback
to:
https://influx.home.my:8888/oauth/GitLab/callback

The current documentation doesn't show this

**Comment by KEClaytor** [comment]
I encountered the same issue. It is unclear that the GENERIC_NAME should appear in the callback url.
Also, note that this must be set in the callback url in gitlab as well.
