### ISSUE TITLE
[DOC] installation description missing entry for debian version 9

### ISSUE THREAD

**Issue by FrankElias** [influxdata/docs.influxdata.com#1366]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/introduction/installation/
Ubuntu + Debian section is missing entry for DEBIAN VERSION 9 (stretch).
--> extend script as following

curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
test $VERSION_ID = "7" && echo "deb https://repos.influxdata.com/debian wheezy stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "8" && echo "deb https://repos.influxdata.com/debian jessie stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "9" && echo "deb https://repos.influxdata.com/debian stretch stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

###### What products and version are you using?
trying influxdb on RPi3B with DietPi

###### Where did you look before opening the issue?
[resolved]

**Comment by timhallinflux** [comment]
fixed.  Thanks @tobiasschaefer
