### ISSUE TITLE
Hugo 0.32 and later fails to render site on localhost

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/docs.influxdata.com#1371]
After updating hugo on my local machine to 0.32.1 (0.32 was released 31.12) only the root page is being rendered.  All other endpoints either return 404 or using generated index.html files for product roots redirect to docs.influxdata.com.  Rolling back to 0.31.1 fixes this issue.  

Console log reports 275 static files and 1616 pages are generated along with 1 sitemap.  I've tried to build a site locally with both 0.32.1 and 0.32, however the issue persists.

**Comment by karel-rehor** [comment]
Also tried release 0.32.2 - still fails to render any pages other than root. 

seems like nested content from /content is not being generated to /public

$ ls -al public/kapacitor/
total 16
drwxrwxr-x  2 karl karl 4096 led  3 14:13 .
drwxrwxr-x 15 karl karl 4096 led  3 14:13 ..
-rw-rw-r--  1 karl karl  108 led  3 14:13 index.html
-rw-rw-r--  1 karl karl  814 led  3 14:13 index.xml

**Comment by karel-rehor** [comment]
I've noticed in working with a test site, that pages are rendered to memory and not necissarily to the directory /public.  Hugo serves pages, which are not built to the disk.

**Comment by karel-rehor** [comment]
I've been trying hugo 0.34 and I have the same results on Ubuntu 16.04 (laptop) and on Windows Server 2016 (AWS). 

Debug logs for 0.31.1 and 0.34 are attached 
[influxdatat-hugo-31.1-debug.log](https://github.com/influxdata/docs.influxdata.com/files/1659361/influxdatat-hugo-31.1-debug.log)

[influxdatat-hugo-34-debug.log](https://github.com/influxdata/docs.influxdata.com/files/1659363/influxdatat-hugo-34-debug.log)

**Comment by karel-rehor** [comment]
Adding a couple of screenshots
![hugo034issue01](https://user-images.githubusercontent.com/25881301/35326514-355ae8b4-00f7-11e8-929a-9e064ac34acc.png)
![hugo034issue02](https://user-images.githubusercontent.com/25881301/35326537-41617b28-00f7-11e8-8b0e-a77142197eb5.png)

**Comment by andrewsav-datacom** [comment]
It appears that renaming all `index.md` to `_index.md` fixes the issue.

Not very scientific...

```
gci -Recurse | ?{$_.FullName.EndsWith("\index.md")} | %{ Move-Item $_.FullName $_.FullName.Replace("index.md","_index.md")}
```

**Comment by karel-rehor** [comment]
Thanks Andrew,

:smiley:

I tried the underscore in a couple of directories and it solves the issue with Hugo 0.35.  However, this needs to be applied across all directories which are maintained by different people.

**Comment by stevebang** [comment]
Applied to all index.md files in the docs master.
