### ISSUE TITLE
Error in JSON Task Definition Syntax for "dbrps" Field

### ISSUE THREAD

**Issue by Z3KAISER** [influxdata/docs.influxdata.com#1372]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.4/guides/template_tasks/#using-the-file-flag

###### What products and version are you using?
Kapacitor 1.4.0 (git: HEAD fcce3ee9e6abcee5595fd61066bfc904edb1e113)

###### Where did you look before opening the issue?
https://github.com/influxdata/kapacitor/issues/1730

```
{
  "template-id": "generic_test_alert_stream",
  "dbrps": [{"db": "telegraf", "rp": "autogen"}],
  "vars": {
    "measurement": {"type" : "string", "value" : "mem" },
    "groups": {"type": "list", "value": [{"type":"string", "value":"host"}]},
    "field": {"type" : "string", "value" : "used_percent" },
    "warn": {"type" : "lambda", "value" : "\"mean\" > 80.0" },
    "crit": {"type" : "lambda", "value" : "\"mean\" > 90.0" },
    "window": {"type" : "duration", "value" : "10m" }
  }
}  
```

**Comment by karel-rehor** [comment]
I've moved and rewritten this document as part of the current sprint.  I did this last week.  I tried the -file flag in my examples and it seemed to work.  This will likely be fixed when a PR is created for the branch 'bonitoo-sp4'.  I still have a couple of things to do in it - adding a new document on working with the command line client.  This should happen early next week.

**Comment by karel-rehor** [comment]
OK.  I checked again, and apparently last week I only verified the simpler examples.  The examples (JSON and YAML) are updated in the bonitoo-sp4 branch and verified locally.  Will finish up work in that branch and create PR by next Monday.

**Comment by stevebang** [comment]
Fixed in the bonitoo sp4 PR.
