### ISSUE TITLE
Installation for Debian Stretch for 1.4 also working 

### ISSUE THREAD

**Issue by dl2sba** [influxdata/docs.influxdata.com#1374]
A new line can be added for installation instructions for debian:

curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
test $VERSION_ID = "7" && echo "deb https://repos.influxdata.com/debian wheezy stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "8" && echo "deb https://repos.influxdata.com/debian jessie stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
**test $VERSION_ID = "9" && echo "deb https://repos.influxdata.com/debian stretch stable" | sudo tee /etc/apt/sources.list.d/influxdb.list**

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/introduction/installation/

###### What products and version are you using?
Influx 1.4.2

###### Where did you look before opening the issue?
Docu pages

**Comment by timhallinflux** [comment]
fixed. Thanks @tobiasschaefer
