### ISSUE TITLE
Anchor link for HTTP config is broken

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#1375]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.4/administration/config/

The `Content` bullet point `HTTP settings [http]` is a broken link, so clicking it does not send you to the HTTP settings section. The real heading reads `HTTP endpoint settings [http]`.

**Comment by stevebang** [comment]
Added missing "endpoint" to link for HTTP endpoint settings.
