### ISSUE TITLE
Incorrect Docs for Retention Policy on Enterprise

### ISSUE THREAD

**Issue by dp1140a** [influxdata/docs.influxdata.com#1380]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.3/administration/configuration#retention-autocreate-true

###### What products and version are you using?
Enterprise 1.3.7 but probably applies to all versions

According to the docs when a retention policy is automatically generated for a db it sets the replication factor to the number of nodes.  This is actually incorrect.  According to Engineering this is capped at 3.  So, even if I have 4 or more nodes the replication factor will never go above 3.  This caused an issue with one of our customers.  This subtle point should be made clear:

https://github.com/influxdata/plutonium/blob/master/meta/store.go#L32

**Comment by stevebang** [comment]
This was documented recently to resolve another issue. https://github.com/influxdata/docs.influxdata.com/issues/2238

See: https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#description-of-syntax-1
Added to the retention policy/retention factor section by @kelseiv:
"By default, the replication factor n usually equals the number of data nodes. However, if you have four or more data nodes, the default replication factor n is 3."
