### ISSUE TITLE
Wrong result for 2nd&3rd Sample last()

### ISSUE THREAD

**Issue by dl2sba** [influxdata/docs.influxdata.com#1381]
The result should look like:

> SELECT LAST(*) FROM "h2o_feet"

time                   **last_level description**   **last_water_level**

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/query_language/functions#last

###### What products and version are you using?
1.4

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.4/query_language/functions#last

**Comment by stevebang** [comment]
Thanks, @dl2sba, for catching those.
