### ISSUE TITLE
[Chronograf] - Managing Users document has malformed lists

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/docs.influxdata.com#1385]
The paragraphs describing steps include a series of "numbered" entries, however the only number used is 1) 

Copy paste from page.

"
1) Open Chronograf in your web browser and select Admin (crown icon) > Chronograf. 1) Click the Users tab and then click Create User. 1) Add the following user information: * Username: Enter the username as provided by the OAuth provider. * Role: Select the Chronograf role. * Provider: Enter the OAuth 2.0 provider to be used for authentication. Valid values are: github, google, and auth0. * Scheme: Displays oauth2, which is the only supported authentication scheme in this release. 1) Click Save to finish creating the user."

See also attached screenshot. 
![chonograf-managing-users](https://user-images.githubusercontent.com/25881301/35108515-1437ea88-fc74-11e7-86f9-d8c11c48793c.png)

Using Chrome 63 

###### URL for relevant page?

https://docs.influxdata.com/chronograf/v1.4/administration/managing-chronograf-users/

###### What products and version are you using?

Chronograf 1.4

###### Where did you look before opening the issue?

Filtered through Documentation issues for "Chronograf" but found nothing similar.

**Comment by stevebang** [comment]
Fixed, merged, and should be live with corrections.
