### ISSUE TITLE
Doc issue on "values per second"

### ISSUE THREAD

**Issue by tmd313** [influxdata/docs.influxdata.com#1389]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/concepts/glossary/

###### What products and version are you using?
1.4 docs

###### Where did you look before opening the issue?
It is a doc issue. This does not seem correct. If, however, I'm incorrect or this is just not sufficient to explain the concept could you please clue me in. The rate per second is 200,000, not 4 like is says in the text: 

This is the section I am referring to and quoting:

"**values per second**
The preferred measurement of the rate at which data are persisted to InfluxDB. Write speeds are generally quoted in values per second.
To calculate the values per second rate, multiply the number of points written per second by the number of values stored per point. For example, if the points have four fields each, and a batch of 5000 points is written 10 times per second, then the values per second rate is 4 field values per point * 5000 points per batch * 10 batches per second = 200,000 values per second."

4 is a long way from 200,000 from what I can see.

**Comment by stevebang** [comment]
Closing -- misreading of the text.
