### ISSUE TITLE
Installation Warning Link for V1.4 Leads to 404

### ISSUE THREAD

**Issue by jtswebdev** [influxdata/docs.influxdata.com#1390]
###### URL for relevant page?
- Location of Warning
https://docs.influxdata.com/chronograf/v1.3/introduction/installation/

![screen shot 2018-01-18 at 1 42 24 pm](https://user-images.githubusercontent.com/30440908/35122986-72e17aa0-fc55-11e7-96a1-cef06e66ee20.png)

- URL of Destination, Not Working
https://docs.influxdata.com/chronograf/v1.4/introduction/getting_started/

![screen shot 2018-01-18 at 1 43 04 pm](https://user-images.githubusercontent.com/30440908/35123013-876d9238-fc55-11e7-9592-446804958c1c.png)

###### What products and version are you using?
V1.3 Docs

**Comment by stevebang** [comment]
Fixed in hard-coded version.html file.
