### ISSUE TITLE
probably found a typo: "USEd database"

### ISSUE THREAD

**Issue by LeiRui** [influxdata/docs.influxdata.com#1392]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/query_language/data_exploration/
###### What products and version are you using?
V1.4
###### Where did you look before opening the issue?
-The basic SELECT statement 
-FROM clause
-FROM <measurement_name>
         Returns data from a single measurement. If you’re using the CLI InfluxDB queries the measurement in the **USEd database** and the DEFAULT retention policy. If you’re using the HTTP API InfluxDB queries the measurement in the database specified in the db query string parameter and the DEFAULT retention policy.

**Comment by stevebang** [comment]
Fixed -- thanks, @LeiRui for pointing that out.
