### ISSUE TITLE
Wrong link to Chronograf's Getting Started page

### ISSUE THREAD

**Issue by gerep** [influxdata/docs.influxdata.com#1398]
###### URL for relevant page?
https://docs.influxdata.com

The Chronograf's Getting Started link points to https://docs.influxdata.com/chronograf/v1.4/introduction/getting_started/

The correct link is https://docs.influxdata.com/chronograf/v1.4/introduction/getting-started/

The wrong link uses `_` as a separator and the correct one uses `-`.

**Comment by stevebang** [comment]
Ugh....this is due to an alias not being recognized and a hard-coded link for all TICK components.

**Comment by stevebang** [comment]
Fixed, closing.
