### ISSUE TITLE
Javascript issues on the Kapacitor cli docs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1406]
Seems like there are some javascript issues in the links on this page.

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.4/working/cli_client/

![image](https://user-images.githubusercontent.com/4805997/35636706-e95d5ddc-0666-11e8-861a-e40a140ab7b9.png)

**Comment by stevebang** [comment]
Removed bad formatting and javascript-void causing layout issues.
