### ISSUE TITLE
'High load' claimed, but not backed up

### ISSUE THREAD

**Issue by DaveBender** [influxdata/docs.influxdata.com#1413]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.4/

###### What products and version are you using?
InfluxDB 1.3.5

###### Where did you look before opening the issue?
Google.  Found some old pages that referenced throughput, but it was for a 0.x version.

This page says prominently that InfluxDB can handle high loads, but it doesn't provide any detail of what comprises a high load.  It would be good to have or link to documentation on how much traffic the product can reliably deal with.

> InfluxDB 
>  is a time series database built from the ground up to handle high write and query loads.

**Comment by timhallinflux** [comment]
@DaveBender -- there are plenty of benchmarking details here:
https://www.influxdata.com/?s=benchmarks

I'd rather not have these in our documentation as they are constantly being updated.  But, have a look at those.  Hope that helps!
