### ISSUE TITLE
Please add a sidebar hide control for documentation pages

### ISSUE THREAD

**Issue by eodeluga** [influxdata/docs.influxdata.com#1414]
###### URL for relevant page?
https://docs.influxdata.com/

###### What products and version are you using?
InfluxDB 1.4

###### Where did you look before opening the issue?
Nowhere

This is not a typo but a strong recommendation for improved web design by adding a hide control for the navigation pane / sidebar of the documentation pages

I'm reading from the website as I get up to speed with the DB and a lot screen space is wasted by that navigation side bar that is only required when the user may want to change topic.

Please include a control to hide it.

Thanks.

**Comment by sanderson** [comment]
Thanks for the feedback @eodeluga. We've made a number of updates to the structure and styling of doc pages that should help with this. Having a toggle-able sidebar introduces other UI/UX complexities that, for now, are prioritized behind other pressing documentation issues. We don't plan on making a toggle-able sidebar on the current docs, but we're in the early stages of building a new documentation site. We'll keep your suggestion in mind. I'm closing this issue for now.
