### ISSUE TITLE
Document the filestore file formats

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1417]
_From @goller on December 19, 2017 21:23_

- [ ] - dashboards
- [ ] - sources
- [ ] - kapacitors
- [ ] - organizations

_Copied from original issue: influxdata/chronograf#2618_

**Comment by russorat** [comment]
@goller could you provide more context for this issue?

**Comment by mwz** [comment]
+1

**Comment by stevebang** [comment]
@noramullen1 Check with @russorat to see if this still needs to be documented.
