### ISSUE TITLE
Document _internal database schema

### ISSUE THREAD

**Issue by dp1140a** [influxdata/docs.influxdata.com#1422]
The Internal database captures a lot of statistics and data about what is going on with your Influx Instance.  However there is very little if any documentation on what all the tags and fields actually are measuring.  This leads to a lot of confusion from users as to what they should be watching, what is important and what is not.

Please add some documentation on the fields and schema of the internal database

**Comment by stevebang** [comment]
Thanks, Dave (@dp1140a)! There was a start at this previously, but the content is seriously lacking. An enterprise customer also asked today for this information. @ono760 and I are collecting information to provide some useful documentation on the _internal database. Here is a link to the incomplete page (https://docs.influxdata.com/enterprise_influxdb/latest/troubleshooting/internal_statistics/), which will be reviewed, updated, and expanded on.

**Comment by timhallinflux** [comment]
The /debug/vars endpoint is not listed nor described here:
https://docs.influxdata.com/influxdb/v1.5/tools/api/

**Comment by stevebang** [comment]
The `/debug/vars` endpoint has been added to the API page as of v1.6.2. Documenting relevant `_internal` measurements that are made available in the `/debug/vars` endpoint and content to also appear in upcoming operations guide.

**Comment by stevebang** [comment]
Closing -- documentation on all measurement metrics in OSS and Enterprise added http://docs.influxdata.com/platform/monitoring/tools/measurements-internal/.
