### ISSUE TITLE
apt-transport-https package needed on debian installations

### ISSUE THREAD

**Issue by andor-pierdelacabeza** [influxdata/docs.influxdata.com#1423]
On Debian installation instructions, before adding influx repository, is needed to add the package 'apt-transport-https', or apt won't be able to read the repository. Light server installations usually don't have that package as default.

So, before adding the influx key, it needs a:
`sudo apt-get update && sudo apt-get install apt-transport-https`

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.5/introduction/installation/

###### What products and version are you using?
Telegraf 1.5

###### Where did you look before opening the issue?
On that doc page

**Comment by stevebang** [comment]
Added command to example. Thanks, @andor-pierdelacabeza!
