### ISSUE TITLE
Chronograf Managing Security hyperlinks to a 404

### ISSUE THREAD

**Issue by Gelob** [influxdata/docs.influxdata.com#1426]
Under Configuration & Security the Managing Security hyperlink goes to the URL below which is a 404.

https://docs.influxdata.com/chronograf/v1.4/administration/security-best-practices/

_See Configuring Chronograf for a description of the available configuration options. See Managing security for TLS and OAuth 2.0 setup instructions._

###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.4/introduction/installation/
###### What products and version are you using?
chronograf 1.4
###### Where did you look before opening the issue?
open issues

**Comment by stevebang** [comment]
Thanks for catching that. Fixed, will appear tonight.
