### ISSUE TITLE
Host Status Icon - Always Red

### ISSUE THREAD

**Issue by Jkarmabhutia** [influxdata/docs.influxdata.com#1428]
Host Status Icon Always red, even when the telegraph, influx db and chronograp reside in the same machine and communicating

**Comment by timhallinflux** [comment]
@Jkarmabhutia -- is this a documentation issue?  Sounds like this is a Chronograf issue?

**Comment by stevebang** [comment]
Closing as a doc issue -- added to Chronograf here https://github.com/influxdata/chronograf/issues/2888.
