### ISSUE TITLE
InfluxDB HTTPS setup page links to wrong page for security best practices

### ISSUE THREAD

**Issue by hnk** [influxdata/docs.influxdata.com#1432]
> ###### URL for relevant page?
> https://docs.influxdata.com/influxdb/v1.4/administration/https_setup/

Hello all,

currently browsing your InfluxDB documentation about HTTPS setup at:
https://docs.influxdata.com/influxdb/v1.4/administration/https_setup/

When trying to access the link about **strongly recommended** security, I receive a 404 at:
https://docs.influxdata.com/influxdb/v1.4/administration/security_best_practices/

My guess is, the link should point to:
https://docs.influxdata.com/influxdb/v1.4/administration/security/

Keep it up, team! You have a great product!

**Comment by stevebang** [comment]
Thanks, @hnk, for the catch -- looks like that was broken for a while. Fixed in the code, but fix won't appear until build works again (someone is working on it).
