### ISSUE TITLE
How to improve forecast efficiency. 

### ISSUE THREAD

**Issue by sushilcmd** [influxdata/docs.influxdata.com#1439]
Hello, Currently i’m using Holt winter model for daily sales forecasting. I have two different type of data. One is restaurant data and another one is lifestyle store data.

When I’ve forecasted restaurant data and match with actual data then prediction is approximately same but same model not work on lifestyle store data, the difference between actual sell and predicted sell is very large for lifestyle store data.
Please tell me how to improve this model
code snapshot is give below

![codesnip](https://user-images.githubusercontent.com/10064480/37025332-710d1ad8-2151-11e8-9d3d-bbb721aebcc4.PNG)

**Comment by timhallinflux** [comment]
Hi Sushil,

This is a pretty specific example and not something that we might more generally document for other customers.  I'd suggest that you work with the community team on reviewing and getting some recommendations for this...  https://community.influxdata.com

Thanks...
