### ISSUE TITLE
Merge conflict on page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1444]
###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.4/troubleshooting/frequently-asked-questions/#how-do-i-connect-chronograf-to-an-influxenterprise-cluster

Looks like 
 - [ ] there is a merge issue where i can still see the `<<<<<<<HEAD` stuff

![image](https://user-images.githubusercontent.com/4805997/37126569-751c01d6-2226-11e8-9fcb-596055dda632.png)

**Comment by stevebang** [comment]
Fixed -- also moving content.
