### ISSUE TITLE
Git merge is visible in the Telegraf getting started page

### ISSUE THREAD

**Issue by arielpeltz** [influxdata/docs.influxdata.com#1445]
###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.5/introduction/getting_started/

###### What products and version are you using?
V1.5

###### Where did you look before opening the issue?
The header "Creating and Editing the Configuration File" is present twice clearly from committing a file merged by GIT.  The <<< HEAD and ===== text is visible in the page

**Comment by stevebang** [comment]
Fixed -- thanks, @arielpeltz for catching this.
