### ISSUE TITLE
colours and fills?

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/docs.influxdata.com#1448]
https://docs.influxdata.com/chronograf/v1.4/guides/visualization-types/

Having got this working on Freebsd 11.

There does not appear to be an option to set the colours of line graphs, or the fills.
Once your under the line fill goes away, there is no way to get it back.

Additionally, there is inconsistency between view and edit.
One particular graph has fill on view, but not in edit.

**Comment by russorat** [comment]
@bunnyevans thanks for the report. i opened a bug and feature request on your behalf in Chronograf. I also filed an issue for fixing the broken images in the docs page you referenced: #1464 

Please follow those issues for resolution.
