### ISSUE TITLE
Documentation. "Sample data" table at "Key concept" page has bad layout

### ISSUE THREAD

**Issue by VladimirApolaiko** [influxdata/docs.influxdata.com#1451]
Here is URL of that documentation page: https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/#field-key

I use Safari browser 11.0.3 on Mac book pro 15 inches
Here is a screenshot:
<img width="1078" alt="screen shot 2018-03-16 at 3 07 09 pm" src="https://user-images.githubusercontent.com/8102790/37519887-eee3e55e-292b-11e8-8356-b98939c916c4.png">

**Comment by stevebang** [comment]
Not an issue now.
