### ISSUE TITLE
Specify in documentation that patch doesn't update the running task. It needs to be disabled and enabled. 

### ISSUE THREAD

**Issue by EspenAlbert** [influxdata/docs.influxdata.com#1453]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.4/working/api/#tasks
###### What products and version are you using?
Kapacitor 1.4
###### Where did you look before opening the issue?
In the docs and in the github issues. 

## Proposal ##
Add sentence: ***When patching a task no changes are made to the running task. The task needs to be disabled and enabled for the changes to take effect.*** 
![image](https://user-images.githubusercontent.com/6596097/37555483-003af6d2-29e8-11e8-89bd-6c1521ba2424.png)

## Background ##
I am working on a smarthouse project where we use kapacitor to trigger certain rules from the sensor data. When updating these rules changes are shown when executing ``` kapacitor list {taskname}``` but no changes occur to the running task until you disable and enable the running task (explained in issue 1195). This behaviour can be confusing and should be made explicit. 

Evidence on the confusion can be seen by the numerous github issues:
https://github.com/influxdata/kapacitor/issues/1195
https://github.com/influxdata/kapacitor/issues/1525
https://github.com/influxdata/kapacitor/issues/1510

**Comment by stevebang** [comment]
Thanks, @EspenAlbert, for taking the time to explain the common confusion about the PATCH method behavior when redefining tasks. Changes have also been made here: https://github.com/influxdata/kapacitor/pull/1864.

Fix is in master, and awaiting a new build.
