### ISSUE TITLE
Minor documentation formatting issue

### ISSUE THREAD

**Issue by marcelloromani** [influxdata/docs.influxdata.com#1459]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/introduction/installation/

###### Description
Look for the following two lines in the page:

Set the environment variable INFLUXDB_CONFIG_PATH to the path of your configuration file and start the process.
For example:

There is a bullet point besides "For example:" which should be instead on the preceding line.

**Comment by sanderson** [comment]
Resolved by 11068613f11b3f323ec689a776c3ebfc411eeeb0
