### ISSUE TITLE
Broken images on chrono page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1464]
https://docs.influxdata.com/chronograf/v1.4/guides/visualization-types/

the images at the top and bottom are broken.

**Comment by timhallinflux** [comment]
@stevebang -- Gauge at the bottom of the page is still broken.

**Comment by stevebang** [comment]
Added gauge example image and renamed file to expected name -- just need to understand how to size these images using Hugo to set consistent image sizes on this page.
