### ISSUE TITLE
Revise Series Cardinality Section of the FAQ

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1466]
###### URL for relevant page?
http://docs.influxdata.com/influxdb/v1.5/troubleshooting/frequently-asked-questions/#how-can-i-query-for-series-cardinality

Reflect the existence of SHOW CARDINALITY

**Comment by stevebang** [comment]
Removed this section from the FAQ since it was a workaround for when the SHOW CARDINALITY commands were not available. Included link to SHOW CARDINALITY commands on related topics in FAQ.
