### ISSUE TITLE
Rendering the top left box is broken on these two pages

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1475]
https://docs.influxdata.com/chronograf/v1.4/guides/transition-web-admin-interface/
https://docs.influxdata.com/chronograf/v1.4/guides/transition-web-admin-interface/

![image](https://user-images.githubusercontent.com/4805997/38043269-82638a80-326b-11e8-992a-1a99355a96ca.png)

**Comment by sanderson** [comment]
It looks like these pages were removed from the docs, so the published pages aren't being updated with the template changes which include the "View in Chronograf" functionality. There's a js error that is keeping the rest of the js from running, so the ads aren't loading.

From what I understand, deleted pages remaining on the published site is a known issue. @stevebang, didn't Gunnar have to ssh into each docs host and manually remove deleted pages?

**Comment by sanderson** [comment]
Clarification. This doc wasn't removed, it was moved from `/guides/` to `/administration/`.

**Comment by russorat** [comment]
we link to these pages from inside the chronograf app. if they are removed, could you set up a redirect link so that users don't see a 404?

**Comment by sanderson** [comment]
Sure, that'll need to be updated in the `nginx.conf`s on each of the docs hosts. I don't have the necessary access on AWS to view the host details and connect, but I believe @gunnaraasen can do it.

I'm wondering if it may be better to store the `nginx.conf` in the project so things like this don't require direct write access to the host servers. On deploy, nginx would need to be restarted using the `nginx.conf` in the project directory.

```bash
nginx -c /abs/path/to/nginx.conf
```

**Comment by sanderson** [comment]
Fixed this using Hugo's built-in aliasing functionality.

**Comment by gunnaraasen** [comment]
@sanderson cool, I think Hugo redirects are the preferred way to deal with redirects for one-off page location changes like this.

Good suggestion about keeping the nginx.conf in source control.
