### ISSUE TITLE
Describe how/when to tune InfluxDB Output timeout setting to something other than the default 

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1477]
###### URL for relevant page?
https://github.com/influxdata/telegraf/tree/release-1.5/plugins/outputs/influxdb

When should the write timeout be set greater than 5 sec?
What is the impact of changing this to a larger value?  (is this behavior different between 1.5 and 1.6??)

More guidance is required in terms of tuning the parameters within the InfluxDB Output plugin --- for example:
1. How many input plugins are you using?
2. How many Telegraf agents are directly writing to the DB or are they writing to a queue (i.e. Kafka or NATS)/other intermediary (i.e. Telegraf)?

The behavior of the time

**Comment by stevebang** [comment]
Closing based on @danielnelson's comment.
