### ISSUE TITLE
Typo in TSI details page

### ISSUE THREAD

**Issue by jayeshkul** [influxdata/docs.influxdata.com#1486]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/concepts/tsi-details/

###### What products and version are you using?
v1.5

###### Where did you look before opening the issue?
Issue1:
Under section "Index File Structure", description for "Trailer" should start on new line 

Issue2:
Under section "Manifest", there is a typo in first statement
It says: "The MANIFEST file is stored the index directory ...".
I think, it should be: "The MANIFEST file is stored **_in_** the index directory"

**Comment by sanderson** [comment]
Thanks @jayeshkul. These have been fixed and will be pushed with the next deploy.
