### ISSUE TITLE
Under 'points per second'   vales is mispelled

### ISSUE THREAD

**Issue by gregallentrester** [influxdata/docs.influxdata.com#1490]

**Comment by sanderson** [comment]
Nice catch @gregallentrester. If you find another typo, be sure to include the page that it's on. Luckily this one was pretty unique and easy to find.

**Comment by gregallentrester** [comment]
You have great documentation.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Scott Anderson <notifications@github.com> Date: 4/3/18  6:04 PM  (GMT-06:00) To: "influxdata/docs.influxdata.com" <docs.influxdata.com@noreply.github.com> Cc: gregallentrester <gregallentrester@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [influxdata/docs.influxdata.com] Under 'points per second' vales
  is mispelled (#1490) 
Nice catch @gregallentrester. If you find another typo, be sure to include the page that it's on. Luckily this one was pretty unique and easy to find.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/influxdata/docs.influxdata.com","title":"influxdata/docs.influxdata.com","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/influxdata/docs.influxdata.com"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sanderson in #1490: Nice catch @gregallentrester. If you find another typo, be sure to include the page that it's on. Luckily this one was pretty unique and easy to find."}],"action":{"name":"View Issue","url":"https://github.com/influxdata/docs.influxdata.com/issues/1490#issuecomment-378426840"}}}
