### ISSUE TITLE
Add <lastmod> to all previous version docs in the sitemap.xml

### ISSUE THREAD

**Issue by stevebang** [influxdata/docs.influxdata.com#1495]
All of our pages get new <lastmod> timestamps of the latest build, so to Google, all of our doc pages look like they're new. Apparently, the noindex, nofollow are not very effective.

This fix is for the sitemap.xml, not header.html it seems.

Just like you added the noindex, nofollow", add a lastmod for an older date.  I'll look at see if it makes any difference, but for now let's add a lastmod date, let's say for April 1, 2014 (04/1/14). :) . Just make sure that it's added using the correct format expected by the protocol:

* https://www.sitemaps.org/protocol.html#lastmoddef

For some insights, see:
https://productforums.google.com/forum/#!topic/webmasters/Xr47H4EALMU

**Comment by stevebang** [comment]
It looks like we could add it right after the <priority> tag for each URL in the sitemap.xml file. 

<url> <loc>
   https://docs.influxdata.com/influxdb/v0.13/data_sources/carbon/
</loc>
  <priority>0.1</priority>
</url>

**Comment by stevebang** [comment]
It looks like we can set the Lastmod in this template -- just need to apply it to all non-default versions.

Sitemap Template | Hugo
https://gohugo.io/templates/sitemap-template/

**Comment by stevebang** [comment]
See this doc for more on lastmod: https://webmasters.googleblog.com/2014/10/best-practices-for-xml-sitemaps-rssatom.html

**Comment by sanderson** [comment]
Resolved by ad194caaeadc96f697c42da9436b854bbbbc2f42
