### ISSUE TITLE
improve 404 page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1499]
https://docs.influxdata.com/chronograf/v1.4/templating/template_tag_values/

the 404 page looks broken. things to think about:
- drop down isn't populated
- provide links to the root of the current docs
- provide links to the docs for other products

**Comment by sanderson** [comment]
I'll dig into this, but it'll likely be trickier than it sounds. The 404 page is served by ngnix from a single 404.html file. We'll have to use some js to populate the dropdown with the appropriate context and version, likely using the URL. However, if the cause of the 404 is in the `project/version` path in the URL, that will mess the js up.

@russorat What are your thoughts on removing the project switcher dropdown from the 404 page, but adding contextual links based on the URL. If the appropriate context can't be detected from the URL, it'll just give a link to the docs homepage and/or back to the previous page?

**Comment by russorat** [comment]
whatever we want to do is fine. As long as it doesn't look broken and gives the users somewhere to go, i'm ok with it.
