### ISSUE TITLE
multiple time ranges not allowed in query

### ISSUE THREAD

**Issue by dgnorton** [influxdata/docs.influxdata.com#1511]
Need to update InfluxDB query docs as noted in [this issue comment](https://github.com/influxdata/influxdb/issues/9606#issuecomment-378997801).

**Comment by stevebang** [comment]
Comment copied from influxdb #9606:

@jsternberg thanks for the clarification. I'll flag this for documentation update.

I see two locations in the docs that specifically say OR doesn't work with absolute time but it needs to say something to the effect of OR can't be used to specify multiple time ranges.

https://docs.influxdata.com/influxdb/v1.0/query_language/data_exploration/#issue-2-using-or-with-absolute-time
https://docs.influxdata.com/influxdb/v1.0/troubleshooting/frequently-asked-questions/#why-is-my-query-with-a-where-or-time-clause-returning-empty-results

**Comment by stevebang** [comment]
Based on the comments thread, it seems that adding the text recommended by @dgnorton that "OR can't be used to specify multiple time ranges" addresses the issue of using multiple time periods, whether they are absolute or relative. But the docs mentioned only deal with absolute time. 

@jsternberg mentions that "OR isn't supported at all so you can't select multiple time intervals".

It seems that this also needs to be doc'ed for relative time too, so adding it to the section on "Relative time" too.

**Comment by stevebang** [comment]
Fixed in PR #1788
