### ISSUE TITLE
Pages that don't exist returning status code 200 but should return a 404

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1518]
Example: https://docs.influxdata.com/chronograf/v1.1/introduction/getting_started/

https://support.google.com/webmasters/answer/181708?ctx=tltp

```
curl -I https://docs.influxdata.com/chronograf/v1.1/introduction/getting_started/

HTTP/2 200
content-type: text/html
content-length: 9947
accept-ranges: bytes
date: Fri, 06 Apr 2018 23:45:51 GMT
etag: "5ac7c369-26db"
last-modified: Fri, 06 Apr 2018 18:58:49 GMT
server: nginx/1.4.6 (Ubuntu)
x-cache: Miss from cloudfront
via: 1.1 f12119dc59597a3cbedac2ac64405829.cloudfront.net (CloudFront)
x-amz-cf-id: 5O-DCzEiP6-OFoD7glX1f-c0-TrFd034U0ja8Lg8UopAxqNUaDAa7A==

```

**Comment by timhallinflux** [comment]
Checked on this.  No longer appears to be an issue.

**Comment by russorat** [comment]
our 404 pages are still returning 200s, including the one in this ticket. in my opinion, this is still an issue.

**Comment by sanderson** [comment]
I just made an update to the nginx configurations that should fix this. It works on some missing pages, but doesn't on others. I believe it has something to do with cached pages in CloudFront, but I don't have any access rights to the CloudFront management panel.

Who has access and is it possible to flush cached doc content?

**Comment by timhallinflux** [comment]
The config change appears to have been successful.  Closing...again.

**Comment by russorat** [comment]
yay!
