### ISSUE TITLE
another minor typo (slightly funny)

### ISSUE THREAD

**Issue by mzauzig** [influxdata/docs.influxdata.com#1523]
On page "Using pre-created dashboards in Chronograf" at:

     https://docs.influxdata.com/chronograf/v1.4/guides/using-precreated-dashboards

The following:

     "Open Chronograf in your web browser and lick Host List"

should probably read:

    "Open Chronograf in your web browser and click Host List"

**Comment by timhallinflux** [comment]
I think if you lick the Host List, it will not yield the result you are look for!  Thanks for the heads-up @mzauzig!
