### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#1531]
**/chronograf/v1.4/guides/create-a-dashboard/**
- [ ] (305:3) <img> => http://localhost:1313/img/chronograf/v1.4/g-dashboard-cell-edit.png (HTTP 404)

**/chronograf/v1.4/guides/visualization-types/**
- [ ] (380:3) <img> => http://localhost:1313/img/chronograf/chrono-viz-step-graph-selector.png (HTTP 404)
- [ ] (384:3) <img> => http://localhost:1313/img/chronograf/chrono-viz-step-graph-controls.png (HTTP 404)
- [ ] (412:3) <img> => http://localhost:1313/img/chronograf/chrono-viz-step-graph-example.png (HTTP 404)

**/enterprise_influxdb/v1.5/**
- [ ] (290:3) <img> => http://localhost:1313/img/chronograf/v1.5/admin-usermanagement-cluster.png (HTTP 404)

**Comment by stevebang** [comment]
Fixed misnamed links. Resolved in Chrono-1.4.4 branch, due to merge today.

**Comment by stevebang** [comment]
All fixed and included in chrono-1.4.4 branch update
