### ISSUE TITLE
Add examples for username and password for http calls to secure Kapacitor

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1534]
https://docs.influxdata.com/kapacitor/v1.4/administration/security/

user request was to add some examples of how to connect to a secure kapacitor using curl

**Comment by stevebang** [comment]
@russorat I'm currently reviewing a PR (https://github.com/influxdata/docs.influxdata.com/pull/1526) that includes Kapacitor security topics and includes an example for this, I believe.  It should be merged into our current docs later today.

**Comment by stevebang** [comment]
Fixed with merging of PR from Bonitoo https://github.com/influxdata/docs.influxdata.com/pull/1526
