### ISSUE TITLE
Redirected on v1.4 documentation

### ISSUE THREAD

**Issue by pcasis** [influxdata/docs.influxdata.com#1537]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/

Hi,

On the previous page, if I click on a key word like database or serie, I'm redirected on https://docs.influxdata.com/influxdb/v1.4/concepts/key_concepts/#database
instead of https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/#database

There is a version issuen at least in the url.

**Comment by sanderson** [comment]
Thanks for the heads up @pcasis
