### ISSUE TITLE
Update Chronograf Release Notes to reflect Chronograf/#3168

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1544]
Add the following into the respective 1.4.x areas of the release notes.

### Bug Fixes
1. [#3168](https://github.com/influxdata/chronograf/pull/3168): Require that emails on GitHub & Generic OAuth2 principals be verified & primary, if those fields are provided

### Bug Fixes
1. [#3168](https://github.com/influxdata/chronograf/pull/3168): Require that emails on GitHub & Generic OAuth2 principals be verified & primary, if those fields are provided

### Bug Fixes
1. [#3168](https://github.com/influxdata/chronograf/pull/3168): Require that emails on GitHub & Generic OAuth2 principals be verified & primary, if those fields are provided

### Bug Fixes
1. [#3168](https://github.com/influxdata/chronograf/pull/3168): Require that emails on GitHub & Generic OAuth2 principals be verified & primary, if those fields are provided

**Comment by sanderson** [comment]
Resolved by a5bdfd850454b090d40d48db6071b9727ff9961e
