### ISSUE TITLE
Query Engine

### ISSUE THREAD

**Issue by benbjohnson** [influxdata/docs.influxdata.com#155]
The new query engine should be largely backwards compatible but I'm adding this issue to track differences.

https://github.com/influxdata/influxdb/pull/5196

**Comment by benbjohnson** [comment]
`SELECT DISTINCT(value)` previously returned an array of values.  It will now return a separate row for each value.

**Comment by rkuchan** [comment]
Queries with `LIMIT` and `SLIMIT` work - must be in that order.
