### ISSUE TITLE
Cluster Documentation for 0.10.0

### ISSUE THREAD

**Issue by jwilder** [influxdata/docs.influxdata.com#156]
There are a number of cluster documentation changes related to the config file for 0.10.0.  See https://github.com/influxdata/influxdb/issues/5168#issuecomment-172064348 for some of the changes.

This PR https://github.com/influxdata/influxdb/pull/5132 is the actual change to be merged.

**Comment by rkuchan** [comment]
@jackzampolin, for `config.md`.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/190
