### ISSUE TITLE
Document deployment to Kubernetes 

### ISSUE THREAD

**Issue by ono760** [influxdata/docs.influxdata.com#1565]
Should add documentation on how to deploy an InfluxDB cluster using Kubernetes. Currently I don't see any docs on this.  Maybe this is relevant? https://www.influxdata.com/blog/how-to-spin-up-the-tick-stack-in-a-kubernetes-instance/

**Comment by sanderson** [comment]
Closing in favor of https://github.com/influxdata/docs.influxdata.com/issues/2063.
