### ISSUE TITLE
Difficult to read Chronograf Auth0 configuration requirements

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/docs.influxdata.com#1570]
The horizontally-scrollable text box here makes it difficult to use this information due to scrolling and difficulty in parsing length horizontal text:
<img width="951" alt="screen shot 2018-04-19 at 5 33 02 pm" src="https://user-images.githubusercontent.com/6403018/39024778-e730e78a-43f7-11e8-9d43-c8be2f4dac96.png">

###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.4/administration/managing-security/#creating-an-auth0-application

###### What products and version are you using?
Chronograf 1.4.4.x

**Comment by stevebang** [comment]
Fixing by reformatting content.
