### ISSUE TITLE
Chronograf Auth0 config requires `PUBLIC_URL` but is not evident as required in config section

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/docs.influxdata.com#1571]
To get Auth0 working as an identity provider for Chronograf, `PUBLIC_URL` is required. This env var is not listed under the auth0 configuration options sections required for successful config.

###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.4/administration/managing-security/#creating-an-auth0-application

###### What products and version are you using?
Chronograf 1.4.4.x

**Comment by stevebang** [comment]
Moved `PUBLIC_URL` from "Google-specific authentication options" to "General authentication options" section.

**Comment by jaredscheib** [comment]
Thanks @stevebang!
