### ISSUE TITLE
Incorrect port (9093) listed in "Example 1"

### ISSUE THREAD

**Issue by shineygreen** [influxdata/docs.influxdata.com#1574]
The first line of "Example 1" for the Kapacitor CLI client documentation uses port 9093. Previous documentation lists port 9092 as the default. Make up your minds.

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.4/working/cli_client/

###### What products and version are you using?
Kapacitor 1.4

###### Where did you look before opening the issue?
https://docs.influxdata.com/kapacitor/v1.4/introduction/getting-started/

**Comment by sanderson** [comment]
Thanks for the heads up @shineygreen. This was likely just a typo and has been fixed. It'll be deployed with the next docs build.
