### ISSUE TITLE
optimzation --> optimization

### ISSUE THREAD

**Issue by zhaitianduo** [influxdata/docs.influxdata.com#1576]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/concepts/storage_engine/

###### What products and version are you using?
I'm not using it currently, I'm reading the docs of v1.5

###### Where did you look before opening the issue?
#compactions/Index Optimization

**Comment by sanderson** [comment]
Nice catch @zhaitianduo! Thanks for letting us know.
