### ISSUE TITLE
Doc Update? Additional note about using telegraf.d dir

### ISSUE THREAD

**Issue by bmagistro** [influxdata/docs.influxdata.com#1589]
I was referencing #486 for information about using telegraf.d, specifically 

> Number (1) is probably a bug, if there is a valid file in telegraf.d we should be able to start Telegraf without specifying a singular .conf file.

While this setup may be "non-standard", we have shifted all configuration items to be loaded from files in telegraf.d.  When initially tried, I had omitted /etc/telegraf/telegraf.conf and that will cause telegraf to fail to start.  To solve this, adding an empty telegraf.conf file allows everything to work and all config files to live in telegraf.d.

From looking at this further the source comes from the telegraf.service file specifying --config and --config-dir.

**Comment by stevebang** [comment]
This issue was moved to influxdata/telegraf#5571

**Comment by stevebang** [comment]
Moved issue to https://github.com/influxdata/telegraf/issues/5571.
