### ISSUE TITLE
Documentation: Continous Queries example/explanation mismatch

### ISSUE THREAD

**Issue by goliatone** [influxdata/docs.influxdata.com#159]
CQ examples. Create a CQ with one function and write the results to another retention policy:
**The retention policy used in the query is *7days* yet in the explanation it is stated as *4hours*.**

Query:
```
> CREATE CONTINUOUS QUERY minnie_jr ON world BEGIN SELECT min(mouse) INTO world."7days".min_mouse FROM world."1day".zoo GROUP BY time(30m) END
```
Explanation:
>The CQ minnie_jr acts in the same way as the CQ minnie, however, InfluxDB calculates the 30 minute minimum of the field mouse in the measurement zoo and under the retention policy 1day, and it automatically writes the results of the query to the measurement min_mouse under the retention policy _4hours_.

**Comment by rkuchan** [comment]
Thanks, @goliatone! Fixed by https://github.com/influxdata/docs.influxdata.com/pull/161.
