### ISSUE TITLE
Document that meta node size impacts backup/restore performance

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs.influxdata.com#1590]
An InfluxDB Enterprise backup will copy all data through the meta node used to execute the backup. This means the performance of a backup (and restore) is typically limited by the network IO of the meta node.

Increasing the resources available to the meta node used for a backup (such as resizing the EC2 instance) can significantly improve backup performance.

This should be mentioned on the InfluxDB Enterprise backup/restore page. 

###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.5/administration/backup-and-restore/

###### What products and version are you using?
InfluxDB Enterprise v1.5

**Comment by stevebang** [comment]
Added a note to Enterprise backup utility covering this.
