### ISSUE TITLE
Document Anti-Entropy enhancements in InfluxDB Enterprise 1.6

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1592]
https://docs.influxdata.com/enterprise_influxdb/v1.5/administration/anti-entropy/
The AE administrative content should also be updated to highlight that the AE service will now inspect and repair data inconsistencies detected within a shard....across shard owners.

and

https://docs.influxdata.com/enterprise_influxdb/v1.5/features/cluster-commands/

Starting in InfluxDB Enterprise 1.6.0 `influxd-ctl` has been updated to include Anti-Entropy commands.  
`influxd-ctl entropy -help` lists what commands are available.

```Usage: influxd-ctl [options] entropy <command> [options] [<args>]

Available commands are:
   show        Show shard entropy
   repair      Repair entropy found in a shard
   kill-repair Cancel repair entropy request for shard

Options:

  -auth-type string
    	Type of authentication to use (none, basic, jwt) (default "none")
  -bind string
    	Bind HTTP address of a meta node (default "localhost:8091")
  -bind-tls
    	Use TLS
  -config string
    	Config file path
  -k	Skip certficate verification (ignored without -bind-tls)
  -pwd string
    	Password (ignored without -auth-type jwt)
  -secret string
    	JWT shared secret (ignored without -auth-type jwt)
  -user string
    	User name (ignored without -auth-type basic | jwt) 
```

There are `show`, `repair`, and `kill-repair` sub-commands

The `influxd-ctl` instructions need to be updated to reflect this.

**Comment by dgnorton** [comment]
Noticed this [in the docs](https://docs.influxdata.com/enterprise_influxdb/v1.5/guides/replacing-nodes/) while looking something up...

> Meta nodes also handle the anti-entropy (AE) process that ensures data nodes have the shards they need.

Meta nodes hold information about which data nodes own which shards. Data nodes handle AE. I.e., the AE service runs on each data node and references the meta nodes to see which shards it (the data node) should have.

**Comment by sanderson** [comment]
Thanks @dgnorton, this ^ has been corrected.

**Comment by stevebang** [comment]
Accidentally remove @sanderson.
