### ISSUE TITLE
Confusion in StateDurationNode docs

### ISSUE THREAD

**Issue by stevebang** [influxdata/docs.influxdata.com#1596]
In the feature request filed here:
https://github.com/influxdata/kapacitor/issues/1757)

@AdamSLevy mentions that "the behavior differs from what is documented" and "The documentation requires a somewhat thorough and careful reading to understand how this node is supposed to work."

Here is our StateDurationNode page:
https://docs.influxdata.com/kapacitor/v1.4/nodes/state_duration_node/

Let's review the content and see what can be improved

**Comment by sanderson** [comment]
@AdamSLevy, can you provide details on the behavior you're seeing?

**Comment by AdamSLevy** [comment]
@sanderson I described this in quite a bit of detail in the original feature request InfluxData/kapacitor#1757. Have you read that? Is there something specific that you want to know that I haven't already written up?

**Comment by sanderson** [comment]
Thanks @AdamSLevy. I somehow missed the link to the kapacitor issue in the original post. I'll read through the thread and let you know if I have any questions.
