### ISSUE TITLE
A Typo in Continuous Queries.InfluxQL for creating a CQ

### ISSUE THREAD

**Issue by AlexanderYAPPO** [influxdata/docs.influxdata.com#160]
In the example section, the given query is this:
> CREATE CONTINUOUS QUERY minnie_jr ON world BEGIN SELECT min(mouse) INTO world."**7days**".min_mouse FROM world."1day".zoo GROUP BY time(30m) END

But the text below says:
> The CQ minnie_jr acts in the same way as the CQ minnie, however, InfluxDB calculates the 30 minute minimum of the field mouse in the measurement zoo and under the retention policy 1day, and it automatically writes the results of the query to the measurement min_mouse under the retention policy **4hours**.

So, the typo is that the end of the sentence should be "... and it automatically writes the results of the query to the measurement min_mouse under the retention policy **7days**"

**Comment by rkuchan** [comment]
Thanks, @AlexanderYAPPO! Fixed by https://github.com/influxdata/docs.influxdata.com/pull/161.
