### ISSUE TITLE
Document SHOW STATS FOR 'indexes'

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/docs.influxdata.com#1610]
https://github.com/influxdata/influxdb/issues/9766

https://docs.influxdata.com/influxdb/v1.5/administration/server_monitoring/#show-stats

Please document this new feature. It's important to note that `SHOW STATS` will *not* list index memory usage. 'indexes' must be explicitly requested because this can be an expensive metric to collect. We walk most of the index data structures recursively, so bigger indexes will take more time to count bytes.

**Comment by stevebang** [comment]
Fixed in recent PR -- https://docs.influxdata.com/influxdb/v1.6/query_language/spec/#show-stats
