### ISSUE TITLE
Documentation links pointing to v1.4

### ISSUE THREAD

**Issue by massimoforni** [influxdata/docs.influxdata.com#1611]
In https://docs.influxdata.com/influxdb/v1.5/concepts/key_concepts/ on the last paragraph, all the links point to v1.4
 Authentication and Authorization => https://docs.influxdata.com/influxdb/v1.4/query_language/authentication_and_authorization/
Continuous Queries => https://docs.influxdata.com/influxdb/v1.4/query_language/continuous_queries/
Getting Started => https://docs.influxdata.com/influxdb/v1.4/introduction/getting_started/
Writing Data => https://docs.influxdata.com/influxdb/v1.4/guides/writing_data/
Querying Data => https://docs.influxdata.com/influxdb/v1.4/guides/querying_data/

**Comment by stevebang** [comment]
Closing -- fixed in master
