### ISSUE TITLE
Add setup instructions and example config files for popular kubernetes container platforms

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1612]
We should add documentation instructions for setting influx products up on popular cloud providers.

- [ ] document how to configure and set up the tick stack locally in docker
- [ ] document how to configure and set up the tick stack on kubernetes (include configs)
  - [ ] telegraf as a sidecar and a daemonset
  - [ ] influxdb, chronograf, kapacitor with persistent volumes
- [ ] document how to configure and set up the tick stack on Amazon EKS https://aws.amazon.com/eks/ (include configs) (should be very similar to others)
- [ ] document how to configure and set up the tick stack on OpenShift (include configs) (should be very similar to others)

**Comment by timhallinflux** [comment]
linking #1565

**Comment by sanderson** [comment]
Closing in favor of https://github.com/influxdata/docs.influxdata.com/issues/2063.
