### ISSUE TITLE
Document Kapacitor subscriptions and replicating data between data centers

### ISSUE THREAD

**Issue by stevebang** [influxdata/docs.influxdata.com#1620]
We need better documentation on Kapacitor subscriptions. Included here are links to a blog posting and various tidbits of information in the InfluxDB documentation.

[Multiple Data Center Replication with InfluxDB](https://www.influxdata.com/blog/multiple-data-center-replication-influxdb/)
- written by @dp1140a
- includes steps on replicating data between clusters using subscriptions

[InfluxDB Enterprise clustering features](https://docs.influxdata.com/enterprise_influxdb/v1.5/features/clustering-features/#subscriptions)
- This "Subscriptions" section includes only the following (this is the entire section):
"Subscriptions used by Kapacitor work in a cluster. Writes to any node will be forwarded to subscribers across all supported subscription protocols."

**InfluxQL subscription-related commands**
- [CREATE SUBSCRIPTION](https://docs.influxdata.com/influxdb/v1.5/query_language/spec/#create-subscription)
- [DROP SUBSCRIPTION](https://docs.influxdata.com/influxdb/v1.5/query_language/spec/#drop-subscription)
- [SHOW SUBSCRIPTION](https://docs.influxdata.com/influxdb/v1.5/query_language/spec/#show-subscriptions)

**`subscription-protocol` setting (`kapacitor.conf`)**
[Kapacitor and InfluxDB HTTPS](https://docs.influxdata.com/kapacitor/v1.4/administration/security/#kapacitor-and-influxdb-https)
- This section has two Kapacitor configuration examples that use the `subscription-protocol` setting:

subscription-protocol – to declare the correct protocol for subscription communications. For example if Kapacitor is to run on HTTP then this should be set to "http", however if Kapacitor is to run on “HTTPS” then this should be set to "https".

[Securing Kapacitor Enterprise](https://docs.influxdata.com/enterprise_kapacitor/v1.4/administration/security/#securing-kapacitor-enterprise)
- Includes a section on "Kapacitor Enterprise over TLS" that briefly mentions `subscription-protocol` settings

**Comment by timhallinflux** [comment]
reference #1319 and close both when complete

**Comment by stevebang** [comment]
Closing #613 as a dup of this, but make sure to verify UDP/TCP discussion in that is covered here.

**Comment by stevebang** [comment]
Note question on Kapacitor subscriptions and clusters here: https://github.com/influxdata/kapacitor/issues/2002

**Comment by stevebang** [comment]
Closing as Scott documented the subscription behavior. MDCR can be skipped for now -- not high-demand for this.
