### ISSUE TITLE
Add documentation for series-file path for influx_inspect dumptsi 

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1622]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/tools/influx_inspect/#influx-inspect-dumptsi

###### What products and version are you using?
1.5.2 

The series-file parameter is required in order for the dumptsi command to work.  Add documentation to describe that parameter and it's function.

**Comment by stevebang** [comment]
Fixed in this PR https://github.com/influxdata/docs.influxdata.com/pull/1627
