### ISSUE TITLE
stop all service about chronograf and telegraf and kapacitor,why my console are still running  data fetch?

### ISSUE THREAD

**Issue by iver3on** [influxdata/docs.influxdata.com#1625]
###### What products and version are you using?
influxdb 1.5
others are latest version,

**Comment by iver3on** [comment]
018-05-22T11:32:50.002258Z     info    Post http://localhost:9092/write?consistency=&db=_internal&precision=ns&rp=monitor: dial tcp [::1]:9092: getsockopt: connection refused   {"log_id": "08DgTS1l000", "service": "subscriber"}

**Comment by sanderson** [comment]
@iver3on, issues submitted on for this should be centered around the documentation of the TICK stack. This appears to be a general troubleshooting issue. I would suggest posting this issue on the [InfluxData Community](https://community.influxdata.com/) where other Influxers can help troubleshoot.
