### ISSUE TITLE
[new page] document how to read logs

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#163]
Could add to the [existing page](https://docs.influxdata.com/influxdb/v0.10/administration/logs/) or start a new one.

v0.9 link:  https://docs.influxdata.com/influxdb/v0.9/administration/logs/

**Comment by beckettsean** [comment]
Mention:
- logging levels: what exists, how to set, what can't be squelched
- explain common log messages and what each column means
- explain what to do with uncommon log messages (E.g copy/paste first 20 lines of any panic into a new GHI, provided searching for the panic on GHI finds no matches already)

**Comment by beckettsean** [comment]
Esp how to find performance numbers (response times, write times) and how to identify queries that never returned (no matching `[http]` return log line)

**Comment by timhallinflux** [comment]
closing as this is addressed with the logging update provided in v1.5
