### ISSUE TITLE
Different info for ManageShard permission on different pages

### ISSUE THREAD

**Issue by gshif** [influxdata/docs.influxdata.com#1631]
###### URL for relevant page?  Chronograf
https://docs.influxdata.com/chronograf/v1.4/administration/managing-influxdb-users/#createdatabase
>ManageShard
Permission to copy, delete, and view shards.
Relevant InfluxQL queries: DropShardStatement, ShowShardGroupsStatement, and ShowShardsStatement
Pages in Chronograf that require this permission: NA

###### URL for relevant page? InfluxDB Enterprise V1.5
https://docs.influxdata.com/enterprise_influxdb/v1.5/features/users/#permissions
>Manage Shards
Permission to copy and delete shards

There is one more permission called `Copy Shard` that is relevant to `influx-ctl copy-shard`command
Since `CopyShard` is a separate permission then I think:
- Remove permission to copy from InfluxDB Enterprise doc. At the same time under `Permission to Statement` (https://docs.influxdata.com/enterprise_influxdb/v1.5/features/users/) header the correct queries are mentioned: 
>ManageShardPermission | DropShardStatement,ShowShardGroupsStatement,ShowShardsStatement

- Make description for `ManageShard`permission in sync between chronograf and influxdb.
DropShardStatement, ShowShardGroupsStatement, and ShowShardsStatement that are mentioned in chronograf are the same as `DROP SHARD`, `SHOW SHARD GROUPS` and `SHOW SHARDS` queries run from using `influx` command from one of the data nodes. But shard can be managed by using `influx-ctl` command as well :
https://docs.influxdata.com/enterprise_influxdb/v1.5/features/cluster-commands/#show-shards
https://docs.influxdata.com/enterprise_influxdb/v1.5/features/cluster-commands/#remove-shard
The question is for @timhallinflux : Should `influx-ctl` show and remove shards be mentioned on the list of permissions?

**Comment by gshif** [comment]
@rbetts - FYI

**Comment by gshif** [comment]
Also, @timhallinflux , should the following `influx-ctl` commands be documented for `CopyShard` Permissions:
>copy-shard          Copy a shard between data nodes
   copy-shard-status   Show all active copy shard tasks
   kill-copy-shard     Abort an in-progress shard copy

**Comment by kelseiv** [comment]
keep open
