### ISSUE TITLE
[new page] upgrade from 0.9x to 0.10x

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#164]
This page is [stubbed out](https://docs.influxdata.com/influxdb/v0.10/administration/upgrading/) and mainly links to the [README.md](https://github.com/influxdata/influxdb/tree/master/cmd/influx_tsm) about the conversion tool.

v0.9 link: https://docs.influxdata.com/influxdb/v0.9/administration/upgrading/

**Comment by beckettsean** [comment]
Upgrade considerations:

How do users identify non-tsm shards?
How do users know if a shard is cold for writes?
Is there a way to convert the shards with zero downtime?
How long per GB does the conversion take for b1, for bz1?
How can users most easily re-issue CQs for the new syntax?

Presumed upgrade path:
install 0.10 on top of running 0.9
update config files
bounce process
copy cold shards to conversion box
convert shards
copy shards back on top of old shards on running server
wait for current shard period to end and repeat conversion for the now cold shards

Lots of holes in that still to be figured out.

**Comment by rkuchan** [comment]
Per conversation with Sean:
* How to make a backup
* Convert shards to TSM
