### ISSUE TITLE
Typo in Contributing new Kapacitor output nodes page

### ISSUE THREAD

**Issue by ninjadude333** [influxdata/docs.influxdata.com#1641]
###### URL for relevant page?
http://docs.influxdata.com/kapacitor/v1.5/about_the_project/custom_output/

###### What products and version are you using?
kapacitor 1.5.0

###### Where did you look before opening the issue?
a tutorial on how to create a node

![image](https://user-images.githubusercontent.com/22522103/40613578-bf8c6994-6287-11e8-910d-0f26af7f1adc.png)

**Comment by sanderson** [comment]
@ninjadude333 I'm having trouble identifying what character you're saying it should be. Can you confirm what character it should be?

**Comment by ninjadude333** [comment]
hi, it should be "d", like all the rest switch cases...
