### ISSUE TITLE
Bullet points don't have newlines in website

### ISSUE THREAD

**Issue by k1-hedayati** [influxdata/docs.influxdata.com#1645]
Hello, in last paragraph of https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.5/concepts/crosswalk.md multiple points are separated using bullet points but in website these newline doesn't exist

###### URL for relevant page? 
https://docs.influxdata.com/influxdb/v1.5/concepts/crosswalk/

###### What products and version are you using?
v1.5

**Comment by stevebang** [comment]
Fixed by #1640 -- change waiting for new doc build. Thanks, @k1-hedayati, for pointing this out.
