### ISSUE TITLE
[new page] [all products] Administration - Production config

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#165]
Our products are all currently configured for the developer use case, with security disabled, everything talking over localhost, etc.

We should have a page for each product that describes the config and architecture choices we recommend users evaluate when moving from dev to production.

**Comment by beckettsean** [comment]
Page should also mention client libraries, telegraf, kapacitor, etc. in appropriate context for best production architecture. Basically "don't roll your own, use tools in the ecosystem"

**Comment by beckettsean** [comment]
Need to mention https://github.com/influxdata/influxdb/pull/6444

**Comment by stevebang** [comment]
Closing -- while a good idea, best use of doc team time is adding production guidelines for 2.0.
