### ISSUE TITLE
Typo in v1.5/query_language/data_exploration/

### ISSUE THREAD

**Issue by Bosma** [influxdata/docs.influxdata.com#1650]
https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/

In the following, `time >= 2015-08-12T00:12:00Z AND time < 2015-08-18T00:24:00Z`, the `2015-08-12` should be `2015-08-18`. This occurs 4 times on the above page.

This is because the query being discussed is `SELECT COUNT("water_level") FROM "h2o_feet" WHERE "location"='coyote_creek' AND time >= '2015-08-18T00:06:00Z' AND time < '2015-08-18T00:18:00Z' GROUP BY time(12m)`, which only includes a 24 minute segment on the 18th, not the 12th.

**Comment by sanderson** [comment]
Nice catch. Thanks @Bosma!
