### ISSUE TITLE
Update Hardware Recommendations for TSI/TSM

### ISSUE THREAD

**Issue by brettwooldridge** [influxdata/docs.influxdata.com#1651]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.5/guides/hardware_sizing/

###### What products and version are you using?
InfluxDB

###### Where did you look before opening the issue?
Issue tracker, user forums.

-----------------------------------------------------
Given the introduction of the Time Series Index, with a substantially different memory profile, and different relation of cardinality to footprint, do the hardware specifications need to be updated?

Basically, when using TSI vs TSM, what are the appropriate values in the following table for TSI and the following hardware recommendations?

Load | Field writes per second per node | Moderate queries per second per node | Unique series per node
-- | -- | -- | --
Low | < 5 thousand | < 5 | < 100 thousand
Moderate | < 100 thousand | < 25 | < 1 million
High | > 100 thousand | > 25 | > 1 million
Probably infeasible | > 500 thousand | > 100 | > 10 million

Low load recommendations
CPU: 2 cores
RAM: 2-4 GB
IOPS: 1000

Moderate load recommendations
CPU: 4-6
RAM: 8-32GB
IOPS: 1000+

High load recommendations
CPU: 8+
RAM: 32+ GB
IOPS: 1000+

**Comment by stevebang** [comment]
@deanasheehan is working on (hopefully, almost complete) with technical content for this page. Existing page accidentally snuck back into the docs -- remove or update ASAP.

**Comment by kelseiv** [comment]
Thank you, @brettwooldridge! Please check out our recently updated [hardware sizing guidelines](https://docs.influxdata.com/influxdb/v1.7/guides/hardware_sizing).
