### ISSUE TITLE
[0.10] Schema Design Review

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#166]
The Schema Design page was created before the tsm storage engine became the default, so we should review the recommendations laid out on that page to ensure everything is still correct. Mainly:

> it is recommended that you encode most metadata into the series `Tags`. Tags are indexed within the InfluxDB system allowing fast querying by 1 or more tag values.

And:

> And the optimal way to structure things is to have many series and a single field named "value" (or some other key of your choice) used consistently across all series.

**Comment by rossmcdonald** [comment]
@jwilder Can you review the two block comments above and let us know what should be changed (if anything)? 

Let me know if you'd like to have a hangout to discuss in more depth.

**Comment by jwilder** [comment]
The second block may not be accurate now.  I think it depends more on how you would query the data and what's possible with the query engine. A measurement with multiple fields gets stored basically the same as multiple measurements with a common field name.
