### ISSUE TITLE
REQUEST:  Documentation for InfluxCloud / Chronograf

### ISSUE THREAD

**Issue by chadothompson** [influxdata/docs.influxdata.com#1662]
As we're going through a process of implementing InfluxCloud, we're finding some differences (talking with support) in how InfluxCloud works vs. other versions.

In particular, the authentication mechanisms for Influx Cloud are

a) . Configured to `auth0` only.
b). Limited to 10 users.
c). Must be created through the `cloud.influxdata.com` interface (to create users in `auth0`)

(Though in general there is almost no documentation on InfluxCloud and the particulars of operating in that environment.)

###### URL for relevant page?

https://docs.influxdata.com/chronograf/v1.5/administration/managing-security/

###### What products and version are you using?

Influx Cloud / Chronograf v. 1.5

###### Where did you look before opening the issue?

Looked at documentation. contacted reps and support - finding this through those channels.

**Comment by sanderson** [comment]
Thanks @chadothompson. InfluxCloud is a separate project than the core TICKstack and is documented separately at https://help.influxcloud.net/. Since InfluxCloud is a separate hosted service, the Influx OSS/Enterprise documentation are handled separately. This is unique to InfluxCloud and should be included in the cloud docs. I've referenced this issue there, but it's currently a private repo, so you won't be able to access it.

**Comment by chadothompson** [comment]
Thank you!

I'll note that the Influx Cloud documentation is pretty sparse when it
comes to this kind of detail - let me know if I can be of help.
--- Chad

--
  Chad Thompson
  git@chadthompson.me



On Wed, Jun 6, 2018, at 6:26 PM, Scott Anderson wrote:
> Closed #1662[1].


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].

Links:

  1. https://github.com/influxdata/docs.influxdata.com/issues/1662
  2. https://github.com/influxdata/docs.influxdata.com/issues/1662#event-1667346932

**Comment by timhallinflux** [comment]
We have added: https://help.influxcloud.net/managing-users/
