### ISSUE TITLE
doc bug on kapacitor/v1.5/event_handlers/email/

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/docs.influxdata.com#1664]
###### URL for relevant page?

http://docs.influxdata.com/kapacitor/v1.5/event_handlers/email/

###### What products and version are you using?

Kevins-MBP:~ kevin$ kapacitor version
Kapacitor  v1.5.0 (git:  4f10efc41b4dcac070495cf95ba2c41cfcc2aa3a)

The last example on this page reads:

```
email_cpu_handler.yaml

id: email-cpu-alert
topic: cpu
kind: email
options:
  to:
    - oncall1@mydomain.com
    - oncall2@mydomain.com
Add the handler:

kapacitor define-topic-handler email_cpu_handler.yaml

```
^^ this does not work as written.  If you run this it will output:
```
Kevins-MBP:~ kevin$ kapacitor define-topic-handler email_cpu_handler.yaml
failed to create handler: unsupported action kind "email"

```

`kind: email` should be replaced w `kind: smtp`  -- tested locally this works

**Comment by sanderson** [comment]
Thanks @kevinhogan111. Can you try with `smtp`? If that works, I'll update it.
