### ISSUE TITLE
Update `max-concurrent-compactions` in 1.5 

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1665]
###### URL for relevant page?
http://docs.influxdata.com/influxdb/v1.5/administration/config/
and
http://docs.influxdata.com/enterprise_influxdb/v1.5/administration/configuration/#max-concurrent-compactions-0

###### What products and version are you using?
1.5.x

The current text reads:
The maximum number of concurrent full and level compactions that can run at one time. A value of 0 results in runtime.GOMAXPROCS(0) used at runtime – which means use all processors. This setting does not apply to cache snapshotting.

This was true to 1.3.x

However, the algorithm has changed.  
A value of 0 results in (processors / 2) -- if the reported value is less than 8.  
If the reported value is 8 or more, the value of 4 is used.

If you wish to use MORE processors for compactions, this setting can be used to increase the amount of processors used.  This is highly recommended for clusters with a large number of processors and a large amount of data ingestion.

**Comment by e-dard** [comment]
@timhallinflux, I noticed this too and mentioned to @stevebang on our channel. I’ll look over the resulting PR.

**Comment by stevebang** [comment]
Closing -- new description of changes in #1669 .
