### ISSUE TITLE
drop database telegraf_bak instead of drop telegraf_bak

### ISSUE THREAD

**Issue by rgarrigue** [influxdata/docs.influxdata.com#1670]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/latest/administration/backup_and_restore/

(or v1.5 instead of latest)

![image](https://user-images.githubusercontent.com/1872031/41223140-3ed843c6-6d69-11e8-89e2-ed4e8bb67a65.png)

**Comment by stevebang** [comment]
Fixed in master -- will appear in next build.
