### ISSUE TITLE
1.5.3 download link isn't working

### ISSUE THREAD

**Issue by musca001** [influxdata/docs.influxdata.com#1672]

**Comment by timhallinflux** [comment]
Could not reproduce.  What OS are you attempting to download?  I was able to get this to work with both RedHat/CentOS and Ubuntu/Debian....  I didn't test them all after these two worked.

**Comment by musca001** [comment]
Hi,

Thx for the follow up. I’m on Mac OS X (latest version). Tried Safari, Chrome and FF and neither  would take me to the link.

Ended up installing the influxdb repo manually on the target machine and upgraded using yum.

All set now. Thank you!

Dan Musca

On Jun 12, 2018, at 4:04 AM, timhallinflux <notifications@github.com<mailto:notifications@github.com>> wrote:


Could not reproduce. What OS are you attempting to download? I was able to get this to work with both RedHat/CentOS and Ubuntu/Debian.... I didn't test them all after these two worked.

**Comment by timhallinflux** [comment]
For OS X -- we use brew. (see screenshot below).

What links were you trying?  If it's a doc issue, we'll fix it.  But, I want to make sure we've got you pointed at the right bits.

<img width="694" alt="screen shot 2018-06-12 at 7 28 38 pm" src="https://user-images.githubusercontent.com/23535264/41309543-ee1ad926-6e76-11e8-8aa3-46308dc195c3.png">

**Comment by musca001** [comment]
Cleared my Chrome cache for something else this morning, and now it works ☺. I see all the brew links pop up.
Weird thing is it’s working for all three browsers now, and I didn’t clear the cache on the other two (FF and Safari).

Thanks for all your help. You can close this incident as opened in error I guess. Not sure what else to say ☹

Dan Musca
HTTS - VzW Mobility
Hours: 11am-7pm CDT
Office:              (469) 255-3768
Mobile:            (972) 768-0937
HTTS Hotline: (800) 495-9121

**Comment by timhallinflux** [comment]
@musca001 -- thanks for letting us know!  Glad this is resolved.  Cheers.
