### ISSUE TITLE
Document influx_tools

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1674]
See:
https://github.com/influxdata/influxdb/tree/master/cmd/influx-tools

Documentation for each of these is required:
1) compact -- offline compaction
2) export -- shard duration change
3) import -- bring exported shards back into the cluster
4) help

**Comment by rbetts** [comment]
@stuartcarnie Can provide you input on (1); @tmgordeeva can help you with (2) and (3).  It is also important to note that (2) and (3) have some functionality that's limited based on replication factors in enterprise clusters, if I've followed details correctly.

**Comment by stuartcarnie** [comment]
note that a recent PR renames to `influx_tools` to match other commands, thus link is now https://github.com/influxdata/influxdb/tree/master/cmd/influx_tools

**Comment by stuartcarnie** [comment]
**`influx_tools compact-shard -path <shard path>`**

The `compact-shard` tool enables an administrator to fully compact a shard at the specified `shard path`. It must be run while the database server is **offline**. When only the required `-path` option is specified, the compact shard tool will prompt the user before proceeding; the `-force` option disables this behavior.

Additional options

* `-verbose` will log additional information to `stdout`, including progress as each `.tsm` file is opened in preparation for compaction. This is useful when compacting larges shards that take some time to open (> 100s of GBs)

* `-force` disables the default prompt asking the user if they wish to proceed with compaction.

**Comment by stevebang** [comment]
@timhallinflux decided this is only to be documented for internal use -- closing and moving content to support wiki.
