### ISSUE TITLE
Update prometheus help with schema mapping

### ISSUE THREAD

**Issue by rbetts** [influxdata/docs.influxdata.com#1677]
URL: https://docs.influxdata.com/influxdb/v1.4/supported_protocols/prometheus#prometheus-remote-read-and-write-api-support

Following up after some slack chatting, the prometheus data model maps to influxdb as follows:

- The prometheus metric name becomes the influxdb measurement name.
- The prometheus sample (value) becomes an influxdb field the field key "value". It is always a float64.
- The prometheus labels become influxdb tags.

Can we add this information to the prometheus doc page?  Came up in a sales enablement conversation.

**Comment by timhallinflux** [comment]
This is for the 1.6 release/updates?  or do you want this for modified for the v1.4/1.5 docs too?

**Comment by rbetts** [comment]
It applies to 1.4/1.5 and 1.6
