### ISSUE TITLE
invalid url in 'InfluxQLNode' page

### ISSUE THREAD

**Issue by BenjaminHuang** [influxdata/docs.influxdata.com#1678]
###### URL for relevant page?
http://docs.influxdata.com/kapacitor/v1.5/nodes/influx_q_l_node/

###### What products and version are you using?
Kapacitor v1.5

###### Where did you look before opening the issue?
http://docs.influxdata.com/kapacitor/v1.5/nodes/influx_q_l_node/

url for 'InfluxQL functions'  seen on this page is 'http://localhost:1313/influxdb/v1.5/query_language/functions/'
perhaps someone forgot to change it back before releasing this page

**Comment by sanderson** [comment]
Nice catch. Thanks!
