### ISSUE TITLE
Typo: Kapacitor v1.5 - QueryNode - Offset

### ISSUE THREAD

**Issue by valentinbora** [influxdata/docs.influxdata.com#1679]
For example an **Offest** of 2 hours and an Every of 5m, Kapacitor will query InfluxDB every 5 minutes for the window of data 2 hours ago.

Should be: For example an **Offset** of 2 hours

###### URL for relevant page?

https://docs.influxdata.com/kapacitor/v1.5/nodes/query_node/#offset

**Comment by sanderson** [comment]
Thanks for the heads up!
