### ISSUE TITLE
Make the docs usable on mobile

### ISSUE THREAD

**Issue by stevebang** [influxdata/docs.influxdata.com#1695]
As part of the redesign for InfluxDB 2.0, we need to make sure that the docs can be used on mobile.  The low usage on mobile is more likely due to design issues than lack of desire.

Are there any short-term fixes we can make?

**From @sanderson:** These are issues that I believe would make the mobile experience better:

- [x] Home page card scaling - Switch to flexbox in addition to % scaling
- [x] Search dropdown display - Right now it pushes off to the right of the screen
- [x] Scrolling - I'm not sure what's causing this, but scrolling right feels "sticky". Usually mobile browsers use scrolling momentum, but for some reason, our docs do not.
- [x] "Un-fix" the top nav - The to is fixed positioned and takes up a lot of space on small screens.
- [x] Left Nav display - The button to expand the docs navigation is fixed positioned at the bottom of the docs, narrowing the view window even further. I think there's a better way, but this one isn't a quick fix.

**Comment by stevebang** [comment]
From [Job van der Voort](https://github.com/JobV):

https://twitter.com/Jobvo/status/1011939840563310594
Job van der Voort @Jobvo
I’m looking at you @InfluxDB docs. What are you even doing? I can’t scroll normally through your docs on mobile.
Twitter Today at 4:50 AM

**Comment by sanderson** [comment]
I've noticed the scrolling issues on mobile too, but I think we're doing any scroll manipulation with js or anything. I'll double-check. Mobile could definitely be improved.

**Comment by sanderson** [comment]
These are issues that I believe would make the mobile experience better.

- [x] Home page card scaling - Switch to flexbox in addition to % scaling
- [ ] Search dropdown display - Right now it pushes off to the right of the screen
- [ ] Scrolling - I'm not sure what's causing this, but scrolling right feels "sticky". Usually mobile browsers use scrolling momentum, but for some reason, our docs do not.
- [ ] "Un-fix" the top nav - The to is fixed positioned and takes up a lot of space on small screens.
- [ ] Left Nav display - The button to expand the docs navigation is fixed positioned at the bottom of the docs, narrowing the view window even further. I think there's a better way, but this one isn't a quick fix.
