### ISSUE TITLE
Error in documentation of Continuous Queries

### ISSUE THREAD

**Issue by PiotrGolonka** [influxdata/docs.influxdata.com#170]
In
https://docs.influxdata.com/influxdb/v0.9/query_language/continuous_queries/#influxql-for-creating-a-cq

The chapter that states:

"The CQ minnie_jr acts in the same way as the CQ minnie, however, InfluxDB calculates the 30 minute minimum of the field mouse in the measurement zoo and under the retention policy 1day, and it automatically writes the results of the query to the measurement min_mouse under the retention policy 4hours"

-> I guess the example refers to 7 days not 4hours.

**Comment by rkuchan** [comment]
Thanks, @PiotrGolonka! We've fixed it [here](https://github.com/influxdata/docs.influxdata.com/commit/4fbecb2b3b306b0a757ba4d8ecdc8aedfee7b362) - the updated page should be up on the site soon.
