### ISSUE TITLE
Document influx_inspect reporttsi

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1712]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/tools/influx_inspect/#main-nav

There is a new command being introduced to `influx_inspect` called `reporttsi`.  This will allows users who use TSI to gain an understanding of series cardinality growth by database and measurement.  This has been a challenge for many customers who have been using the inmem index type.  However, with the introduction of TSI which is designed to support a high number of ephemeral series -- this level of understanding around series growth is even more critical. 

###### What products and version are you using?
This will be added to 1.6.1 release of the database.

Contact @e-dard for more details.  https://github.com/influxdata/influxdb/issues/10032

**Comment by stevebang** [comment]
Fixed in 1.6.1 OSS -- closing.
