### ISSUE TITLE
Document Chronograf swagger documentation available at :8888/docs

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#1717]
Chronograf swagger documentation is available at the `/docs` path in Chronograf

http://localhost:8888/docs

**Comment by sanderson** [comment]
@russorat mentioned that endpoints in the Chronograf API are often in flux and broken and that it may be better to leave this undocumented. Should I close this issue?

**Comment by stevebang** [comment]
@sanderson 00 -- I think we can close this for now and re-evaluate when Chronograf API is more stable in new platform.
