### ISSUE TITLE
Wrong version in link

### ISSUE THREAD

**Issue by foxsam21** [influxdata/docs.influxdata.com#1722]
###### URL for relevant page?

https://docs.influxdata.com/chronograf/v1.5/introduction/getting-started/

###### What products and version are you using?

latest....

###### Where did you look before opening the issue?

```
wget https://dl.influxdata.com/chronograf/releases/chronograf_1.4.0.0_amd64.deb
sudo dpkg -i chronograf_1.4.0.0_amd64.deb

```
should reflect the latest version not an old one especially considering it is a page specifically for v1.5 it should not have a link to v1.4
Maybe there should be a static link to the latest version.

**Comment by stevebang** [comment]
Made this non-specific about versions. Changed the step to say to download and install InfluxDB, getting the files at the InfluxData Downloads page. Closing -- change made in master and will appear in next build.
