### ISSUE TITLE
v1.6 documentation links to v1.4 instead of v1.6

### ISSUE THREAD

**Issue by sjlevin** [influxdata/docs.influxdata.com#1732]
Many of the links on the v1.6 key_concepts page point to v1.4 urls. Examples include glossary of terms, Queries, schema, and Database Management. Looking at the page's source, it looks like there are 10 links with this issue on that page

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/concepts/key_concepts/
###### What products and version are you using?
Documentation Website
###### Where did you look before opening the issue?
Github open issues

**Comment by sanderson** [comment]
Nice catch @sjlevin. Thanks for the heads-up!
