### ISSUE TITLE
Document Compaction Throughput Config Option

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1737]
Add documentation to describe: https://github.com/influxdata/influxdb/pull/9939 

###### URL for relevant page?
http://docs.influxdata.com/influxdb/v1.6/administration/config/#data-settings-data

###### What products and version are you using?
InfluxDB 1.6.1

Default config will align precisely with the current "hardcoded" setting.  This means the behavior will be the same as before.  However, it will allow for more fine tuning over the compaction process beyond just the number of processors to leverage.

**Comment by zachgoldstein** [comment]
Should I close https://github.com/influxdata/docs.influxdata.com/issues/1654 here? Does this replace that?

**Comment by timhallinflux** [comment]
Sorry @zachgoldstein -- you did this perfectly!  I duped your original issue.  I'll close my dup.
