### ISSUE TITLE
Document TSM MADV_WILLNEED Config Option

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1738]
https://github.com/influxdata/influxdb/issues/10117

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/administration/config/#data-settings-data

Add configuration option for turning this option on/off.

Apparently there are some issues when using RHEL or CentOS when this was enabled.  The default configuration option will be to set this to OFF.

**Comment by stevebang** [comment]
Fixed in 1.6.1 OSS -- closing.
