### ISSUE TITLE
Document the TLS 1.2 Config Option

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1739]
https://github.com/influxdata/influxdb/issues/8637

###### URL for relevant page?
Both of these pages will need to be enhanced to capture the configuration change and what it means.

https://docs.influxdata.com/influxdb/v1.6/administration/https_setup/
https://docs.influxdata.com/influxdb/v1.6/administration/config/#http-endpoint-settings-http

To maintain the current behavior, the default option will be to enable ALL certs.  However, a new configuration option will be introduced to allow for a more strict configuration setting TLS 1.2 and a secure set of ciphers to be used. 

It should be noted that the workaround for this issue is to front-end access to the database/data nodes through a load balancer/proxy which restricts access to the more secure ciphers.  This is clearly an undesirable configuration for OSS users with a single node.

**Comment by stevebang** [comment]
Closing since fixed in 1.6.1 OSS.
