### ISSUE TITLE
1.6 documentation links pointing to old 1.4 version

### ISSUE THREAD

**Issue by massimoforni** [influxdata/docs.influxdata.com#1745]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/concepts/key_concepts/

On this page, apart from the links in the first table, all the other links point to the old 1.4 documentation

**Comment by massimoforni** [comment]
But from what I can see in the master the links are correctly pointing to 1.6
Could it be that this was fixed but not published?

**Comment by sanderson** [comment]
@massimoforni Yes, that's what happened. This has been fixed. I'll make sure it gets published today. Thanks for reporting.
