### ISSUE TITLE
Typo in "getting started"

### ISSUE THREAD

**Issue by patkru** [influxdata/docs.influxdata.com#1751]
"The task can be **modify** to be really sensitive to ensure that the alerts are working. In the TICKscript change the lamda function .crit(lambda: "usage_idle" < 70) to .crit(lambda: "usage_idle" < 100), and define the task once more."

fifth word should by "modified" instead of "modify"

###### URL for relevant page?
https://github.com/influxdata/docs.influxdata.com/issues/new
###### What products and version are you using?
n/a
###### Where did you look before opening the issue?
n/a

**Comment by sanderson** [comment]
Thanks for the heads up @patkru. It's been fixed and should be live later today.
