### ISSUE TITLE
Possible typo in Kapacitor documentation

### ISSUE THREAD

**Issue by paulinalei** [influxdata/docs.influxdata.com#1752]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/introduction/getting-started/ 

###### What products and version are you using?
Using Kapacitor 1.5

###### Where did you look before opening the issue?
I looked at the section "Triggering alerts from stream data"

In the section, there is a sentence:
"Before being enabled it should first be tested to ensure that it does not do spam the log files or communication channels with alerts."

"it does not do spam" sounds off and was wondering if this was a possible typo.

**Comment by sanderson** [comment]
Nice catch @paulinalei. Thanks for the heads up. It's been fixed and will be live shortly.
