### ISSUE TITLE
Enhance prometheus read/write docs

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1767]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/supported_protocols/prometheus/#prometheus-remote-read-and-write-api-support

We should add a few more details to this page.
- [x] update the config example to be in `yml` format like the prom config file is. In order to get this to work, you need to create a database to write the metrics to (`prometheus`) and then add these lines to the config (using hyphens instead of asterisks)
```
remote_write:
  - url: 'http://localhost:8086/api/v1/prom/write?db=prometheus'
```

 - [ ] update the `u=` params and `p=` params to match the other examples in the docs
 - [x] provide some guidance as to how prometheus metrics are parsed. These are the rules:
```
- The prometheus metric name becomes the influxdb measurement name.
- The prometheus sample (value) becomes an influxdb field the field key "value". It is always a float.
- The prometheus labels become influxdb tags.
```
and here is an example
```
example_metric{queue="0:http://example:8086/api/v1/prom/write?db=prometheus",le="0.005"} 308

measurement
 example_metric
tags
 queue = "0:http://example:8086/api/v1/prom/write?db=prometheus"
 le = "0.005"
 job = "prometheus"
 instance = "localhost:9090"
 __name__ = "example_metric"
fields
 value = 308
```
- [x] possibly adding a note that all `# HELP` and `# TYPE` lines are ignored
- [x] add a note that this format is different from the Telegraf `prometheus` input plugin which has an example of the formatting on the readme: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus

**Comment by timhallinflux** [comment]
also the current doc says "two" endpoints have been added --- and then three are listed.

**Comment by gunnaraasen** [comment]
We should also note the measurement name is no longer `_` in InfluxDB for the data written via remote write starting in InfluxDB 1.6.

**Comment by rbetts** [comment]
EAR that would benefit from these docs: https://github.com/influxdata/EAR/issues/435
