### ISSUE TITLE
version typo in upgrade doc

### ISSUE THREAD

**Issue by snypez** [influxdata/docs.influxdata.com#1784]
step 8 says you are now on v1.5 when the docs are for 1.6.1
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.6/administration/upgrading/

**Comment by stevebang** [comment]
Fixed in unreleased docs -- Enterprise 1.6.1 has not been released yet, so this is based on an AWS S3 copy that shouldn't be online yet.
