### ISSUE TITLE
Update docs: validate behavior of booleans when used in query where clause

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1787]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/troubleshooting/frequently-asked-questions/#why-can-t-i-query-boolean-field-values

Review of status of https://github.com/influxdata/influxdb/issues/3939

###### What products and version are you using?
Check behavior with 1.6 and determine if the reference in the documentation should be dropped and the DB issue itself should be closed.

**Comment by sanderson** [comment]
This behavior is still present. Boolean values cannot be queried using shorthand `t|T` or `f|F`. You can only query boolean values using `true|True|TRUE` or `false|False|FALSE`.

**Comment by sanderson** [comment]
I'm guessing the DB issue can be closed unless there is a feature request to be able to query boolean values using shorthand.

**Comment by sanderson** [comment]
@timhallinflux I'm wondering what the status of this issue should be. The behavior documented is the current behavior in InfluxDB, so the documentation matches to product. Should it remain open until [influxdata/influxdb#3939](/influxdata/influxdb/issues/3939) is closed?

**Comment by russorat** [comment]
closing this since influxdata/influxdb#3939 is closed as well
