### ISSUE TITLE
Large image headers decrease docs usability

### ISSUE THREAD

**Issue by thomasboyt** [influxdata/docs.influxdata.com#179]
The large image header on each page requires a user to scroll past the height of the viewport just to read the content of the page. This is rather annoying, and I'm not sure why this whitespace was added. Simply removing [this rule](https://github.com/influxdata/docs.influxdata.com/blob/master/static/css/layout.css#L682) makes the  docs significantly easier to read.

It's especially annoying when I'm switching between pages looking for a specific piece of information, as the page's table of contents is below the fold, requiring me to scroll just to figure out if the page I'm on contains the information I'm looking for.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/352
