### ISSUE TITLE
document url params for presentation mode

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1791]
###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.6/guides/dashboard-template-variables/#defining-template-variables-in-the-url

we should document that if a user wants to jump directly into presentation mode, they can add `present=true` to their url.

**Comment by sanderson** [comment]
It doesn't look like presentation mode is mentioned in the docs currently. Maybe we should even do a standalone guide for Chronograf's presentation mode. It wouldn't be long, but could be useful for some.

Just some quick thoughts and notes:
- Presentation hides the Chronograf navigation (left and top)
- Possible keywords: fullscreen, hide navigation
- Use-Case - stationary screens dedicated to monitoring visualizations (maybe include a pic of the display in the office that shows all the cloud metrics)
- Using the `&present=true` query parameter in links to load the dashboard in presentation mode.
- **Note:** Presentation mode enabled with the `present` query parameter cannot be exited with `Esc`.
