### ISSUE TITLE
Documentation SMTP settings in kapacitor.conf of the "to" value

### ISSUE THREAD

**Issue by mindstormsbe** [influxdata/docs.influxdata.com#1792]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/event_handlers/email/

###### What products and version are you using?
kapacitor version 1.5

###### Where did you look before opening the issue?
the documentation and example configs in stackexchange 

The example code in the documentation, under the item "Using the SMTP/Email event handler" on the page "https://docs.influxdata.com/kapacitor/v1.5/event_handlers/email/" has a typo. 

Current config of the "to" parameter: 
`to = "oncall0@mydomain.com"`

Does not work. 
Starting the kapacitor service returns the following error: 
"2018/08/29 09:36:25 Using configuration at: /etc/kapacitor/kapacitor.conf
ts=2018-08-29T09:36:25.927Z lvl=error msg="encountered error" service=run err="parse config: toml: cannot load TOML value of type string into a Go slice"
run: parse config: toml: cannot load TOML value of type string into a Go slice
"

Even for a single value it should be a list of one value. 
Fix: 
`to = ["oncall0@mydomain.com"]`

With this change the service stars without issues

**Comment by sanderson** [comment]
Great find @mindstormsbe. You're correct. The `to` data needs to be formatted as an array, even for single recipients. I've updated the example.
