### ISSUE TITLE
Add toggle for light theme

### ISSUE THREAD

**Issue by joelegasse** [influxdata/docs.influxdata.com#180]
I get that dark themes are "cool", but I find them really hard to read. Would it be possible to add a light/dark toggle somewhere along the top bar for those of us whose eyes strain with dark background themes?

**Comment by rkuchan** [comment]
https://github.com/influxdata/docs.influxdata.com/pull/352

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/352
