### ISSUE TITLE
Dark theme doesn't apply to all elements.

### ISSUE THREAD

**Issue by joelegasse** [influxdata/docs.influxdata.com#181]
The current top bar is white,  and the background on the doc pages is essentially black. This creates a very hard contrast line that is almost painful to look at. 

![top_bar](https://cloud.githubusercontent.com/assets/1391698/12625661/a80869dc-c4e9-11e5-8b6a-085d10bf3a9e.png)

In addition, the landing page for the docs doesn't seem to have been accounted for with the dark theme, creating a very awkward appearance.

![main_page](https://cloud.githubusercontent.com/assets/1391698/12625662/a80a86cc-c4e9-11e5-816d-48c681f81a0f.png)

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/352
