### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by 1039871** [influxdata/docs.influxdata.com#1815]
###### URL for relevant page?
localhost:8086 gives the default but not with my 10.xxx.xx.xx

###### What products and version are you using?
influxdb-1.7.0~n201809050800-0.x86_64

###### Where did you look before opening the issue?
Google

**Comment by sanderson** [comment]
Issues on this repo should be directly related to the InfluxData documentation. This appears to be related to InfluxDB and networking, so I'm closing this issue.

I think a better place for this question would the [InfluxData community](https://community.influxdata.com/) where others can see and answer the question. Although I do have some thoughts...

I assume you're running this on your local machine. Chances are that your IP is not directly accessible to network traffic. Most consumer machines come configured that way. Doing it involves some configuration changes and port-forwarding.
