### ISSUE TITLE
Wrong URL for netstat plugin documentation

### ISSUE THREAD

**Issue by francoisfaubert** [influxdata/docs.influxdata.com#1818]
On [this page](https://docs.influxdata.com/chronograf/v1.6/guides/using-precreated-dashboards/#netstat), I think the documentation link should be:

* https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/README.md

instead of :

* https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/NETSTAT_README.md

**Comment by sanderson** [comment]
Thanks for the heads up @francoisfaubert. The link is wrong. It should actually go here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NETSTAT_README.md.

I've pushed a fix.
