### ISSUE TITLE
SSL: Secure Connection Failed

### ISSUE THREAD

**Issue by nb-sn** [influxdata/docs.influxdata.com#1821]
Documentation can't be accessed over HTTPS, thought I should let you know...
![screenshot from 2018-09-12 11-15-53 2](https://user-images.githubusercontent.com/42645733/45415433-f6a55e00-b67d-11e8-8ffd-5799d8e85686.png)
https://docs.influxdata.com/

**Comment by sanderson** [comment]
@nb-sn  Can you inspect the certificate chain and paste a screenshot here?

**Comment by sanderson** [comment]
@nb-sn We found the issue was isolated Firefox. We switched to an AWS managed SSL certificate and it should now be working. Can you confirm?

**Comment by nb-sn** [comment]
Works like a charm!
