### ISSUE TITLE
send parameter to exec event handler

### ISSUE THREAD

**Issue by TomMir** [influxdata/docs.influxdata.com#1822]
Hi,
how I can send the timestamp like parameter to the external program in the exec event handler?

**Comment by sanderson** [comment]
@TomMir The Exec event handler sends all alert data via STDIN to the declared executable in JSON format. The timestamp is included in the alert data. While it can't be passed directly as an argument to the executable, it can be extracted and used in the executable.

**Comment by sanderson** [comment]
There may be other ways to do what you're trying to do as well. I think the [InfluxData Community](https://community.influxdata.com/) would be a great place to post this question and probably more appropriate for the type of question it is. Closing this issue for now.
