### ISSUE TITLE
[0.10.0-nightly] Wrong download link for RHEL/CentOS?

### ISSUE THREAD

**Issue by zstyblik** [influxdata/docs.influxdata.com#183]
Hello,

https://s3.amazonaws.com/influxdb/influxdb-nightly-1.x86_64.rpm from https://influxdata.com/downloads//#influxdb-nightly returns 404. However, https://s3.amazonaws.com/influxdb/influxdb-nightly.x86_64.rpm can be downloaded. Is there a bug in nightly build script or has the filename been changed?

**Comment by rossmcdonald** [comment]
@zstyblik This has now been updated, sorry for the confusion. The new link is:

https://s3.amazonaws.com/influxdb/influxdb-nightly.x86_64.rpm

Without the `-1`.

**Comment by zstyblik** [comment]
@rossmcdonald no prolem. Thanks.
