### ISSUE TITLE
Typo issue

### ISSUE THREAD

**Issue by vigneshrajarr** [influxdata/docs.influxdata.com#1841]
According to docs in, https://docs.influxdata.com/influxdb/v1.6/concepts/key_concepts/, `tags`  store the meta data and `fields` store the measured value.

In the immediate doc `key_concepts`, https://docs.influxdata.com/influxdb/v1.6/concepts/key_concepts/, its given that `field keys` store metadata. (Sample Data -> Discussion -> Para 3 -> Line 2).

Correct me, in case of an invalid issue report/misunderstanding. TIA

**Comment by sanderson** [comment]
Resolved by #1904
