### ISSUE TITLE
Multiple pages cannot be displayed

### ISSUE THREAD

**Issue by te4336** [influxdata/docs.influxdata.com#1847]
Multiple pages cannot be displayed in the Kapacitor 1.5 documentation regarding event handlers. If you click on "Post", "Publish", "Exec", etc they go to a Page cannot be displayed instead of opening.

https://docs.influxdata.com/kapacitor/v1.5/

Latest TICK stack versions

In the Kapacitor documentation page

**Comment by sanderson** [comment]
This appears to have been caused by a temporary web-sever issue. These pages should now be loading correctly.
