### ISSUE TITLE
Documentation for upgrading influxdb from 1.2.2 to 1.6

### ISSUE THREAD

**Issue by nsphaniraj** [influxdata/docs.influxdata.com#1848]
###### URL for relevant page?
N/A

###### What products and version are you using?
Influxdb 1.2.2

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.6/administration/upgrading/ 

Referred above documentation for upgrade instructions. I could not find steps for upgrading from 1.2.2 to 1.6 version. Please suggest.

**Comment by sanderson** [comment]
@nsphaniraj The instructions are listed on that page, but there are some typos and information that need to be updated. The instructions provided in this section cover the upgrade process you're looking for:

https://docs.influxdata.com/influxdb/v1.6/administration/upgrading/#upgrading-influxdb-1-0-1-4-to-1-5-x

I've noted the changes that need to be made to this page and am closing this issue for now.
