### ISSUE TITLE
Code in Kapacitor's getting started guide doens't work with Telegraf >= 0.10.0

### ISSUE THREAD

**Issue by OrangeTux** [influxdata/docs.influxdata.com#185]
I tried to follow [Kapactior's getting started guide](https://docs.influxdata.com/kapacitor/v0.10/introduction/getting_started/), but I could not get it working. 

The docs mention explicitly that you must use Telegraf >= 0.1.9, but the provides sample code will fail when you use Telegraf >= 0.10.0.  Starting from this release Telegraf uses only 1 measurement for all values per plugin.

**Comment by rkuchan** [comment]
Thanks, @OrangeTux. Fixed by https://github.com/influxdata/docs.influxdata.com/pull/194.
