### ISSUE TITLE
What to do when data nodes will not come up and are trying to load expired shards

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/docs.influxdata.com#1851]
###### What products and version are you using?

InfluxDB

###### Where did you look before opening the issue?

In the influx docs
---------------------------------------

After determining this is the case by looking at the show-shards output..The standard procedure for this should be to shut the data nodes down and then manually remove all the shards in both the data directory and wal directories that shouldn't be there, and then attempt to start the node back up again.

**Comment by stevebang** [comment]
http://docs.influxdata.com/enterprise_influxdb/v1.6/guides/replacing-nodes/
@sanderson Does this need to be added to the page you created in the page on replacing data and meta nodes?
