### ISSUE TITLE
Debian 9.5 influxdb.service is masked

### ISSUE THREAD

**Issue by ShiroiKuma** [influxdata/docs.influxdata.com#1852]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/introduction/installation/

###### What products and version are you using?
Debian 9.5

###### Where did you look before opening the issue?
I googled and found I need to unmask the influxdb.service, this should be included in the documentation as standard

**Comment by sanderson** [comment]
Thanks for the heads-up @ShiroiKuma. Here's the PR with the updated installation instructions:

https://github.com/influxdata/docs.influxdata.com/pull/1857
