### ISSUE TITLE
Update links to license of dependencies for InfluxDB 1.7

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#1858]
This is related to the following change: https://github.com/influxdata/influxdb/pull/9703/files

Instances of the following in `content/influxdb/v1.7/`:

```bash
https://github.com/influxdata/influxdb/blob/1.5/LICENSE_OF_DEPENDENCIES.md
# OR
https://github.com/influxdata/influxdb/blob/1.6/LICENSE_OF_DEPENDENCIES.md
```

Need to be replaced with:
```
https://github.com/influxdata/influxdb/blob/master/DEPENDENCIES.md
```

**Comment by gshif** [comment]
I have merged the changes into master:
```
commit e529bf57fb4e80b321e567cbee73ade41edbe5f0 (HEAD -> master, origin/master, origin/HEAD)
Merge: c6889b1a9 2a9744f80
Author: Gershon Shif <gershon@influxdata.com>
Date:   Wed Oct 3 09:00:21 2018 -0700

    Merge branch 'eirinikos-update-license'
```

**Comment by stevebang** [comment]
Changes made to 1.5, 1.6, and 1.7 in the `influxdb-1.7` branch.

**Comment by timhallinflux** [comment]
actually, for the 1.5 release -- the existing link is correct and should not be changed.

for each release -- it should point to it's branch and the appropriate file underneath that.  Currently, the 1.7 release should point to:
`https://github.com/influxdata/influxdb/blob/1.7/DEPENDENCIES.md`  and this is the correct link going forward.

**Comment by stevebang** [comment]
Fixed.
