### ISSUE TITLE
Query issue on chronograf

### ISSUE THREAD

**Issue by narendralanka** [influxdata/docs.influxdata.com#187]
Hi 

I am getting data into influxdb . But I am trying to get graphs through chronograf getting "your query returned no result".

**Comment by beckettsean** [comment]
@narendralanka this is not an issue with the documentation. Please email the mailing list at influxdb@googlegroups.com for assistance with Chronograf support (the repo is still closed source, so you cannot open an issue on the Chronograf repo.)
