### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs.influxdata.com#192]

**Comment by beckettsean** [comment]
@kostasb @gunnaraasen is there a way to do this with Hugo or do we need to set up something on AWS? Right now a 404 loads http://docs.influxdata.com/ without changing the URL, so it's a really confusing experience.

Even a simplistic web server 404 would be a better return that what we're doing now.

**Comment by kostasb** [comment]
@beckettsean This was done on purpose, instead of displaying a not-so-useful "not found" page it will automatically redirect you to the main index so you can continue searching the docs. If you would prefer a "not found" page then we can do that as well.

**Comment by beckettsean** [comment]
I think a 404 page with the search bar would be more clear.

**Comment by kostasb** [comment]
@beckettsean Agreed, I will adjust the "not found" page accordingly.
