### ISSUE TITLE
distinct function issue

### ISSUE THREAD

**Issue by GitRainy** [influxdata/docs.influxdata.com#1941]
###### URL for relevant page?
http://docs.influxdata.com/influxdb/v1.6/query_language/functions/#distinct

###### What products and version are you using?
influxdb1.6 (open source)
###### Where did you look before opening the issue?
doc.influxdb.com

in your documents,the function named distinct can use [*|field_key|regular_expression] as paramater but in my use ,this function can use field key only.I find followed codes about distinct function
>func (c *compiledField) compileDistinct(args []influxql.Expr, nested bool) error {
>	if len(args) == 0 {
>		return errors.New("distinct function requires at least one argument")
>	} else if len(args) != 1 {
>		return errors.New("distinct function can only have one argument")
>	}
>
>	if _, ok := args[0].(*influxql.VarRef); !ok {
>		return errors.New("expected field argument in distinct()")
>	}
>	if !nested {
>		c.global.HasDistinct = true
>	}
>	c.global.OnlySelectors = false
>	return nil
>}

**Comment by stevebang** [comment]
I found the following InfluxDB issue (https://github.com/influxdata/influxdb/issues/9973), which is related. Awaiting word from @jsternberg about what exactly DISTINCT supports and if these are not supported now, I'll remove the examples and fix the syntax.

**Comment by kangqiwang** [comment]
hi, I got same issue as well, distinct(*) will return ERR: expected field argument in distinct(), when I run in influx 1.7.4.
but in influx 1.1.1, I can get result.
I guest it is not supports any more. I try to find another alternative way

**Comment by sbm17** [comment]
@kangqiwang Did you get a workaround for this? I am facing similar issue where a query fetching 2 distinct values worked in influx 1.2 but does not work in influx 1.7.6
