### ISSUE TITLE
Document changes to /ping API 

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1942]
Changes /ping route to return status code 200 instead of 204 when verbose is set

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/tools/api/#ping-http-endpoint

###### What products and version are you using?
InfluxDB OSS 1.7.0

###### Where did you look before opening the issue?
https://github.com/influxdata/influxdb/pull/10321

Some older context which is useful to understand more can be found here:
https://github.com/influxdata/influxdb/pull/9784

If the user requests "verbose=true" along with the /ping request, HTTP status code may be different than without the "verbose" setting.

**Comment by stevebang** [comment]
Added to `influxdb-1.7` branch. Pending InfluxDB 1.7 release to appear in the docs.

**Comment by stevebang** [comment]
Closed -- verified in 1.7 docs. https://docs.influxdata.com/influxdb/v1.7/tools/api/#verbose-option
