### ISSUE TITLE
Scrolling the docs is very slow on Ubuntu - Chromium and UP/DOWN is not working on keyboard.

### ISSUE THREAD

**Issue by viktorsmari** [influxdata/docs.influxdata.com#1943]
The docs pages are very slow | unresponsive to scroll on Ubuntu 16, newest Chromium browser.

* Slow using the mouse wheel.
* Slow using the UP/DOWN arrows on a keyboard.
* It is NOT as slow on Firefox.

Related issue:
* When clicking  'Getting Started' on the left side, you cannot anymore use UP/DOWN on keyboard to scroll the page, which is annoying. You have to click the center page again to move the focus to is.
* This happens both on Chromium and Firefox
https://docs.influxdata.com/influxdb/v1.6/introduction/getting-started/

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/introduction/getting-started/

###### What products and version are you using?
Ubuntu 16 + Latest Chromium and Firefox
This has been an issue for ~ a year but now I was bothered enough to report it.

###### Where did you look before opening the issue?
I looked for 'slow' in the issues.

**Comment by aldas** [comment]
can confirm this. scrolling is really slow

This is profile when scrolling on https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/ page from my chrome maybe it helps:
![screenshot_20181114_230413](https://user-images.githubusercontent.com/2320301/48512252-b9b63d00-e861-11e8-8053-7916d973d6ba.png)
