### ISSUE TITLE
Add how Chronograf sets the status indicator on the host list page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#1979]
we should add a note into the chronograf docs to describe how the host status is determined. It is based on the results of these two queries:
```
SELECT non_negative_derivative(mean(uptime)) AS deltaUptime FROM "system" WHERE time > now() - 1h * 10 GROUP BY host, time(1h) fill(0);
SELECT non_negative_derivative(mean("System_Up_Time")) AS winDeltaUptime FROM "win_system" WHERE time > now() - 1h * 10 GROUP BY host, time(1h) fill(0);
```

so for linux systems, they need to have the Telegraf system plugin configured and sending data. For windows machines, they will need to configure the https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_perf_counters plugin to populate the win_system measurement.

![image](https://user-images.githubusercontent.com/4805997/48371762-7f864900-e671-11e8-98c7-fbd4f95bea34.png)

**Comment by OutOfFunException** [comment]
Is there an interval for the execution of the query and can you adjust it in the config? We changed the interval data is being sent using telegraf to 5 minutes and now the host status switches back and forth depending on the result of this query I believe.

**Comment by tushar-rishav** [comment]
> Is there an interval for the execution of the query and can you adjust it in the config? We changed the interval data is being sent using telegraf to 5 minutes and now the host status switches back and forth depending on the result of this query I believe.

@stevebang @russorat I'm facing a similar issue. Any pointers would be very much appreciated. Thanks in advance!
