### ISSUE TITLE
Verify snapshot configuration setting for InfluxDB's Backup and Restore

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#198]
This section:

https://docs.influxdata.com/influxdb/v0.10/administration/backup_and_restore/#configuration-options

Mentions a `[snapshot]` section that can be added to the configuration, though this section is not present in any other documentation or the example configurations. Is this still accurate? If not, that section should be removed to avoid confusion.

Brought up by influxdata/influxdb#5528

**Comment by beckettsean** [comment]
@rossmcdonald I'm 90% sure that's only there because it carried over from the 0.9 version of the page. I think we should delete everything from the 0.9 page and assume it's all new.

**Comment by rossmcdonald** [comment]
@beckettsean Agreed. Closing this issue, since it won't apply anymore.
