### ISSUE TITLE
Clarify the link between the Telegraf Database Name and Host List Page

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#1996]
###### URL for relevant page?
http://docs.influxdata.com/chronograf/v1.7/administration/creating-connections/#managing-influxdb-connections-using-the-chronograf-ui

###### What products and version are you using?
Chronograf...all versions

###### Where did you look before opening the issue?
Receiving a number of questions from customers and prospect about why their hosts weren't show ing up.

I think there is a lot more context that should be provided about what drives the host list page and how this is connected to the data source connection setup. Specifically, the Telegraf Database Name is part of the data source connection because the host list view is looking for the various (and this should be enumerated as well!) Telegraf plugins which identify the hosts being monitored. 

If the user decides to use a database name other than the `telegraf` default, they need to update this in the data source connection for the host list view to function.

Alternatively, if you want to prevent users from using the host list page -- leave this field BLANK!

**Comment by noramullen1** [comment]
We fixed this a while back but I never closed the issue, closing now
