### ISSUE TITLE
Document the use of content-encoding: gzip for HTTP Write API

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2003]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/guides/writing_data/#sidebar

###### What products and version are you using?
Documentation currently doesn't describe how to provide gzip encoded content to the HTTP Write API.  This is supported -- as Telegraf takes advantage of this.  But folks using the client libraries or writing their own Line Protocol processors should be able to take advantage of the compression as well.

**Comment by kelseiv** [comment]
Merged PR: [add "configure gzip compression" #2199](https://github.com/influxdata/docs.influxdata.com/pull/2199)
