### ISSUE TITLE
Update config for access-log-status-filter settings

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2004]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/administration/config/#access-log-status-filters

###### What products and version are you using?
Influx DB 1.7.x

###### Where did you look before opening the issue?
The input values for the access-log-status-filters is an array.  When setting this through env variables, the values can be supplied as follows:
INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS_0=4xx INFLUXDB_HTTP_ACCESS_LOG_STATUS_FILTERS_1=5xx 

the _N at the end of the env var represents the array position of the entry.  As in:
`access-log-status-filter = ["4xx", "5xx"]`

"4xx" is in array position 0
"5xx" is in array position 1

**Comment by stevebang** [comment]
Fixed in master -- update will appear when docs are published.
