### ISSUE TITLE
Add docs for inter-data-node TLS

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/docs.influxdata.com#2006]
Please document this change:
https://github.com/influxdata/plutonium/pull/2857

This only affects data nodes. The following config options have been added:
```
[cluster]
  https-enabled = true
  https-certificate = "/etc/ssl/influxdb.crt"
  https-private-key = "/etc/ssl/influxdb.key"
  https-insecure-tls = true
```

This is very similar to meta node TLS:
https://github.com/influxdata/docs.influxdata.com/issues/1285

###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.6/administration/config-data-nodes/#cluster-settings

###### What products and version are you using?
1.7.2

**Comment by stevebang** [comment]
Added to 1.7.2 Enterprise docs pending release.
