### ISSUE TITLE
BarrierNode example 

### ISSUE THREAD

**Issue by ptrdlbrg** [influxdata/docs.influxdata.com#2009]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/nodes/barrier_node/

###### What products and version are you using?
Kapacitor 1.5.1 via Docker (`kapacitor:1.5.1-alpine`)

###### Where did you look before opening the issue?
Other Github issues. 

###### What is the problem?
The example in the BarrierNode documentation is not a valid TICKscript, at least not with this version. When attempting to define a task with the example TICKscript, Kapacitor returns the error:
```invalid TICKscript: line 2 char 4: no method or property "barrier" on *pipeline.StreamNode```

**Comment by sanderson** [comment]
Thanks for pointing this out @ptrdlbrg. I've updated the example to be valid. Before, the example didn't define the source or scope of the query (`from()`), so nothing was actually being queried and no barriers could be set. This update will will out with the Kapacitor 1.5.2 documentation in the next week or so.
