### ISSUE TITLE
Typos when referencing influxd-ctl

### ISSUE THREAD

**Issue by stevenh** [influxdata/docs.influxdata.com#2016]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.6/guides/replacing-nodes/

###### What products and version are you using?
Influxdb v1.6.4

In the above page there a few places where `influx-ctl` is used for the command name instead of `influxd-ctl` i.e. missing the **d**.

**Comment by stevebang** [comment]
Fixed two instances in master -- will appear next publishing of docs.
