### ISSUE TITLE
influx data or influx db executables packages or files

### ISSUE THREAD

**Issue by ashuptdr** [influxdata/docs.influxdata.com#2018]
can we have influx data or influx db executables packages or files like prometheus and atlas:
e.g.
https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.linux-amd64.tar.gz

https://github.com/Netflix/atlas/releases/download/v1.5.3/atlas-1.5.3-standalone.jar

**Comment by sanderson** [comment]
@ashuptdr all executable packages can be downloaded using commands/links available on the [InfluxData Downloads](https://portal.influxdata.com/downloads) page.
