### ISSUE TITLE
API Response for query's that run too long

### ISSUE THREAD

**Issue by andrew-influx** [influxdata/docs.influxdata.com#2021]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/administration/config/#query-timeout-0s

###### What products and version are you using?
1.6.x

###### Where did you look before opening the issue?
Documentation and internal resources (InfluxData)

In cases of query's that run too long what is the HTTP API response going to be?
The 4xx codes listed only cover 403 forbidden. 5xx responses focus on an error.

This information is helpful for certain organizations that run metrics based on HTTP responses.

**Comment by timhallinflux** [comment]
@andrew-influx -- you could try it and see what happens... that would be helpful in terms of reproduction.

**Comment by stevebang** [comment]
@andrew-influx If you can test it and let me know the outcome, I'll add it to the documentation I'm creating about monitoring and tracking slow queries.
