### ISSUE TITLE
Explicitly add two timestamps in example writing several data points

### ISSUE THREAD

**Issue by tvwerkhoven** [influxdata/docs.influxdata.com#2052]
I propose to explicitly add two timestamps to the example writing several points in one HTTP call. Currently it can be interpreted as if the timestamp applies for both data points, while this is not the case.

Current:
```
$ curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary \
'mymeas,mytag=3 myfield=89
mymeas,mytag=2 myfield=34 1463689152000000000'
```

Proposed (1 hour difference in timestamps):
```
$ curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary \
'mymeas,mytag=3 myfield=89 1463685552000000000
mymeas,mytag=2 myfield=34 1463689152000000000'
```

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/tools/api#examples-6

###### What products and version are you using?
N/A

###### Where did you look before opening the issue?
N/A

**Comment by sanderson** [comment]
@tvwerkhoven Thanks for the feedback. The example provided is meant to show that multiple points of data can be added at the same time with the same timestamp. The data written in the example is for two separate fields with different tags.

For example, assume you're writing data from two different servers. Many data points will share the same timestamp, but they are still unique data points. The curl command could be:

```bash
curl -i -XPOST "http://localhost:8086/write?db=mydb" --data-binary \
'monitoring,host=host1 percent_used=24.6
monitoring,host=host2 percent_used=35.2 1463689152000000000'
```

I think the docs could be updated to clarify that this is what is meant to happen. This is a somewhat implicit method for assigning multiple data points the same timestamp. You can also explicitly include timestamps in each line, even if they're the same, but it's not necessary.

**Comment by tvwerkhoven** [comment]
As you describe it is how I interpreted the example, but if I run it, I get the following data:

```
time                           myfield mytag
----                           ------- -----
2016-05-19T20:19:12Z           34      2
2018-12-10T18:53:27.769465831Z 89      3
```

while I would expect (if I understand you correctly):
```
time                           myfield mytag
----                           ------- -----
2016-05-19T20:19:12Z           34      2
2016-05-19T20:19:12Z           89      3
```

If so, my question still holds.

**Comment by sanderson** [comment]
Ah, I understand and I was wrong about how multiple lines are ingested. Each line is treated as a separate data point and do not inherit the timestamp of other lines. If a data point doesn't includ a timestamp, InfluxDB assumes `now` and will assign the current timestamp according to the time of ingest.

The example does need to be updated. Thanks for calling this out.
