### ISSUE TITLE
Broken link to docs

### ISSUE THREAD

**Issue by amok** [influxdata/docs.influxdata.com#206]
Link "Documentation" here https://influxdata.com/ is broken and points to https://docs.influxdata.com/docs/v0.10/introduction/overview.html instead of https://docs.influxdata.com/influxdb/v0.10/

http://prntscr.com/9za13r

**Comment by gunnaraasen** [comment]
Thanks for the report. Looks like the link is now pointing to `https://docs.influxdata.com`.

**Comment by amok** [comment]
:+1:, tnx
