### ISSUE TITLE
slightly wrong subtitle in examples of histogram() function

### ISSUE THREAD

**Issue by itsbrody** [influxdata/docs.influxdata.com#2066]
Found be reading

###### http://docs.influxdata.com/flux/v0.7/guides/histograms/

that it has an examples section, showing two different examples, one with a linear time splitting, the second with a logarithmic splitting, but both named the same:

**Generating a histogram with linear bins**

**Comment by sanderson** [comment]
Thanks for calling this out @itsbrody.
