### ISSUE TITLE
Shard Duration min is 1 hour

### ISSUE THREAD

**Issue by BondAnthony** [influxdata/docs.influxdata.com#2067]
Shard duration min is 1 hour however the documentation has 30m throughout the docs. Example can be found within the retention policy.

https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#modify-retention-policies-with-alter-retention-policy

**Comment by noramullen1** [comment]
Hi @BondAnthony, thanks for letting us know. I did a search of the docs and was unable to find any other places where we mention 30 minute shard group duration. Do you have another example of where you saw this?

Thanks,
Nora

**Comment by BondAnthony** [comment]
My mistake @noramullen1, that would be the only spot.
