### ISSUE TITLE
Key concenpts - "schema case study" - wrong tooltips

### ISSUE THREAD

**Issue by gietki** [influxdata/docs.influxdata.com#2071]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/concepts/key_concepts/

###### What products and version are you using?
https://docs.influxdata.com/influxdb/v1.7/concepts/key_concepts/

###### Where did you look before opening the issue?
As you can see the tooltip is wrong. It should be "tag value". Same in the field beside and in table header.

![image](https://user-images.githubusercontent.com/41086805/50055382-6c720780-014e-11e9-9d3f-12c0df74e9a2.png)

**Comment by sanderson** [comment]
@gietki, the tooltips are correct. In this specific context, the example dataset illustrates a schema structure that has been optimized for its specific query load by making `location` and `scientist` fields and `butterflies` and `honeybees` tags.

**Comment by gietki** [comment]
Thank you!
