### ISSUE TITLE
wrong link for "Installing Telegraf"

### ISSUE THREAD

**Issue by petrasl1976** [influxdata/docs.influxdata.com#2073]
Link for "Installing Telegraf" simply points to the Chronogfraf installation docs, but not Telegraf
###### URL for relevant page?
https://docs.influxdata.com/platform/installation
###### What products and version are you using?
google chrome on mac
###### Where did you look before opening the issue?
https://docs.influxdata.com/platform/introduction

**Comment by vavdoshka** [comment]
strange, it is 2020 and the issue is still being relevant
