### ISSUE TITLE
404 for v1.9 documenation

### ISSUE THREAD

**Issue by boilermanc** [influxdata/docs.influxdata.com#2082]
###### Telegraf
Links for the v1.9 documentation in github are 404's

**Comment by sanderson** [comment]
Thanks @boilermanc. While the InfluxData docs are viewable on Github, they are meant to be viewed at https://docs.influxdata.com. The links used in the raw markdown are relative and assume the docs.influxdata.com context. The corresponding page is viewable [here](https://docs.influxdata.com/telegraf/v1.9/administration), where the links work correctly.
