### ISSUE TITLE
Kubernetes page issues

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#2087]
###### URL for relevant page?
https://docs.influxdata.com/platform/integrations/kubernetes/

- [x] Monitor Kubernetes and Deploy the TICK Stack on Kubernetes links are broken in the second paragraph
- [ ] All urls in the page should use the /latest/ urls, not version specific ones.
- [ ] All github links should point to master branches
- [ ] broken link in the "ways to deploy InfluxDB on Kubernetes" text

**Comment by sanderson** [comment]
Thanks for pointing these out @russorat!
