### ISSUE TITLE
Update InfluxEnterprise Third-party Libraries for 1.6 Release

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2092]
###### URL for relevant page?

http://docs.influxdata.com/enterprise_influxdb/v1.6/about-the-project/

###### New third party libraries to be referenced
https://github.com/mark-rushakoff/ldapserver
Basic LDAP v3 functionality for the GO programming language.
--
https://github.com/mark-rushakoff/ldapserver/blob/master/LICENSE
License: BSD-3-Clause

https://github.com/go-asn1-ber/asn1-ber
ASN1 BER Encoding / Decoding Library for the GO programming language.
--
https://github.com/go-asn1-ber/asn1-ber/blob/master/LICENSE
License: MIT

https://github.com/go-ldap/ldap
Basic LDAP v3 functionality for the GO programming language.
--
https://github.com/go-ldap/ldap/blob/master/LICENSE
License: MIT

**Comment by stevebang** [comment]
Updated in master. Appearing after next build.
