### ISSUE TITLE
Update InfluxEnterprise Third-party Libraries for 1.7 release

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2093]
###### URL for relevant page?
http://docs.influxdata.com/enterprise_influxdb/v1.6/about-the-project/

Be sure to include the 1.6 updates prior to cloning for 1.7 release.

###### New third party libraries to be referenced
https://github.com/gorilla/context
A golang registry for global request variables. 
--
https://github.com/gorilla/context/blob/master/LICENSE
License: BSD-3-Clause

https://github.com/hashicorp/go-immutable-radix
An immutable radix tree implementation in Golang
--
https://github.com/hashicorp/go-immutable-radix/blob/master/LICENSE
License: MPL-2.0

https://github.com/hashicorp/golang-lru
Golang LRU cache
--
https://github.com/hashicorp/golang-lru/blob/master/LICENSE
License: MPL-2.0

**Comment by stevebang** [comment]
Added previously missing 1.6 additions and new 1.7 additions. Changes appearing in next build.
