### ISSUE TITLE
show series cardinality

### ISSUE THREAD

**Issue by DarrenMendalka** [influxdata/docs.influxdata.com#2106]
Filtering by time is only supported when TSI (Time Series Index) is enabled... 
https://docs.influxdata.com/influxdb/v1.7/query_language/spec/#show-series-cardinality
https://docs.influxdata.com/influxdb/v1.7/query_language/spec#drop-series

So really filtering by time is not supported? I think the docs for "show series cardinality" would be improved without the quoted clause.

Testing this using TSI has given the below error. 
Show series cardinality on telegraph where time > now() -5m
ERR: SHOW SERIES EXACT CARDINALITY doesn't support time in WHERE clause

Looks in few documents to confirm.

**Comment by stevebang** [comment]
Changed note in SHOW SERIES CARDINALITY to state: "Filtering by time is not supported in the WHERE clause. Change to appear in next doc publish.
