### ISSUE TITLE
Modify documentation to note WHERE time limitation in main doc / not just FAQ

### ISSUE THREAD

**Issue by andrew-influx** [influxdata/docs.influxdata.com#2115]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-where-clause

###### What products and version are you using?
1.6.4

###### Where did you look before opening the issue?
Documentation.

We have a request from a customer (Zen Desk Ticket #40124) and they recommend having this limitation (MULTIPLE TIME queries for the same statement) would be best in the documentation on the WHERE Clause not just in the FAQ.

Reference:
https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#why-is-my-query-with-a-where-or-time-clause-returning-empty-results

**Comment by kelseiv** [comment]
Thank you, @andrew-influx! 
Updated v 1.6 and 1.7 docs to include this limitation in the Data exploration... topic.
