### ISSUE TITLE
unable to install telegraf service on windows 2016 standard server

### ISSUE THREAD

**Issue by Yuwei-Zhou** [influxdata/docs.influxdata.com#2122]
Hi ,
I got follow output while try to install the telegraf agent for windows 2016, how to correct it ?

C:\Users\Administrator>C:\"Program Files"\Telegraf\telegraf.exe -service install
2019-01-29T09:09:12Z I! Starting Telegraf 1.9.2
2019-01-29T09:09:12Z I! Using config file: C:\Program Files\Telegraf\telegraf.conf

Thanks

**Comment by sanderson** [comment]
@Yuwei-Zhou The output suggests that Telegraf is running normally using the configuration file stored at `C:\Program Files\Telegraf\telegraf.conf`
