### ISSUE TITLE
Golang client point to a 404 repo

### ISSUE THREAD

**Issue by Willis0826** [influxdata/docs.influxdata.com#2124]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/tools/api_client_libraries/
###### What products and version are you using?
InfluxDB v1.7
###### Where did you look before opening the issue?
The link in the page https://github.com/influxdata/influxdb/blob/master/client/README.md
The InfluxDB go client repo https://github.com/influxdata/influxdb1-client

The repo has been moved to [influxdb1-client](https://github.com/influxdata/influxdb1-client), the link for the golang client should be updated.

**Comment by sanderson** [comment]
Thanks for the heads-up @Willis0826. The master branch of the InfluxDB repo was recently replaced with the v2.0 alpha InfluxDB source code. In that process, the InfluxDB (v1.x) Go client was moved into its own repo here: https://github.com/influxdata/influxdb1-client

I've updated all the links to the previous client location to point to the new location.
