### ISSUE TITLE
Installation for Windows

### ISSUE THREAD

**Issue by viogp** [influxdata/docs.influxdata.com#2128]
I would like to try out the TICK Stack on my Windows 10 machine. I tried following the "wget" instructions given in the download website (https://portal.influxdata.com/downloads/) but that didn't seem to do anything. Telegraf can be downloaded using Chocolatey (https://chocolatey.org), so I did that. However, I get the following error message:

`
PS C:\Program Files\telegraf> ls
    Directory: C:\Program Files\telegraf
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       05/02/2019     14:56                telegraf.d
-a----       05/02/2019     15:24         337940 telegraf.conf
-a----       22/01/2019     22:09       59849728 telegraf.exe

PS C:\Program Files\telegraf> .\telegraf --version
Telegraf 1.9.3 (git: HEAD 6ad8c8b0)

PS C:\Program Files\telegraf> .\telegraf --version
Telegraf 1.9.3 (git: HEAD 6ad8c8b0)
PS C:\Program Files\telegraf> .\telegraf
2019-02-05T15:27:54Z I! Starting Telegraf 1.9.3
2019-02-05T15:27:54Z I! Using config file: C:\Program Files\Telegraf\telegraf.conf
2019-02-05T15:27:54Z E! [telegraf] Error running agent: Error parsing C:\Program Files\Telegraf\telegraf.conf, toml: line 1: parse error

PS C:\Program Files\telegraf> .\telegraf config > telegraf.conf
2019/02/05 15:24:38 W! [inputs.wireless] Current platform is not supported
`

This for Telegraf, InfluxDB doesn't even have a Windows option. In my organization the computers are set up in such a way that volumes cannot be shared in Docker, and thus, I cannot really use that option.

**Comment by sanderson** [comment]
Currently, Telegraf Windows support is experimental, but you should follow the installation instructions provided here: http://docs.influxdata.com/telegraf/v1.9/introduction/installation/. Select the Windows option. Telegraf needs to be installed and run as a Windows service.

**Comment by Vaidyaakash** [comment]
@sanderson, can you please give us any update.
"Current platform is not supported"
I'm facing this issue
