### ISSUE TITLE
Add guaranteed persistence of data information

### ISSUE THREAD

**Issue by TheKaterTot** [influxdata/docs.influxdata.com#2131]
The community would benefit from a clear statement in the docs about the promises we make (or don't make) about the persistence of data points.

###### URL for relevant page?
This stems from this community question: 

> https://community.influxdata.com/t/guaranteed-persistence-of-data-in-influxdb/8331
> #

##### What products and version are you using?
InfluxDB 1.7.1 
###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.7 1

**Comment by TheKaterTot** [comment]
Update:

@nisley and I met and reviewed the current docs. The idea of durability and persistence seems relevant to this section of the docs [about the HHQ](https://docs.influxdata.com/enterprise_influxdb/v1.7/concepts/clustering/#hinted-handoff) (including the configuration for any, quorum, all, etc.) for Enterprise.

**Comment by nisley** [comment]
I have some additional info that may be helpful when we sit down to address this issue.
