### ISSUE TITLE
InfluxDB 1.x Third Party Software Link Broken in 1.7 docs

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2132]
With the shift to 2.0 on master in the InfluxDB repo, the documentation links to the third party software dependencies are now broken. 

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/about_the_project/third-party/

Points to: https://github.com/influxdata/influxdb/blob/master/DEPENDENCIES.md
This link is no longer correct now that 2.0 is on master.

###### What products and version are you using?
v1.7

New link should be: 
https://github.com/influxdata/influxdb/blob/1.7/DEPENDENCIES.md

**Comment by stevebang** [comment]
Fixed. Will appear in next build.
