### ISSUE TITLE
Incorrect date spec in example

### ISSUE THREAD

**Issue by jfecteauWork** [influxdata/docs.influxdata.com#2139]
" (assume we executed the SELECT queries at 2016-05-13T00:59:59Z)"  at the attached, I believe should read  " (assume we executed the SELECT queries at 2016-05-1**4**T00:59:59Z)"

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/guides/downsampling_and_retention/#definitions

###### What products and version are you using?
InfluxDb - single node, version 1.7.1

###### Where did you look before opening the issue?
Seems to be a minor oversight;  wouldn't expect it to find info anywhere on this.

**Comment by stevebang** [comment]
Thanks, @jfecteauWork ! 
Fixed in master -- will appear in next doc publish.
