### ISSUE TITLE
SELECT last(*) returns time=0

### ISSUE THREAD

**Issue by andig** [influxdata/docs.influxdata.com#2153]
Consider:

    select last(value) from data
    (
        [time] => 2015-06-25T18:10:49.001Z
        [last] => 0.84
    )

but:

    select last(*) from data
    (
        [time] => 1970-01-01T00:00:00Z
        [last_cpucount] => 10
        [last_value] => 0.84
    )

Here time is suddenly 0. The same is reproducible using `epoch=ms`

**Comment by FedeBev** [comment]
Any news about this? Now I'm using `ORDER BY time DESC LIMIT 1` as workaround.

For example
```
SELECT last(status), last(size)  FROM volume_metrics GROUP BY *
```
becomes
```
SELECT status, size  FROM volume_metrics GROUP BY * ORDER BY time DESC LIMIT 1
```
Any better solution/workaround?
