### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Fredericco72** [influxdata/docs.influxdata.com#2158]
Hi, I noticed a small typo on the following page:
https://docs.influxdata.com/influxdb/v1.7/concepts/key_concepts/

It currently says:
Assume that the data live in a database called ...

I think it should be change to:
Assume that the data **lives** in a database called ...

![image](https://user-images.githubusercontent.com/33041227/53235042-cc25eb00-3688-11e9-8fbd-f8d26762368a.png)

Thanks!

**Comment by kelseiv** [comment]
@Fredericco72 thank you, we updated this typo (also updated docs throughout to make data singular) 77f0d7afa280e8d9c9f8750befdaff43ab9f8530
