### ISSUE TITLE
Precision for UDP?

### ISSUE THREAD

**Issue by tpitale** [influxdata/docs.influxdata.com#216]
This page suggests precision can be set in the "query string" https://docs.influxdata.com/influxdb/v0.10/write_protocols/line/. How does it get set when using UDP? What is the default precision for UDP?

**Comment by beckettsean** [comment]
@sparrc @jwilder is it possible to control the timestamp precision when writing over UDP, or is it always nanosecond precision?

**Comment by jwilder** [comment]
It's nanosecond, but @tpitale submitted (and we merged yesterday) a PR to allow changing the precision via the config.  https://github.com/influxdata/influxdb/pull/5565

**Comment by beckettsean** [comment]
Awesome!

@rkuchan we need to update the UDP docs when influxdata/influxdb#5565 merges

**Comment by jwilder** [comment]
@beckettsean @rkuchan  It's already merged as of yesterday.
