### ISSUE TITLE
AE needs to be disabled during a restore

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2160]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/backup-and-restore/#restore

###### What products and version are you using?
All versions greater than 1.5

Essentially, AE will attempt to start replicating data which lands via restore.  So, in order to perform a restore, first AE should be disabled --- one data node at a time.  Perform a rolling restart of the cluster after each configuration is adjusted...and wait for the nodes to return to a healthy state (up, receiving writes/reads, and hinted handoff queue drained.)  Then, perform the restore.

After the restore completes, AE can be re-enabled by running back through the configuration change and associated restart of the data nodes.

**Comment by stevebang** [comment]
Looks good.
