### ISSUE TITLE
Setup HTTPS with a CA-Signed certificate -> file permissions issue

### ISSUE THREAD

**Issue by lafrech** [influxdata/docs.influxdata.com#2162]
The docs read

> Certificate files require read and write access by the root user. 

InfluxDB may not be launched as root. When installed using the .deb packages from https://repos.influxdata.com/, it runs as influxdb user, therefore the certificate files should be readable by the influxdb user. The details on how to do that (group ownership, etc) may be out of scope, but I found the wording to be misleading.

Also, I don't see the need for the write access.

Would it be more correct to say that the certificate files should be readable by the user running influxdb?

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/

###### What products and version are you using?

influxdb |    1.7.4-1 | https://repos.influxdata.com/debian stretch/stable

###### Where did you look before opening the issue?

Search engine, which pointed me to various Q&A (Influx community, Stack Exchange) and to this bugtracker.

**Comment by kelseiv** [comment]
thank you, @lafrech! We've updated the [docs](https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/) to reflect that users running influxdb require read permissions to certificate files.
