### ISSUE TITLE
Running InfluxDB as a service: No documentation exists for installation under Windows

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/docs.influxdata.com#2164]
The InfluxDB documentation only includes instructions on how to install influxDB for various flavors of Linux, but I do not see any documentation about installing InfluxDB for Windows. Basic installation is pretty straight forward, but installing InfluxDB as a Windows service can be a pain in the *, so it would be nice to have some documentation about it so that everybody is using the same method for this.

Here's my suggestion:
Download nssm 2.24 (zip) from https://nssm.cc/download
Unzip nssm.exe from it and put in a new folder called nssm (I put it in the InfluxDB folder)
Create a batchfile nssmInstall.bat containing the following text:
_nssm install InfluxDB_
Run nssminstall.bat and fill in the tabs on the window that is displayed. Here is an example:
**Tab "application"**
Path:                     D:\PortableApps\Influx\InfluxDB\influxd.exe
Startup directory: D:\PortableApps\Influx\InfluxDB
Arguments:         -config influxdb.conf
**Tab "details"**
Display name:      InfluxDB Service
Description:         InfluxDB running as a service. Installed by nssm, the non sucking service manager
StartupType:       Automatic

Leave the other tabs at their default settings
Create a batchfile nssmStart.bat containing the following text:
_nssm start InfluxDB_
Run NssmStart.bat
And you are done!

I suggest to build a few extra batch files:
NssmStop.bat   : 
_nssm stop InfluxDB_
NssmStatus.bat : 
_nssm status InfluxDB_
pause
NssmEdit.bat:
_nssm edit InfluxDB_

Please let me know if you have any suggestions for improving upon this method.

**Comment by stevebang** [comment]
Relevant discussion in the community: https://community.influxdata.com/t/running-influxdb-as-a-service-on-windows/751

**Comment by stevebang** [comment]
@noahcrowley wrote a blog that includes relevant content: https://www.influxdata.com/blog/running-the-tick-stack-on-windows/

**Comment by kjetilgloppen** [comment]
Here is another write-up:
http://richardn.ca/2019/01/04/installing-influxdb-on-windows/

**Comment by aggarwalanubhav** [comment]
Hi @Kortenbach, I get the following error when I run the start command:
`Can't open service!
OpenService(): Access is denied.`
How do I resolve this?

**Comment by andow1199** [comment]
Can you help me? I can not find Influxdb.conf in Influxdb2.2, how can I do ?

**Comment by sanderson** [comment]
@andow1199 InfluxDB 2.x doesn't store an `influxdb.conf` file on disk by default. You can create one and read configuration options from it, but it isn't required. There are multiple ways to configure 2.x. Here's the documentation: [InfluxDB 2.2 configuration options](https://docs.influxdata.com/influxdb/v2.2/reference/config-options/)

**Comment by alexchandel** [comment]
`nssm` has not had an update in years and has known bugs related to unexpected child process termination.  It is not an acceptable solution.

Making ONE executable support running as both a regular process and a service on Windows is very easy, and this needs to be natively supported by InfluxDB.

**Comment by MalzSmith** [comment]
I've successfully set it up using [WinSW](https://github.com/winsw/winsw). It was pretty straightforward:

 - [Downloaded the latest release](https://github.com/winsw/winsw/releases/) (using the bundled version)
 - Created this configuration file (named `WinSW-x64.xml`):
 
```xml
  <id>influxdb-winsw</id>
  <name>InfluxDB-winsw</name>
  <workingdirectory>C:\Users\MYUSER\Desktop\Influxdb</workingdirectory>
  <description>Influxdb service managed by WinSW</description>
  <executable>C:\Users\MYUSER\Desktop\Influxdb\influxd.exe</executable>
  <arguments>--reporting-disabled --bolt-path=./.influxdbv2/influxd.bolt --engine-path=./.influxdbv2/engine --sqlite-path ./.influxdbv2/influxd.sqlite</arguments>
</service>
```

 - Installed it using `WinSW-x64.exe install`
 - Started the service using `WinSW-x64.exe start`
 - Navigated to `localhost:8086` to check if it's working
 - (It wasn't working because I used a wrong path so I checked `WinSW-x64.wrapper.log` to troubleshoot)


Seems to be working fine so far. I'd still appreciate a proper installer for this, but this was a workable solution for me.

**Comment by alexchandel** [comment]
The workflow for a process that supports Win32 service mode and regular is simple.  At start, you:

1.  Call `StartServiceCtrlDispatcherA()`.
2. If it returns the error `ERROR_FAILED_SERVICE_CONTROLLER_CONNECT`, you are not a service, and you proceed as normal and call your `real_main()`.
3. If it returns another error, you are a service but had an error, so `exit()`.
