### ISSUE TITLE
Authentication doc example should read https-enabled = true

### ISSUE THREAD

**Issue by lafrech** [influxdata/docs.influxdata.com#2165]
Since basic auth is used, it would we sensible to enable https.

I think this was the intent, since a cert is provided.

```
[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = true # ✨
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false  # <----------- Shouldn't this be true?
  https-certificate = "/etc/ssl/influxdb.pem"
```

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/#2-by-default-authentication-is-disabled-in-the-configuration-file

###### What products and version are you using?

InfluxDB 1.7

**Comment by stevebang** [comment]
Fixed in master and closing.
