### ISSUE TITLE
Upgrade instructions -- improve clarity on "remove from load balancer" step

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2166]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/upgrading/
and previous editions of upgrade instructions which include instructions about the "load balancer"

###### What products and version are you using?
InfluxDB Enterprise

###### Where did you look before opening the issue?
Two customers have raised support cases regarding the upgrade instructions which indicate some confusion with this particular step.

https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/upgrading/#step-2-remove-the-data-node-from-the-load-balancer

First, what is happening here?
In the production installation instructions, we indicate:
https://docs.influxdata.com/enterprise_influxdb/v1.7/install-and-deploy/production_installation/data_node_installation/#load-balancer

That a load balancer should be used to distribute read and write traffic across available data nodes.  However, when a data node is taken down for maintenance --- the customer can proactively remove the node from the load balancer PRIOR to taking the node offline.  

Second, What does this do?
Effectively, removing the data node from the load balancer's configuration prevents the load balancer from distributing traffic to a node that is offline.  What typically happens is that if the customer DOES NOT remove the data node from the LB configuration prior to taking it offline, the load balancer will attempt to route traffic to the dead node.  Since the node is unavailable, the load balancer (depending on it's features and functions) may attempt to re-route the traffic to other available nodes.  Or, if may simply report a failure back to the requestor (read or write).  Typically, load balancers will STOP routing traffic to nodes after some number of predefined failures (3-5 is typical), so, this tends to be a temporary issue.  Once the node returns to a healthy state, LBs may also re-attempt to route to it (based on a "health check" or ping that the LB performs against the node in the routing table). Again, this is based on the underlying features, capabilities and configuration of the LB itself. So, the specifics of configuring all of this is outside of the scope of our documentation. 

So, the best practice is to change the load balancer configuration to avoid triggering any failures back to the requestors.  Is this absolutely required, no.  

There will be customers who have access to the software configuration "stack" -- but may NOT have access to the networking "stack" (i.e. LBs).  In those cases, they may choose to simply have the ability  (without significant effort or coordination with other teams) to change the LB.  So, they may choose to simply endure a small number of failures while they upgrade the database.

**Comment by kelseiv** [comment]
resolved in #2168
