### ISSUE TITLE
Export document incorrect

### ISSUE THREAD

**Issue by justinbrock** [influxdata/docs.influxdata.com#2167]
###### Where did you look before opening the issue?documentation and other locations on the interwebs.

In the information, it says that the timestamp has to be in RFC3339, which links another area in influx documentation (https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#absolute-time). However, it actually requires a more formal RFC3339. The format that worked in the end is: 2019-01-25T00:00:00+00:00 without single quotes.

**Comment by kelseiv** [comment]
Thank you @justinbrock! Nice catch.

We added examples of valid RC3339 formats to the export document, and removed the link to #absolute time, as you noticed, that example reflects using single quotes when RFC3339 is used as part of a query. That said, we'd expect single quotes to be consumed by the shell (not cause issues).

We're curious if you'd share sample syntax of what didn't work (we'd love to help others know what to watch out for). Thanks again!

**Comment by justinbrock** [comment]
This is what eventually worked.

influx_inspect.exe export -out C:\export\export.txt -datadir F:\influxdb\data -waldir F:\influxdb\wal -database XXX -compress -start 2019-01-25T00:00:00+00:00 -end 2019-02-25T00:00:00+00:00

I tried multiple variations that were listed on that RFC page, but none of them worked. Not 100% sure why, but I know this worked. 

I attempted with and without quotes this format 'YYYY-MM-DDTHH:MM:SS.nnnnnnnnnZ' I tried with the Z, without the Z, with the n's and without the n's. 

I also tried this format 'YYYY-MM-DD HH:MM:SS.nnnnnnnnn'

**Comment by kelseiv** [comment]
Thank you so much @justinbrock!

For RC3339, Z (or +0.00) is required for no time zone offsets. 

.nnnnnnnnn represents fractional seconds, which are optional for RC3339.

To be sure, did you try this format (and it didn’t work):
YYYY-MM-DDTHH:MM:SSZ

**Comment by justinbrock** [comment]
That information was not included in either the influx_inspect section or the section in the RFC help area. 

I did try that format and it didn't work either.

**Comment by kelseiv** [comment]
@justinbrock yes sir, it was not included and confusing. Thanks to you, we've updated examples in our influx_inspect docs. 

If you run into future issues using the suggested RC3339 formats in our docs, please send us your error. In your specific case, we'd expect 2019-02-25T00:00:00Z to work.
