### ISSUE TITLE
Document LDAP security settings for InfluxEnterprise

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#2172]
I believe 1.7.0 was the first release that included LDAP security.

https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/ldap/ appears to still have the 1.6 LDAP config sample.

Documentation should be updated to include the newest sample config and should detail the `security` setting:

> There's one new configuration setting per LDAP server: `security`. The allowed options are:

> * `starttls`, which uses an unencrypted connection and upgrades to TLS, per the LDAP spec, as its first action; if starttls fails, the connection does not continue. starttls is the default setting if unspecified.
> * `starttls+insecure`, which operates the same as starttls but does not validate the serverside certificate. Standard caveats apply as with any insecure skip verification.
> * `none`, which just uses an unencrypted connection, identical to 1.6 and earlier behavior, which did not contain the `security` configuration.

**Comment by stevebang** [comment]
Added new sample LDAP config file, with the new security options, to this page.
