### ISSUE TITLE
tsi-preview-instances-only-prepare-your-node-to-support-time-series-index-tsi

### ISSUE THREAD

**Issue by DarrenMendalka** [influxdata/docs.influxdata.com#2185]
https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/upgrading/#step-5-for-tsi-preview-instances-only-prepare-your-node-to-support-time-series-index-tsi

We need to remove the `**for tsi preview-instances-only`** and should be done for all moving to TSI. 

Currently 
~~~
step-5-for-tsi-preview-instances-only-prepare-your-node-to-support-time-series-index-tsi
~~~

Should read as follows 
~~~
step-5-Prepare-your-node-to-support-time-series-index-tsi
~~~

https://influxdb.zendesk.com/agent/tickets/40704

**Comment by DarrenMendalka** [comment]
@kelseiv  Updated this.  Let me know if you need any other assistance on this one. 

Thanks

**Comment by kelseiv** [comment]
Thank you, @DarrenMendalka
