### ISSUE TITLE
documentation monitor service README link is broken

### ISSUE THREAD

**Issue by wdhnl** [influxdata/docs.influxdata.com#2186]
inside page: https://docs.influxdata.com/influxdb/v1.7/administration/server_monitoring/#influxdb-metrics-http-endpoint

the "monitor service README" link points at https://github.com/influxdb/influxdb/blob/master/monitor/README.md

I'm not sure what the right new link is due to the refactoring

**Comment by kelseiv** [comment]
Thank you, @wdhnl! fixed
