### ISSUE TITLE
Improve Chronograf docs re: security setup

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2188]
There is some confusion re: when/why the Chronograf Admin tab appears (or not).  
```I set up Chronograf and did the install but I’m not sure why according to the documentation I should see Chronograf Admin but I do not. I only see InfluxDB Admin.```

###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.7/administration/managing-security/
https://docs.influxdata.com/chronograf/v1.7/administration/managing-chronograf-users/
https://docs.influxdata.com/chronograf/v1.7/administration/managing-organizations/

###### What products and version are you using?
Chronograf 1.4 or higher

###### Where did you look before opening the issue?
Current doc set.

See attached image. 
![Screen Shot 2019-03-18 at 4 34 56 PM](https://user-images.githubusercontent.com/23535264/54570546-23735e80-499c-11e9-90af-2da7b18cb513.png)

It sounds like the documentation isn't clear about when this particular tab appears and that it ONLY appears once you've configured the authentication/authorization setup for Chronograf itself.  We need to figure out how to highlight this within the documentation for Chronograf.

**Comment by kelseiv** [comment]
Thanks, @timhallinflux - clarified docs to address this issue.
