### ISSUE TITLE
[InfluxDB] Clustering Problem - 0.10

### ISSUE THREAD

**Issue by corsoalex-pro** [influxdata/docs.influxdata.com#219]
Hello,

I tried to install InfluxDB on 3 nodes and configured a cluster. I followed this documentation : https://docs.influxdata.com/influxdb/v0.10/guides/clustering/

influxdb-itx5.gix <-> influxdb-itx2.gix <-> influxdb-th2.gix

==== influxdb-itx5.gix ====
```
vim /etc/influxdb/influxdb.conf
[meta]
  http-bind-address = "influxdb-itx5.gix:8091"
  bind-address = "influxdb-itx5.gix:8088"
```

==== influxdb-itx2.gix ====
```
vim /etc/influxdb/influxdb.conf
[meta]
  http-bind-address = "influxdb-itx2.gix:8091"
  bind-address = "influxdb-itx2.gix:8088"
```

```
vim /etc/default/influxdb
  INFLUXD_OPTS="-join influxdb-itx5.gix:8091"
```

==== influxdb-th2.gix ====
```
vim /etc/influxdb/influxdb.conf
[meta]
  http-bind-address = "influxdb-th2.gix:8091"
  bind-address = "influxdb-th2.gix:8088"
```

```
vim /etc/default/influxdb
  INFLUXD_OPTS="-join influxdb-itx5.gix:8091"
```

==== My procedure ===
influxdb-itx5.gix => service influxdb start
influxdb-th2.gix => service influxdb start
influxdb-itx2.gix => service influxdb start

My issue is : I cannot have a cluster on data node:

```
root at influxdb-itx5 ➜  ~  influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
> show servers
name: data_nodes
----------------
id	http_addr	tcp_addr
1	localhost:8086	influxdb-itx5.gix:8088

name: meta_nodes
----------------
id	http_addr		tcp_addr
1	influxdb-itx5.gix:8091	influxdb-itx5.gix:8088
2	influxdb-th2.gix:8091	influxdb-th2.gix:8088
3	influxdb-itx2.gix:8091	influxdb-itx2.gix:8088
```

Is there someone who can help me with the configuration

Alexandre Corso
acorso@franceix.net

**Comment by rossmcdonald** [comment]
@corsoalex-pro Per our conversation on the mailing list, the issue was due to the `http`.`bind-address` not being bound to the same hostname as the `meta` parameters. This was actually fixed with #215 a few days ago.
