### ISSUE TITLE
Select shows incorrect results

### ISSUE THREAD

**Issue by DG12** [influxdata/docs.influxdata.com#2204]
On page
[https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-basic-select-statement](https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#the-basic-select-statement)

The output is incorrect as there is a limit 3 only 3 results will be returned.

> > SELECT "water_level","location" FROM "h2o_feet" LIMIT 3
> name: h2o_feet
> time                   water_level  location
> ----                   -----------  --------
> 2015-08-18T00:00:00Z   8.12         coyote_creek
> 2015-08-18T00:00:00Z   2.064        santa_monica
> [...]
> 2015-09-18T21:36:00Z   5.066        santa_monica
> 2015-09-18T21:42:00Z   4.938        santa_monica

**Comment by kelseiv** [comment]
thank you @DG12! removed LIMIT 3
