### ISSUE TITLE
invalid markdown on influxdb auth page

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#2208]
Markdown is wrong in one of the notes on this page:
```
> **Note:** The password [string](/influxdb/v1.7/query_language/spec/#strings) must be wrapped in single quotes.
```

https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/#user-types-and-privileges

**Comment by noramullen1** [comment]
Thanks Russ! Fixed
