### ISSUE TITLE
Collectd documentation could be more clear

### ISSUE THREAD

**Issue by martinrw** [influxdata/docs.influxdata.com#2213]
I am currently setting up influxdb from scratch and to me the documentation is lacking a bit in some areas.
I wanted to set up the collectd database so I found this page:
https://docs.influxdata.com/influxdb/v1.7/administration/config/#collectd-settings
Reading through these docs you get the impression that by enabling collectd that it will automatically create the database for you, this did not happen for me I had to create it manually.

It's also not clear what value should be in retention-policy = ""

I spoke to your support who confirmed that I will need to create the database manually like this:

 CREATE DATABASE "collectd" WITH DURATION 52w REPLICATION 1 NAME "collectd-1-year"

then in the config file I can have:  retention-policy = "collectd-1-year"

It would be great if this could be clarified in the docs. 

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/administration/config/#collectd-settings

###### What products and version are you using?
Influx enterprise 1.7.4

###### Where did you look before opening the issue?
Searched through entire influx docs and also spoke to support

**Comment by stevebang** [comment]
Hmm...there's no mention of the doc page on the CollectD protocol and configuration here https://docs.influxdata.com/influxdb/v1.7/supported_protocols/collectd/.  I'll review that page and make sure the comments above are included. Also, checking that the config settings have a link to that page.

**Comment by stevebang** [comment]
@martinrw According to the CollectD protocol page mentioned in the previous comment, the database should be automatically created. If it is not, then this sounds like a bug. I'm updating the protocol to include some information that you provided that might help other users.

**Comment by martinrw** [comment]
Thanks for looking into it @stevebang 
Do you want me to raise it as a bug or shall I just leave it with you?

**Comment by stevebang** [comment]
@martinrw One engineer sounded surprised that the docs (the page that I referenced) said we would automatically create a database.  So, we'll have to check this out -- maybe it never did. Depending on the outcome, we might document this incorporating info provided by you.
