### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by martinrw** [influxdata/docs.influxdata.com#2214]
This page - https://docs.influxdata.com/influxdb/v1.7/administration/config/#collectd-settings
contains a few broken links.

There are 3 places on the page where it says "see the README on github" each time the page they link to gives a 404 error

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/administration/config/#collectd-settings

###### What products and version are you using?
influx enterprise 1.7.4

**Comment by stevebang** [comment]
Thanks, @martinrw, for letting us know!
All links fixed and pointing to the docs versions of the UDP, OpenTSDB, and Graphite pages.
Also, added the links to the data node configuration settings documentation.
Fixed in master and published.

**Comment by trafficonese** [comment]
There are still a lot of broken links in the `/content` section.
