### ISSUE TITLE
Incorrect parameter in documentation for aggregateWindow()

### ISSUE THREAD

**Issue by christopherlange** [influxdata/docs.influxdata.com#2231]
Documentation shows timeColumn as a parameter for aggregateWindow(). When using command line, it should be timeSrc 

> aggregateWindow
(columns: [string], createEmpty: bool, ^every: duration, ^fn: (^columns: [string], |pipe|: {map[kind:string] Ø (kind)}) -> {map[kind:string] Ø (kind)}, ^<-tables: {map[kind:string] Ø (kind)}, timeDst: string, timeSrc: string) -> {map[kind:string] Ø (kind)}

###### URL for relevant page?
https://docs.influxdata.com/flux/v0.24/functions/built-in/transformations/aggregates/aggregatewindow/#timecolumn

###### What products and version are you using?
InfluxDB shell version : 1.7.6

###### Where did you look before opening the issue?
Github issues. Does not appear to be listed as a bug.

**Comment by sanderson** [comment]
Thanks for the heads-up @christopherlange. I think this was a case of over-zealous find and replace. I just updated it across all Flux versions. The fix will go live on the next docs deploy.
