### ISSUE TITLE
Typo in Kapacitor and Chrono

### ISSUE THREAD

**Issue by caminsha** [influxdata/docs.influxdata.com#2233]
[https://docs.influxdata.com/kapacitor/v1.5/working/kapa-and-chrono/#managing-kapacitor-from-chronograf](https://docs.influxdata.com/kapacitor/v1.5/working/kapa-and-chrono/#managing-kapacitor-from-chronograf)

Typo in "To modify a ~thrid~ party alert handler:"

Fix: "To modify a **third** party alert handler:"

**Comment by sanderson** [comment]
Thanks @caminsha!
