### ISSUE TITLE
Link to http-listener and puppet-agent github readme is broken (404) [Telegraf input plugins v1.10]

### ISSUE THREAD

**Issue by beljoost** [influxdata/docs.influxdata.com#2236]
###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.10/plugins/inputs/#http-listener
Link "HTTP Listener input plugin" points to "https://github.com/influxdata/telegraf/blob/release-1.10/plugins/inputs/http_listener/README.md" which results in a 404 not found error.

https://docs.influxdata.com/telegraf/v1.10/plugins/inputs/#puppet-agent
Link "Puppet Agent input plugin" points to "https://github.com/influxdata/plugins/inputs/puppetagent" which results in a 404 not found error.

**Comment by stevebang** [comment]
Fixed Puppet link and removed http_listener from supported section (it had already been moved to the deprecated section). Changes appearing in next publishing of docs.
