### ISSUE TITLE
latest bind input not found

### ISSUE THREAD

**Issue by tomertcherniak1** [influxdata/docs.influxdata.com#2237]
which version to use for usage with bind plugin?

root@bind:~# telegraf --input-list | grep bind
root@bind:~# telegraf --version
Telegraf 1.10.3 (git: HEAD 294bb666)
root@bind:~# 

cat /etc/telegraf/telegraf.d/input_bind.conf 
[[inputs.bind]]
 ## Default is "http://localhost:8053/xml/v3".
  urls = ["http://localhost:8053/xml"]
  gather_memory_contexts = false
  gather_views = false

**Comment by danielnelson** [comment]
This plugin will be in 1.11.0, but you can try the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) based on the latest development version.
