### ISSUE TITLE
Default replication factor behavior

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2238]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.7/concepts/glossary/#replication-factor

A link to the details may also need to appear here (and/or as part of CREATE DATABASE)
https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#modify-retention-policies-with-alter-retention-policy

###### What products and version are you using?
All

###### Where did you look before opening the issue?
Searched replication factor....couldn't quickly find the default behavior and I believe it should appear on the page listed above.

The default replication factor for new databases created within InfluxEnterprise is equal to the number of data nodes for configurations where data nodes <=3.  For configurations which have more than 3 data nodes, the default replication factor is 3.  It is critical for users to review the replication factor for new databases created when they have more than 3 data nodes to ensure that the correct replication factor is set correctly.

**Comment by kelseiv** [comment]
Thank you, @timhallinflux!
