### ISSUE TITLE
[feature request] Add more examples of downsampling complex datasets

### ISSUE THREAD

**Issue by mjdesa** [influxdata/docs.influxdata.com#224]
As noted in https://github.com/influxdata/influxdb/issues/5578#issuecomment-182284985

>... it'd be really great to provide some examples of down-sampling strategies and use-cases should be done or not done

**Comment by rkuchan** [comment]
Anyone interested in downsampling, please provide specific areas in the documentation that could be improved. I'd recommend first taking a look at the [Downsampling and Retention](https://docs.influxdata.com/influxdb/v0.10/guides/downsampling_and_retention/) guide and letting us know if this is insufficient.
