### ISSUE TITLE
How to insert a piece of data into all the measurements in database

### ISSUE THREAD

**Issue by BoysAndGirls** [influxdata/docs.influxdata.com#2241]
###### What products and version are you using?
Package: influxdb
Version: 1.7.4

At a fixed moment, I want to add a piece of data to all the tables in the specified database, what should I do, thank you!

**Comment by sanderson** [comment]
@BoysAndGirls I don't know of a way to "wildcard" a measurement, so you'll have to write to each measurement separately. Probably the easiest way would be to just [write raw line protocol](http://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/).

Run `SHOW MEASUREMENTS` to get a list of all your measurements. You'll need the unix epoch timestamp for the time you want the new data points to show up at. The line protocol would look something like this:

```
measurement1 newField="piece of data" 1557151874745110000
measurement2 newField="piece of data" 1557151874745110000
measurement3 newField="piece of data" 1557151874745110000
measurement4 newField="piece of data" 1557151874745110000
etc.
```

**Comment by BoysAndGirls** [comment]
Thank you very much, since there is no "wildcard", I will use your method.  @sanderson
