### ISSUE TITLE
Missing the field "PreviousLevel" from the available fields

### ISSUE THREAD

**Issue by charlesrwood** [influxdata/docs.influxdata.com#2242]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/event_handlers/post/#alert-templates

###### What products and version are you using?
Kapacitor 1.5

###### PreviousLevel can be found here:
https://github.com/influxdata/kapacitor/blob/master/alert/types.go
func (e Event) AlertData() Data {
	return Data{
		ID:            e.State.ID,
		Message:       e.State.Message,
		Details:       e.State.Details,
		Time:          e.State.Time,
		Duration:      e.State.Duration,
		Level:         e.State.Level,
		Data:          e.Data.Result,
		PreviousLevel: e.previousState.Level,
		Recoverable:   e.Data.Recoverable,
	}
}

**Comment by sanderson** [comment]
Thanks for pointing this out @charlesrwood.
