### ISSUE TITLE
Add instructions for sideload all sources reload

### ISSUE THREAD

**Issue by MaksimPuzyrkov** [influxdata/docs.influxdata.com#2246]
Source data reload description is needed for sideload node as current documentation and Shedulled downtime guide leads to wrong expectations what data refreshed automatically.

> As your scheduled downtime begins, update the maintenance value in the appropriate host and host group source files to avoid alerts being triggered for those specific hosts and host groups.

Need to be changed to something like:

> As your scheduled downtime begins, update the maintenance value in the appropriate host and host group source files **and reload sideload** to avoid alerts being triggered for those specific hosts and host groups. 

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/nodes/sideload_node
https://docs.influxdata.com/kapacitor/v1.5/guides/scheduled-downtime/

**Comment by sanderson** [comment]
Thanks @MaksimPuzyrkov
