### ISSUE TITLE
How to query multiple measurements return single result

### ISSUE THREAD

**Issue by BoysAndGirls** [influxdata/docs.influxdata.com#2247]
Package: influxdb
Version: 1.7.4

I have two measurements, m and n

![image](https://user-images.githubusercontent.com/25577689/57696156-b53cd680-7682-11e9-9c5c-3571a44f44a1.png)

When I execute command “select * from m,n”, I get this result but not want

![image](https://user-images.githubusercontent.com/25577689/57696207-cd145a80-7682-11e9-91a8-fecb6d39b614.png)

I want them to be merged together and **sorted by time**. like this:  single result

time    &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;   &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; age name todo
----                --- ---- ----
1557834982119904700 &ensp;11  tom
1557834988682721800 &ensp;10  sam
1557835012263480100  &ensp;&ensp;&ensp; &ensp;&ensp;&ensp;&ensp;        good
1557835025176070900 &ensp;15  amy

What should I do, my influxdb client("github.com/influxdata/influxdb/client/v2"),thank you very much

**Comment by sanderson** [comment]
The data structure you're looking for requires a join and isn't possible with InfluxQL, but should be pretty simple to get with Flux. Are `age`, `name`, and `todo` tags or fields?

**Comment by BoysAndGirls** [comment]
Thank you for your answer. The age, name, and todo are fields. I didn't know Flux before, so I need to study it now.

**Comment by BoysAndGirls** [comment]
https://github.com/influxdata/docs.influxdata.com/issues/2249#issue-444427499

I am having some trouble when using FLux.

**Comment by BoysAndGirls** [comment]
I use Chronograf, but I still can't get the results I want.

I want a data structure like this

time    &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;   &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp; age name todo
----                --- ---- ----
1557834982119904700 &ensp;11  tom
1557834988682721800 &ensp;10  sam
1557835012263480100  &ensp;&ensp;&ensp; &ensp;&ensp;&ensp;&ensp;   good
1557835025176070900 &ensp;15  amy
1557835025176070900  &ensp;&ensp;&ensp; &ensp;&ensp;&ensp;&ensp;   bad

Instead of a bunch of duplicate data. @sanderson 

![1558003356(1)](https://user-images.githubusercontent.com/25577689/57848003-6c178e80-780a-11e9-873f-983c3166b8f4.jpg)

**Comment by sanderson** [comment]
After thinking through it, I don't think join is what you need. None of the example data points share any common attributes, so there's nothing that the could usefully join on. I think you can use `pivot()`, `union()`, and `group()` to get what you need. Try this:

```
data = from(bucket: "database/autogen")
	|> range(start: -10h)
  
m = data
  |> filter(fn: (r) => r._measurement == "m" )
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")

n = data
  |> filter(fn: (r) => r._measurement == "n")
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  
union(tables: [n,m])
 |> group()
```

`pivot()` will align all the field key-value pairs into columns. `union()` will join to two streams into one. `group()` (which by default removes all grouping) will combine everything into a single table.

**Comment by BoysAndGirls** [comment]
You are awesome! In your way, I have completely achieved the desired result. It looks like this:

![1558061099(1)](https://user-images.githubusercontent.com/25577689/57899851-323d9b00-7891-11e9-90e8-f0e45361c71f.jpg)

Thank you  @sanderson ! Thank you very much!
