### ISSUE TITLE
Use a regex to filter by field key

### ISSUE THREAD

**Issue by suvvenndu** [influxdata/docs.influxdata.com#2248]
https://docs.influxdata.com/flux/v0.24/guides/regular-expressions/ 

There is an error/typo in,  Use a regex to filter by field key, 

The following example writes, it  excludes records that **do not have _percent** in a field key.

```
from(bucket: "telegraf/autogen")
  |> range(start: -15m)
  |> filter(fn: (r) =>
    r._measurement == "mem" and
    r._field =~ /_percent/
  )
```
Where as in example we use `=~` , which includes all fields which have _percent.

The example should use,  !~, instead.
```
from(bucket: "telegraf/autogen")
  |> range(start: -15m)
  |> filter(fn: (r) =>
    r._measurement == "mem" and
    r._field !~ /_percent/
  )
```

**Comment by sanderson** [comment]
Thanks for the heads up @suvvenndu!

**Comment by sanderson** [comment]
Because the example is meant to  **exclude** records that **do not have _percent** in a field key, it is technically correct, but the double negative in the explanation is confusing. I've updated both the wording and the example.

**Comment by suvvenndu** [comment]
@sanderson , Doesn't `r._field =~ /_percent/` mean , get all the fields where field like/contains  "_percent"?

![image](https://user-images.githubusercontent.com/17617440/58296350-b904f180-7e16-11e9-8836-09a5987fa708.png)

https://docs.influxdata.com/flux/v0.24/language/operators/

**Comment by sanderson** [comment]
Correct, the wording in the description was confusing. If you **exclude** records that **do _not_ have** x, it's the same as **including** only those things **with** x. The double-negative was admittedly confusing, so I've updated it to be more clear.

"**Exclude** all records that **do not** have `_percent` in a field key" is the same as "**Include** only records with `_percent` in the field key."

**Comment by suvvenndu** [comment]
Thanks for clarification @sanderson
