### ISSUE TITLE
Error: client error: 401 Unauthorized

### ISSUE THREAD

**Issue by BoysAndGirls** [influxdata/docs.influxdata.com#2249]
Package: influxdb
Version: 1.7.4

I enable Flux by setting influxdb.conf: flux-enabled = true

I execute the following command from the terminal

**influx  -type='flux' -username=XXX  -password=XXX**

When I execute the following command

 **from(bucket:"dabase/demo")**

I got an error message:  **Error: client error: 401 Unauthorized**

I'm new to Flux and what should I do. Thank you

**Comment by sanderson** [comment]
Does the user you're authorizing with have have access to the `dabase` database and `demo` retention policy?

**Comment by BoysAndGirls** [comment]
Yes, this user has permissions. And it is normal in **InfluxQL Query**.  @sanderson

**Comment by BoysAndGirls** [comment]
Amazing! When I execute the command through chronograf, it is normal, but it is not normal at the terminal. @sanderson

**Comment by sanderson** [comment]
Hmm, it may be that with the 1.7.4 version of `influx`, `-type='flux'` doesn't support authorization.

**Comment by BoysAndGirls** [comment]
May be that doesn't support authorization. I can get results through Chronograf or POST request, not through the terminal, so it does not affect me now. If you feel it is necessary, you can close it. Thanks again @sanderson
