### ISSUE TITLE
Wrong text in DOCS

### ISSUE THREAD

**Issue by flopp999** [influxdata/docs.influxdata.com#2252]
on this page
https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#tags
is says
" Supported operators:  `=`    equal to  `<>`  not equal to  `!=`  not equal to"

I think it should be
" Supported operators:  `=`    equal to  `<>`  less/more than  `!=`  not equal to"

**Comment by sanderson** [comment]
The documentation is correct as is. `<>` is a single operator that evaluates to `true` if both operands are not equal. It is essentially the same as `!=`.

```js
a != b // Evaluates to true
a <> b // Evaluates to true

a != a // Evaluates to false
a <> a // Evaluates to false
```
