### ISSUE TITLE
Select documentation too long and too wide

### ISSUE THREAD

**Issue by DG12** [influxdata/docs.influxdata.com#2253]
https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/

Would it be possible to
1) provide an entire select railroad diagram (something like that at http://real-world-systems.com/docs/influx.1.html#select my personal example rich, content poor page)

2) break example statements so they fit in the window. In particular so the clause being discussed can be viewed without needing to scroll (especially as there is no indication that there is content to the right)

3) split the page in to 2 or 3 because scrolling up and down to find various clauses causes one to loose ones place. Adding TOP links would also be helpful.

**Comment by sanderson** [comment]
Thanks @DG12. All great suggestions. We're in the process of addressing the overly long pages in the docs. I agree with limiting the width of code inside of code blocks.
