### ISSUE TITLE
Attempting to add a data node to cluster returns: add-data: operation exited with error: open <license key>: no such file or directory

### ISSUE THREAD

**Issue by dbernbeck** [influxdata/docs.influxdata.com#2259]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.6/install-and-deploy/production_installation/data_node_installation/#join-the-data-nodes-to-the-cluster

###### What products and version are you using?
Influx Enterprise 1.6.3

###### Where did you look before opening the issue?
Google, which pointed to some issues in github

I was able to use add-meta commands using the same license-key.

**Comment by sanderson** [comment]
@dbernbeck The `license-path` or `license-key` is specified in the config file used for your data nodes. Meta nodes use a separate config file. You likely just need to updatedyour data node config files with either the `license-path` or `license-key`, restart the `influxd` process, then try to add the node(s) again.

**Comment by dbernbeck** [comment]
Thanks @sanderson I do have a license-key value in place, and the error I receive provides the license-key value instead of '<license-key." (I just didn't add it to this issue in case it is publically accessible.)

I went back to the config file, ensured it has the license key value I was given, stopped and started the data node service.  Same error on the meta node when I try the add-data command

**Comment by dbernbeck** [comment]
I found the problem. on the meta node I'm using to add the data nodes to the cluster, I had errantly add the key to the license-path parameter. Once I corrected the meta node, the add-data command worked.
