### ISSUE TITLE
New config options for Kapacitor re: TLS

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2261]
See https://github.com/influxdata/kapacitor/pull/2198

Similar to the change that was made for InfluxDB -- 
http://docs.influxdata.com/influxdb/v1.7/administration/config/#transport-layer-security-tls-settings

###### URL for relevant page?
http://docs.influxdata.com/kapacitor/v1.5/administration/configuration/

###### What products and version are you using?
Kapacitor 1.5.3

**Comment by stevebang** [comment]
Closing -- documentation was recently added to the 1.5.x docs.
