### ISSUE TITLE
document _internal values

### ISSUE THREAD

**Issue by desa** [influxdata/docs.influxdata.com#227]
https://github.com/influxdata/influxdb/issues/5616

> Hello,
> 
> I would like to have some stats about the DB
> 
> the only documentation ressource I found is: https://influxdata.com/blog/how-to-use-the-show-stats-command-and-the-_internal-database-to-monitor-influxdb
> 
> Can you please describe the values for each measurement.
> 
> there are some self-explanatory values like (batchesTx, batchesTxFail, pointsRx, queryFail, queryOk, ....)
> 
> but becomes more complicated with
> engine:
> pointsWrite, pointsWriteDedupe ?, blksWriteBytes, blksWriteBytesC ?
> what's the difference ?
> 
> and most of the runtime, wal, write values
> 
> This may be time consuming. but at least few words for the most complicated ones
> 
> thank you !

**Comment by beckettsean** [comment]
#### Size on disk:
select sum(diskBytes)/(1024*1024) as db_size_mb from "_internal"."monitor"."shard" where time > now() - 10s group by hostname,"database"

#### metaseries cardinality
SELECT sum(numSeries) AS "total_series" FROM "_internal".."database" WHERE time > now() - 10s

**Comment by beckettsean** [comment]
closing in favor of #758

**Comment by Hamelina** [comment]
Hello,
I've been trying to search for the unit of each value for each measurement in the _internal database but didn't find them. Does anyone know where I can find them ? 
Thank you in avance

**Comment by desa** [comment]
@Hamelina a better place to ask this question would be http://community.influxdata.com/

It seems like according to this issue https://github.com/influxdata/docs.influxdata.com/issues/758#issuecomment-400380981 they are not documented. A better place to ask this question would be http://community.influxdata.com/

**Comment by sanderson** [comment]
Resolved in https://github.com/influxdata/docs.influxdata.com/pull/1908
