### ISSUE TITLE
Dead links in Chronograf docs

### ISSUE THREAD

**Issue by danatinflux** [influxdata/docs.influxdata.com#2270]
Trying to get more info on OAUTH and Chronograf. 

Went to https://docs.influxdata.com/chronograf/v1.7/administration/managing-chronograf-users/ , which shows a link for 'managing security' (https://docs.influxdata.com/chronograf/1.7/administration/managing-security/) which 404s.

I tried substituting 1.6 for 1.7 and that did not work either.

**Comment by timhallinflux** [comment]
also

http://docs.influxdata.com/chronograf/v1.7/administration/creating-connections/#managing-influxdb-connections-using-the-chronograf-ui

Step 4. has a link to https://docs.influxdata.com/chronograf/v1.7/create-a-dashboard which is non-existent
