### ISSUE TITLE
Update Hinted Handoff Metrics

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2271]
The description of the metrics captured for InfluxEnterprise need to be updated based on this PR. https://github.com/influxdata/plutonium/pull/2961

###### URL for relevant page?
https://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/measurements-internal/

###### What products and version are you using?
Enterprise 1.7.7 and beyond

**Comment by stevebang** [comment]
All new hh measurements added to _internal listing.

**Comment by stevebang** [comment]
Closed by https://github.com/influxdata/docs.influxdata.com/pull/2342
