### ISSUE TITLE
Broken link on Enterprise meta config page

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs.influxdata.com#2278]
The link for "Configuration and operational considerations on a cluster" on the Enterprise meta config page points to https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/config-meta-nodes/enterprise_influxdb/latest/features/clustering-features/#configuration-and-operational-considerations-on-a-cluster. Which looks like the paths from two links were combined.

###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/config-meta-nodes/#lease-duration-1m0s

###### What products and version are you using?
InfluxDB Enterprise 1.7

###### Where did you look before opening the issue?
Did not check existing issues.

**Comment by kelseiv** [comment]
Thank you, Gunnar
