### ISSUE TITLE
Telegraf Docs -- Add InfluxDB v2 Input Plugin

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2285]
There isn't a specific InfluxDB v2 Input Plugin for Telegraf as InfluxDB v2 exposes it's metrics using the Prometheus Exposition Format.

Users might be confused as to why there is an InfluxDB v1 input and InfluxDB v1 and InfluxDB v2 output plugins....but not a specific InfluxDB v2 input plugin.

For ease of understanding, putting this into the docs so that users who are looking specifically to collect metrics from InfluxDB v2 to InfluxDB Cloud (for example) can easily find and understand how to configure this.

For example, running the collection on an instance running on localhost the configuration is:
```
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://localhost:9999/metrics"]
```
###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.10/plugins/inputs/#influxdb-v1-x

**Comment by stevebang** [comment]
Added to InfluxDB 2.0 docs listing too.
