### ISSUE TITLE
Typo in https://docs.influxdata.com/influxdb/v0.10/guides/hardware_sizing/

### ISSUE THREAD

**Issue by cristian-marin-hs** [influxdata/docs.influxdata.com#229]
In the paragraph "How should I configure my hardware?", in the first line, there should be: 
When running InfluxDB in a production environment the wal directory **and** the data directory should be on separate storage devices.

**Comment by rkuchan** [comment]
Thanks, @cristian-marin-hs! Fixed by https://github.com/influxdata/docs.influxdata.com/pull/234.
