### ISSUE TITLE
Install input plugin on Windows

### ISSUE THREAD

**Issue by alexmc1510** [influxdata/docs.influxdata.com#2290]
Dear community,
I have telegraf already running in a PC. I would like to add ping input plugin but I have no idea how to do that. Could you give me some info? Is it possible?

Regards

**Comment by sanderson** [comment]
@alexmc1510 Make sure you have Telegraf 0.1.8+ (this is a fairly old version so I'm guessing you have a newer version installed). Add an `[[inputs.ping]]` section to your `telegraf.conf`. Examples of the available configuration options are available here: https://github.com/influxdata/telegraf/blob/release-1.11/plugins/inputs/ping/README.md

Once the ping input is added to your `telegraf.conf`, restart the telegraf agent using the updated config.
