### ISSUE TITLE
OpenTSDB README page not found

### ISSUE THREAD

**Issue by kebe7jun** [influxdata/docs.influxdata.com#2299]
The [README](https://github.com/influxdata/influxdb/blob/master/services/opentsdb/README.md) link return a 404 page.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/supported_protocols/opentsdb/

###### What products and version are you using?
1.7

###### Where did you look before opening the issue?
https://github.com/influxdata/influxdb
https://docs.influxdata.com/influxdb/v1.7/supported_protocols/opentsdb/

**Comment by kelseiv** [comment]
thank you, @kebe7jun!
