### ISSUE TITLE
Point inaccurately described

### ISSUE THREAD

**Issue by bwmcbride** [influxdata/docs.influxdata.com#2312]
###### github suggestions

The key_concepts page states:

[[
Finally, a point is the field set in the same series with the same timestamp. For example, here’s a single point:
]]

It then goes on to show a measurement with a single row, which is not a field set.

Picky - but it is potentially confusing.

Is a point a row in a measurement or a field set?

**Comment by stevebang** [comment]
Thanks, @bwmcbride, for catching that -- it's definitely incorrect.  The best definition in the docs is:

   "A single line of text in line protocol format represents one data point in InfluxDB. It informs 
    InfluxDB of the point’s measurement, tag set, field set, and timestamp."
From:
https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/#syntax

@kelseiv - Also take a look at the glossary definition for point -- it needs updating and clarification too. https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#point

**Comment by stevebang** [comment]
Here's a little about points, quoting Ryan Bett's popular "InfluxDB Internals" presentation:

An InfluxDB database stores points. A point has four components: a measurement, a tagset, a fieldset, and a timestamp.
...
Each point is stored within exactly one database within exactly one retention policy. A database is a container for users, retention policies, and points.

"https://www.influxdata.com/blog/influxdb-internals-101-part-one/

**Comment by kelseiv** [comment]
Thank you, @bwmcbride and @stevebang! updated both glossary and key concept definitions.
