### ISSUE TITLE
systemctl custom option port not working

### ISSUE THREAD

**Issue by snenkov** [influxdata/docs.influxdata.com#2317]
I am trying to run chronograf systemctl on a different port from the default 8888, as this one is where my jupyter notebook runs on.

Basically I run `systemctl start chronograf --port=8888` and get the following error:
`systemctl: unrecognized option '--port=8888'`

Can anyone help with this?
###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.7/administration/config-options#host

###### What products and version are you using?
I am using Chronograf 1.7.

###### Where did you look before opening the issue?
I checked on the relevant URL page provided above,

**Comment by stevebang** [comment]
@snenkov Did you try changing the port in the chronograf configuration settings? If the default port (8888) conflicts with your Jupyter notebook's port, then you should be able to change the port to an unused port that will not conflict. If that doesn't work, then it might be a product bug. This doesn't sound like a doc issue — questions like this are better answered in the InfluxData community (https://community.influxdata.com/) or the Slack community mentioned on that page.
