### ISSUE TITLE
Security issue with lodash 

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs.influxdata.com#2318]
Github is reporting a security vulnerability in the `lodash` dependency. It needs to be updated to `4.6.2`.

**Comment by timhallinflux** [comment]
@sanderson can you teach @kelseiv how to make these kinds of updates?  Perhaps we can/should document this and then share with the team?

**Comment by sanderson** [comment]
I'll document this process in the internal docs wiki.

This issue was closed by #494bbdf.
