### ISSUE TITLE
standardize on either sh or shell for shell code highlight

### ISSUE THREAD

**Issue by kyzh** [influxdata/docs.influxdata.com#232]
I'm looking at the documentation and for highlighting shell code, there is a mix of
```
```sh
```
and 
```
```shell
```

I created 2 PR:
- PR#230 to standardize on [sh](https://github.com/influxdata/docs.influxdata.com/pull/230)
- PR#231 to standardize on [shell](https://github.com/influxdata/docs.influxdata.com/pull/231)

That way you can just pick your favourite.

**Comment by gunnaraasen** [comment]
Thanks @kyzh. Looking at the Prism.js docs realized both `sh` and `shell` are incorrect. It should be `bash`.

**Comment by kyzh** [comment]
I'll submit a PR with `bash` instead then.

**Comment by kyzh** [comment]
@gunnaraasen I closed the two original PR and open a new one with the suggested fix [here](https://github.com/influxdata/docs.influxdata.com/pull/237)
Thanks for :mag: at my PRs

**Comment by gunnaraasen** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/237
