### ISSUE TITLE
Plugins overview has swapped descriptions for output and processor 

### ISSUE THREAD

**Issue by kevin-cantwell** [influxdata/docs.influxdata.com#2321]
###### URL for relevant page?

https://docs.influxdata.com/telegraf/v1.11/plugins/

###### What products and version are you using?

Telegraf (v1.6 - v1.11)

###### Where did you look before opening the issue?

Issues page

----------------------

I noticed that the descriptions for output and processor plugins seemed swapped in a bunch of places.

It should be changed so that:

1. Output plugins are always described as "write metrics to various destinations."
1. Processor plugins are always described as "transform, decorate, and filter metrics."

**Comment by stevebang** [comment]
Thanks, @kevin-cantwell!

**Comment by kevin-cantwell** [comment]
Hi @stevebang thanks for closing, but just fyi the PR you submitted only fixes a subset of the typos. I do have a PR open that fixes them all I believe. Please take a look at merge it if it looks good to you: https://github.com/influxdata/docs.influxdata.com/pull/2320
