### ISSUE TITLE
Can I have multiple time stamps?

### ISSUE THREAD

**Issue by snenkov** [influxdata/docs.influxdata.com#2323]
As counterintuitive for a TSDB as this may sound, can I have multiple time series in the DB?

Example:
- one time stamp is date of arrival 
-  one time stamp is date for which the data is relevant for

I understand that one of these can be as a value field in the data, but is this the best way to implement?

Thanks!

###### URL for relevant page?
None.

###### What products and version are you using?
Influx DB 1.7

###### Where did you look before opening the issue?
Documentation

**Comment by timhallinflux** [comment]
You cannot.  I believe what you are after is support for a datetime type.  There is only one of those allowed at present which you can set to one of these values.

However, you can create a field with either a string which captures this information or a field as an integer offset value -- this might allow you to then manipulate the other data in your application?

**Comment by stevebang** [comment]
@snenkov I think that @timhallinflux answered your question. 
@timhallinflux I'm assigning this to @kelseiv to see if we can add anything relevant to the docs based on your suggestion.

**Comment by timhallinflux** [comment]
@snenkov -- any other questions?

**Comment by snenkov** [comment]
No, thank you very much! :)
