### ISSUE TITLE
Load directory service guide typo

### ISSUE THREAD

**Issue by MaksimPuzyrkov** [influxdata/docs.influxdata.com#2332]
It is like a typo in signal name what is used to trigger load directory Kapacitor service. Where's no signal "NOHUP" exist, "SIGHUP" should be used instead. 

"The load directory service enables file-based definitions of Kapacitor tasks, templates, and topic handlers that are loaded on startup or when a **NOHUP** signal is sent to the process."
need to be changed to 
"The load directory service enables file-based definitions of Kapacitor tasks, templates, and topic handlers that are loaded on startup or when a **SIGHUP** signal is sent to the process."

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/guides/load_directory/

###### What products and version are you using?
Kapacitor Enterprise 1.5.2

###### Where did you look before opening the issue?
https://en.wikipedia.org/wiki/Signal_(IPC)
https://en.wikipedia.org/wiki/SIGHUP

**Comment by stevebang** [comment]
Updated in master -- change will appear in next publishing today. Thanks, @MaksimPuzyrkov !!
