### ISSUE TITLE
Document the format of the http access_log

### ISSUE THREAD

**Issue by rbetts** [influxdata/docs.influxdata.com#2338]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.7/administration/logs/

###### What products and version are you using?

InfluxDB 1.6+

###### Where did you look before opening the issue?

Above link.

Request to document the http access log format that we spew.  Example log line:

172.19.8.11,172.19.5.162 - - [21/Jul/2019:03:01:27 +0000] "GET /query?db=metrics&q=SELECT+MEAN%28value%29+as+average_cpu%2C+MAX%28value%29+as+peak_cpu+FROM+%22foo.load%22+WHERE+time+%3E%3D+now%28%29+-+1m+AND+org_id+%21%3D+%27%27+AND+group_id+%21%3D+%27%27+GROUP+BY+org_id%2Cgroup_id HTTP/1.0" 200 11450 "-" "Baz Service" d4ca9a10-ab63-11e9-8942-000000000000 9357049  

I _think_ the format is:

```
	return fmt.Sprintf(`%s - %s [%s] "%s %s %s" %s %s "%s" "%s" %s %d`,
		host,
		detect(username, "-"),
		start.Format("02/Jan/2006:15:04:05 -0700"),
		r.Method,
		uri,
		r.Proto,
		detect(strconv.Itoa(l.Status()), "-"),
		strconv.Itoa(l.Size()),
		detect(referer, "-"),
		detect(userAgent, "-"),
		r.Header.Get("Request-Id"),
		// response time, report in microseconds because this is consistent
		// with apache's %D parameter in mod_log_config
		int64(time.Since(start)/time.Microsecond))
```

From: `influxdb/services/httpd/response_logger.go`

**Comment by timhallinflux** [comment]
Let's add this to the platform documentation section.

**Comment by noramullen1** [comment]
@timhallinflux I'm wondering if it makes more sense for this to go in the influxdb logs documentation (https://docs.influxdata.com/influxdb/v1.7/administration/logs/) instead?

**Comment by timhallinflux** [comment]
yeah...I think you are right.
