### ISSUE TITLE
Exporting from OSS to Cloud details

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs.influxdata.com#2341]
Ticket:  https://influxdb.zendesk.com/agent/tickets/42135

Add details/limitations to [Importing data to InfluxCloud from InfluxDB](https://help.influxcloud.net/import-into-cloud/).

From the ticket: 

- If the amount of information on the OSS instance is fairly small you can export it using the export tooling documented at https://docs.influxdata.com/influxdb/v1.7/tools/influx_inspect/#export. This will produce a file containing all of the points that can then be imported as normal writes using the influx command documented at https://docs.influxdata.com/influxdb/v1.7/tools/shell/#import.

- My understanding is that this may produce too large of a file based on the size estimates from Trevor so the other option is to produce a portable backup that we can restore on the cloud cluster. To make this backup please use the command documented at https://docs.influxdata.com/influxdb/v1.7/administration/backup_and_restore/ while making sure to include the portable flag. Please keep in mind that in restoring this information we will need to create a new databases as restoring does not allow data to be merged."

**Comment by kelseiv** [comment]
Keep open for @noramullen1
