### ISSUE TITLE
Telegraf docs search issue

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs.influxdata.com#2345]
The search bar doesn't seem to work in the Telegraf docs. Is this something we can fix in Algolia?

https://docs.influxdata.com/telegraf/v1.11/

**Comment by sanderson** [comment]
I cleaned up some of the logic around generating the search "facets" in https://github.com/influxdata/docs.influxdata.com/commit/39dd60865317fff329a1effdbd09cd2ad76c2966, but it looks like there are some issues with the Algolia index itself. I've submitted a support request with them.
