### ISSUE TITLE
Describe/visualize the basics of HA/Clustering

### ISSUE THREAD

**Issue by nisley** [influxdata/docs.influxdata.com#2349]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/high_availability/

Have we considered describing/visualizing HA/Clustering here? The link goes through to Influx Enterprise but nowhere do they see a picture or explanation of how the HA/Clustering is implemented or looks.

**Comment by kelseiv** [comment]
Let's add the following sentence/link:
To learn more about high availability clustering, see [Clustering in InfluxDB Enterprise](/enterprise_influxdb/latest/concepts/clustering/).

**Comment by pierwill** [comment]
Will be closed when https://github.com/influxdata/docs-v2/pull/1331 gets to `master`.
