### ISSUE TITLE
Hi Team, i am not able to install the telegraf agent on checkpoint firewall.can you share the steps to install and get the data in influx db.

### ISSUE THREAD

**Issue by Aathi87** [influxdata/docs.influxdata.com#2353]

**Comment by sanderson** [comment]
@Aathi87 Can you please include details about what issues you ran into during the installation process? Which operating system is installed? Check Point IPSO (based on FreeBSD), IPSO-SX, or IPSO-LX (based on Linux)?  Each include enhanced security options that may prevent you from installing and running the Telegraf agent.

**Comment by Aathi87** [comment]
Hi Sanderson,

Please find the below details
uname -a:
Linux Firewall 2.6.18-92cpx86_64 #1 SMP Tue Sep 4 13:46:30 IDT 2018 x86_64 x86_64 x86_64 GNU/Linux

Checkpoint OS is Gaia
This is Check Point's software version R80.20 - Build 255
I tired to install rpm package got the below message.
/usr/bin/telegraf: /usr/bin/telegraf: cannot execute binary file

regards
Aathi

**Comment by sanderson** [comment]
Are there any other details about why it can't execute the file? Does it have executable permissions?

```
chmod +x /user/bin/telegraf
```
