### ISSUE TITLE
is there any  telegraf plugin to get the tcpdump source and destination ip at interface level.We have to get the source and destination ip on influx DB

### ISSUE THREAD

**Issue by Aathi87** [influxdata/docs.influxdata.com#2358]

**Comment by sanderson** [comment]
We try to keep issues on the docs repo to issues specific to the docs project (missing content, typos, broken links, etc.). Project-specific questions like this are better suited for the [InfluxData Community](https://community.influxdata.com/) or the [Telegraf project](https://github.com/influxdata/telegraf) itself.

But to answer your question, there currently isn't a tcpdump Telegraf plugin, but there may be another way to accomplish what you're trying to do.
