### ISSUE TITLE
unclear in documentation : Show tag keys with where time clause uses shard duration as finest granularity 

### ISSUE THREAD

**Issue by marcvandermeiren** [influxdata/docs.influxdata.com#2366]
see this discussion on the influx community to see what I mean :-) 

https://community.influxdata.com/t/undocumented-behaviour-with-show-tag-keys-values/10805

**Comment by kelseiv** [comment]
Thank you, @marcvandermeiren! 

Updated [docs](https://docs.influxdata.com/influxdb/v1.7/query_language/schema_exploration/#filter-meta-queries-by-time).
