### ISSUE TITLE
Add queries that assume `/debug/vars` (watcher of watchers) method is being used

### ISSUE THREAD

**Issue by samhld** [influxdata/docs.influxdata.com#2422]
Currently, the downloadable dashboards [here](https://docs.influxdata.com/platform/monitoring/monitoring-dashboards/) assume the use of `_internal`...which is not our best practice.  Can we get dashboards for the Watcher of Watchers approach?  I think the modifications should be limited to simply removing the `"_internal"..` from each `FROM` clause and adding `influxdb_` as a prefix to each `SELECT`'ed field.
###### URL for relevant page?
https://docs.influxdata.com/platform/monitoring/monitoring-dashboards/

**Comment by timhallinflux** [comment]
@samhld -- I believe that BOTH are represented.  There are two sections of those docs: one which is _internal and the other which is based on Telegraf.  The reason?  Because many folks will simply start with _internal enabled and then need to shift to the best practices as you point out.
