### ISSUE TITLE
Typo in enterprise 1.7 documentation

### ISSUE THREAD

**Issue by jordantaylor2** [influxdata/docs.influxdata.com#2440]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/renaming/

In the main section "Before You Begin" it says spend where I assume it should be suspend:

> First, spend write and query activity to the cluster.

###### What products and version are you using?
InfluxDB Enterprise 1.7

###### Where did you look before opening the issue?
In the open issues to see if this had been mentioned already, to find that it hadn't.

**Comment by sanderson** [comment]
Thanks for reporting @jordantaylor2!
