### ISSUE TITLE
Function math.m_max() doesn't exist.

### ISSUE THREAD

**Issue by FSkayer** [influxdata/docs.influxdata.com#2444]
The function math.m_max() doesn't exists on Influx 1.7.6. The working function is math.mMax()

###### URL for relevant page?
https://docs.influxdata.com/flux/v0.36/functions/math/m_max/

###### What products and version are you using?
version: 1.7.6

**Comment by sanderson** [comment]
Thanks @FSkayer! You are absolutely right. I'll get these updated.
