### ISSUE TITLE
Chronograf 1.7 basic user auth

### ISSUE THREAD

**Issue by tmeralus** [influxdata/docs.influxdata.com#2449]
###### URL for relevant page?
https://docs.influxdata.com/chronograf/v1.7/administration/config-options
https://docs.influxdata.com/chronograf/v1.7/administration/configuration/

###### What products and version are you using?
Chronograf Version: 1.7.14

###### Where did you look before opening the issue?
https://docs.influxdata.com/chronograf/v1.7/administration/configuration/

Basic Authentication fails in chronograf. I have setup env variables for gitlab Oauth2 with no avail and turned to look at basic auth with roles and permissions but with chronograf 1.7.12 and 1.7.14 (current build) there doesnt seem to be options to set a config file for chronograf or troubleshoot authentication other than the 404 errors that lead nowhere.

when changing auth-enabled option to true I lose all my data and hosts (dashboards are active but everything else fails).

[http]
  enabled = true
  bind-address = ":8086"
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  auth-enabled = true 
  flux-enabled = true

**Comment by tmeralus** [comment]
BUELLER.....BUELLER...

**Comment by timhallinflux** [comment]
@tmeralus -- have a look at this: ity.influxdata.com/t/chronograf-gitlab-impossible-to-get-authentication-working/6787

@pierwill -- please update the Chronograf docs with the information contained within the community post for GitLab.

**Comment by tmeralus** [comment]
Thank you. Glad someone got to this :)

**Comment by timhallinflux** [comment]
@tmeralus -- did that pointer resolve your issue?

**Comment by tmeralus** [comment]
It did not but I am under the impression that chronograf does not and will not support basic authentication. I have switched to grafana as my GUI of choice. I'm way to update the docs or send a PR to add a note for that if someone can verify this to be true.
