### ISSUE TITLE
clarify Windows support per-product on the downloads page

### ISSUE THREAD

**Issue by jackpoz** [influxdata/docs.influxdata.com#245]
[Download](https://influxdata.com/downloads/#influxdb) and [Installation](https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v0.10/introduction/installation.md) pages don't mention at all if InfluxDB supports Windows and which steps are required to set it up on that OS.
The fact that https://docs.influxdata.com/ is missing a "search" feature makes it even more difficult to find any documentation about the topic.

**Comment by beckettsean** [comment]
Windows is unsupported for InfluxDB and will remain so until the TSM engine can be compiled on Windows. See https://github.com/influxdata/influxdb/issues/5359 for more on Windows support for each product in the TICK stack.

**Comment by mvadu** [comment]
@beckettsean TSM compiles and works well enough as of now on master. Clustering is still work in progress. People are welcome to test the version and report bugs. If someone can't build on their own, they can download from https://github.com/mvadu/influxdb/releases/tag/v0.10.1

**Comment by jackpoz** [comment]
@mvadu could you please upgrade your Windows binaries to a more recent version like v0.10.3 ? Anything containing https://github.com/influxdata/influxdb/commit/e84cbc569016509f1ec1d2c8736c051b215b1839 is welcome

**Comment by mvadu** [comment]
@jackpoz Please check out [v0.11.0-rc1](https://github.com/mvadu/influxdb/releases/tag/v0.11.0-rc1). This is same 0.11 code that Influx pushed out last week with one additional fix for windows side to fix port 8091 issue.

**Comment by beckettsean** [comment]
Windows isn't officially supported for any products, although it works for some. Will document things when they are official.
