### ISSUE TITLE
Repetitive alerts 

### ISSUE THREAD

**Issue by xSachinBharadwajx** [influxdata/docs.influxdata.com#2450]
I am relatively new to the TICK stack. 
While setting up an alerting mechanism I came across an issue of repetitive alerting. 

For Example: 
**Alerting condition:** Send Alert where "X metric" is less than 50 Preview data from Past 10m. 

Once the above condition is met an alerting mail is triggered. A ticket for this alert would be created from our end . Assuming the issue is not fixed in the 10 minute window(most likely the case). Another alert would be triggered in the next 10m causing a duplication of tickets. 

Is there a way to avoid this form of duplication? 

![image](https://user-images.githubusercontent.com/41123416/67274689-9c143d80-f4de-11e9-9eb8-d7b91f1bfa55.png)

**Comment by sanderson** [comment]
You can use `StateChangesOnly`: https://docs.influxdata.com/kapacitor/v1.5/nodes/alert_node/#statechangesonly
