### ISSUE TITLE
Running chronograf as non-root 

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs.influxdata.com#2454]
**Question**: "I'm trying to run your chronograf docker file here at IBM and am having a hard time getting it to run as non root. Keeps saying

ime="2019-10-11T16:05:15Z" level=error msg="Unable to open boltdb; is there a chronograf already running?  open /var/lib/chronograf/chronograf-v1.db: permission denied" component=boltstore"

**Answer from Russ**: The default location where Chronograf stores its state is in /var/lib... but it can be overridden using the $BOLT_PATH env var in your Docker file. You can reference any path to a file that your user has access to and Chronograf will create the file there if it doesn't exist.

➜  bin export BOLT_PATH=/tmp/chronograf-v1.db
➜  bin ./chronograf
INFO[0000] Running migration 59b0cda4fc7909ff84ee5c4f9cb4b655b6a26620
INFO[0000] Serving chronograf at http://[::]:8888        component=server

we have this: 
https://docs.influxdata.com/platform/installation/sandbox-install/ but I didn’t see an obvious link from the getting started section of the 1.x docs.

**Comment by pierwill** [comment]
Closing this after #2494. For future reference, the `BOLT_PATH` environment variable is referenced here: https://docs.influxdata.com/chronograf/v1.7/administration/config-options/.
