### ISSUE TITLE
run: create server: to upgrade a cluster, please contact support at influxdata

### ISSUE THREAD

**Issue by devdba** [influxdata/docs.influxdata.com#246]
upgrade from 0.9.6.1 to 0.10.0,when execute /etc/init.d/influxdb start,but failed. see the /var/log/influxdb/influxd.log find this:
2016/02/16 10:29:34 Go version go1.4.3, GOMAXPROCS set to 40
2016/02/16 10:29:34 Using configuration at: /etc/influxdb/influxdb.conf
run: create server: to upgrade a cluster, please contact support at influxdata

**Comment by beckettsean** [comment]
This is not an issue with the documentation, so I will close this out.

The experimental clustering in 0.9 is incompatible with the clustering implementation in 0.10. There is no migration path. If you need to recreate your cluster with data, please contact support as directed in the error message.
