### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by dgm816** [influxdata/docs.influxdata.com#2466]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.7/query_language/data_download/

Documentation says "every 6 seconds" but I believe it should read "every 6 minutes"

**Comment by timhallinflux** [comment]
@noramullen1 -- can you please review?

**Comment by noramullen1** [comment]
Thanks @dgm816 -- we've updated the units. Closing this issue.
