### ISSUE TITLE
No introduction on "Introducing Influx OSS" page

### ISSUE THREAD

**Issue by RIKnight** [influxdata/docs.influxdata.com#2467]
I want to know what the difference between "InfluxDB" and "InfluxDB OSS" is.  This page purports to be an introduction to "InfluxDB OSS" but completely fails to mention what OSS means.  Please fix.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/introduction/

###### What products and version are you using?
influxdb

###### Where did you look before opening the issue?
google

**Comment by timhallinflux** [comment]
InfluxDB -- generically is a time series database.
There are multiple editions.  
OSS is the Open Source Software.
Enterprise is the commercial closed source, high availability and horizontal scale-out edition.
Cloud is our managed SaaS offering.
