### ISSUE TITLE
Improve cluster documentation for dynamic environments

### ISSUE THREAD

**Issue by sybrandy** [influxdata/docs.influxdata.com#248]
Hello,

We're using InfluxDB for stats collection and we're trying to upgrade to 0.10.0 as well as set up a cluster.  We're running it in under Marathon/Mesos inside a Docker container.  I did manage to get it clustered, however by restarting the cluster in Marathon, which brings up 3 additional nodes, waits for them to be healthy, then stops the old nodes (simplistic), InfluxDB still thinks there are six nodes and tries to connect to them.

So, is there a way to remove nodes from a cluster?  Is there a timeout that can be set so that if a node is unresponsive InfluxDB can automatically drop it from the cluster and heal?  Or, is this one of the "rough edges" that the documentation alluded to?

**Comment by beckettsean** [comment]
With clustering moving out of the open source product, the open source docs on clustering will not receive substantial investment.

**Comment by sybrandy** [comment]
Do you have any more information regarding clustering?  We want to move towards using it with 0.10, but if it's being dropped from the open source version, we'll have to find an alternative.

**Comment by rossmcdonald** [comment]
@sybrandy Please the blog post [here](https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/) for more information.
