### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [influxdata/docs.influxdata.com#2480]
"**Tp** enable HTTPS, set the value to" should be "**To** enable HTTPS, set the value to"

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/administration/config

###### What products and version are you using?
v1.7

###### Where did you look before opening the issue?
N/A

**Comment by pierwill** [comment]
Thanks for this!
