### ISSUE TITLE
Update Telegraf influxdb_listener plugin description to indicate only for InfluxDB 1.x

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs.influxdata.com#2496]
Update Telegraf influxdb_listener plugin description to indicate only supports InfluxDB 1.x.  No plugin yet for v2 support

**Comment by kelseiv** [comment]
Thank you for calling this to our attention, @sjwang90! We've added a note to indicate this plugin supports 1.x only. 

In the spirit of this request, we're looking at ways to implement a filter in the docs to identify InfluxDB version support.
