### ISSUE TITLE
Add warning about writing fields and tags with same name

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2498]
We need to call out that adding fields and tags with the same name will result in duplicate tags and the inability to select the tag.

Example from the community:
https://community.influxdata.com/t/why-is-my-tag-get-duplicated-suddenly-and-i-cant-select-using-the-tag/11678

We're waiting on possible solutions from @influxdata/support, but right now, it appears the only solution is to drop the affected shards.

###### URL for relevant page?
I'm not sure where best to land this. Maybe in the line protocol and client library docs. We may need to do an audit of Telegraf plugins to identify which ones this problem could occur with (input plugins where users structure the data like `csv` or `file`).

**Comment by gunnaraasen** [comment]
Check out the [`::tag` and `::field` syntax](https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#select-specific-tags-and-fields-from-a-single-measurement-and-provide-their-identifier-type) in InfluxQL.

Also, there's [this troubleshooting section](https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#identifier-names) about tags and fields with the same name.

**Comment by gunnaraasen** [comment]
I agree we should make warnings about this more visible and put a note on the line protocol page.

**Comment by kelseiv** [comment]
Thank you all! Content's merged.
