### ISSUE TITLE
Collectd link is dead

### ISSUE THREAD

**Issue by dimisjim** [influxdata/docs.influxdata.com#2502]
Github collectd readme link is dead:

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/administration/ports/

###### What products and version are you using?
1.7
###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.7/administration/ports/

**Comment by pierwill** [comment]
Thanks for this! 👍
