### ISSUE TITLE
Change test commands for $(lsb_release -cs) on installation process on debian

### ISSUE THREAD

**Issue by pablo-qb** [influxdata/docs.influxdata.com#2509]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/introduction/installation/
###### What products and version are you using?
InfluxDB 1.7.9
###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.7/introduction/installation/

Hello, wouldn't it be easier replacing the following snippet:
`wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
test $VERSION_ID = "7" && echo "deb https://repos.influxdata.com/debian wheezy stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "8" && echo "deb https://repos.influxdata.com/debian jessie stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
test $VERSION_ID = "9" && echo "deb https://repos.influxdata.com/debian stretch stable" | sudo tee /etc/apt/sources.list.d/influxdb.list`

By this one:
`wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/influxdb.list`
?
Regards,
Pablo.

**Comment by pierwill** [comment]
Thanks for this! We'll look into your suggestion for a more concise command—

**Comment by pierwill** [comment]
A quick copy-and-paste run of this command in a debian environment failed. We're certainly open to a more concise command or two, though -- and using `lsb_release` seems like the right approach.

**Comment by pablo-qb** [comment]
Nice! Me, as sysadmin never had problem using $(lsb_release -cs) to get distro codename on debian. But I'm sure there're so many ways to do this. Even I've done the InfluxDB installation with the snippet i showed above.
Right now, someone that uses debian 10 will remain without its repository.
Kindly regards, Pablo.
