### ISSUE TITLE
Usage of the HTTP-API

### ISSUE THREAD

**Issue by philippde04** [influxdata/docs.influxdata.com#2515]
Hey, 
is it possible to use the HTTP-Api, without using curl?

**Comment by sanderson** [comment]
@philippde04, yes, you can use any HTTP client that sends HTTP requests and returns HTTP responses. `curl` and `wget` are the most commonly used command line tools, but you can also use language-specific [client libraries](https://docs.influxdata.com/influxdb/v1.7/tools/api_client_libraries/) to integrate with the InfluxDB API.

**Comment by philippde04** [comment]
Hey, thanks for your Answer.
I have one more Question. Is there a easy way to convert a QueryResult to a normal Javastructure like for every Column a Array?
________________________________
Von: Scott Anderson <notifications@github.com>
Gesendet: Dienstag, 19. November 2019 17:07
An: influxdata/docs.influxdata.com <docs.influxdata.com@noreply.github.com>
Cc: philippde04 <philipp.deuchert@hotmail.de>; Mention <mention@noreply.github.com>
Betreff: Re: [influxdata/docs.influxdata.com] Usage of the HTTP-API (#2515)


@philippde04<https://github.com/philippde04>, yes, you can use any HTTP client that sends HTTP requests and returns HTTP responses. curl and wget are the most commonly used command line tools, but you can also use language-specific client libraries<https://docs.influxdata.com/influxdb/v1.7/tools/api_client_libraries/> to integrate with the InfluxDB API.

**Comment by sanderson** [comment]
There may be, I'm not sure. InfluxDB returns results in JSON, so it shouldn't be too hard to convert to the format you need, but it would have to be done client-side.
