### ISSUE TITLE
Incorrect path on https://docs.influxdata.com/influxdb/v1.7/about_the_project/

### ISSUE THREAD

**Issue by ptdecker** [influxdata/docs.influxdata.com#2518]
The link under "contributing to Influx" references https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md which is an invalid link.  I could not locate the correct asset.  

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/about_the_project/

###### What products and version are you using?
n/a

###### Where did you look before opening the issue?
currently open issues

**Comment by pierwill** [comment]
Thanks for this!
