### ISSUE TITLE
Issue with installation instructions at the very end

### ISSUE THREAD

**Issue by Andytmlr80** [influxdata/docs.influxdata.com#2521]
At the very bottom of the installation instructions is states:

_For InfluxDB 1.7.6 or later, you must give owner permissions to the init.sh file. To do this, run the following script in your influxdb directory:_

It sounds like there should be a script to run, but below that is a screenshot of what look like the output of a diff command.  How should we proceed?

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/introduction/installation/

###### What products and version are you using?
Influx 1.7.8

###### Where did you look before opening the issue?
docs.influxdata.com and google

**Comment by sanderson** [comment]
Thanks @Andytmlr80. This does appear to be diff output. I believe the script should be:

```
 if [ ! -f "$STDOUT" ]; then
    mkdir -p $(dirname $STDOUT)
    chown $USER:$GROUP $(dirname $STDOUT)
 fi
 
 if [ ! -f "$STDERR" ]; then
    mkdir -p $(dirname $STDERR)
    chown $USER:$GROUP $(dirname $STDERR)
 fi
 
 # Override init script variables with DEFAULT values
```

@kelseiv Do you remember where the original script came from here?

**Comment by kelseiv** [comment]
Thank you, @sanderson and @Andytmlr80. The original script came from an internal documentation assistance request ([DAR#12](https://github.com/influxdata/DAR/issues/12)) in our private DAR repo. @jvaldez-influx, who submitted the original DAR confirms the updated script looks accurate.
