### ISSUE TITLE
Update ECS Telegraf Plugin info to "Amazon ECS"

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs.influxdata.com#2527]
Update ECS plugin title to "Amazon ECS" and all description information

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.12/plugins/plugin-list/#ecs

###### What products and version are you using?
v1 Docs

**Comment by kelseiv** [comment]
Thank you, @sjwang90! Updated.
