### ISSUE TITLE
Broken Flux Example

### ISSUE THREAD

**Issue by dp1140a** [influxdata/docs.influxdata.com#2556]
The example query which you have below does not work

###### URL for relevant page?
https://docs.influxdata.com/flux/v0.50/stdlib/experimental/prometheus/scrape/#sidebar

###### What products and version are you using?
Influx DB 1.7.9

**Comment by sanderson** [comment]
Whoops, you're right. This was some copy-pasta from 2.0. Just need to update the port used in the example.
