### ISSUE TITLE
influxdb client can't write data using "n" as time Precision

### ISSUE THREAD

**Issue by bmeboy** [influxdata/docs.influxdata.com#256]
influxdb 0.10.0:
1. I download influxdb 0.10.0's standalone Binary from https://influxdata.com/downloads/#influxdb
    and then unzip it 
2. when i went to the dir influxdb-0.10.0-1/usr/bin, use ./influxd  to start influxdb

influxdb client 0.10.0:
i just use the ExampleClient_Write in dir github.com\influxdata\influxdb\client，it worked ok， can write data to influxdb。
however, when is changed Precision's value at  the 100th line from 's' to 'n' or 'ns', it did not work well, in other words, it can not write data to influxdb.

**Comment by beckettsean** [comment]
What exactly do you mean by "it can not write data to influxdb"? Please give actual error output. Paste in the entire command line session showing use of the client and all return values, if possible.

**Comment by gunnaraasen** [comment]
@bmeboy Bug reports for the InfluxDB client should be opened up on the [InfluxDB repo](https://github.com/influxdata/influxdb/issues/new). This doesn't appear to be a documentation issue.
