### ISSUE TITLE
Provide more in-depth detail for 'EXPLAIN ANALYZE'

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2564]
Right now, there is no explanation of the output of `EXPLAIN ANALYZE`. We should document how to intrerpret the output of this statement. The following gist provided by @stuartcarnie provides great information:

https://gist.github.com/stuartcarnie/c68054cdf2a139491d2b43e98ffdbd5b

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/query_language/spec#explain-analyze

**Note:** Whatever changes we make should be backported to 1.5 and 1.6.

**Comment by kelseiv** [comment]
addressed by PRs: #2570 #2574
