### ISSUE TITLE
MD5 sum for influxdb_0.10.1-1_amd64.deb is incorrect

### ISSUE THREAD

**Issue by asacamano** [influxdata/docs.influxdata.com#258]
Good morning.

According to https://influxdata.com/downloads/, it should be 36c19001f1c26c0262e132130fdf30a0
However, I just downloaded it and computed it to be 

MD5 (influxdb_0.10.1-1_amd64.deb) = 59a0dad806b057f7910a59208a2b385f

Tanks!

**Comment by gunnaraasen** [comment]
Thanks @asacamano for pointing that out. I've updated the page with the correct hashes.

**Comment by asacamano** [comment]
Thanks for the quick turn around!

-Andrew
