### ISSUE TITLE
Add support for Kapacitor custom CA certificates 

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs.influxdata.com#2592]
Include the following new Kapacitor [auth] configuration settings in examples and procedures:

- meta-ca = "/etc/kapacitor/ca.pem"
- meta-cert = "/etc/kapacitor/cert.pem"
- meta-key = "/etc/kapacitor/key.pem"

The following pages need to be updated (other pages may be affected):

- Managing security in Kapacitor Enterprise: https://docs.influxdata.com/enterprise_kapacitor/v1.5/administration/security/

- Enabling authentication in Kapacitor:
https://docs.influxdata.com/enterprise_kapacitor/v1.5/administration/auth/#enabling-authentication-in-kapacitor

- Configuring Kapacitor Enterprise:
https://docs.influxdata.com/enterprise_kapacitor/v1.5/administration/#configuring-kapacitor-enterprise-enterprise-kapacitor-v1-5-administration-configuration

**Comment by pierwill** [comment]
Looks like this was fixed in https://github.com/influxdata/docs.influxdata.com/pull/2593; closing.
