### ISSUE TITLE
describe why clusters must be at least three machines, not two

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#26]
Originally: https://github.com/influxdb/influxdb.com/issues/537

@pauldix I think you are best able to elucidate this. Let's chat and then my team can write it up.

**Comment by pauldix** [comment]
sure, schedule something for next week :)

**Comment by rkuchan** [comment]
Closing in favor of https://github.com/influxdata/docs.influxdata.com/issues/220
