### ISSUE TITLE
Add a note about `default` being a reserved word for create database

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#2606]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/introduction/getting-started/#creating-a-database

see this comment. Looks like trying `create database default` results in an error.  https://github.com/influxdata/influxdb-ruby/issues/237#issuecomment-579871542

**Comment by kelseiv** [comment]
thank you @russorat!
