### ISSUE TITLE
Document HA for Chronograf

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2607]
Chronograf 1.8 will introduce high-availability functionality. We need to document the recommended architecture and how to set it up.

**Comment by glinton** [comment]
Some super basic doumentation:

## Running Chronograf with etcd

### etcd
Get latest etcd release (from github)[https://github.com/etcd-io/etcd/releases/tag/v3.3.18]:

For linux:
```sh
# fetch the binary
curl -L https://github.com/etcd-io/etcd/releases/download/v3.3.18/etcd-v3.3.18-linux-amd64.tar.gz | tar -zxf -

# run the binary
./etcd-v3.3.18*/etcd
```

### chronograf
Start chronograf and use etcd as the storage layer:

```sh
chronograf --etcd-endpoints localhost:2379
```

Other usage:
```
  -e, --etcd-endpoints=                       List of etcd endpoints [$ETCD_HOSTS]
      --etcd-username=                        Username to log into etcd. [$ETCD_USERNAME]
      --etcd-password=                        Password to log into etcd. [$ETCD_PASSWORD]
      --etcd-dial-timeout=                    Total time to wait before timing out while connecting to etcd endpoints. 0 means no timeout.
                                              (default: -1s) [$ETCD_DIAL_TIMEOUT]
      --etcd-request-timeout=                 Total time to wait before timing out the etcd view or update. 0 means no timeout. (default:
                                              -1s) [$ETCD_REQUEST_TIMEOUT]
```

**Comment by pierwill** [comment]
Thanks for this, @glinton! 🙏

**Comment by glinton** [comment]
np. there's also a new route for dead simple (just a 200 header response) lb health checks at `/ping`

**Comment by russorat** [comment]
There is also the ability to migrate from bolt to etcd using the `chronoctl` cmd. 

```
➜  chronograf git:(master) ✗ ./chronoctl migrate -h
Usage:
  chronoctl [OPTIONS] migrate [migrate-OPTIONS]

The migrate command (beta) will copy one db to another

Help Options:
  -h, --help      Show this help message

[migrate command options]
      -f, --from= Full path to boltDB file or etcd (e.g. 'bolt:///path/to/chronograf-v1.db' or 'etcd://user:pass@localhost:2379 (default: chronograf-v1.db)
      -t, --to=   Full path to boltDB file or etcd (e.g. 'bolt:///path/to/chronograf-v1.db' or 'etcd://user:pass@localhost:2379
```

**Comment by pierwill** [comment]
Thanks, @russorat !

**Comment by glinton** [comment]
a little more that the docs team can look over - added a readme to the cmd/chronoctl directory and tried adding some docs about the migrate command. i don't english as good as y'all so feel free to request feedback (pr is closed, but new additions are possible). https://github.com/influxdata/chronograf/pull/5362#issue-370512858

**Comment by glinton** [comment]
Another note about pre-canned dashboards (not sure if that's proper terminology)
>If using `.dashboard` files to pre-populate available dashboards, those files should be updated and the `id` should be converted to a string value.

**Comment by pierwill** [comment]
#2615 merged. Closing this and creating a new issue for documenting the migration tool.
