### ISSUE TITLE
Typo in docs for `delete-topic-handlers` cli command

### ISSUE THREAD

**Issue by paddyohanlon** [influxdata/docs.influxdata.com#2617]
The following:

```kapacitor delete topic-handler [TOPIC_ID] [HANDLER_ID]```

Should be:

```kapacitor delete topic-handlers [TOPIC_ID] [HANDLER_ID]```

`topic-handlers` instead of `topic-handler`.

###### URL for relevant page?

https://docs.influxdata.com/kapacitor/v1.5/working/cli_client/#delete-topic-handlers

###### What products and version are you using?

NA

###### Where did you look before opening the issue?

NA

**Comment by sanderson** [comment]
Thanks @paddyohanlon! We'll get this fixed.
