### ISSUE TITLE
Document Chronograf bolt>etcd migration tool

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs.influxdata.com#2620]
For more information, see:

- https://github.com/influxdata/docs.influxdata.com/issues/2607#issuecomment-582083507
- https://github.com/influxdata/chronograf/pull/5362#issue-370512858
- https://github.com/influxdata/chronograf/issues/5062
- https://github.com/influxdata/docs.influxdata.com/issues/2620#issuecomment-583049494

**Comment by russorat** [comment]
Something important to highlight is that migrating from bolt to etcd will change your source ids which change your urls. 

so urls that were:
`http://localhost:8888/sources/1/status`
would change to 
`http://localhost:8888/sources/373921399246786560/status`

If you are deep linking into chronograf from external sources, those links will need to be updated.
