### ISSUE TITLE
Documentation around Windows not an officially supported platform?

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs.influxdata.com#2621]
Support Engineer reached out that they often get Windows tickets and can't do much with them because we do not fully support Windows since it's considered ["experimental"](https://www.influxdata.com/blog/running-the-tick-stack-on-windows/) for everything besides Telegraf. 

Suggestion was to indicate somewhere on the downloads/docs page that Windows isn't an official supported platform - could suggest to use docker container on Windows. 

Open for discussion or curious if there has been conversation of this in the past.

**Comment by kelseiv** [comment]
Hi @sjwang90, yes this issue has a past. Verified with @timhallinflux @influxdata/docs-team our position remains Windows's experimental, and we'll review docs to be sure we're consistent in messaging and add note on the main docs page.
