### ISSUE TITLE
getting error on prometheus logs 

### ISSUE THREAD

**Issue by roiromanoclick** [influxdata/docs.influxdata.com#2624]
###### Where did you look before opening the issue? every where

 After 1d promethus is increasing the local disk.
 and i can see a lot of logs with error " msg="dropped sample for series that was not explicitly dropped via relabelling"

when i'm restarting the influxdb server, the prometheus back to normal. 
it's happening only after few hours\day

What can be the issue.

Thanks,

**Comment by timhallinflux** [comment]
Issue moved to [influxdata/influxdb #16755](https://github.com/influxdata/influxdb/issues/16755) via [**ZenHub**](https://www.zenhub.com/)

**Comment by timhallinflux** [comment]
This doesn't appear to be a documentation related issue.  

Moving this to the InfluxDB repo.  @roiromanoclick -- can you describe your setup in a bit more detail?  It isn't clear what you are doing, how you have things configured, etc.   We could make some very broad assumptions based on what is described here...but, better to have you outline what the setup is.  Thanks.
