### ISSUE TITLE
Document password restrictions

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs.influxdata.com#2627]
Document the password length and restrictions, for example, special characters.
Review both InfluxDB and Chronograf docs to determine where content updates need to be made.

**Comment by dgnorton** [comment]
I don't see a limit for password length in the InfluxDB code. In practice, on my development laptop using the `influx` CLI, I was able to create users with 32KB passwords. I tested beyond that and ran into problems but I think those were with my terminal and not InfluxDB. I think we should state something to the effect of "max password length is system dependent but 4KB is the suggested limit". Also worth noting is that there is no minimum password length.

Passwords can include any valid UTF-8 character other than newline (`\n`). The `\` and `'` characters are special and must be escaped with `\`. E.g., `\\` and `\'`.

We'll need someone with Chronograf experience to provide details there.
