### ISSUE TITLE
Fill InfluxDB with static data aligned with Telegraf measurements?

### ISSUE THREAD

**Issue by ajohnson-512** [influxdata/docs.influxdata.com#2639]
###### What products and version are you using?
Telegraf 1.13.3

###### Where did you look before opening the issue?
https://github.com/influxdata/telegraf/issues/3279

Due to a legacy calculation, I find myself needing to send a piece of static data along with the collections that Telegraf is sending. I've tried searching every way that I can, but I've been unable to find a solution.

Due to a legacy calculation that occurs when polling our InfluxDB data, I'm in need of a field - "Units" in this case - be filled with 1, but aligned with each polling period from Telegraf. 

Is there a Telegraf or Kapacitor solution here that I'm not seeing that will for this kind of alignment?

**Comment by russorat** [comment]
@ajohnson-512 thank you for opening this issue. I'm not sure I completely understand. You might be able to use the influxql FILL option in your query to do this. https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#group-by-time-intervals-and-fill

This looks more like a question, that would be better asked in either on https://community.influxdata.com or the community Slack space: https://influxdata.com/slack. I'm going to close this for now and look forward to seeing you in those spaces.
