### ISSUE TITLE
"Getting started" page mentions `select * from cpu_load_short`, but that measurement doesn't exist

### ISSUE THREAD

**Issue by jlebar** [influxdata/docs.influxdata.com#2652]
The "Getting Started" page suggests running `SELECT * FROM "cpu_load_short"` as an example of...something.  I'm not sure what it's illustrating, because that measurement wasn't defined in the tutorial.  (Is it `select *`?  But that's demo'ed right above...)

#### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.7/introduction/getting-started/

###### What products and version are you using?

n/a, I'm just reading docs at the moment

###### Where did you look before opening the issue?

Poked around other documentation pages, but didn't see anything obvious.

**Comment by russorat** [comment]
@jlebar great catch. thank you! we will take a look.
