### ISSUE TITLE
Missing "," in custom-aggregate-function examples

### ISSUE THREAD

**Issue by wetterfrosch** [influxdata/docs.influxdata.com#2656]
###### URL for relevant page?
https://docs.influxdata.com/flux/v0.50/stdlib/custom-functions/custom-aggregate/

###### What products and version are you using?

InfluxDB 1.7.9.

###### Where did you look before opening the issue?
https://docs.influxdata.com/flux/v0.50/stdlib/custom-functions/custom-aggregate/#create-a-custom-average-function

When trying the example "Create a custom average function" through Grafana's flux-"interface" I recognized an "Internal Server Error" and that it is resolved when one adds a comma between the two `reduce()` parameters `identity: {...}` and `fn: (...) => ...`.

Seems like it is missing in some other examples there, too.

But anyhow: Thanks for the great software :)

**Comment by russorat** [comment]
@wetterfrosch thanks for the issue! we will take a look.

**Comment by sanderson** [comment]
Thanks you for point this out @wetterfrosch. I've updated these guides and the changes will be live later today.
