### ISSUE TITLE
repos.influxdata.com only resolved to SFO cloudfront

### ISSUE THREAD

**Issue by yangzhaofeng** [influxdata/docs.influxdata.com#2657]
I know here is not the best place to report this problem, but I find nowhere else for it.

I tested the domain on several machines in several places with several dns servers, but all resolved to Amazon Cloudfront in San Francisco. Some of my machines have slow connection to Amazon SFO datacenter. Would you mind changing the resolve to the user's nearest Cloudfront server?

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.13/introduction/installation/
###### What products and version are you using?
telegraf 1.13.3-1

**Comment by sanderson** [comment]
@yangzhaofeng Just to clarify,  `https://docs.influxdata.com/telegraf/v1.13/introduction/installation/` is the domain you're testing?

**Comment by russorat** [comment]
@yangzhaofeng i'm checking to see who can help update the cloudfront config for repos.influxdata.com.  stay tuned.

**Comment by yangzhaofeng** [comment]
@sanderson No. I was testing repos.influxdata.com

That url is where I find this domain.
