### ISSUE TITLE
kapacitor: update docs for int function

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#2664]
from https://github.com/influxdata/kapacitor/issues/2294

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/tick/expr/#int

I don't think the `int` function supports durations.

**Comment by timhallinflux** [comment]
this is unclear as to whether we intended this to work...and hence the docs are correct and we have a defect. This will need some investigation to determine how best to resolve.  We could remove this from the docs temporarily...but, I'd prefer to discuss with engineering to determine which way this should land.

**Comment by russorat** [comment]
There's more detail in https://github.com/influxdata/kapacitor/issues/2294

**Comment by kelseiv** [comment]
Thank you, @russorat! @timhallinflux discussed with Nathaniel and confirmed issue is a defect to address in product.
