### ISSUE TITLE
Document v2.0 /write API compatibility

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2667]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/tools/api/

###### What products and version are you using?
InfluxDB 1.8

InfluxDB 1.8 introduces compatibility for the 2.0 write API.  This enables users who are on 1.8 to adopt new v2.0 client libraries now.  With the arrival of 1.8, users should be able to leverage both Flux (as their primary query language) and the 2.0 write API making their transition to 2.0 OSS, Cloud and Enterprise seamless.

However, we should document the best practices to ensure that this is as easy as possible for our users.  

Tracking issue:
https://github.com/influxdata/influxdb/issues/16898

PR:
https://github.com/influxdata/influxdb/pull/16908/

**Comment by pierwill** [comment]
Closed via #2701.

**Comment by pierwill** [comment]
#2733
