### ISSUE TITLE
What's max index log file size?

### ISSUE THREAD

**Issue by TheLudlows** [influxdata/docs.influxdata.com#2668]
The description in the document is 5M https://docs.influxdata.com/influxdb/v1.7/concepts/tsi-details/
config file ` max-index-log-file-size = "1m"` and in config.go is  `DefaultMaxIndexLogFileSize = 1 * 1024 * 1024`. So what'smax index log file size?

**Comment by russorat** [comment]
@TheLudlows thanks for opening this. Looks like the default was changed in this PR: https://github.com/influxdata/influxdb/commit/92d38414f2eb51753e53797ff2294f022eaa4305 and we need to update the docs.
