### ISSUE TITLE
Update replication factor guidance

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2675]
Our documentation for InfluxDB Enterprise needs to be fixed re: replication factor. The current guidance is wrong. 

Replication factor must be equal to or evenly divisible into the number of data nodes within the cluster. 

When replication factor = number of data nodes, the data is fully replicated to all data nodes and each node can respond to queries without communicating with other data nodes. However, more typical configurations are replication factor of 2 with data nodes 4,6,8 which allows for more series to be stored within the database. 

We can go into more detail here about how the data is distributed across the nodes and how a the query engine gathers the data residing across multiple nodes...

We should highlight the downside of not following this guidance (i.e. RF=2 and Data node = 3...as an example).  The cluster can become unbalanced in terms of how the data is distributed across the cluster.  This can lead to poor performance depending on the queries being issued. 

###### URL for relevant page?
- https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#create-retention-policies-with-create-retention-policy
- https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#replication-factor
- _Likely others_

**Comment by kelseiv** [comment]
update #2685
