### ISSUE TITLE
LineProtocol - tag value cannot end with "\" even if escaped

### ISSUE THREAD

**Issue by Trovalo** [influxdata/docs.influxdata.com#2676]
A tag value cannot end with a backslash, even if escaped. You will get the following error:
> 2020-03-02T15:09:50Z E! [outputs.influxdb] When writing to [http://127.0.0.1:8086]: received error unable to parse {LineProtocolStringhere} : invalid tag format

But a tag value can end with spaces and other special chars.

So for example:
``` 
#Those are invalid rows
test, Tag1=HelloThere\ value1=1
test, Tag1=HelloThere\\ value1=1

#This is valid
test, Tag1=HelloThere\  value1=1
``` 

I've not found any reference to this limitation in the docs (but I remember reading something like it somewhere in a comment)

###### URL for relevant page?
- https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/
- https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/
###### What products and version are you using?
- Telegraf v1.13.2
- InfluxDB v1.7.8
###### Where did you look before opening the issue?
- https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/
- https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/

**Comment by pierwill** [comment]
Thanks for this @Trovalo! We're looking into it—

**Comment by theodiefenthal** [comment]
Why was that notice in docs removed in InfluxDB 1.8 docs? still having this issue with InfluxDB 1.8.4.
