### ISSUE TITLE
In Section 4 have the cert and key name for meta nodes different than influxdb example

### ISSUE THREAD

**Issue by mprintz** [influxdata/docs.influxdata.com#2681]
###### URL for relevant page?
https://docs.influxdata.com/enterprise_influxdb/v1.7/guides/https_setup/

###### What products and version are you using?
Influx 1.7.10 Ent

###### Where did you look before opening the issue?
Talked to Support to confirm. Andrew Spencer

We should call the crt and key different names for the InfluxDB side and Meta side. Right now both are labled as influxdb.crt and influxdb.key. So customers are trying to use the same cert for each. I would recommend influxdb-meta.crt and influxdb-meta.key on the meta section picture.

![image](https://user-images.githubusercontent.com/9125473/75717266-69513180-5c96-11ea-8f8e-ff0800450623.png)

**Comment by pierwill** [comment]
Does this mean users need to create two cert/key pairs in step 1?

**Comment by mprintz** [comment]
Hey @pierwill . Sorry for my delay. Yes. For Enterprise users we should have them create two cert/key pairs in step 1. OSS we can leave as all using the same key. Some enterprise customers will have a different cert/key pair per server even, but showing at least two here would be helpful.
