### ISSUE TITLE
Wrong user/permissions on private cert

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2694]
Users have run into an issue where we direct them to set the wrong permissions on the certificate private key files, so the `influxdb` user cannot read them.

```
sudo chmod 600 /etc/ssl/<private-key-file>
```

~Needs to be updated to:~

[ deleted ]

**Update:** We need to make it clear that the user running InfluxDB must own the certificate files. In general, InfluxDB shouldn't be run by `root`, so certificate files should not be owned by the `root` user.

###### URL for relevant page?
- https://docs.influxdata.com/enterprise_influxdb/v1.7/guides/https_setup/#setup-https-in-an-influxdb-enterprise-cluster
- https://docs.influxdata.com/influxdb/v1.7/administration/https_setup/#configure-influxdb-to-use-tls
- _There may be others_

**Comment by sanderson** [comment]
`600` is the correct permissions. `644` is not secure enough for a private key. The issue is that the private key must be owned by the user running InfluxDB.

**Comment by sanderson** [comment]
The enterprise docs say that the `root` user should own the certificate files. This needs to be updated. Whatever user is running InfluxDB needs to own the files. We generally do not recommend running InfluxDB as `root`.

**Comment by pierwill** [comment]
Closed in #2740.
