### ISSUE TITLE
Kapacitor Enterprise with Chronograf

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2706]
We need to provide some overarching concepts and instructions for using Kapacitor Enterprise with Chronograf. I think we can just add a section to [Using Kapacitor in Chronograf](https://docs.influxdata.com/kapacitor/v1.5/working/kapa-and-chrono/) for Kapacitor Enterprise that references the concepts outlined in [Alerts in a Kapacitor Enterprise cluster](https://docs.influxdata.com/enterprise_kapacitor/v1.5/cluster-management/cluster-alerts).

###### URL for relevant page?
- https://docs.influxdata.com/kapacitor/v1.5/working/kapa-and-chrono/
- https://docs.influxdata.com/enterprise_kapacitor/v1.5/cluster-management/cluster-alerts

**Comment by timhallinflux** [comment]
you must treat them as independent entities.  Chronograf doesn't know about the Kapacitor Enterprise nodes being clustered
