### ISSUE TITLE
Enterprise cluster command setup

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs.influxdata.com#2707]
From Will La:

Hello Docs team, I just completed a call with a prospect and during their experience trying to set up a cluster, they ran into a lot of issues with the commands for setting up the cluster.

- https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/config-data-nodes

- https://docs.influxdata.com/enterprise_influxdb/v1.7/administration/configuration/#sidebar

When I asked about specific issues, he stated “a command tries to default/resolve to localhost could be problematic” and a few other commands would throw errors. Also, they stated that it would be helpful to have a team member run through the setup process and give the document any needed updates. Please note that they have been very happy with the documentation in general. This was feedback given during a call. I told them I would send it along internally.

**Comment by kelseiv** [comment]
Thank you, @noramullen1 

Unable to address this piece in docs:
_Command tries to default/resolve to localhost could be problematic... and a few other commands would throw errors._ 

However, @mdevy-influxdata has run through the setup docs with @psteinbachs and updated setup info in this [PR](https://github.com/influxdata/docs.influxdata.com/pull/2732), which helps clarify DNS info for both meta and data node setup.

Note, updates were made to "setup" procedures. Docs the customer referred to were actually reference docs for the config file, so not ideal to follow for setup.
