### ISSUE TITLE
Telegraf MySQL plugin description - Add MariaDB & Percona support

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs.influxdata.com#2709]
Update MySQL Input Plugin description:

`The MySQL input plugin gathers the statistics data from MySQL servers.  Input plugin supports MariaDB and Percona. `

###### URL for relevant page?
https://v2.docs.influxdata.com/v2.0/reference/telegraf-plugins/
https://docs.influxdata.com/telegraf/v1.13/plugins/plugin-list/

<br/>
Refer to:  https://github.com/influxdata/telegraf/issues/7099

**Comment by kelseiv** [comment]
thank you, @sjwang90!
