### ISSUE TITLE
Can't locate signature files for Telegraf

### ISSUE THREAD

**Issue by bart-gisspecialisten** [influxdata/docs.influxdata.com#2715]
The installation instructions for Telegraf on Debian list steps to verify the installation:
https://docs.influxdata.com/telegraf/v1.13/introduction/installation/

However, the link for the verification file does'nt work. I tried updating the link to 1.13.4 and some other versions, but none of them works.

**Comment by sanderson** [comment]
Thanks for reporting @bart-gisspecialisten. We'll look into this an make any necessary updates.

**Comment by pierwill** [comment]
Hi @bart-gisspecialisten. Looks like there is a typo in the URL on that page. We'll get that fixed!

In the meantime, you should be able to find detached signature files by adding `.asc` to the telegraf download URLs on this page: https://portal.influxdata.com/downloads/.

For instance, if you're looking to verify the 64-bit Linux binary, the signature lives at https://dl.influxdata.com/telegraf/releases/telegraf-1.13.4_linux_amd64.tar.gz.asc.

Let us know if you have further questions!
