### ISSUE TITLE
influxdb 1.6.4 tls ciphers only contains TLS_RSA*

### ISSUE THREAD

**Issue by wskyp** [influxdata/docs.influxdata.com#2720]
my influxdb1.6.4,built in golang 1.10.3
 this wiki (https://docs.influxdata.com/influxdb/v1.6/administration/config/#transport-layer-security-tls-settings-tls)
it list some ciphers such as:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 and so on.
but I found my influxdb only surport TLSV1.0-1.2, and it's ciphers conly contains TLS_RSA_*, not found TLS_ECDHE*.

**Comment by russorat** [comment]
@wskyp thanks for the issue. Please upgrade to the latest Influx 1.7.10 to see if that resolves your issue.

**Comment by russorat** [comment]
@wskyp oops sorry about that. We will take a look.

**Comment by pierwill** [comment]
Hi @wskyp! Can you update to 1.7.10 and let us know if this solves your issue?

**Comment by pierwill** [comment]
Also note that the available ciphers depend on the version of Go used to build influxdb. See https://golang.org/pkg/crypto/tls/#pkg-constants.
