### ISSUE TITLE
Documentation Updates for GCP Marketplace

### ISSUE THREAD

**Issue by emilykurze** [influxdata/docs.influxdata.com#2743]
@gunnaraasen Here is a roundup of the docs items we discussed early this week. Let me know if there is anything else I can provide.

**Getting started on the Google Cloud Platform Marketplace** https://docs.influxdata.com/enterprise_influxdb/v1.7/other_installation/google_marketplace/
 -  Needs references to InfluxDB Enterprise bring-your-own-license (BYOL) solution and links removed as this version is being deprecated. 
 - General content and screenshots updates to reflect current InfluxDB Enterprise listing needed

**InfluxDB Enterprise 1.7 documentation**
https://docs.influxdata.com/enterprise_influxdb/v1.7/
 - Add menu item under Install and Deploy side menu for Deploy on Google to mirror "Deploy in ASW" menu item?

**Get started with InfluxDB Cloud 2.0** 
https://v2.docs.influxdata.com/v2.0/cloud/get-started/
 - Add instructions for GCP to mirror AWS instructions?

**Comment by kelseiv** [comment]
Thank you, @emilykurze and @gunnaraasen! Updates merged:
https://github.com/influxdata/docs.influxdata.com/pull/2754
