### ISSUE TITLE
check the API libraries to make sure they are up to date with 0.10

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#275]
We list a number of libraries listed but I'm not sure they are all compatible with the latest in 0.10. Let's verify, and pull down any that aren't.

#### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.10/clients/api/

**Comment by rkuchan** [comment]
Possibly not functional with 0.10:
[Haskell](https://github.com/maoe/influxdb-haskell)

**Comment by rkuchan** [comment]
Closing in favor of https://github.com/influxdata/docs.influxdata.com/issues/276#issuecomment-193973109
