### ISSUE TITLE
Document transitioning from 1.x to 2.0 client libraries

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2752]
InfluxDB 1.8 ships with a 2.0 compatible `/write` endpoint that lets users use the new 2.0 client libraries to write to InfluxDB 1.8 and Cloud 1. We need to write a guide or guides for transitioning from the 1.x to the 2.0 client libraries.

##### Notes & questions
- These may need to be language/client specific
- What are the gotchas of the new clients?
- Are there new concepts that 1.x users need to understand to successfully use the new clients.

**Comment by kelseiv** [comment]
close per https://github.com/influxdata/docs.influxdata.com/pull/2757
