### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AP-Engineering** [influxdata/docs.influxdata.com#2755]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.7/introduction/getting-started/
###### ISSUE is typo ######
I noticed the following is written under heading 'Creating a database':
Execute influx to start the CLI and automatically connect to the local InfluxDB instance (assuming you have already started the server with **service influxdb start** or by running influxd directly).

I believe that it should state **service influxd start**

**Comment by pierwill** [comment]
Hello, @AP-Engineering – when starting InfluxDB as a system service, `service influxdb start` is indeed the correct command.

**Comment by AP-Engineering** [comment]
That’s odd, influxdb doesn’t work for me but influxd does

**Comment by pierwill** [comment]
The exact command can vary based on operating system and architecture. Have a look at the installation documentation for your OS: https://docs.influxdata.com/influxdb/v1.7/introduction/installation/#installing-influxdb-oss.

**Comment by AP-Engineering** [comment]
Thanks - I will look into that

 

Cheers,

 

Cliff Laver, P.Eng

250-201-3720
