### ISSUE TITLE
Flux for v1 docs is vague about how to supply security creds when authentication is required

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2759]
###### URL for relevant page?
https://docs.influxdata.com/flux/v0.50/guides/executing-queries#influxdb-api

###### Issue:
There isn't any information about supplying the appropriate security credentials when attempting to access the Flux endpoint.  This needs to be fleshed out.  Chronograf is ok...as the username:password for the connection is re-used for Flux queries in the same way that it is used for InfluxQL...

But the CLI and CURL need to be described, if security is enabled.

**Comment by sanderson** [comment]
Resolved by #2760. Will rollout out with InfluxDB 1.8 / Flux 0.65
