### ISSUE TITLE
Need some qualification or certification for libraries

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#276]
Should communicate whether the library is actively maintained and with what versions it is compatible. Might even need breakdown of API features implemented. Perhaps a chart?
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.10/clients/api/
###### What products and version are you using?

all

**Comment by beckettsean** [comment]
@toddboom @rkuchan let's discuss when Todd is back.

**Comment by beckettsean** [comment]
Pull the API page out of the versioned docs and put it on a page that's outside the versioned docs structure, possibly on the wordpress site.

**Comment by gunnaraasen** [comment]
We can add non-versioned pages for client libraries to the docs. It could be at `docs.influxdata.com/influxdb/clients/`.

I think it would be a confusing experience if the client library doc lived on the wordpress site.

**Comment by beckettsean** [comment]
+1 for that URL, I like it.

**Comment by beckettsean** [comment]
Meanwhile, I'd love to get the last modification date onto that page:

The idea would be that when browsing https://docs.influxdata.com/influxdb/v0.10/clients/api/ the content would look like this:

InfluxDB Erlang UDP by palkan, last updated Nov 5, 2015

InfluxDB Go by InfluxDB, last updated 26 days ago

**Comment by beckettsean** [comment]
@mjdesa we had talked about this being a small project for you, lemme know if you need clarification or resources.

**Comment by mjdesa** [comment]
I believe @jackzampolin had started working on something for this.

**Comment by jackzampolin** [comment]
Here is the tool: https://github.com/influxdata/support-tools/tree/master/api_freshness

I believe I have it deployed somewhere too. Hit me up @mjdesa
