### ISSUE TITLE
Add Flux info to Downsampling and retention doc

### ISSUE THREAD

**Issue by noramullen1** [influxdata/docs.influxdata.com#2777]
https://docs.influxdata.com/influxdb/v1.8/guides/downsample_and_retain/

This page only mentions InfluxQL queries. We need to also add Flux. 

https://v2.docs.influxdata.com/v2.0/process-data/common-tasks/downsample-data/

**Comment by noramullen1** [comment]
CQs can only be implemented using InfluxQL -- we should point out that this is replace by tasks in 2.0 and pointer

**Comment by kelseiv** [comment]
clarified 2.0 only #2790
