### ISSUE TITLE
Telegraf Agent input as http_listener_v2 and output as azure application insight

### ISSUE THREAD

**Issue by arunsingh2009** [influxdata/docs.influxdata.com#2780]
I have configured my telegraf agent with input plugin as http_listener_v2 to collect the custom metrics and send them to azure application insight as output plugin.

I am not able to receive the metrics at application insight collected via http_listener . I have fallowed below link to configure  http_listener_v2 there is no error found into log. 

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_listener_v2

**Comment by russorat** [comment]
@arunsingh2009 thanks! This might not be the right place for this. This is probably best for https://community.influxdata.com or Slack https://influxdata.com/slack. When you ask there, please make sure to post your telegraf configuration as well.

**Comment by arunsingh2009** [comment]
Thanks you comment. But got the resolution for same. string values are not allowed into into custom metrics.
