### ISSUE TITLE
Pull Installing Telegraf as a Windows Service into the official docs

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2784]
Source materials to be reviewed and leveraged for this.

###### URL for relevant page?
https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md
and
https://www.influxdata.com/blog/using-telegraf-on-windows/

This needs its own separate install guide. It is the best practice for running telegraf on Windows machines.

**Comment by pierwill** [comment]
Closed by #2783 and #2918.
