### ISSUE TITLE
add upgrade instructions to the installation page

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#28]
Originally: https://github.com/influxdb/influxdb.com/issues/533

let's be explicit about any upgrade needs, for example:

when upgrading from 0.9.4 and prior, file paths have changed
when upgrading from 0.9.2 and prior, integers now require i
etc.

@rossmcdonald

**Comment by rkuchan** [comment]
@beckettsean, need release checklist.

**Comment by beckettsean** [comment]
@rkuchan https://influxdb.atlassian.net/wiki/display/SUP/New+Release+Checklist

Needs love.

**Comment by beckettsean** [comment]
Include page with links to new docs.

**Comment by beckettsean** [comment]
Also include cluster upgrade steps
