### ISSUE TITLE
Document running Telegraf using remote configuration files

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2802]
When starting Telegraf, you can use a URL with the `-config` flag to pull a configuration file from a remote endpoint and start Telegraf using that configuration.

#### Related links
- https://docs.influxdata.com/telegraf/v1.14/administration/configuration/
- https://github.com/influxdata/telegraf#run-telegraf-with-all-plugins-defined-in-config-file

**Comment by kelseiv** [comment]
thanks, @sanderson, @rbetts! addressed in #2802
