### ISSUE TITLE
Missing Content and Broken links

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/docs.influxdata.com#2817]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.6/tools/shell/#import-data-from-a-file-with-import
doesn't look like it migrated across to 1.7 and 1.8

https://docs.influxdata.com/influxdb/v1.7/guides/writing_data/
is missing in the 1.8 release.

https://docs.influxdata.com/influxdb/v1.7/guides
broken header.

**Comment by kelseiv** [comment]
fix broken header https://github.com/influxdata/docs.influxdata.com/commit/35c256fff99ec5a608fed79872acfb81d3740795

**Comment by kelseiv** [comment]
Thanks @timhallinflux, resolved
