### ISSUE TITLE
I have reviewed all the commands BUT where is the UPDATE or equivalent command to replace wrong values <0 reported by my sensors ??

### ISSUE THREAD

**Issue by Sofianov** [influxdata/docs.influxdata.com#2822]

**Comment by sanderson** [comment]
@Sofianov Some information for some context: https://docs.influxdata.com/influxdb/v1.8/concepts/crosswalk/#influxdb-is-not-crud

To update a field value, write a new point with the same measurement, tag set, timestamp, and field.

**Comment by Sofianov** [comment]
Well it is very hard to correct these values. 
![image](https://user-images.githubusercontent.com/36585529/81429480-ebfedd00-916e-11ea-818f-deca3e2cc892.png)

it reminds me when I was working on equity and futures markets... with bad prices...

Well I guess that without a serious admin GUI I have to consider MySQL just because you can correct a value. I said a value and existing value.

Serious limitation here.

Thanks for any help

**Comment by sanderson** [comment]
You can update them by overwriting them. You need to query the points you want to updated, convert the points into line protocol, update the values so they are correct, then insert them back into the database.

**Comment by Sofianov** [comment]
Thanks Sanderson

I have tried this quick method :
I can of course view my bad values here 
> select * from GardenT where value<0
but this is NOT working for some reason!
> select * from GardenT where ("value<0" *-1) - 100

any idea by chance?

Thanks

**Comment by sanderson** [comment]
@Sofianov Are you using Grafana or Chronograf?

**Comment by Sofianov** [comment]
Hi Scot

Grafana

**Comment by sanderson** [comment]
I don't know Grafana very well, but I know Chronograf has a feature that lets you view raw data. I'm curios to see what the actual values are in the erred data points.

**Comment by Sofianov** [comment]
Well instead of reading 36  the sensor went on error and trow me -136 ....
thats whay I have tried to select the <0 and +100 and * -1
simple but for some reason didn't work on InfluxDB

Sofian
