### ISSUE TITLE
[RFC] Remove InfluxDB Enterprise Quickstart installation

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2824]
The SE team recommends against using the Quickstart installation method for InfluxDB Enterprise because it is prone to failure. It appears it's main purpose was to facilitate quick product evaluations, but we now have other less error-prone options for that including provider marketplace integrations.

I propose that we remove references to and instructions for the InfluxDB Enterprise Quickstart installation.

#### Related URLs
- https://docs.influxdata.com/enterprise_influxdb/v1.8/introduction/installation_guidelines/
- https://docs.influxdata.com/enterprise_influxdb/v1.8/install-and-deploy/quickstart_installation/
- https://docs.influxdata.com/enterprise_influxdb/v1.8/install-and-deploy/production_installation/

**Comment by dp1140a** [comment]
agree.  Its duplicate, unnecessary and causes confusion.  I tell customers and prospects to kindly ignore it and use the production install method.

**Comment by samhld** [comment]
Thirded
