### ISSUE TITLE
Not all Telegraf plugins listed

### ISSUE THREAD

**Issue by alsargent** [influxdata/docs.influxdata.com#2841]
###### URL for relevant page?

https://docs.influxdata.com/telegraf/v1.14/plugins/plugin-list/

###### What products and version are you using?

Telegraf 1.14

###### Details

This spreadsheet lists all telegraf plugins on the telegraf github repo: 

https://docs.google.com/spreadsheets/d/1EEDYX1oRIdYNmGrsfKi1W_KD5eYxbNoi-SJxoHqcpWI/edit#gid=1269851980

As you can see, it lists 263 plugins. But, the doc page https://docs.influxdata.com/telegraf/v1.14/plugins/plugin-list/ only lists 238 plugins. (238 = 181+34+6+17.)

![image](https://user-images.githubusercontent.com/20701/82270375-77bff880-9929-11ea-9b0a-f3bba56c9314.png)

So, can you please go through this spreadsheet and add whatever plugins are missing from the doc page? 

Often times, our deals come about because Telegraf supports a particular type of technology. Not having all plugins listed on this page means that our revenue is being impacted. Thanks!

**Comment by kelseiv** [comment]
Thank you @alsargent, your plugin list includes:
-  **parsers** and **serializers** - Folks can add these to a plugin to input a data format (parser) or output a data format (serializer), and they're included in our docs as [Telegraf data formats](https://docs.influxdata.com/telegraf/v1.14/data_formats/).
- **webhooks** in [repo](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/webhooks), which are documented in the [Webhooks plugin](https://docs.influxdata.com/telegraf/v1.14/plugins/plugin-list/#webhooks)

I've updated the docs to clarify parsers and serializers in a couple places. Also added 3 missing data formats in #2852. 

The rest of the plugins in your list are documented. A couple updates/notes for your spreadsheet:
- `filepath` will be released in 1.15 (end of June)
- `dns_query_time` >> `dns_query`
- `httpjson` deprecated as of v1.5.3. Use the HTTP plugin.
- InfluxDB Line Protocol >> distinguish input and output
