### ISSUE TITLE
flush_interval description out of date?

### ISSUE THREAD

**Issue by bencarlton** [influxdata/docs.influxdata.com#2849]
From the Telegraf docs:

> flush_interval: Default data flushing interval for all outputs. **You should not set this below interval**. Maximum flush_interval will be flush_interval + flush_jitter

Is the bolded statement still true? I do not see that same comment repeated at https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md. Telegraf seems to function normally in my limited tests when `flush_interval` is set below `interval`.

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.14/administration/configuration/#agent-configuration

###### What products and version are you using?
Telegraf v1.14.2

###### Where did you look before opening the issue?
The documentation

**Comment by pierwill** [comment]
Any thoughts on this, @danielnelson?

**Comment by danielnelson** [comment]
Documentation in the Telegraf repo is correct, there isn't any reason why this can't be set this lower than the interval.  There are a few instances where you may want to set Telegraf up like this, primarily if you are using service inputs which don't use the interval.

The best way to think about this option is that it is the maximum amount of time it can take before metrics are (at least attempted to be) written.

**Comment by bencarlton** [comment]
@danielnelson, thank you for the clarification.

I can close this out if you would like, or we can keep it open until the documentation is updated.

**Comment by kelseiv** [comment]
Thank you @bencarlton, @pierwill, @danielnelson - removed statement
