### ISSUE TITLE
TSM Indexing

### ISSUE THREAD

**Issue by r1ckbrown** [influxdata/docs.influxdata.com#2851]
https://docs.influxdata.com/influxdb/v1.8/administration/upgrading/#switch-between-tsm-and-tsi-indexes

TSM Indexing as an alternative to TSI1 indexing isn't a thing. This was correct in the v1.7 docs, but incorrect in previous versions. In v1.8 docs, it's wrong again.

**Comment by sanderson** [comment]
Thanks @r1ckbrown. This is definitely a docs regression. We'll be sure to apply the changes to the InfluxDB 1.8 documentation.

**Comment by kelseiv** [comment]
thanks @r1ckbrown @sanderson - updated this content
