### ISSUE TITLE
[Strange formation] duration_literal

### ISSUE THREAD

**Issue by HsienChing** [influxdata/docs.influxdata.com#2853]
###### URL for relevant page?
[https://docs.influxdata.com/influxdb/v1.8/query_language/explore-data/#the-time-zone-clause](https://docs.influxdata.com/influxdb/v1.8/query_language/explore-data/#the-time-zone-clause)
###### What products and version are you using?
influxDB 1.8.0
###### Where did you look before opening the issue?

The description in the "duration_lteral" is strange while I following the instruction.
It seems that "microseconds" corresponds to "ms", "milliseconds" corresponds to "s", ..., "days" corresponds to "w", and "week" corresponds to "nothing".
![Image 6](https://user-images.githubusercontent.com/64768830/82731617-d5de4880-9d3a-11ea-8fa5-4ab2b14f4e1e.jpg)

Although I've understood the correspondences, this minor issue should be pointed out and fixed for the next reader/beginner.

**Comment by kelseiv** [comment]
thank you, @HsienChing- fixed
