### ISSUE TITLE
run: open server: listen: listen tcp 127.0.0.1:8088: bind: address already in use

### ISSUE THREAD

**Issue by gurv23** [influxdata/docs.influxdata.com#2859]
influxd

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2020-05-31T11:27:56.424425Z	info	InfluxDB starting	{"log_id": "0N6ce_20000", "version": "1.6.4", "branch": "unknown", "commit": "unknown"}
2020-05-31T11:27:56.424453Z	info	Go runtime	{"log_id": "0N6ce_20000", "version": "go1.10.4", "maxprocs": 2}
run: open server: listen: listen tcp 127.0.0.1:8088: bind: address already in use

**Comment by gurv23** [comment]
when i check port: port is free. please help me.

**Comment by gurv23** [comment]
when check port it shows it is free but when start influxd it shows address already in use

**Comment by kelseiv** [comment]
Hi @gurv23, does this [InfluxData community post](https://community.influxdata.com/t/listen-tcp-127-0-0-1-bind-address-already-in-use/11816) help? 

To get help on issues like this, please check out our https://community.influxdata.com or Slack https://influxdata.com/slack. 

This repo is best for issues on docs.influxdata.com.

**Comment by gurv23** [comment]
Hi @kelseiv, 
Thanks for writing. I am newbee in linux, github and influxdb. So sorry for this.

Thank you!

**Comment by kelseiv** [comment]
My pleasure, @gurv23—welcome aboard!
