### ISSUE TITLE
Remove "Use a Client Library" Section

### ISSUE THREAD

**Issue by russorat** [influxdata/docs.influxdata.com#2872]
https://docs.influxdata.com/influxdb/v1.8/tools/api_client_libraries/

https://docs.influxdata.com/influxdb/v1.8/tools/api_client_libraries/#use-a-client-library
this section is specific to python and doesn't really make sense on this page.

**Comment by kelseiv** [comment]
Discussed with @russorat and updated docs to clarify that steps are specific to the Python client library. We're leaving the Python library instructions there for now and will create a new issue to add the rest of the client library instructions to v1.
