### ISSUE TITLE
Kapacitor Documentation is incomplete

### ISSUE THREAD

**Issue by brewneaux** [influxdata/docs.influxdata.com#288]
I'm attempting to get started using Kapacitor, but having issue after issue. 

First, it appears that the 'real world' stream example just doesn't work
`invalid task: error calling func "percentile" on obj *kapacitor.influxqlMapReducers: reflect: Call using int64 as type float64`

From there, I attempted to find the documentation for percentile, and found nothing. 

Further, the sigma function says it uses a 'running mean', but the concept of running mean never defined.

These issues, and the general state of the documentation, are making it very hard to get using Kapacitor.

**Comment by beckettsean** [comment]
@nathanielc does this suggest any improvements to the docs?

**Comment by nathanielc** [comment]
@beckettsean There is a typo in the getting started guide for the percentile call. I'll fix that here in a bit before I forget.
