### ISSUE TITLE
There was a error sending test alert to Alerta Token is invalid.

### ISSUE THREAD

**Issue by jdworske** [influxdata/docs.influxdata.com#2881]
Any help much appreciated.  We have having problems with Kapacitor connecting to Alerta.

We are getting "Token is invalid".

URL:
**http://192.168.0.126:8888/sources/18/kapacitors/55/edit**

**kapacitor-1.5.2-1.x86_64**

**Chrongraf v1.7.11**

root@aws-hub-alerta-01:~# alerta version
**alerta 7.2.7
alerta client 7.2.1
requests 2.22.0
click 7.0**
root@aws-hub-alerta-01:~#

###### Where did you look before opening the issue?

I looked all over TICK stack Influxb documentation.

**kapacitor.conf:**

[alerta]
  # Configure Alerta.
  enabled = true
  # The Alerta URL.
  url = "http://aws-hub-alerta-01.mydomain.com/api"
  # Default authentication token.
  #  token = "Bm,......removed Y"
  # Default token prefix
  # If you are on older versions of alerta you may need to change this to "Key"
  token-prefix = "Bearer"
  # Default environment.
  environment = "Production"
  # Default origin.
  origin = "kapacitor"

===============================================================

s=2020-06-19T16:44:00.145-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T16:45:00.083-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T16:46:00.218-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T16:47:00.219-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T16:48:00.154-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T16:50:00.229-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:51:00.249-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:52:00.139-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:53:00.258-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:54:00.162-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:55:00.253-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:56:00.189-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:57:00.215-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:58:00.246-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T16:59:00.196-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Key' is invalid"
ts=2020-06-19T17:00:00.054-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-50dbeefb-9e81-4256-86f3-ed3bcb111077 err="API key parameter 'Bearer' is invalid"
ts=2020-06-19T17:00:00.080-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Bearer' is invalid"
ts=2020-06-19T17:01:00.146-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Bearer' is invalid"
ts=2020-06-19T17:02:00.264-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Bearer' is invalid"
ts=2020-06-19T17:03:00.107-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Bearer' is invalid"
ts=2020-06-19T17:04:00.152-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="API key parameter 'Bearer' is invalid"
ts=2020-06-19T18:30:00.161-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:31:00.241-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:32:00.271-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:33:00.239-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:34:00.135-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:35:00.152-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:36:00.129-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:37:00.150-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:38:00.161-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:39:00.179-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:40:00.049-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-50dbeefb-9e81-4256-86f3-ed3bcb111077 err="Token is invalid"
ts=2020-06-19T18:40:00.051-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:41:00.270-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:42:00.305-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:43:00.247-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:44:00.144-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:45:00.309-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:46:00.160-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:47:00.295-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:48:00.154-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:49:00.196-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:50:00.038-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-50dbeefb-9e81-4256-86f3-ed3bcb111077 err="Token is invalid"
ts=2020-06-19T18:50:00.054-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:51:00.208-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:52:00.127-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:53:00.187-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:54:00.144-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:55:00.160-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:56:00.288-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:57:00.152-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:58:00.232-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T18:59:00.159-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:00:00.172-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-50dbeefb-9e81-4256-86f3-ed3bcb111077 err="Token is invalid"
ts=2020-06-19T19:00:00.239-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:01:00.161-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:02:00.170-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:03:00.171-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:04:00.171-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:05:00.055-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:06:00.198-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:07:00.193-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:08:00.155-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:09:00.293-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:10:00.069-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-50dbeefb-9e81-4256-86f3-ed3bcb111077 err="Token is invalid"
ts=2020-06-19T19:10:00.087-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:11:00.203-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
ts=2020-06-19T19:12:00.194-07:00 lvl=error msg="failed to send event to Alerta" service=alerta task=chronograf-v1-7f5638e1-7bdb-411e-9724-c8ee93a665b4 err="Token is invalid"
[root@aws-hub-kapacitor-01 kapacitor]#

**Comment by kelseiv** [comment]
Hi @jdworske, I believe this is an [open issue](https://github.com/influxdata/kapacitor/issues/1165). Please try updating configuration to:
token-prefix ="Key"

**Comment by kelseiv** [comment]
Thanks for reporting @jdworske, we've updated the docs accordingly.
