### ISSUE TITLE
convert fields data type

### ISSUE THREAD

**Issue by xiaosuiyue** [influxdata/docs.influxdata.com#2882]
The influx version that i used is 1.8
The field I stored was string, but now I want to change the field type to float, and I get an error.
How do I convert previously stored data types

**Comment by sanderson** [comment]
@xiaosuiyue There currently isn't a way to change the type of a field after it's written to InfluxDB. You have a few options:

1. Create a new field for the new data type.
2. Delete and rewrite the points that have the wrong data type.

Here are some related links:
- https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#can-i-change-a-field-s-data-type
- https://github.com/influxdata/influxdb/issues/2651
