### ISSUE TITLE
Problem adding influxdata repository to ubuntu apt sources

### ISSUE THREAD

**Issue by mwThinks** [influxdata/docs.influxdata.com#2883]
I followed the instructions on [https://docs.influxdata.com/telegraf/v1.14/introduction/installation/](https://docs.influxdata.com/telegraf/v1.14/introduction/installation/) to install telegraf on Ubuntu. 

My Ubuntu version:
```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

When running 
```bash
$ echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```
as per the instructions I get a  bad substitution error and 
```bash
echo ${DISTRIB_ID}
```
gives `Ubuntu` with a upper-case U.

Only when adding the repo with 
```bash
$  echo "deb https://repos.influxdata.com/ubuntu focal stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```
by "hand" did 
```bash
$ sudo apt-get update && sudo apt-get install telegraf
```
run without errors. 

I see how this is a minor thing but as a not so experienced Linux user this took me a bit to solve.

Possibly related issue (where I have been told to open a new one) https://github.com/influxdata/telegraf/issues/7422

**Comment by pierwill** [comment]
Thanks, @mwThinks! We'll look into this—

**Comment by pierwill** [comment]
I was able to run the [provided Ubuntu installation instructions](https://docs.influxdata.com/telegraf/v1.14/introduction/installation/) successfully on Ubuntu 18.04. We definitely want to make sure as many Ubuntu versions as possible are supported, though!

@mwThinks: could you confirm the output of

```
$ echo ${DISTRIB_ID,,}
```

on your machine? The commas use [Bash parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) to lowercase the distribution name.

**Comment by mwThinks** [comment]
Sorry for the late response. So I tested it again. All of the commands below just give me an empty line
```bash
$ echo ${DISTRIB_ID,,}
$ echo ${DISTRIB_ID}
$ echo ${DISTRIB_CODENAME}
```

Some additional information, I am using a server version of Ubuntu 20.04 [https://ubuntu.com/download/server](https://ubuntu.com/download/server).

**Comment by danielnelson** [comment]
The current install instructions for Ubuntu use the `/etc/lsb-release`, which has somewhat fallen out of favor in recent years. I suggest we update the instruction to make use of `/etc/os-release`.  Here are the `/etc/os-release` contents for our other supported Ubuntu versions:

```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by pierwill** [comment]
Closing this. Let us know if problems persist...
