### ISSUE TITLE
Question: Meaning of "✨" symbol (U+2728) in documentation?

### ISSUE THREAD

**Issue by Paraphraser** [influxdata/docs.influxdata.com#2884]
Possibly a **seriously** dumb question but...

In many places in the documentation, I see the "✨" symbol ("sparkles" U+2728).

An example is in the page on [authentication](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#2-by-default-authentication-is-disabled-in-the-configuration-file). I have searched high and low but have not been able to find a definition of this symbol:

<img width="784" alt="Screen Shot 2020-06-23 at 16 58 41" src="https://user-images.githubusercontent.com/34226495/85370959-e15ba400-b572-11ea-9c1c-3ba2c4437451.png">

Is it simply a highlight or call-out indicator? For example, the preamble is talking about "auth-enabled" and that's the line with the ✨ in the configuration file snippet.

Alternatively, does it have some other meaning like "deprecated feature - going away soon"?

**Comment by sanderson** [comment]
Thank you @Paraphraser. It's not a dumb question at all. Here, the ✨ symbol is just meant to highlight the `auth-enabled` configuration setting. We've been going through and removing most of these from the code snippets in the documentation, but looks like we missed this one.

There are examples in the documentation that illustrate writing strings with special characters to InfluxDB, but this obviously is not one of them 😄 .
