### ISSUE TITLE
Definition of Series

### ISSUE THREAD

**Issue by BryceShakeAir** [influxdata/docs.influxdata.com#2885]
Hi
In the key concepts page , a series is defined as a collection of points that share a measurement, tag set, and field key.
In this blog https://www.influxdata.com/blog/influxdb-internals-101-part-one/#:~:text=A%20series%20is%20simply%20a,members%20of%20the%20same%20series%20.
I have come to know that a series is defined by measurement , tag set and retention policy and not field key. Also this makes more sense

**Comment by kelseiv** [comment]
Thank you, @BryceShakeAir - while there are some undercover technical details, the overall idea is indeed that a series is a group of points that share a measurement, tag set, and field key. We've updated the blog above to align with the docs.
