### ISSUE TITLE
backward WHERE queries

### ISSUE THREAD

**Issue by Gnoudini** [influxdata/docs.influxdata.com#2888]
###### Where did you look before opening the issue: At the bottom of the above page where it says "Please, open an issue."

The examples are supposed to limit "results to series in the shard group that contain a timestamp in the last minute" or to return "all series in shard groups that contain a timestamp in the last 28 days", but, respectively, the clauses `WHERE time < now() - 1m` and `WHERE time < now() - 28d` are backwards. They could be changed to `WHERE now() - 1m < time` and `WHERE now() - 28d < time`.

**Comment by kelseiv** [comment]
Thank you @Gnoudini! Fixed.
