### ISSUE TITLE
Performance testing gap for influxdb

### ISSUE THREAD

**Issue by clarkzheng** [influxdata/docs.influxdata.com#289]
###### Performance testing

Hi guys, 

We are newer to influxdb, it looks like very cool. 
Before taking it as core of our monitoring solution, we want to make a performance testing on it.

We built one m4.2xlarge EC2 instance as single node influxdb which is beyond the high performance hardware guideline from official wiki https://docs.influxdata.com/influxdb/v0.10/guides/hardware_sizing/

Because we do not know how telegraf communicate with influxdb, we establish a performance testing plan by triggering as much REST call of writing operation as influxdb could hold to influxdb.
We generate 40 ec2 instances with one shell script in cron job which will trigger 1000 REST api request for writing data into influxdb per 1 minter.
The simple script is coded as below:

> for i in {1..1000}
do
curl -i -XPOST http://10.145.53.178:8086/write?db=testdb --data-binary "testdata,host=$IP value=$i"
done

After several round, the influxdb can only handle the workload for first 20 minutes, then it would crash.
The writes query will cost 6 ms to finish, while the time cost will be increased as the time going.
It will take at almost 10+s before it crash. 

On official wiki, influxdb is claimed to have the capability to hold the 300000 concurrent write operation at most, which looks have a huge gap from our testing result.

We want to get some clarification:

1. Does the 300000 concurrent write operation mean the REST call operation?
2. If yes, why it has the gap from our result, or how could we optimise our testing plan to get the closest result?
3. If no, how could we mock up the way telegraf communicated with influxdb with least ec2 resource? I.G. It's crazy for us to create 300000 EC2 instance If we only deploy/run one telegraf on one EC2 instance. Of course maybe we could deploy multi telegraf on one EC2 VM, but it looks like it still need require too much resource.

Any kindly comments are appreciated.
Thank you

**Comment by beckettsean** [comment]
You have opened a bug with the documentation repo, but this is neither a bug nor a feature request. For general questions, please write to the mailing list: influxdb@googlegroups.com.

InfluxDB can easily ingest hundreds of thousands of points per second, but that is not the same as handling hundreds of thousands of HTTP connections per second. You must batch the points to reduce the TCP overhead. https://docs.influxdata.com/influxdb/v0.10/guides/writing_data/#writing-multiple-points

Also, please note, InfluxDB is not REST-ful.
