### ISSUE TITLE
Kapacitor : Aggregate handlers does not accept interval

### ISSUE THREAD

**Issue by bsabsp** [influxdata/docs.influxdata.com#2891]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/event_handlers/aggregate/#aggr-cpu-alerts-yaml

###### What products and version are you using?
Kapacitor OSS 1.5.4 (git: HEAD 1f648f85772efe222a3853fe1a0d9ef88854a8c1)

###### Where did you look before opening the issue?
On the documentation 

When trying to reproduce the "aggregate" documentation, i'm getting this error :

```
failed to create handler: failed to decode options into *alert.AggregateHandlerConfig: 1 error(s) decoding:
* 'interval' expected type 'time.Duration', got unconvertible type 'string'
```

I tried with :
- exactly the same YML file
- changing _interval: 10m_ to _interval: '10m'_

**Comment by kelseiv** [comment]
Thank you, @bsabsp,
We have an [open issue](https://github.com/influxdata/kapacitor/issues/1783). Please change 10m to 600000000000. Updated documentation to say the interval must be specified in nanoseconds.
