### ISSUE TITLE
Incorrect documentation regarding `influx_inspect deletetsm` command 

### ISSUE THREAD

**Issue by couloum** [influxdata/docs.influxdata.com#2908]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.8/tools/influx_inspect/

###### What products and version are you using?

InfluxDB v1.8.0

###### Description of the issue

Hi,

The documentation of command `influx_inspect deletetsm` (https://docs.influxdata.com/influxdb/v1.8/tools/influx_inspect/) gives exemples with `-sanitize` option, while it should be `-measurement MEASUREMENT`

This:
```
Examples

Delete a measurement from a single shard

./influx_inspect deletetsm -sanitize /influxdb/data/location/autogen/1384/*.tsm

Delete a measurement from all shards in the database

./influx_inspect deletetsm -sanitize /influxdb/data/location/autogen/*/*.tsm
```

Should be replaced by this:
```
Examples

Delete measurement `h2o_feet` from a single shard

./influx_inspect deletetsm -measurement h2o_feet /influxdb/data/location/autogen/1384/*.tsm

Delete measurement `h2o_feet` from all shards in the database

./influx_inspect deletetsm -measurement h2o_feet /influxdb/data/location/autogen/*/*.tsm
```

Also, the behavior of -sanitize option is still unclear to me after reading the doc.

**Comment by kelseiv** [comment]
Thank you, @couloum. We've corrected the example and updated docs to clarify `deletetsm` requires either the `-measurement` or `-sanitize` flag. 
Non-printable Unicode characters in tag or field keys may cause shard corruption. `-sanitize` removes non-printable Unicode characters in a raw TSM file (from specified shards).
