### ISSUE TITLE
1.15 changelog - fix processor names

### ISSUE THREAD

**Issue by sjwang90** [influxdata/docs.influxdata.com#2928]
In 1.15 changelog, need to update: 
Reverse DNS Processor Plugin(`execd`) to (`reverse_dns`)
Starlark Processor Plugin(`execd`) to (`starlark`)

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.15/about_the_project/release-notes-changelog/

**Comment by noramullen1** [comment]
Fixed!
