### ISSUE TITLE
Documentation does not discuss how to format multi-line strings in line protocol.

### ISSUE THREAD

**Issue by sjlongland** [influxdata/docs.influxdata.com#2930]
I'm trying to insert multi-line string data via the line protocol.  The documentation doesn't cover how to do it.  I took a guess and came up with this.

```
Str,fqname=graphql_WC3057.equip2.strPoint1,id=d6fb7b9a-a952-47cb-ae00-b4a3a209e97e value="multi\nline\nstring" 1451772480000000000
```

(Note, original version of this bug had an error, my text editor had "helpfully" broken the exceptionally long line for me and I didn't see the unintentional line break.)

It'd be worth documenting escape sequences like `\n` (and others like `\t`, etc if supported) in case people need them.

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/

###### What products and version are you using?

```
InfluxDB v1.5.3 (git: 1.5 89e084a80fb1e0bf5e7d38038e3367f821fdf3d7)
```

###### Where did you look before opening the issue?

* Documentation
* Issues for this project
* Issues for `influxdb` project itself

**Comment by sanderson** [comment]
@sjlongland The following note is at the top of the doc you referenced:

> **Note** Line protocol does not support the newline character `\n` in tag values or field values.
