### ISSUE TITLE
Clicking a help topic on the left pane causes the page to reload and my scroll point to be reset

### ISSUE THREAD

**Issue by 8none1** [influxdata/docs.influxdata.com#2931]
As I drill down in to the help topics on the left I typically get further and further down the page.  When I find a topic which sounds like it might be what I'm looking for I click on it.  The whole page seems to reload, both left and right panes, and the scroll point on the left pane resets back to the top of the list.

This is frustrating as I can't be certain where I'd got to in the topic list on the left.

I'd much prefer it if the left list stayed where it was and only the right pane reloaded to show the new content.

**Comment by 8none1** [comment]
https://www.youtube.com/watch?v=Xi8EFluEuwk&feature=youtu.be

**Comment by sanderson** [comment]
@8none1 I'm in the process of porting all the 1.x docs to the v2 theme. The UX (particularly in this case) is much better with the v2 docs. It'll still be a few weeks before the work is complete and we make the switch, but I'm going to go ahead and mark this as closed.
