### ISSUE TITLE
[DOCS] Wrong RFC Reference

### ISSUE THREAD

**Issue by jessegeens** [influxdata/docs.influxdata.com#2932]
###### URL for relevant page?
https://docs.influxdata.com/flux/v0.65/language/lexical-elements#date-and-time-literals

The docs reference RFC3639 (Considerations on the use of a Service Identifier in Packet Headers) as the timestamp specification used in flux. However, RFC3639 does not specify any timestamp. I believe the relevant RFC is RFC3339: Date and Time on the Internet.

**Comment by pierwill** [comment]
Thanks for this, @jessegeens!
