### ISSUE TITLE
Example flux query shows 'AND' in the filter clause. Should be lowercase 'and'.

### ISSUE THREAD

**Issue by jpwijbenga** [influxdata/docs.influxdata.com#2946]
Tried to use flux, but error message was too cryptic ('expected an operator between two expressions', even when typing the example. Just trying I found the uppercase AND does not work.

###### URL for relevant page?
https://docs.influxdata.com/flux/v0.65/introduction/getting-started/

Specifically the image above the header `Key concepts`.

###### What products and version are you using?
Influx 1.8
###### Where did you look before opening the issue?
Docs, Github

**Comment by pierwill** [comment]
Thanks for this, @jpwijbenga!
