### ISSUE TITLE
Build archived state for v1 docs

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs.influxdata.com#2956]
This repository will soon be archived and a static snapshot of the documentation will be hosted at a new domain.

- [x] Add a persistent banner about these docs being archived and where they can see the newer docs.
- [x] Delete all content that is still relevant and available on docs.influxdata.com
    - [x] InfluxDB v1.3+
    - [x] Telegraf v1.9+
    - [x] Chronograf v1.6+
    - [x] Kapacitor v1.4+
    - [x] InfluxDB Enterprise v1.5+
    - [x] Platform
- [x] Remove Algolia search functionality
- [ ] Remove sitemap
- [x] Update latest warning block to use `latest` path and be version agnostic.

**Comment by kelseiv** [comment]
@sanderson left sitemap in so search engines can still find it.
