### ISSUE TITLE
Add checksum details to docs

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#296]
###### URL for relevant page?
Installation pages and possibly the [downloads page](https://influxdata.com/downloads/).

See: https://github.com/kyzh/docs.influxdata.com/commit/91a8cfadb283de10ef720685e0f8a1aa72dbd9bf#diff-a1d5f3ae423b181848d95500e9cd2a42R53

Props to @kyzh for thinking of this.

**Comment by kyzh** [comment]
thanks :)

**Comment by beckettsean** [comment]
This is on the downloads page now.
