### ISSUE TITLE
Duplicate section of InfluxDB Enterprise v1.8.2 release notes

### ISSUE THREAD

**Issue by tianshengye** [influxdata/docs.influxdata.com#2965]
On the section of v1.8.2 [2020-08-24] -> Features -> Hinted handoff improvements (
https://docs.influxdata.com/enterprise_influxdb/v1.8/about-the-project/release-notes-changelog/#hinted-handoff-improvements), 
following paragraph is duplciated:
> Update the hinted handoff queue to ensure that various entries to segment files occur atomically. Prior to this change, entries were written to disk in three separate writes (len, data, offset). If the process stopped in the middle of any of those writes, the hinted handoff segment file was left in an invalid state.

See attached screenshot.
![InfluxDBEnterpriseV1 8 2ReleaseNotesDuplicateParagraph](https://user-images.githubusercontent.com/5965475/91677680-0291cf80-eb76-11ea-9dca-deb9c31b9de8.png)

**Comment by kelseiv** [comment]
Thank you, @tianshengye - removed
