### ISSUE TITLE
[new page] how to interpret SHOW STATS

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#30]
Originally: https://github.com/influxdb/influxdb.com/issues/531

**Comment by beckettsean** [comment]
https://groups.google.com/d/msgid/influxdb/43392f1d-4bba-4655-b79a-796cdd8a6a98%40googlegroups.com has good information on the "runtime" numbers and what they mean,

**Comment by stevebang** [comment]
SHOW STATS page added to monitoring section and all metrics available documented in the _internal measurements page http://docs.influxdata.com/platform/monitoring/tools/measurements-internal/.
Google group page no longer available.
