### ISSUE TITLE
Document environment variables

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs.influxdata.com#304]
Environment variables do not seem to be documented anywhere. They should probably be discussed in the [configuration doc](https://docs.influxdata.com/influxdb/v0.10/administration/config/).

Follow up issue for https://github.com/influxdata/influxdb/issues/5964.

**Comment by gunnaraasen** [comment]
The code that generates the environment variables is [here](https://github.com/influxdata/influxdb/blob/master/cmd/influxd/run/config.go#L181).

**Comment by beckettsean** [comment]
Also document https://github.com/influxdata/influxdb/pull/6444
