### ISSUE TITLE
[new page] non-clustered solutions for HA

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#305]
Lift from https://influxdata.com/high-availability/ but give more context and concrete examples.

**Comment by rkuchan** [comment]
https://influxdata.com/high-availability/

**Comment by beckettsean** [comment]
Really breaks down to two things for 0.12:
- dual-write for redundancy (nginx, app shim, InfluxDB Relay are all just flavors of dual-write)
- horizontally shard data for throughput
- combine both for redundancy and throughput, and also great sadness. Maybe just pay for clustering at that point?

**Comment by beckettsean** [comment]
adequately documented on main site.
