### ISSUE TITLE
accessing chrongraf outside localhost

### ISSUE THREAD

**Issue by shred444** [influxdata/docs.influxdata.com#308]
i've forwarded port 10000 on my local router but i'm unable to access chronograf outside the network.  Any idea what's going on here?

**Comment by beckettsean** [comment]
@shred444 this is not a documentation question or bug. Please contact the mailing list at influxdb@googlegroups.com for assistance. Many users are successfully proxying Chronograf, so I would investigate your network setup as the most likely issue.
