### ISSUE TITLE
New system stats for the monitoring page

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#318]
New performance and health metrics available from `_internal`
https://github.com/influxdata/influxdb/pull/5758
https://github.com/influxdata/influxdb/pull/5810
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.10/troubleshooting/system_monitoring/

**Comment by beckettsean** [comment]
related to https://github.com/influxdata/docs.influxdata.com/issues/227, should tackle both together.

**Comment by beckettsean** [comment]
@dgnorton @e-dard @timraymond @jwilder who can we talk to about the `_internal` stats and what they mean? Units, etc.

@toddboom @pauldix possible hackday project post 1.0 release.

**Comment by beckettsean** [comment]
@dgnorton @e-dard @timraymond @jwilder, asking again, who understands `_internal` output? We don't want to talk now, but we want to know who to talk with in ~2 weeks to get the page started.

**Comment by timraymond** [comment]
@beckettsean I haven't worked with `_internal` to speak of at all. The others would have a better handle on what you need.

**Comment by dstreppa** [comment]
It should be very useful to have some docs about _internal

+1

**Comment by stevebang** [comment]
Not documenting _internal metrics.  Intended for internal / support use.

**Comment by Hamelina** [comment]
Hello, are there any news about the doc for _internal ? it could be really useful.

**Comment by sanderson** [comment]
Resolved in https://github.com/influxdata/docs.influxdata.com/pull/1908
