### ISSUE TITLE
document breaking changes in 0.11 releases

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#320]
Chronograf 0.10 and earlier is not compatible with InfluxDB 0.11+, due to changes in the SHOW SERIES and SHOW TAG VALUES return format

Grafana 2.6 query builder likely will not work with InfluxDB 0.11. Existing queries/dashboards will be fine.

DISTINCT return format changed

**Comment by rkuchan** [comment]
Fixed by: https://github.com/influxdata/docs.influxdata.com/pull/328
