### ISSUE TITLE
Fix scroll to anchor issues

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/docs.influxdata.com#322]
###### URL for relevant page?

http://docs.influxdata.com/kapacitor/v0.10/tick/window_node/#alert
###### Where did you look before opening the issue?

See https://github.com/influxdata/docs.influxdata.com/pull/309#issuecomment-196482358

Details on the anchors not working right:
1.  Click on this link http://docs.influxdata.com/kapacitor/v0.10/tick/window_node/#alert
   It should take you to the Window Node docs at the section about the Alert chaining method.
2. Click on the link in `Returns: AlertNode` 
3. Click back.

Now you are at the top of the WindowNode docs and not at the Alert method section. This makes it really easy to get lost in the docs.

**Comment by beckettsean** [comment]
@mark-rushakoff @willpiers @wfro @121watts any ideas?

@toddboom @pauldix possible hackday project post 1.0 release.
