### ISSUE TITLE
Update distinct() documentation for new output format

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#324]
The output for `distinct()` isn't correct anymore with the query engine refactor. The new query engine doesn't have the capability of returning an array so, instead, it returns a separate entry for each unique point in the interval.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.10/query_language/functions/#distinct

###### What products and version are you using?
InfluxDB 0.11rc1

**Comment by rkuchan** [comment]
Thank you, @jsternberg! Closing in favor of: https://github.com/influxdata/docs.influxdata.com/issues/155
