### ISSUE TITLE
comparisions of other tools out in the marketplace

### ISSUE THREAD

**Issue by kangman** [influxdata/docs.influxdata.com#327]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.10/introduction/getting_started/
###### What products and version are you using?
more of a documentation issue
###### Where did you look before opening the issue?
look at aforementioned URL

I am a fan of the way hashicorp gets out front of the question on the value proposition their tools bring to the table.  In particular I think they do a great job of giving a high level overview of what's already out there and why they've created their product amongst the other options.  For example. 

https://www.vaultproject.io/intro/vs/index.html
https://www.terraform.io/intro/vs/index.html
https://www.consul.io/intro/vs/index.html

I would really like to see something similar in your docs as well that compares and contrasts tools such as the ELK stack, prometheus, bosun, scollector. OpenTSDB etc.

**Comment by beckettsean** [comment]
@toddboom @jginfluxdata I think this is happening on the main site, not in the docs. Can you confirm so we can close?

**Comment by beckettsean** [comment]
White papers on comparisons are coming as of today. They will be on the main site at https://influxdata.com/technical-papers/

**Comment by beckettsean** [comment]
@jginfluxdata @ShubhraKar a few good links to what other companies do for competitor comparisons

**Comment by ShubhraKar** [comment]
@beckettsean thanks for sending along. I like it. In my past OSS company, we put out compare pages like : http://strong-pm.io/compare/ . This should be on the main site

**Comment by gunnaraasen** [comment]
I'll strongly second putting up comparison pages on the main website with a similar style to Hashicorp's comparison pages. Adding a comparison chart would also be nice but it might be harder to do one-to-one feature comparison with other products.
