### ISSUE TITLE
[new page] telegraf configuration

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#330]
The Telegraf config page is very light and doesn't really describe any of the options. It is always nice to link directly into the config docs when responding to questions, but for Telegraf I can't.

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v0.10/introduction/configuration/
###### What products and version are you using?
telegraf 0.10+

@sparrc is the config stable enough to warrant the effort of something like https://docs.influxdata.com/influxdb/v0.10/administration/config/?

**Comment by sparrc** [comment]
I think it could have something like that, but there are actually only two permanent sections in the telegraf config: [tags] and [agent], the rest are all for enabling plugins.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/416
