### ISSUE TITLE
InfluxQL spec incomplete on SELECT FROM clause

### ISSUE THREAD

**Issue by CamJN** [influxdata/docs.influxdata.com#337]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.10/query_language/spec/
###### What products and version are you using?
0.10.3
###### Where did you look before opening the issue?
at the source code for the query parser and at the query language spec page.

From what I can tell the current spec is incomplete, for example it doesn't cover regex literals in the from clause of a select statement. Is there a complete and correct spec somewhere?

**Comment by beckettsean** [comment]
@CamJN the InfluxQL spec in the code repo should be the source of truth: https://github.com/influxdata/influxdb/blob/master/influxql/README.md.

**Comment by beckettsean** [comment]
@benbjohnson or @dgnorton can you suggest the proper syntax to https://docs.influxdata.com/influxdb/v0.12/query_language/spec/#clauses so that it indicates regex is valid in the FROM clause?

**Comment by dgnorton** [comment]
@beckettsean wrong in the README.md also. Made a PR for that. If that passes review, we can make the same change to the docs.
