### ISSUE TITLE
Better documentation around collectd + InfluxDB and Telegraf

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#34]
Originally: https://github.com/influxdb/influxdb.com/issues/501

Please add to the docs:
* How to configure collectd to send data to InfluxDB
* How to configure collectd in the InfluxDB Managed Hosting environment
* Documentation about the native collectd plugin

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdata/docs.influxdata.com/issues/147
