### ISSUE TITLE
parallel construction in the left nav bar across products

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#349]
At a minimum, it seems like we should make the Intro sections congruent across products, possibly replicating "Concepts" and "Guides" across the other products, too:

<img width="349" alt="screen shot 2016-03-24 at 14 26 56" src="https://cloud.githubusercontent.com/assets/6537329/14031936/9ed2598a-f1cc-11e5-9a95-4955ab2cc017.png">
<img width="342" alt="screen shot 2016-03-24 at 14 27 03" src="https://cloud.githubusercontent.com/assets/6537329/14031934/9ed026ec-f1cc-11e5-928d-15822d83d477.png">
<img width="353" alt="screen shot 2016-03-24 at 14 27 08" src="https://cloud.githubusercontent.com/assets/6537329/14031937/9ed25a98-f1cc-11e5-89ad-5fc70d2527b3.png">
<img width="353" alt="screen shot 2016-03-24 at 14 27 13" src="https://cloud.githubusercontent.com/assets/6537329/14031935/9ed1d2ee-f1cc-11e5-96d8-9e3808e7fa11.png">

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/416 and https://github.com/influxdata/docs.influxdata.com/pull/426
