### ISSUE TITLE
The link in the landing page leads to doc for previous version

### ISSUE THREAD

**Issue by MathieuLorber** [influxdata/docs.influxdata.com#355]
The "get started" link from the landing page (influxdata.com) leads to the documentation for v0.10. I guess you wish to link to lastest release.

###### URL for relevant page?

https://influxdata.com/

###### What products and version are you using?

NA

###### Where did you look before opening the issue?

NA

**Comment by MathieuLorber** [comment]
Same problem in Admin UI

**Comment by rkuchan** [comment]
Thanks @MathieuLorber! Starting with 0.12.1 we use `latest` links so this issue shouldn't come up again.
