### ISSUE TITLE
Code examples can't scroll horizontally on mobile

### ISSUE THREAD

**Issue by setharnold** [influxdata/docs.influxdata.com#357]
None of the code example boxes in the guides can scroll horizontally when viewed via Chrome on Android. Since the interesting parts of queries are often on the right end of the string usually the interesting part is what is missing and impossible to see.

I'd rather see the whole query on multiple lines without any interaction needed but if that's not possible then allowing the query to scroll horizontally would at least make the interesting parts visible.

Thanks

**Comment by gunnaraasen** [comment]
Thanks for the report @setharnold. Side-scrolling on Chrome on Mac OS X works so it appears that this may be a mobile specific issue. I'm partial to scrolling since wrapping code examples will make multi-line examples confusing to read.

cc/ @alexpaxton

**Comment by beckettsean** [comment]
@setharnold what version of Android and Chrome? 

Does it still happen? We just pushed an updated design with new CSS.

**Comment by setharnold** [comment]
I'm sorry to say that the new version is even worse -- many of the code boxes are now completely blank.

For example, https://docs.influxdata.com/influxdb/v0.13/introduction/getting_started/

Of the eleven code boxes, only three actually have text rendered inside:
- CREATE DATABASE mydb
- SHOW DATABASES
- USE mydb

The other eight are blank. If I hold my finger down inside them, I can blindly select the text, and Chrome's bottom-bar shows what text is selected, but it remains invisible when selected. (Which is a neat trick.)

I'm on Android 6.0.1, April 2, 2016 patch level. Chrome is version 50.0.2661.89. It's a Nexus 6P.

Thanks

**Comment by beckettsean** [comment]
thanks @setharnold, I can repro what you are seeing in Chrome Dev Tools.

@alexpaxton @gunnaraasen let me know if I can help, but basically just load the page in Chrome, launch developer tools, emulate the Nexus 6P, and you'll see that most of the code blocks are just blank until you interact with them. Maybe a z-axis issue? The problem is changing any of the CSS properties automatically makes all code blocks on the page appear. Most likely will need to hack local code while running the emulation in Chrome to see what finally fixes it.

**Comment by alexpaxton** [comment]
I was able to reproduce using the Nexus 6P emulator, and out of curiosity tried on on an iPhone 6 and found the same issue. Very bizarre. I will look into this.

**Comment by beckettsean** [comment]
@willpiers @wfro @mark-rushakoff @121watts any ideas?

@toddboom @pauldix possible hackday project post 1.0 release.

**Comment by setharnold** [comment]
Should this fix be live on the website?

The code box after "The following lines are all examples of points that can
be written to InfluxDB" for example is still completely blank on the page
https://docs.influxdata.com/influxdb/v0.13/introduction/getting_started/

Many others are blank, some have content.

I'm on a nexus 6p 6.0.1 July update, chrome version 51.0.2704.81

Thanks

**Comment by beckettsean** [comment]
@setharnold we do not immediately deploy the site, the fix should be live after tonight's automated push.
