### ISSUE TITLE
What is Relay, and where it's the doc?

### ISSUE THREAD

**Issue by hgfischer** [influxdata/docs.influxdata.com#381]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.12/high_availability/relay/

###### What products and version are you using?
InfluxDB 0.12

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v0.12/concepts/011_vs_012/#new-high-availability-tool

**Comment by rkuchan** [comment]
@hgfischer, the README is available [here](https://github.com/influxdata/influxdb-relay).

We've [merged](https://github.com/influxdata/docs.influxdata.com/pull/376) in that README to the documentation this morning; it'll be up on the docs site soon.
