### ISSUE TITLE
Triple-click highlights more than current line

### ISSUE THREAD

**Issue by dmke** [influxdata/docs.influxdata.com#387]
When triple-clicking on a code sample (the `CREATE CONTIUOUS QUERY` code in the screenshot below) I'd expect only the code sample to become highlighted. Instead, the sections above (both "CQ definition" and "InfluxQL for creating a CQ") are selected.

![image](https://cloud.githubusercontent.com/assets/327411/14428068/b0110a0a-fff7-11e5-8bba-a5dc5e5584a3.png)

This makes copying code samples tedious (this is necessary, because I can't see the whole sample and need to paste it in my editor, cf. #357).

The cause for this behavior is found in `typography.css`:

```css
.page--body pre /* and others */ {
  display: inline-block;
  /*...*/
}
```

--Dominik

###### URL for relevant page?
e.g. https://docs.influxdata.com/influxdb/v0.12/query_language/continuous_queries/#the-create-continuous-query-statement

###### What products and version are you using?
Google Chrome 49.0.2623.110 (current stable) on Debian Jessie/8.4

###### Where did you look before opening the issue?
n/a

**Comment by rkuchan** [comment]
Thank you for pointing this out, @dmke. I see what you mean and this will be fixed by https://github.com/influxdata/docs.influxdata.com/pull/352.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/352
