### ISSUE TITLE
Lack of any numbers regarding RAM usage

### ISSUE THREAD

**Issue by piotr-piatkowski** [influxdata/docs.influxdata.com#392]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.12/guides/hardware_sizing/#when-do-i-need-more-ram
###### What products and version are you using?

influxdb 0.12

The chart is missing values on y-axis. Actually, there's no single value regarding to the memory requirements - only generic things like "large amount of RAM". Not very useful.

**Comment by gunnaraasen** [comment]
Thanks @piotr-piatkowski. The section on memory usage can be expanded to explain the other drivers of memory use aside from series cardinality, such as the query engine and write input methods.

We can also look into publishing some discrete numbers for a generic use case. cc/ @mark-rushakoff @mjdesa

**Comment by mjdesa** [comment]
working on it.

**Comment by beckettsean** [comment]
@mark-rushakoff @mjdesa any idea if we might get RAM vs. cardinality numbers post-1.0?

**Comment by mark-rushakoff** [comment]
We did some cursory tests about a month ago, and I'm pretty sure we saw a linear relationship between number of series and memory consumption. 

It will be extremely difficult to get precise numbers on byte overhead per series, but we can likely get an order of magnitude estimate. Those numbers will be dependent on the build and architecture, so post 1.0 seems like a reasonable timeframe.

**Comment by beckettsean** [comment]
@mark-rushakoff I think for our performance numbers we need to establish a baseline machine and dataset. We then can make a few targeted deviations from that to give context on how more RAM or more fields per point changes things, for example.

Not interested in publishing bytes per series, but more trendlines. It's good to know it looks linear, but what if there are 10000 measurements with 10 series each vs. 1 measurement with 100000 series? Those are the comparisons that would allow users to read their own use case into what we publish.

No rush on this, but I think perhaps we should devote an entire testing iteration to performance characterization in the next 2 months.

**Comment by stevebang** [comment]
@mark-rushakoff Was any further testing done related to your comment that "we saw a linear relationship between number of series and memory consumption."?  The docs erroneously state that the increase in RAM needs relative to series cardinality are exponential" and don't discuss the impact of TSI on RAM needs (as mentioned in a related doc issue #1651 ).

**Comment by stevebang** [comment]
For now, I removed statement about exponential increases from the hardware sizing page.

**Comment by kelseiv** [comment]
updated in https://github.com/influxdata/docs.influxdata.com/pull/2673

**Comment by kelseiv** [comment]
Thank you, @piotr-piatkowski! Please check out our recently updated [RAM guidelines](https://docs.influxdata.com/influxdb/v1.7/guides/hardware_sizing#when-do-i-need-more-ram).

**Comment by piotr-piatkowski** [comment]
"In general, more RAM improves query speed. Your RAM requirements are primarily determined by series cardinality. Higher cardinality requires more RAM."

Oh yeah, that's definitely more specific and gives you particular numbers. Not.

**Comment by sanderson** [comment]
@piotr-piatkowski If you follow the links that come after what you quoated (or just scroll up the page), there are base recommendations for both InfluxDB OSS and Enterprise:

[InfluxDB OSS hardware guidelines](https://docs.influxdata.com/influxdb/v1.7/guides/hardware_sizing#influxdb-oss-guidelines)  
[InfluxDB Enterprise hardware guidelines](https://docs.influxdata.com/influxdb/v1.7/guides/hardware_sizing#influxdb-enterprise-cluster-guidelines)

**Comment by kelseiv** [comment]
thank you, @sanderson, @piotr-piatkowski, 

Moved the conceptual statement that @piotr-piatkowski refers to below guidelines @sanderson refers to ......so it's not first thing you read

**Comment by piotr-piatkowski** [comment]
Sorry, you're right - there're numbers, for different series numbers - so that's what I expected initially. Thank you!
