### ISSUE TITLE
Document new Elapsed function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/docs.influxdata.com#393]
A new `elapsed` function was added to InfluxQL. https://github.com/influxdata/influxdb/pull/6423 

It should be added to this page. https://docs.influxdata.com/influxdb/v0.12/query_language/functions/

**Comment by beckettsean** [comment]
@nathanielc can you give a few complete examples of the syntax and the output? It's hard for us non-devs to derive it from just the Go code.

**Comment by nathanielc** [comment]
@beckettsean yes,

The elapsed function works exactly like the derivative function except that it computes differences in time.

Returns elapsed time in number of nanoseconds
```
SELECT elapsed(value) FROM m WHERE time > now() - 1m
```


Returns elapsed time in number of seconds
```
SELECT elapsed(value, 1s) FROM m WHERE time > now() - 1m
```

Can also be used with aggregates

```
SELECT elapsed(last(value), 1s) FROM m WHERE time > now() - 1m GROUP BY time(5s)
```

**Comment by rkuchan** [comment]
I'm a little confused about the use case with aggregates.

The `GROUP BY time` interval determines the timestamps in the results for `max()`, so all of the `elapsed()` results will be the same. The only case where the results won't be the same is if there are no data in some of the `GROUP BY` time intervals, but even then, users won't be able to see the actual elapsed time between `max()`es because the default `GROUP BY time()` intervals determine the timestamps.

Sample data:
```
> select * from mymeas
name: mymeas
------------
time			        source
2016-04-22T18:43:40Z	100
2016-04-22T18:43:41Z	50
2016-04-22T18:43:42Z	200
2016-04-22T18:43:43Z	300
2016-04-22T18:43:45Z	400
2016-04-22T18:43:49Z	500
```
Just `max()` with a `2s` `GROUP BY time()` interval:
```
> select max(source) from mymeas where time >= '2016-04-22T18:43:40Z' and time <= '2016-04-22T18:43:49Z' group by time(2s)
name: mymeas
------------
time			        max
2016-04-22T18:43:40Z	100
2016-04-22T18:43:42Z	300
2016-04-22T18:43:44Z	400
2016-04-22T18:43:46Z
2016-04-22T18:43:48Z	500
```
`elapsed()` with `max()`:
```
> select elapsed(max(source),1s) from mymeas where time >= '2016-04-22T18:43:40Z' and time <= '2016-04-22T18:43:49Z' group by time(2s)
name: mymeas
------------
time			        elapsed
2016-04-22T18:43:42Z	2
2016-04-22T18:43:44Z	2
2016-04-22T18:43:48Z	4
```
I kind of wanted the difference between where the `max()`es happened:
```
time
43:43   3
43:45   2
43:49   4
```

**Comment by nathanielc** [comment]
@rkuchan You are correct, there needs to be away for selectors to preserve their time values. Kapacitor has this via the `usePointTimes` property https://docs.influxdata.com/kapacitor/v0.12/nodes/influx_q_l_node/#usepointtimes

So for Kapacitor you can do what you suggest and get the elapsed times between `max`es.

ATM there isn't a way to specify this in InfluxQL to my knowledge. Do you think we should disallow the use of aggregates for now?

**Comment by beckettsean** [comment]
@nathanielc @rkuchan I think until the nested function behaves as expected we shouldn't implement it.

**Comment by rkuchan** [comment]
I agree. Would be cool to have that functionality eventually.
