### ISSUE TITLE
remove SERVER related queries from InfluxQL spec page

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#401]
###### URL for relevant page?

Issue: https://github.com/influxdata/influxdb/issues/6465
PR: https://github.com/influxdata/influxdb/pull/6470 (merged)

###### What products and version are you using?

0.13 InfluxDB docs need updating.

**Comment by rkuchan** [comment]
I actually removed them in 0.12. 

Long backstory:
I [added descriptions](https://github.com/influxdata/docs.influxdata.com/pull/345) of `SHOW SERVERS` and `DROP SERVER` to 0.11 once we'd already cut the 0.12 branch and intentionally left them out of the 0.12 branch because of the cluster removal.
