### ISSUE TITLE
downloads link on older docs is confusing

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#404]
###### URL for relevant page?
http://docs.influxdata.com/influxdb/v0.11/

Left side nav shows a Downloads link, but that redirects to https://influxdata.com/downloads/#influxdb, which only references the latest release.

I think we should either remove the link or have it go to a page that gives the URL to download the last release in the 0.11 line.

Same for 0.10, 0.9, 0.8. We should just remove it from 0.7 and 0.6.

**Comment by beckettsean** [comment]
@rkuchan do we actually care about this? No one is asking much anymore for old releases. I vote we close.

**Comment by rkuchan** [comment]
Fine with me.
