### ISSUE TITLE
Add documentation for DELETE SERIES

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#406]
###### URL for relevant page?
https://github.com/influxdata/influxdb/pull/6484

**Comment by beckettsean** [comment]
syntax at https://github.com/influxdata/influxdb/blob/master/influxql/README.md#delete-series

**Comment by skazi0** [comment]
is this "DELETE FROM cpu" or "DELETE SERIES FROM cpu"? the examples and syntax definition are not matching.

**Comment by rkuchan** [comment]
@skazi0, `DELETE FROM <measurement_name>` is the correct syntax. We'll get `README.md` updated - thanks for pointing that out.
