### ISSUE TITLE
"GROUP BY time intervals" example doesn't explain time interval offsets

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#41]
Originally: https://github.com/influxdb/influxdb.com/issues/462

Related to influxdb/influxdb#1837

In the "GROUP BY time intervals" example in [this section of the documentation](https://influxdb.com/docs/v0.9/query_language/data_exploration.html#the-group-by-clause), there is a lower time bound of `2015-08-18T00:00:00Z` and a `GROUP BY time(2d)` in the query. The first timestamp returned is `2015-08-17T00:00:00Z`.

A couple observations:
  1. It is surprising that a timestamp is returned that lies outside the range specified in the `WHERE` clause.
  1. It is not discussed why this particular timestamp was the first returned.

I infer from the issue linked above that this occurs because `2015-08-17T00:00:00Z` is zero seconds modulo `(2*24*60*60)`, but this is not obvious from reading the example. I could have just as easily concluded (falsely) that `GROUP BY time(2d)` assumes my time lower bound refers to the midpoint of the `GROUP BY` interval.

This example should be updated to indicate what exactly is going on by default, and perhaps link to the issue.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/122
