### ISSUE TITLE
Minute missing from unit specification for durations on query spec

### ISSUE THREAD

**Issue by mrsheepuk** [influxdata/docs.influxdata.com#419]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.12/query_language/spec/#durations

###### What products and version are you using?
Documentation for v0.12 

###### Where did you look before opening the issue?
Checked open issues.

###### Description
The specification for duration includes the following:

    duration_lit        = int_lit duration_unit .
    duration_unit       = "u" | "µ" | "s" | "h" | "d" | "w" | "ms" .

Whereas the table directly above it includes "m" for "minute". I assume the duration_unit list should include | "m" | between "s" and "h".

**Comment by rkuchan** [comment]
Thank you for pointing this out, @mrsheepuk! Fixed in  https://github.com/influxdata/docs.influxdata.com/pull/444.

**Comment by mrsheepuk** [comment]
Welcome @rkuchan :)
