### ISSUE TITLE
No mention of buffering in Relay documentation

### ISSUE THREAD

**Issue by mrcrilly** [influxdata/docs.influxdata.com#424]
The Relay documentation does not contain any information regarding the buffering functionality.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.12/high_availability/relay/

###### What products and version are you using?
Latest.

###### Where did you look before opening the issue?
N/A

**Comment by rkuchan** [comment]
Thanks, @mrcrilly! We've updated the [still-to-come 0.13 docs](https://github.com/influxdata/docs.influxdata.com/pull/416/commits/5fac3ae2730f64dbc36c3d18b9695dfca2c4270f) to link directly to the [README.md](https://github.com/influxdata/influxdb-relay/blob/master/README.md) on GitHub.
