### ISSUE TITLE
suggestion for Influx DB documentation: page style - easier to print

### ISSUE THREAD

**Issue by minnieshi** [influxdata/docs.influxdata.com#425]
Hi,

For Influx DB documentation, such as:
https://docs.influxdata.com/influxdb/v0.12/introduction/getting_started/

it would be nice to have the background not dark, so that when user prints the page, it does not waste lots of ink.

Also, a user would naturally click getting started when they are new, it would be nice to guide (URL link) to the key concept page otherwise they can be lost easily.  A very good sample of the documentation is the grafana getting started page which guided user to read some fundamental stuff before getting started: http://docs.grafana.org/guides/gettingstarted/

**Comment by beckettsean** [comment]
Will be fixed by #352

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/352
