### ISSUE TITLE
[new page] migration from other tools

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#43]
Originally: https://github.com/influxdb/influxdb.com/issues/450

Graphite is the first one to tackle.
* how to configure carbon-relay to send existing graphite stream to graphite AND InfluxDB
* how to configure the graphite plugin, with basic templates for collectd and statsd metrics 
* example queries for cpu usage and average network bandwidth on eth0

**Comment by beckettsean** [comment]
Will ask for community help

**Comment by beckettsean** [comment]
related to #327

**Comment by beckettsean** [comment]
closing as this is something Marketing is doing.
