### ISSUE TITLE
Document field type output for SHOW FIELD KEYS

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#433]
###### URL for relevant page?
influxdata/influxdb#6592

###### What products and version are you using?
InfluxDB v1.0.0

**Comment by rkuchan** [comment]
@jsternberg, is it still possible to have a field with different data types across shards? If that's still the case how does `SHOW FIELD KEYS` choose which type to report?

**Comment by jsternberg** [comment]
It is still possible, but the output will be whichever type is highest on the precedence list (`float` > `integer` > `string` > `boolean`).
