### ISSUE TITLE
Docs design issues

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#436]
* [x] Linkable headers (Fixed by: https://github.com/influxdata/docs.influxdata.com/pull/435)
* [x] Navbar covers anchor links
* [x] Code blocks appear blank until the user interacts with them (Issue: https://github.com/influxdata/docs.influxdata.com/issues/357 - the issue is for mobile but it also occurs non-mobilely)
* [x] Version colors
* [x] Chronograf version is missing (Fixed by: https://github.com/influxdata/docs.influxdata.com/pull/444)

**Comment by gunnaraasen** [comment]
The search bar is also not working.

**Comment by rkuchan** [comment]
@gunnaraasen, looks like search is working again - is it working for you?

**Comment by gunnaraasen** [comment]
Yup, it's working again. There was an issue with the indexing script not parsing the content correctly in the new layout.

**Comment by gunnaraasen** [comment]
We may want to investigate some of these approaches to fix the anchor links. http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

**Comment by beckettsean** [comment]
@willpiers @wfro @mark-rushakoff @121watts any ideas?

@toddboom @pauldix possible hackday project post 1.0 release.

**Comment by alexpaxton** [comment]
Just pushed some updates that color code each product

**Comment by alexpaxton** [comment]
Fixed **Navbar covers anchor links** with help from @toddboom

**Comment by alexpaxton** [comment]
Just pushed a commit that fixes #357 I tested it on a few different things and it looks okay. I ended up z-indexing the code blocks higher and that fixed the issue

**Comment by beckettsean** [comment]
I wondered if it was a z-index thing. Thanks, @alexpaxton!

**Comment by rkuchan** [comment]
🎉 thanks, @alexpaxton!!
