### ISSUE TITLE
Outside searches should lead to the most recent version of the docs

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#439]

**Comment by gunnaraasen** [comment]
We already have a [`sitemap.xml`](https://github.com/influxdata/docs.influxdata.com/blob/master/layouts/sitemap.xml) which places the priority of all pages for the current version at priority 0.9 and all other pages for older versions at priority 0.1. According to the [thread linked](https://moz.com/community/q/priority-attribute-in-xml-sitemaps-still-valid) in @beckettsean's post, it sounds like we should really be setting a [lastmod attribute](http://www.sitemaps.org/protocol.html). That may be a little tricky to get right, but definitely possible.

We need to add the version number to the title (I thought we already did this but [apparently not](https://github.com/influxdata/docs.influxdata.com/blob/master/layouts/partials/header.html#L6)).

Improving the meta tags and noting a page has been deprecated in the meta text should also be fairly easy to add. It's probably time to start writing up specific [meta descriptions](https://github.com/influxdata/docs.influxdata.com/blob/master/layouts/partials/header.html#L7) for each page as well by setting a "description" in the metadata on each content page.

We'll need to look into deleting the index for certain versions. Removing the 0.6 and 0.7 versions makes sense to me. Removing versions 0.9, 0.10, 0.11, and 0.12 might make sense too, but I'm worried it might impact our (admittedly small) amount of google juice. It looks like the [robots.txt noindex tag](https://support.google.com/webmasters/answer/6062608?hl=en) does not work and the recommendation is to use [meta tags](https://support.google.com/webmasters/answer/93710). The options for a [robots meta tag](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag#valid-indexing--serving-directives) seem fairly extensive and potentially useful. We should also take a look at setting [canonical URLs](https://support.google.com/webmasters/answer/139066?hl=en) pointing to the pages of the latest version.

**Comment by beckettsean** [comment]
Do we know who signed up for the Search Console? @toddboom @gunnaraasen @alexpaxton @kfitzpatrick?

**Comment by beckettsean** [comment]
@toddboom @pauldix possible hackday project post 1.0 release.

SEO to fix the website results so they favor recent releases.

**Comment by dandv** [comment]
Any progress on this? Search results still point to old pages, and it's been quite annoying.

+1 on the canonical URLs. I'm a Googler working on AMP.

**Comment by rkuchan** [comment]
Update on this: We now have `/latest/` links and the warning at the top of the docs from v0.9+ link directly to the relevant page in the most recent doc version. It's not a perfect fix but hopefully this isn't as painful as before.

**Comment by xPaw** [comment]
This is still quite an annoying problem, as pretty much any query I do on google leads to an older version of InfluxDB documentation.

**Comment by Punkoivan** [comment]
Hello from December folks!
Any progress?
Links to the outdated documentation are confusing..

**Comment by stevebang** [comment]
Resolved by SEO work by @sanderson and @stevebang.
