### ISSUE TITLE
update write pages to reflect new partial batch success writes

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#44]
Originally: https://github.com/influxdb/influxdb.com/issues/436

From https://github.com/influxdb/influxdb/pull/4587:

"HTTP line protocol handler will now write all successfully parsed points instead of failing the entire batch if one failed. When some points fail to parse and the remaining are written successfully, the endpoint returns a partial write error with the failed lines in the response. This makes the behavior more consistent with the other inputs."

**Comment by beckettsean** [comment]
hasn't been a source of confusion since the change, closing.
