### ISSUE TITLE
[new page] external resources

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#443]
We need to put a page in the docs that links to the white papers, videos, and relevant blog posts (CP vs AP, TSM, Clustering closed source, etc.) so they are easier for users to discover from the docs.

###### URL for relevant page?
something under the Guides or Concepts section, maybe?

**Comment by beckettsean** [comment]
A short list of links to mention, there are no doubt others:

https://influxdata.com/technical-papers/
https://influxdata.com/videos/
https://influxdata.com/blog/update-on-influxdb-clustering-high-availability-and-monetization/
https://influxdata.com/blog/graphite-whisper-influxdb-migration-utility-beta/
https://influxdata.com/blog/category/tech-tips/
https://influxdata.com/blog/how-to-create-iot-influxdb-google-cloud-platform-part-1/
https://influxdata.com/blog/getting-started-with-sending-statsd-metrics-to-telegraf-influxdb/
https://influxdata.com/blog/testing-influxdb-storage-engines/
https://influxdata.com/blog/new-storage-engine-time-structured-merge-tree/
https://influxdata.com/blog/influxdb-clustering-design-neither-strictly-cp-or-ap/
https://influxdata.com/blog/combining-kapacitor-and-continous-queries/
https://influxdata.com/blog/influxdb-markedly-elasticsearch-in-time-series-data-metrics-benchmark/

@pauldix @toddboom @jwilder @nathanielc @sparrc @jginfluxdata @ShubhraKar Thoughts on the above links? Are some too old now? Did we miss some other good content?

**Comment by pauldix** [comment]
remove
> https://influxdata.com/blog/testing-influxdb-storage-engines/
> https://influxdata.com/blog/influxdb-clustering-design-neither-strictly-cp-or-ap/

**Comment by rkuchan** [comment]
Somewhat fixed in the 1.0 branch - a new External Resources section links to the videos and blogs page.
