### ISSUE TITLE
Define retention policy

### ISSUE THREAD

**Issue by rehevkor5** [influxdata/docs.influxdata.com#447]
The page mentioned below says:

> Once those data have timestamps that are older than two hours, InfluxDB deletes those data.

I can assume the timestamp they're referring to is the value provided in the insert statement. However, it doesn't say what the timestamps are compared to in order to determine whether they're "older than two hours". Is it compared to the local server clock? A globally coordinated cluster clock? The most recent timestamp put into the database? table?

Or is it the insertion timestamp (from system clock) compared with the system clock?

It's important to know the details in case the timestamps being ingested are not be close to the value of the system clock.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/guides/downsampling_and_retention/

###### What products and version are you using?
InfluxDB 0.13

###### Where did you look before opening the issue?
Docs, GitHub issues, Google

**Comment by rkuchan** [comment]
@rehevkor5, InfluxDB compares the timestamps on the data to `now()` where `now()` is  your local server's current timestamp.

I'll keep this issue open so that we clarify that behavior in the downsampling and retention guide. Thank you for pointing that out!

**Comment by rehevkor5** [comment]
@rkuchan thanks for the quick answer!

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/499
