### ISSUE TITLE
What should I fill in the username and password in kapacitor.conf

### ISSUE THREAD

**Issue by 1512100046** [influxdata/docs.influxdata.com#449]
https://docs.influxdata.com/kapacitor/v0.13/nodes/alert_node/#email

in kapacitor.conf, at smtp section, the usename and password should be what? 

suppose my yahoo's email is  mytest@163.com  and it's password is  mytest

![image](https://cloud.githubusercontent.com/assets/10609344/15319582/1fb09a42-1c5e-11e6-9033-5c4be77778cc.png)

**Comment by beckettsean** [comment]
Those are the SMTP settings. I googled "yahoo email smtp" and these are the most relevant results I found.

https://askleo.com/what-are-yahoos-imap-pop3-and-smtp-settings/
http://www.serversmtp.com/en/smtp-yahoo
