### ISSUE TITLE
when i use func hour it tell me expression returned unexpected type invalid type

### ISSUE THREAD

**Issue by qianlnk** [influxdata/docs.influxdata.com#450]
# cat cpu_alert.tick
stream
    |from()
        .measurement('cpu')
    |alert()
        .crit(lambda: "usage_idle" <  70 AND hour("time") > 1)
        .log('/tmp/alerts.log')
        .email()

E! error while evaluating expression: Failed to handle 1 argument: expression returned unexpected type invalid type

doesn't it use like so?

**Comment by rossmcdonald** [comment]
This should be filed against https://github.com/influxdata/kapacitor, and it looks like there's already a similar issue opened with https://github.com/influxdata/kapacitor/issues/555. Please comment on that issue with your test case.
