### ISSUE TITLE
Document Holt Winters method

### ISSUE THREAD

**Issue by nathanielc** [influxdata/docs.influxdata.com#459]
A Holt Winters forecasting method has been added to the query engine. We should document its use. See https://github.com/influxdata/influxdb/pull/6621 for basic usage. 

What other information would you want to add to a docs page? Maybe a simple explanation of what the method is doing under the covers? Let me know how I can help out here.

**Comment by beckettsean** [comment]
@nathanielc Is there a good resource elsewhere on the web that addresses some or all of the following?
 - why I would use Holt-Winters
 - why I wouldn't use Holt-Winters
 - the mathematical underpinnings of Holt-Winters
 - the common pitfalls or mistakes when using Holt-Winters

As for the InfluxDB documentation, I think we can just document the syntax as described in the PR and link to external references for the rest, at least for now.

**Comment by nathanielc** [comment]
@beckettsean Here is a great resource on the math behind it but it doesn't address the whys very well. https://www.otexts.org/fpp/7/5

I looked around a bit but no other resources that I could find are good at explaining the whys

**Comment by rkuchan** [comment]
Include a note about getting fewer points back than expected:

The math became unstable and could not forecast past that point. This means that either Holt-Winters is not suited for the dataset or that the seasonal parameter is invalid and is confusing the algo.
