### ISSUE TITLE
Chronograf query result can be rename? like grafana?

### ISSUE THREAD

**Issue by echodusty** [influxdata/docs.influxdata.com#466]
I use Chronograf Stable v0.13.0 now, I have some questions:

1. I perfer to rename query result name , but it can't done. Should support this? Or there's another way to solve it?
like this:
![image](https://cloud.githubusercontent.com/assets/19525078/15460547/9ff2f8c8-20e4-11e6-9f1c-205355c0fda0.png)
2. Query results can be sorted by some filter and displayed ?like grafana：
![image](https://cloud.githubusercontent.com/assets/19525078/15460679/390f9fa6-20e6-11e6-9d9a-d5df7ec8b190.png)

Forgive my poor English, and look forward to your reply.

**Comment by beckettsean** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list.

1. You can use `AS` to rename the output, e.g. `SELECT foo AS bar FROM ...` would return `bar` as the name of the result.

2. There is no way to order by anything other than time.
