### ISSUE TITLE
update max time range

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#467]
Per https://github.com/influxdata/influxdb/issues/3369#issuecomment-221267403, we need to update https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/#querying-outside-the-min-max-time-range.

**Comment by beckettsean** [comment]
This is a short-term bug that will be fixed by https://github.com/influxdata/influxdb/issues/6740 so let's leave it as-is for now.

**Comment by jsternberg** [comment]
The maximum time range was changed to `2262-04-11 23:47:16.854775806 +0000 UTC` at some point and I think this is the latest time we can realistically do. The documentation should be check to ensure that is documented.

Thanks!

**Comment by rkuchan** [comment]
https://github.com/influxdata/influxdb/blob/07071279dc550ce7ed7fbd151b7d7385d00ee4c2/models/time.go#L12
