### ISSUE TITLE
check docs for resolved issues

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#468]
We have a number of links to GHI in the docs, some are now closed. We should check each one before 1.0 docs.

**Comment by beckettsean** [comment]
https://docs.influxdata.com/influxdb/v0.13/concepts/insights_tradeoffs/ and https://docs.influxdata.com/influxdb/v0.13/concepts/crosswalk/ both link to https://influxdata.com/blog/influxdb-clustering-design-neither-strictly-cp-or-ap/ which I think Paul might want to downplay these days. It's pretty out of date.

Similarly, https://docs.influxdata.com/influxdb/v0.13/concepts/storage_engine/ needs updating to remain relevant.

On https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/, the following issues are closed. We should review the mentions of them. Some might still be relevant but we should mention they are currently closed.
https://github.com/influxdata/influxdb/issues/3369
https://github.com/influxdata/influxdb/issues/3130
https://github.com/influxdata/influxdb/issues/3337
https://github.com/influxdata/influxdb/issues/3242
https://github.com/influxdata/influxdb/issues/2977

On https://docs.influxdata.com/influxdb/v0.13/query_language/data_exploration/ the https://github.com/influxdata/influxdb/issues/4232 issue is closed and should be reviewed.

**Comment by beckettsean** [comment]
@pauldix should we remove references to https://influxdata.com/blog/influxdb-clustering-design-neither-strictly-cp-or-ap/ from the 0.13+ docs?

**Comment by pauldix** [comment]
yeah, should remove

**Comment by beckettsean** [comment]
Created https://github.com/influxdata/docs.influxdata.com/issues/479 for the storage engine page.

**Comment by beckettsean** [comment]
All issues have been addressed in the PR except the storage engine.
