### ISSUE TITLE
List of outputs does not match the list on telegraf GitHub Readme

### ISSUE THREAD

**Issue by tonydewan** [influxdata/docs.influxdata.com#469]
The [telegraf readme](https://github.com/influxdata/telegraf#supported-input-plugins) on GitHub includes a link to Instrumental, but the [web docs](https://docs.influxdata.com/telegraf/v0.13/outputs/) do not.

I'd be happy to make a PR if desired, but wanted to start with an issue as described in the footer of docs. :)

###### URL for relevant page?
https://docs.influxdata.com/telegraf/v0.13/outputs/

###### What products and version are you using?
N/A

###### Where did you look before opening the issue?
N/A

**Comment by rkuchan** [comment]
@tonydewan, thank you for pointing this out! We love PRs 😀
