### ISSUE TITLE
update storage engine doc to reflect latest

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#479]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/concepts/storage_engine/

https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v0.13/concepts/storage_engine.md

The content on this page hasn't been updated at all in 2016. It is most definitely out of date.

**Comment by beckettsean** [comment]
@jwilder @pauldix who can update the storage engine page for the 1.0 launch? We don't want to go live to a larger audience with this outdated and occasionally incorrect info.

**Comment by beckettsean** [comment]
@jwilder @pauldix we're gonna go live with 1.0 docs next Tuesday, but they won't be the "latest" docs.

By 1.0 final I think the storage engine page needs to be revisited by a developer familiar with the internals. It was written in the 0.9 timeframe, I believe.

Can you let us know who will revisit this doc, please, so that Regan and I can coordinate with them?

**Comment by pauldix** [comment]
Totally agree that it needs to get updated before 1.0 final. @jwilder is the best person to own this. I can probably pitch in too.

**Comment by jwilder** [comment]
I won't be able to look at this until after get plutonium feature
complete.  I'm assuming we'd have time to finalize 1.0 docs before we
release 1.0 final.

**Comment by beckettsean** [comment]
@jwilder no worries, we can wait until you are above water again.

**Comment by pauldix** [comment]
Definitely. Plenty of time until 1.0 final is out between Plutonium feature complete
