### ISSUE TITLE
bash test syntax debian repo install typo

### ISSUE THREAD

**Issue by dejaeghered** [influxdata/docs.influxdata.com#481]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/introduction/installation/
###### What products and version are you using?
Influxdb, v0.13, on debian
###### Where did you look before opening the issue?
/

The documented statements for debian repo install will always result in the jessie repo being written toinfluxdb.list

The following commands (wrong vs correct) are run on Jessie.

```
david@debian:~/Downloads$ test $VERSION_ID="7" && echo "deb https://repos.influxdata.com/debian wheezy stable" 
deb https://repos.influxdata.com/debian wheezy stable

david@debian:~/Downloads$ test $VERSION_ID = "7" && echo "deb https://repos.influxdata.com/debian wheezy stable"
david@debian:~/Downloads$ 
```

**Comment by beckettsean** [comment]
@rossmcdonald
