### ISSUE TITLE
InfluxQL cheat sheet

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#49]
Originally: https://github.com/influxdb/influxdb.com/issues/359

List all queries with their full syntax, in alphabetical order.

https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md has the list of all queries and a lot of the syntax, but it needs to be simplified and we need to make some of the syntax more explicit, e.g. what can accept regex operators and what cannot.

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/commit/5f9f6f8857a5a4dddc3dae43dfd3a116ec5e8d62
