### ISSUE TITLE
Add Compatibility Guarantee to docs

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#491]

**Comment by beckettsean** [comment]
@pauldix @jsternberg do we still want to publish a compatibility guarantee in the 1.0 docs? If so, is the finalized text available somewhere?

**Comment by jsternberg** [comment]
We're going to skip this at the moment and come back to it later.

**Comment by pauldix** [comment]
I think it would be a good idea to write something up. At least guidance to our users about what to expect. I can write something up in the next few days.

**Comment by beckettsean** [comment]
@pauldix still want to do this?
