### ISSUE TITLE
add installing doc on ubuntu 16 (systemd)

### ISSUE THREAD

**Issue by boynet** [influxdata/docs.influxdata.com#494]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/introduction/installation/

in ubuntu 16 instead of doing this to start the service:
```
sudo apt-get update && sudo apt-get install influxdb
sudo service influxdb start
```

you need to use systemctl
to start the service:
`systemctl start influxdb`

check is status:
`systemctl status influxdb`

make it run on boot
`systemctl enable influxdb`

you can see for example how grafana docs handle it:
http://docs.grafana.org/installation/debian/#start-the-server-via-systemd

ubuntu 14 lts end of life is in August 2016 and I guess that a lot will start to use ubuntu 16 lts lts which uses systemctl

**Comment by beckettsean** [comment]
@rossmcdonald
