### ISSUE TITLE
Can't custom the size of charts in Dashboard?

### ISSUE THREAD

**Issue by yonger1516** [influxdata/docs.influxdata.com#504]
###### What products and version are you using?
Chronograf 0.13 start by Docker Container
###### Where did you look before opening the issue?

Also can't move the charts at all.

**Comment by beckettsean** [comment]
@yonger1516 this looks like an issue with Chronograf, not the docs. Please email chronograf@influxdb.com for bug reports and feature requests on Chronograf.
