### ISSUE TITLE
update monitoring language

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#507]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/administration/config/#reporting-disabled-false

###### What products and version are you using?
Relevant for all versions of InfluxDB, all docs should be updated.

New wording:

InfluxData, the company, relies on reported data from running nodes primarily to track the adoption rates of different InfluxDB versions. This data helps InfluxData support the continuing development of InfluxDB. 

The `reporting-disabled` option toggles the reporting of data every 24 hours to `m.influxdb.com`. Each report includes a unique, randomly-generated identifier (an 8-byte Raft ID), OS, architecture, InfluxDB version, and the number of [databases](definition), [measurements](definition), and unique [series](definition). Setting this option to `true` will disable reporting.

**Comment by pauldix** [comment]
Language should be this:
```
# Once every 24 hours InfluxDB will report usage data to usage.influxdb.com
# The data includes a random ID, os, arch, version, the number of series and other
# usage data. No data from user databases is ever transmitted.
# Change this option to true to disable reporting.
reporting-disabled = false
```

**Comment by beckettsean** [comment]
@pauldix We offer expanded explanatory text on the config page of the docs, we don't just repeat the sample config text. Do you object to my text above? It's a simplification of what is already in the docs.

**Comment by pauldix** [comment]
It's just not quite accurate. We no longer use a raft ID and the report gets sent to usage.influxdb.com

**Comment by pauldix** [comment]
actually, it's usage.influxdata.com

**Comment by beckettsean** [comment]
InfluxData, the company, relies on reported data from running nodes primarily to track the adoption rates of different InfluxDB versions. This data helps InfluxData support the continuing development of InfluxDB. 

The `reporting-disabled` option toggles the reporting of data every 24 hours to `usage.influxdb.com`. Each report includes a randomly-generated identifier, OS, architecture, InfluxDB version, and the number of [databases](definition), [measurements](definition), and unique [series](definition). Setting this option to `true` will disable reporting.

> **Note** No data from user databases is ever transmitted.

**Comment by beckettsean** [comment]
Thanks, @pauldix! I updated the errors and highlighted the important bit.

**Comment by pauldix** [comment]
sounds good
