### ISSUE TITLE
CQs plus offset in GROUP BY

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#512]
Did some testing and we should probably document this behavior.

If a CQ is set up with an offset in the `GROUP BY` clause, the CQ will execute the query with the proper offset, but the query will be run at intervals that don't include the offset. For example, a CQ with the clause `GROUP BY time(1d, 3h)` will run at `00:00 UTC` but the `WHERE time` clause will start at `03:00 UTC` and end at `02:59 UTC` the following day.

As a user, I would expect the CQ to execute at `03:00` if I have an offset in the `GROUP BY`. Probably should put this on the CQ page, or FEI, or maybe the GROUP BY offset section.

**Comment by beckettsean** [comment]
@jwilder @pauldix is this an intentional design decision, or just a consequence of the CQ scheduler not being aware of `GROUP BY` offsets? Ideally CQs would be delayed or accelerated by the offset if it exists.

**Comment by beckettsean** [comment]
Until https://github.com/influxdata/influxdb/issues/7025 is fixed, we should plan to document this on FEI and CQ pages.

**Comment by rkuchan** [comment]
Partially fixed by: https://github.com/influxdata/docs.influxdata.com/commit/4cf51cd7bd4e0295fe626959b3cae4f3aa807dbc. Still need to add to FEI.
