### ISSUE TITLE
Bad link to GitHub Webhooks

### ISSUE THREAD

**Issue by cbandy** [influxdata/docs.influxdata.com#513]
In the navigation panel on the left, in the "Service Inputs" section, the [GitHub Webhooks](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/github_webhooks) link returns a 404.

###### URL for relevant page?

https://docs.influxdata.com/telegraf/v0.13/

###### Where did you look before opening the issue?

https://github.com/influxdata/telegraf/tree/master/plugins/inputs

I tried removing the last segment from the URL, but didn't see a `git` or `github` folder to try.

**Comment by rkuchan** [comment]
Thanks you, @cbandy! This will be fixed by  https://github.com/influxdata/docs.influxdata.com/pull/509. In case you couldn't find it, the new link is:  https://github.com/influxdata/telegraf/tree/master/plugins/inputs/webhooks/github.
