### ISSUE TITLE
metadir & datadir are compulsory to restore backup

### ISSUE THREAD

**Issue by ashishdoneriya** [influxdata/docs.influxdata.com#514]
Accordin to the documentation, To restore from a backup the command is "influxd restore /tmp/backup". -metadir and -datadir flags are under optional flags. But when i fire the command it asks for both metadir and datadir flags which is unexpected.

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/administration/backup_and_restore/#main-nav
###### What products and version are you using?
Product : Influxdata, Version : 0.13
###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v0.13/administration/backup_and_restore

**Comment by rkuchan** [comment]
Thanks, @ashishdoneriya!
