### ISSUE TITLE
Grammartical Error

### ISSUE THREAD

**Issue by Onuonga** [influxdata/docs.influxdata.com#516]
The error is specifically at: https://docs.influxdata.com/influxdb/v0.13/guides/writing_data/ 
This is based of the docs that are on influx db - Writing data (version 0.1.3 )

**Comment by beckettsean** [comment]
@Onuonga that's a fairly large page. Can you specify what grammatical error you see and where?

**Comment by beckettsean** [comment]
Data is commonly used in the plural sense, especially in documentation. Either is acceptable and correct.
