### ISSUE TITLE
Missing "-name" in kapacitor doc.

### ISSUE THREAD

**Issue by Kaacz** [influxdata/docs.influxdata.com#518]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v0.13/introduction/getting_started/

in example of define new stream:
```
kapacitor define cpu_alert \
    -type stream \
    -tick cpu_alert.tick \
    -dbrp kapacitor_example.default
```

should be:
```
kapacitor define -name cpu_alert \
    -type stream \
    -tick cpu_alert.tick \
    -dbrp kapacitor_example.default
```

**Comment by beckettsean** [comment]
@Kaacz that syntax is only valid for 0.12 and prior, not 0.13+

https://github.com/influxdata/docs.influxdata.com/pull/539#issuecomment-234396492
