### ISSUE TITLE
document migration of single node into cluster

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#519]
###### URL for relevant page?

New page, probably in Administration.

###### What products and version are you using?
InfluxDB 1.0+ 

###### Where did you look before opening the issue?
Use https://github.com/influxdata/support-runbooks/blob/ga-migration/hosted/aws/OSS_MIGRATION.md as the template.

**Comment by rkuchan** [comment]
Part of InfluxEnterprise docs: https://docs.influxdata.com/enterprise/v1.0/guides/migration/
