### ISSUE TITLE
add installation instruction for Linux Mint

### ISSUE THREAD

**Issue by tsionyx** [influxdata/docs.influxdata.com#521]
as the Mint is Ubuntu derivative you can add the following lines after Ubuntu instructions

```
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/${ID,,} $(echo $VERSION | awk '{print tolower($3)}') stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```

**Comment by beckettsean** [comment]
@rossmcdonald I think we should get Mint instructions out there if different from vanilla Ubuntu. It's not a common server OS but it is one of the most common desktop OSes. I'd skip it for Enterprise, those are almost always going on servers or VMs, not desktops.

**Comment by rossmcdonald** [comment]
@beckettsean I agree. The difficulty is getting a Linux Mint distribution installed to test on, so I apologize for this taking so long. 

Once I've been able to verify the updated steps above work then I'll open a PR. I'll see if I can't get this done today.

**Comment by beckettsean** [comment]
@rossmcdonald good point. I'll make sure we get you a laptop for multi-OS testing

**Comment by rossmcdonald** [comment]
@tsionyx Can you provide the output to `cat /etc/os-release` on your Linux Mint system? 

I was finally able to test this on Linux Mint 18, however the commands you've used above don't work properly. This is the contents of my `/etc/os-release`:

```
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
....
UBUNTU_CODENAME=xenial
```

Based on the contents of my version, I think it should be:

```
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
echo "deb https://repos.influxdata.com/${ID_LIKE,,} $(echo $UBUNTU_CODENAME stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```

**Comment by timhallinflux** [comment]
closing due to lack of interest in having official Mint install instructions.  If there is more demand for getting "derivative" installation instructions produced, we will re-open.  For now, standard installation instructions for Linux distros are documented.
