### ISSUE TITLE
FEI entry

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#522]
https://github.com/influxdata/influxdb/issues/6967

fill doesn't always have data

**Comment by beckettsean** [comment]
also https://github.com/influxdata/influxdb/issues/6878 if we haven't already documented that

**Comment by rkuchan** [comment]
Link to from `fill()` docs in data exploration.

**Comment by rkuchan** [comment]
Actually, influxdata/influxdb#6967 isn't documented.
