### ISSUE TITLE
Inconsistency between SHOW MEASUREMENTS in documentation and code

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#523]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/query_language/schema_exploration#explore-measurements-with-show-measurements

###### What products and version are you using?
InfluxDB v1.0.0-beta2-53-g11d141a

###### Where did you look before opening the issue?
The code and unit tests seem to believe there should be an `=` or `=~` sign after `WITH MEASUREMENT` and before the actual measurement name. This does not appear to be reflected in the documentation. The example needs to be changed to include this.

There's also a current bug I found at the same time where the `=` and `=~` sign don't matter in this usage. This appears to be a parser error and has nothing to do with the documentation, but that knowledge might be useful to support if somebody asks questions about it.

**Comment by beckettsean** [comment]
The actual example gives the right syntax but the generic pseudocode leaves out the operator.

@jsternberg I noticed that the behavior in 0.13 appears to support both `=` and `=~` in their intended uses, with one outlier:

regex operator working as expected

```
> show measurements with measurement =~ /foo/
name: measurements
------------------
name
fillfoo
foo
sfoo

> show measurements with measurement =~ /^foo$/
name: measurements
------------------
name
foo
```

equality operator working as expected:

```
> show measurements with measurement = foo
name: measurements
------------------
name
foo

> show measurements with measurement = fo
> 
```

Here's the weird one, equality operator accepts and properly applies a regex:

```
> show measurements with measurement = /foo/
name: measurements
------------------
name
fillfoo
foo
sfoo
```

Other queries don't allow that mixed syntax:

```
> show series where t1 =~ /a/
key
regex,t1=aaa

> show series where t1 = /a/
ERR: error parsing query: found /, expected identifier, string, number, bool at line 1, char 24
> 
```

I'll open a bug on influxdb repo.

**Comment by jsternberg** [comment]
Yea, the intended syntax works fine. It's just that it also accepts unintended syntax.
