### ISSUE TITLE
Series per measurement type, or tag per measurement type?

### ISSUE THREAD

**Issue by retorquere** [influxdata/docs.influxdata.com#527]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.13/concepts/key_concepts/#series

###### What products and version are you using?

influxdb-0.13.0

###### Where did you look before opening the issue?

Influx website

I understand the concepts of tags, fields and measurements, but not when to choose between tags and measurements. I collect data for several cars, and for each car I collect some 60 signals like speed and tank level. Would I insert that as

```
speed,car=1 value=10
tanklevel,car=1 value=0.5
```

or something like

```
car,id=1 tanklevel=0.5,speed=10
```

I'd want to correlate these values at a given timestamp later.

**Comment by beckettsean** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list
