### ISSUE TITLE
Make clear in the documentation that basic authentication is supported

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#532]
https://github.com/influxdata/influxdb/issues/7019#issuecomment-232992380

Basic authentication is supported along with using query string parameters. Make clear in the documentation that it is supported. The documentation currently says:

> The InfluxDB API provides a simple way interact with the database. It uses HTTP response codes, **HTTP authentication**, and responses are returned in JSON.

This implies it supports basic authentication, but it's not explicit enough for anybody to figure that out without guessing. It's very easy to think we're just referring to the `u` and `p` parameters. The documentation for those also says:

> Optional if you haven’t enabled authentication. Required if you’ve enabled authentication.

This implies that this is the only way to set authentication for the request. They are only required if you aren't using basic authentication.

Thanks!

**Comment by beckettsean** [comment]
@rossmcdonald @kostasb can you give us some Basic Auth examples to use in the docs?

**Comment by kostasb** [comment]
@beckettsean @rkuchan 

As Jonathan mention in #7019 this curl command uses the HTTP authentication header:
`curl -GET -u admin:admin 'http://localhost:8086/query?db=_internal' --data-urlencode "q=SHOW MEASUREMENTS"`

This is how the actual request looks like:

```
GET /query?db=_internal&q=SHOW%20MEASUREMENTS HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4=
User-Agent: curl/7.35.0
Host: localhost:8086
Accept: */*
```

The "Authorization: Basic" part is the HTTP authentication header. `YWRtaW46YWRtaW4=` is the base64 encoded representation of "admin:admin".

The above approach is equivalent to passing username and password with `u` and `p` parameters in the request string:

`curl -GET 'http://localhost:8086/query?db=_internal&u=admin&p=admin' --data-urlencode "q=SHOW MEASUREMENTS"`

This is how the request will look like in this case:

```
GET /query?db=_internal&u=admin&p=admin&q=SHOW%20MEASUREMENTS HTTP/1.1
User-Agent: curl/7.35.0
Host: localhost:8086
Accept: */*
```

The InfluxDB API supports both the HTTP Authentication header as well as passing `u` and `p` credentials in the request string.
