### ISSUE TITLE
Make full text of white papers available via link

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#533]
Currently the white papers are only available for download via PDF. It would be nice if the full text for the whitepapers was available to link to from the documentation.

**Comment by beckettsean** [comment]
@jginfluxdata @toddboom we have a challenge where we often want to point users to one or more of the white papers. However, all we can do is link them to the generic `https://influxdata.com/technical-papers/` page and give the title of the paper. 

Is there a reason we don't provide anchor links to specific papers on that page?

**Comment by rkuchan** [comment]
Half-fixed in the 1.0 branch - a new External Resources section links to the technical papers page.
