### ISSUE TITLE
improve GROUP BY time() examples, including offsets

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#536]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.13/query_language/data_exploration/#group-by-time-intervals

Use a slightly clearer example with more round numbers. It's tough to parse the day offset, especially with odd dates rather than even dates.

Also, let's show what happens if there are points with fields that don't always have a value. E.g. show the buckets with no values, then use `FILL()` and show buckets with the filled values.

**Comment by rkuchan** [comment]
Try 1h
