### ISSUE TITLE
Glossary pages for all products

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#542]
Enterprise, Kapacitor, and Telegraf need a Concepts/Glossary page.

**Comment by rkuchan** [comment]
Also see https://github.com/influxdata/docs.influxdata.com/issues/541

**Comment by beckettsean** [comment]
@nathanielc @rossmcdonald what would you put into a Kapacitor glossary that isn't already on the [InfluxDB glossary](http://docs.influxdata.com/influxdb/v1.0/concepts/glossary/)? E.g. `DAG`, `TICKscript node`, etc.

@sparrc @kostasb what would you put into a Telegraf glossary that isn't already on the [InfluxDB glossary](http://docs.influxdata.com/influxdb/v1.0/concepts/glossary/)? E.g. `input plugin`, etc.

**Comment by kostasb** [comment]
I'd say:

`agent`,`input plugin`,`service input plugin`,`output plugin`, `interval`, `flush_interval`, `metric buffer`, `collection jitter`, `flush jitter`

We will need to add aggregator plugins in the future.

**Comment by sparrc** [comment]
yes, also add `aggregator plugin` `processor plugin` `batch size` `precision`

**Comment by nathanielc** [comment]
For Kapacitor:

chaining method
property method
pipeline/DAG
TICKscript nodes/edges
lambda
stream
batch
task
template
replay
recording
time - not as a glossary item but rather how time works inside Kapacitor


That would be a good start.
