### ISSUE TITLE
It should be stated clearly that the primary keys are timestamp and the tag set

### ISSUE THREAD

**Issue by h12w** [influxdata/docs.influxdata.com#546]
It took me hours to try to find out what the primary keys really are, and here is why:

https://docs.influxdata.com/influxdb/v0.13/concepts/crosswalk/
"This is like an SQL database table where the primary key is pre-set by the system and is always time." Wrong! The primary keys are both time and the tag set.

https://docs.influxdata.com/influxdb/v0.13/guides/writing_data/
Primary key is not even mentioned in this page.

Reference:
https://github.com/influxdata/influxdb/issues/4614
"A point is uniquely identified by the measurement, tag set, and timestamp."

**Comment by beckettsean** [comment]
@h12w thanks for the feedback. Why were you looking for the primary key, out of curiosity? That will help us add more docs in the right place. Why would it be useful to know as part of the writing data guide, for example.

**Comment by h12w** [comment]
The first thing I must know about a database is how I can specify the primary keys, so that I am able to map the business data onto the model provided by InfluxDB. It is not enough to know that tags are indexed and fields are not, because it is different between "uniquely indexed" and only "indexed". It should be documented and emphasized that the combination of timestamp and tags uniquely identifies a `points` (or rows) within a measurement (table) under a retention policy.
