### ISSUE TITLE
verify curl syntax for POST

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#547]
###### URL for relevant page?
 https://docs.influxdata.com/influxdb/v0.13/guides/writing_data/

###### What products and version are you using?
0.13+ (when the POST method was required for destructive actions)

From
https://github.com/influxdata/influxdb/issues/6787#issuecomment-235087485

**Comment by rossmcdonald** [comment]
I believe the docs are correct... Against 0.13, creating a database with a GET yields:

```
> curl -i -XGET localhost:8086/query?q=create%20database%20yellow
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Request-Id: 0d62447f-52b5-11e6-8005-000000000000
X-Influxdb-Version: 0.13.0
Date: Mon, 25 Jul 2016 22:13:44 GMT
Content-Length: 158

{"results":[{"messages":[{"level":"warning","text":"deprecated use of 'CREATE DATABASE yellow' in a read only context, please use a POST request instead"}]}]}
```

So it's technically still possible, but the docs should direct users to use POST as using GET is deprecated.

```
> curl -i -XPOST localhost:8086/query?q=create%20database%20red
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Request-Id: 4f525e26-52b5-11e6-8006-000000000000
X-Influxdb-Version: 0.13.0
Date: Mon, 25 Jul 2016 22:15:35 GMT
Content-Length: 16

{"results":[{}]}
```

Or am I missing something?

**Comment by beckettsean** [comment]
@rossmcdonald I think the docs have `curl -POST` whereas your examples have `curl -XPOST`. Can you double check the docs syntax?

**Comment by rossmcdonald** [comment]
Ah, I could have sworn you didn't need to specify the `-X`, but it looks like you do. I'll open a PR to fix it.
