### ISSUE TITLE
Library for perfmon unavailable

### ISSUE THREAD

**Issue by adamperlin** [influxdata/docs.influxdata.com#549]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.13/clients/api/
https://github.com/willemdh/naf_windows_perfmon_to_influxdb

###### What products and version are you using?

Influxdb client api site

**Comment by beckettsean** [comment]
fixed by https://github.com/influxdata/docs.influxdata.com/commit/708f6e1a6050f1d5fca9e6c430f62038039d21d8 and https://github.com/influxdata/docs.influxdata.com/commit/cbf13b6405e8a57b8ba1463f823b0096a4c0f645
