### ISSUE TITLE
404 page is broken

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#551]
![screen shot 2016-07-26 at 11 09 45](https://cloud.githubusercontent.com/assets/6537329/17147788/7c4b00b8-5321-11e6-91ea-6ff324267545.png)

Looks like the new landing page broke the 404 page.

**Comment by beckettsean** [comment]
@alexpaxton @benstronaut @toddboom any chance we can get the Docs 404 page fixed before next Tuesday?

**Comment by alexpaxton** [comment]
I can tackle today

**Comment by beckettsean** [comment]
@alexpaxton any updates
