### ISSUE TITLE
need a page in InfluxDB docs about clustering

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#552]
It's our #1 search term, we need to send users somewhere helpful, like the new Enterprise docs, or for older versions, to Paul's blog post, perhaps.

**Comment by pauldix** [comment]
I'd rather not bother to send them to the blog post. Let's just have a landing page in the docs for when they search on clustering. Something like this should be enough.

> Clustering is offered in our commercial Enterprise offering of InfluxDB. Go [here](https://portal.influxdata.com/) for more details.

**Comment by beckettsean** [comment]
Updated copy:

> For high availability or scale out clustering we have a commercial offering called InfluxEnterprise. For details go here.

**Comment by beckettsean** [comment]
Final text for the page:

============
Open-source InfluxDB does not support clustering. For high availability or horizontal scaling of InfluxDB, please investigate our commercial clustered offering, [InfluxEnterprise](https://portal.influxdata.com).

**Comment by beckettsean** [comment]
@rkuchan can you add the same page to the 0.13 docs, too?
