### ISSUE TITLE
Update information logging with systemd journald

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#556]
###### URL for relevant page?
Not sure

###### What products and version are you using?
1.0

###### Where did you look before opening the issue?
InfluxDB Changelog:
```
With this release the systemd configuration files for InfluxDB will use the system configured default for logging and will no longer write files to /var/log/influxdb by default. On most systems, the logs will be directed to the systemd journal and can be accessed by journalctl -u influxdb.service. Consult the systemd journald documentation for configuring journald.
```

**Comment by rkuchan** [comment]
I'm removing this entirely from `statistics.md`:

> To find the number of writes separated by database since the beginning of the log file:
> ```bash
> $ grep 'POST' /var/log/influxdb/influxd.log | awk '{ print $10 }' | sort | uniq -c
> ```

I wasn't sure how to get the same information using `journalctl -u influxdb.service`.

**Comment by beckettsean** [comment]
@rossmcdonald will you be able to get a PR up by Wednesday?

**Comment by rossmcdonald** [comment]
@beckettsean I just pushed https://github.com/influxdata/docs.influxdata.com/pull/642, sorry for the delay in getting to this. Let me know what you think.
