### ISSUE TITLE
Add full syntax example to regex

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#56]
Originally: https://github.com/influxdb/influxdb.com/issues/313

https://influxdb.com/docs/v0.9/query_language/data_exploration.html#regular-expressions needs to show a full regex query.

**Comment by rkuchan** [comment]
This should be taken care of by https://docs.influxdata.com/influxdb/v0.9/query_language/data_exploration/#regular-expressions-in-queries
