### ISSUE TITLE
Unclear what RESAMPLE does for continuous queries

### ISSUE THREAD

**Issue by halt-hammerzeit** [influxdata/docs.influxdata.com#568]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.13/query_language/continuous_queries/

###### What products and version are you using?

latest

###### Where did you look before opening the issue?

in my monitor

It's unclear why would anyone need `RESAMPLE`.
`GROUP BY(interval)` tells the computer to run the continuous query every `interval`.
So who might need that `RESAMPLE EVERY x` thing?

And what does `RESAMPLE FOR y` do?
If one writes `... RESAMPLE EVERY day FOR hour GROUP BY minute` then it would downsample at most one hour of data (grouped by minutes) for each day and the other 23 hour data vanishes. Who might even need that kind of a weird thing going on in their database.

**Comment by rkuchan** [comment]
@halt-hammerzeit, we appreciate the feedback. We've recently revisited the CQ page to make the syntax and use cases clearer. Please feel free to open a new issue if things are still unclear.
