### ISSUE TITLE
Should document CollectD integration 

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#57]
Originally: https://github.com/influxdb/influxdb.com/issues/297

**Comment by beckettsean** [comment]
@jackzampolin given the work you've done with it, is there something to document here? I kinda feel like the README is adequate for now.

**Comment by jackzampolin** [comment]
I haven't really used the `collectd` endpoint. Just looking at the [code](https://github.com/influxdata/influxdb/tree/master/services/collectd) it looks like the service hasn't been updated in a while. The most recent commits look like an `influxdb` wide logging change, @gunnaraasen's change to make all services `[[ collectd ]]`, and the switch from `influxdb -> influxdata`. I would imagine it spits out a non-optimized schema but can't be sure.

As far as documentation needs having some sample input and output would be helpful to anyone running into that the first time.

**Comment by beckettsean** [comment]
not really sure what to document here, folks don't seem to have issues.
