### ISSUE TITLE
define tasks 404

### ISSUE THREAD

**Issue by huamaolin** [influxdata/docs.influxdata.com#572]
the "To define a task POST to the /kapacitor/v1/tasks/ endpoint"

correct to  "To define a task POST to the /kapacitor/v1/tasks endpoint"

**Comment by beckettsean** [comment]
@huamaolin what docs page is this on?

**Comment by beckettsean** [comment]
Looks like https://docs.influxdata.com/kapacitor/v0.13/api/api/#define-task

**Comment by beckettsean** [comment]
@nathanielc?

**Comment by nathanielc** [comment]
This will be fixed with #586
