### ISSUE TITLE
broken source bash for ubuntu install

### ISSUE THREAD

**Issue by dansteingart** [influxdata/docs.influxdata.com#577]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/introduction/installation/

###### What products and version are you using?
xenial ubuntu

###### Where did you look before opening the issue?
here

The problem is this line

`echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list`

it executes but creates a "malformed sources file" breaks `apt`.  Workaround to manually specify

`deb https://repos.influxdata.com/ubuntu xenial stable`

**Comment by beckettsean** [comment]
@rossmcdonald can you help?

**Comment by rossmcdonald** [comment]
Did you run the full set of commands?

```
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```

The important bit is the `source /etc/lsb-release`, which sets those variables. I just tested on Ubuntu Xenial and everything seems to be working.

**Comment by dansteingart** [comment]
I did, on 14.04 it didn’t set the variables.  will try on 16.04

On August 23, 2016 at 3:53:29 PM, Ross McDonald (notifications@github.com)
wrote:

Did you run the full set of commands?

curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,}
${DISTRIB_CODENAME} stable" | sudo tee
/etc/apt/sources.list.d/influxdb.list

The important bit is the source /etc/lsb-release, which sets those
variables. I just tested on Ubuntu Xenial and everything seems to be
working.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/influxdata/docs.influxdata.com/issues/577#issuecomment-241855656>,
or mute the thread
