### ISSUE TITLE
add JS snippet to send traffic metrics to InfluxDB

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#58]
Originally: https://github.com/influxdb/influxdb.com/issues/291

Let's dogfood with our own traffic metrics.

@pauldix anything in particular you want to capture?

- browser string
- URL visited

**Comment by pauldix** [comment]
Referrer, IP.

Should write it all as field values, not tags. Except the URL visited should be a tag :)

**Comment by rkuchan** [comment]
Closing old issue.
