### ISSUE TITLE
CQ page is inaccurate, users can set the interval boundaries explicitly

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#582]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v0.13/query_language/continuous_queries/#cq-definition

The time ranges of the CQ results have round-number boundaries that are set internally by the database. There is currently no way for users to alter the start or end times of the intervals.

###### What products and version are you using?
GROUP BY offsets do work in CQs, although only really in 1.0, since this fix isn't in 0.13: https://github.com/influxdata/influxdb/issues/7025

**Comment by rkuchan** [comment]
This is fixed in https://github.com/influxdata/docs.influxdata.com/commit/4cf51cd7bd4e0295fe626959b3cae4f3aa807dbc. It probably warrants a longer discussion, but, for now, the docs aren't lying anymore.
