### ISSUE TITLE
update OSS to Enterprise migration docs with RPM steps, too

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#590]
See https://status.zendesk.com/ for the `dpkg --remove influxdb` equivalent.

###### URL for relevant page?
http://docs.influxdata.com/enterprise/v1.0/guides/migration/

**Comment by rkuchan** [comment]
Ross took care of this in https://github.com/influxdata/docs.influxdata.com/commit/943541732d49c016661886236b64df9900b047a0,
