### ISSUE TITLE
Some chaining methods on Kapacitor HTTPOutNode are confusing

### ISSUE THREAD

**Issue by timraymond** [influxdata/docs.influxdata.com#595]
The top section is great—it tells me what an `HTTPOutNode` does, and a simple example of how it would be used. However, I'm confused by the presence of some of the chaining methods present. Some make sense, like `top` (it's used in the example), `derivative`, `elapsed`, etc. Others leave me with questions:
- What would the effects of having an `alert` or `deadman` chained in with the `HTTPOutNode`? Does it show whether or not the alert was tripped?
- What about a chained `httpOut` on an `httpOut`?
- What does `influxdbOut` do differently when chained with `httpOut`? Is it just a passthrough?

These can probably be addressed with a few more examples.
###### URL for relevant page?

https://github.com/influxdata/docs.influxdata.com/blob/master/content/kapacitor/v1.0/nodes/http_out_node.md
###### What products and version are you using?

Kapacitor v0.13
###### Where did you look before opening the issue?

I looked exclusively at the doc page.

**Comment by beckettsean** [comment]
@rossmcdonald @nathanielc thoughts on how to clear up Tim's confusion for future docs readers?

**Comment by nathanielc** [comment]
@timraymond @beckettsean The httpOut is just a passthrough with the side effect of caching the data under and http endpoint. As such any chaining method applies. I think to fix the docs we should make it clear that the httpOut node is a passthrough.
