### ISSUE TITLE
Broken TICKscript spec link

### ISSUE THREAD

**Issue by dgnorton** [influxdata/docs.influxdata.com#597]
###### URL for relevant page?

https://github.com/influxdata/docs.influxdata.com/blob/master/content/kapacitor/v1.0/nodes/index.md

The TICKscript Language Specification link gives a 404.

![image](https://cloud.githubusercontent.com/assets/209347/18054302/45fcfe24-6dd1-11e6-9f7e-f3400cb91655.png)

@rkuchan @beckettsean

**Comment by rossmcdonald** [comment]
I believe that link works:

http://docs.influxdata.com/kapacitor/v1.0/tick/

It doesn't work when viewing in Github, though, since it has to be fully rendered.

**Comment by rkuchan** [comment]
Closing after double-checking that the link works on the live site.
