### ISSUE TITLE
Kapacitor's CLA page is not used.

### ISSUE THREAD

**Issue by goller** [influxdata/docs.influxdata.com#603]
The CLA page for kapacitor is not linked to.

###### URL for relevant page?
https://github.com/influxdata/docs.influxdata.com/blob/master/content/kapacitor/v1.0/about_the_project/cla.md
###### What products and version are you using?
1.0
###### Where did you look before opening the issue?

- index.md: is not linked.

**Comment by rkuchan** [comment]
Are you talking about the CLA link to the old website? I believe it does show up in the About the Project submenu on the site:
![image](https://cloud.githubusercontent.com/assets/8750814/18144798/49171bbe-6f7d-11e6-9a2f-9fd3b1bda327.png)

**Comment by rkuchan** [comment]
@goller ^

**Comment by goller** [comment]
Oh ok... does the CLA.md get used in the About the Project side bar?

**Comment by rkuchan** [comment]
It's there it just sends people to https://influxdb.com/community/cla.html directly. No one actually sees the .md file and that's intentional.
