### ISSUE TITLE
Kapacitor Batch Node page references Stream nodes

### ISSUE THREAD

**Issue by desa** [influxdata/docs.influxdata.com#607]
Not a major issue, it was just slightly confusing that the Batch Node page references a `stream` in the examples for the `deadman` subsection.
###### URL for relevant page?

https://github.com/influxdata/docs.influxdata.com/blob/master/content/kapacitor/v1.0/nodes/batch_node.md#deadman
###### Where did you look before opening the issue?

No where

**Comment by beckettsean** [comment]
@nathanielc does deadman also work with batches? Can we update the example on the batch page to use a batch instead of a stream, or is that all autogenerated?

**Comment by nathanielc** [comment]
yes it does work for and that is autogenerated, and is the same for all nodes, because it is the same method on all nodes. We could add a batch example though so its clear.

**Comment by beckettsean** [comment]
I like the idea of adding a batch example for clarity. It will also introduce people to both concepts no matter which they start with.

**Comment by stevebang** [comment]
@sanderson -- You may have already fixed this issue -- please verify or take a look into this.
