### ISSUE TITLE
Are we going to update the NOAA example data?

### ISSUE THREAD

**Issue by desa** [influxdata/docs.influxdata.com#609]
The example`NOAA`  has an `0.9` that it references. I'm not sure if that is just the results of something else, or if thats InfluxDB related. 

```
curl https://s3-us-west-1.amazonaws.com/noaa.water.database.0.9/NOAA_data.txt > NOAA_data.txt
```

###### URL for relevant page?
https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.0/query_language/data_download.md#download-and-write-the-data-to-influxdb

**Comment by rkuchan** [comment]
Thanks, @desa. Didn't notice that for ages.
