### ISSUE TITLE
rethink downloads page and installation page

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#61]
Originally: https://github.com/influxdb/influxdb.com/issues/279

It's tough keeping them in sync and the version-specific download and installation data should probably live in only one place.

Also maybe we should link Downloads in the left side nav of the docs.
 @beckettsean

**Comment by beckettsean** [comment]
+1 for linking downloads in the docs left side nav.

**Comment by leonty** [comment]
Please also move the blog post about available linux repos to the Download page.
