### ISSUE TITLE
InfluxDB allows more than just UDP subscriptions 

### ISSUE THREAD

**Issue by desa** [influxdata/docs.influxdata.com#613]
To my knowledge, InfluxDB subscriptions can be `HTTP[s]` or `UDP`. The section listed below just refers to the `UDP` subscriptions and makes no mention of `HTTP[s]`. I know the section I was looking at is just a `getting started` section, but it could possibly lead to some misunderstanding for the reader.

Additionally, the `subscriptions` link on the page links to the InfluxQL spec which isn't super helpful. [subscriptions](https://github.com/influxdata/influxdb/blob/master/influxql/README.md#create-subscription)
###### URL for relevant page?

https://github.com/influxdata/docs.influxdata.com/blob/master/content/kapacitor/v1.0/introduction/getting_started.md#starting-kapacitor

**Comment by stevebang** [comment]
Closing as a dup of newer #1620.
