### ISSUE TITLE
document shard group durations

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#62]
Originally: https://github.com/influxdb/influxdb.com/issues/275

If the RP has a duration less than 2 days, all shards are 1h shards. If the RP has a duration of 2 days to 6 months, all shards are 1d shards. For durations greater than 6 months, all shards are 7d shards.

If writes are slowing down as the BoltDB files grow, moving to a narrower shard duration should help.

**Comment by rkuchan** [comment]
Closed in favor of https://github.com/influxdata/docs.influxdata.com/issues/35
