### ISSUE TITLE
Enterprise backup and restore... suggestions and questions.

### ISSUE THREAD

**Issue by goller** [influxdata/docs.influxdata.com#629]
Here are a bunch of minor rewrites and questions... I didn't want to put in a PR yet until some of the questions had been answered.

### Questions
-
> "Similarly, if the user creates a backup of a three node cluster with a replication factor of three and restores that backup to a two node cluster, the data will be distributed to as many nodes as possible (in this case, to two data nodes)."

What does this mean and what will the result be?

-

> "From the same meta node in the InfluxEnterprise Cluster, run:"

Does this mean to use the same node for backup and restore?

-
> "From the CLI:"

From CLI of the node? Any node in the cluster? Where the backup was dropped?

-

### Rewrite for clarity
-

> "Currently, users can perform backups and restores for all data in the cluster. They can be carried out on down clusters or on running clusters. Note that this feature does not support conflict resolution; any backed up data that conflict with existing data will not overwrite the existing data during the restore."

I think this would be more clear with:

> Backup and restore can be carried out on the entire cluster whether it is running or down.
> 
> Conflicts occur when restored data does not match active data (this usually occurs in an active cluster wherein the data has changed due to standard use). Conflicting data will not overwrite the existing and conflicting data during the restore.

-

> "As of version 0.7.4, InfluxEnterprise Clustering does not support backups or restores:"

Would be more clear if it reads something like:

> As of version 0.7.4, InfluxEnterprise Clustering does not support backups or restores in the following cases:

-
> "In the following example, we create a backup of a running cluster, drop data from the cluster that are in that backup, and add those data back into the cluster with a restore."

Might be more clear if read something like:

> The following example creates a backup of a running cluster, drops data from the cluster, and adds it to the back up, and adds data back into the cluster with a restore.

-

> "In this step, we drop data from the telegraf database that are older than 2016-07-08 23:42:43 (the time at which we created the backup)."

Might be more clear if read:

> This step drops data from the telegraf database that is older than 2016-07-08 23:42:43 (the time of which the backup was created).

###### URL for relevant page?
https://github.com/influxdata/docs.influxdata.com/blob/master/content/enterprise/v1.0/guides/backup-and-restore.md
###### What products and version are you using?
master
###### Where did you look before opening the issue?
n/a

**Comment by rkuchan** [comment]
Thank you, @goller. This is really helpful.

### Questions 

> "Similarly, if the user creates a backup of a three node cluster with a replication factor of three and restores that backup to a two node cluster, the data will be distributed to as many nodes as possible (in this case, to two data nodes)."

> What does this mean and what will the result be?

If the replication factor of the backed-up data is greater than the number of nodes in the cluster that the data are being restored to, then the backed-up data will be restored to the greatest number of nodes possible.

> "From the same meta node in the InfluxEnterprise Cluster, run:"

> Does this mean to use the same node for backup and restore?

Hm, yes. I assume that that is a requirement. In step 4 that's not clear at all.

> "From the CLI:"

> From CLI of the node? Any node in the cluster? Where the backup was dropped?

This is referencing the CLI on the data nodes. It could be from any data node in the cluster.
