### ISSUE TITLE
[new page] how to file bug reports

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#63]
Originally: https://github.com/influxdb/influxdb.com/issues/257

I like https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting as an example.

**Comment by rkuchan** [comment]
We do have a [contributing.md file](https://github.com/influxdata/docs.influxdata.com/blob/master/CONTRIBUTING.md) - we should link to it somewhere in the actual docs.

**Comment by beckettsean** [comment]
not many contributors get it wrong for simple edits, and we have the GHI template now to help with bug reports.
