### ISSUE TITLE
put InfluxEnterprise binaries on influxdata.com/downloads page

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#634]
###### URL for relevant page?

http://docs.influxdata.com/enterprise/v1.0/introduction/download/
and
https://influxdata.com/downloads/#enterprise (doesn't exist yet)

**Comment by beckettsean** [comment]
@rossmcdonald @toddboom how do we get the InfluxEnterprise binaries on the wordpress site?

**Comment by beckettsean** [comment]
@toddboom we really really want to get enterprise on the normal downloads page. How do we do that?

**Comment by rossmcdonald** [comment]
I've synced the existing releases from the old bucket to https://dl.influxdata.com/enterprise/releases, so all that should be needed is to update the Downloads page and other documentation.

**Comment by beckettsean** [comment]
@toddboom @jginfluxdata did we decide not to put the InfluxEnterprise binaries on the influxdata.com/downloads page? Seems like a natural place for them, and will simplify the docs when all downloads are in the same place.

**Comment by toddboom** [comment]
@beckettsean sorry about this - i didn't see this issue before launching. we can definitely get these added.

**Comment by andyfeller** [comment]
I'd really like to see RPMs available through https://repos.influxdata.com/ like the rest of them.

**Comment by beckettsean** [comment]
Not something docs can control. Moving to https://github.com/influxdata/influxdata.com/issues/36
