### ISSUE TITLE
[new page] open feature requests

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#64]
Originally: https://github.com/influxdb/influxdb.com/issues/234

Let's put up a page of the larger feature requests (timezone support, month/year support, custom functions, multiple mount points, etc) so that they are discoverable, and so that we can make some comments about them all in one place. It will help the community understand what's on the eventual roadmap, what's open for debate, and what's not going to be considered until 2.x or later.

**Comment by rkuchan** [comment]
@beckettsean, would it be good enough to link to the issues tagged with rfc on GitHub or does it need a full doc?

**Comment by beckettsean** [comment]
@rkuchan this is actually different from the `rfc` issues. It's less about "what do you think we should do with these?" which is the `rfc` label, and more about "you probably expect the database to do these, but it doesn't yet. Here are the relevant issues so you can follow them without having to search the 450 open issues for them, or emailing us about it."

I think it should be a simple list of the 10-15 most requested features that aren't yet implemented. I'll do my best to add representative links here soon.

**Comment by beckettsean** [comment]
Here is my list with a quick runthrough of the open issues. It's a good start, and might need to be edited down a bit. If we can logically group them it might be clearer with a long list. 

- auto-select retention policy when querying - https://github.com/influxdata/influxdb/issues/2625
- math across measurements - https://github.com/influxdata/influxdb/issues/3552
- RENAME [database, measurement, tag, field] https://github.com/influxdata/influxdb/issues/4154, https://github.com/influxdata/influxdb/issues/4155, https://github.com/influxdata/influxdb/issues/4156, https://github.com/influxdata/influxdb/issues/4157
- support for NaN - https://github.com/influxdata/influxdb/issues/4089
- month and year durations - https://github.com/influxdata/influxdb/issues/3991
- HAVING clause (filter by function results) - https://github.com/influxdata/influxdb/issues/5266
- timezone offsets - https://github.com/influxdata/influxdb/issues/2074
- custom functions - https://github.com/influxdata/influxdb/issues/68
- DELETE SERIES (delete data by time range) - https://github.com/influxdata/influxdb/issues/1647
- requested functions (all feature_request + function label issues) - https://github.com/influxdata/influxdb/issues?q=is%3Aopen+is%3Aissue+label%3Acategory%2Ffunctions+label%3A%22category%2Ffeature+request%22
- requested package support (all packaging + feature_request label issues) - https://github.com/influxdata/influxdb/issues?q=is%3Aopen+is%3Aissue+label%3Acategory%2Fpackages+label%3A%22category%2Ffeature+request%22
- set when GROUP BY windows start - https://github.com/influxdata/influxdb/issues/1837
- cluster auto-discovery of nodes - https://github.com/influxdata/influxdb/issues/1065

**Comment by jufemaiz** [comment]
Another one which I think would be worthwhile dealing with is falling edge / trailing edge for data.

Accumulators (for instance) are generally timestamped on the falling edge of the period in which they've counted values for, yet this causes problems at transitions of time (e.g. 00:00 with a fifteen minute periodicity would encompass data values from 23:45 to 00:00 but the previous day).

**Comment by beckettsean** [comment]
It's a good idea, but too much work to maintain.
