### ISSUE TITLE
Backups documentation not clear enough

### ISSUE THREAD

**Issue by jimaek** [influxdata/docs.influxdata.com#649]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v0.13/administration/backup_and_restore/
###### What products and version are you using?

InfluxDB 0.13
###### Where did you look before opening the issue?

The docs

The current backup docs dont answer a lot of questions such as:

Scenario: My dedicated server burns down, I only have backups and I am planning to restore them on a new server.
1. Does metastore backup continues queries as well? Or I will need to re-create them?
2. Lets say it took me 1 hour to setup the new server. After restoring I insert all the missing data for the 1 hour the DB was down. Will CQ process the data correctly since its technically from the past?
3. In the above scenario do I need to do anything else to get a new server with 1:1 data as the old one except from the commands below?

```
S1: influxd backup /path/to/metadata
S1: influxd backup -database mydatabase /path/to/backup
S2: influxd restore /tmp/backup
S2: influxd restore -database mydatabase /tmp/backup
```

Bonus: What stops me from doing rsync on the directories used by InfluxDB? I could keep a second server in sync and if something happens to master I could simply do `service start influxdb` on the second server to get up and running without doing any backup restores.

Thank you!

**Comment by ono760** [comment]
It seems that there are certain requirements the backups have with certain flags that the docs do not inform customers of.
For example, the –shard flag needs the –db flag unless there is only one shard per db.
Also, the –full flag timed out restoring the same shards as the incrementals without it, hard to say given the same conditions that the –full flag should be tamed with –db and/or –shard as well.

The –full flag is either broken or simply not working as its supposed to based on the docs. 
So, just running without the flag, an incremental of each db shards seems to do the trick.
When trying to restore each shard without the –db flag, it resulted in a conflict when it tried to restore shards within the same db, so it seems that the db flag must be required to restore each shard individually. Most of this is not indicated in the docs.

**Comment by stevebang** [comment]
Closing as legacy backup documentation has been deprecated. New enterprise-compatible backup and restore is documented and was reviewed.
