### ISSUE TITLE
Enterprise Getting Started link 404

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#654]
![screenshot 2016-09-07 09 41 04](https://cloud.githubusercontent.com/assets/7452680/18320554/3df65a1c-74df-11e6-9920-160c108d5416.png)

![screenshot 2016-09-07 09 40 02](https://cloud.githubusercontent.com/assets/7452680/18320565/4dbce0b0-74df-11e6-8991-a41b09bf495d.png)

**Comment by rkuchan** [comment]
Should be quick fix - the link should be `/getting-started/` instead of `/getting_started/'.

**Comment by rkuchan** [comment]
Actually - I'll take this :)
