### ISSUE TITLE
Links like https://docs.influxdata.com/influxdb/ should redirect to the latest version

### ISSUE THREAD

**Issue by wfro** [influxdata/docs.influxdata.com#656]
Googling 'influxdb docs' yields this link as the first result for me: https://docs.influxdata.com/influxdb/.

That page in the browser:

![screen shot 2016-09-07 at 3 11 35 pm](https://cloud.githubusercontent.com/assets/6454987/18330442/6eccadc0-750d-11e6-89b3-1c711e53ad3f.png)

It'd be good if we redirected to whatever the latest version is, i.e. https://docs.influxdata.com/influxdb/latest/, which has the much more friendly welcome page (intro, key features).

###### URL for relevant page?

https://docs.influxdata.com/influxdb/

###### Where did you look before opening the issue?

Searched through open issues.

**Comment by rkuchan** [comment]
Thanks, @wfro! Fixed!
