### ISSUE TITLE
Documentation typo in the "Downsampling and Data Retention" page

### ISSUE THREAD

**Issue by fabricedesre** [influxdata/docs.influxdata.com#658]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.0/guides/downsampling_and_retention/

In the `Results` section, instead of `name: cpu` and `name: downsampled_cpu` this should be `name: orders` and `name: downsampled_orders`

**Comment by rkuchan** [comment]
Thank you, @fabricedesre! This will be fixed by  https://github.com/influxdata/docs.influxdata.com/commit/2c52a037764861bda5e74cd9eddc3eefa49bfdce.
