### ISSUE TITLE
[new page] document size on disk guidelines

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#66]
Originally: https://github.com/influxdb/influxdb.com/issues/205

Will need to get numbers from perf testing, but for now just summarize https://github.com/influxdb/influxdb/issues/3554 and talk a bit about https://github.com/influxdb/influxdb/pull/3544

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/92
