### ISSUE TITLE
Need more Documentation on Conditional Functions

### ISSUE THREAD

**Issue by sarathj** [influxdata/docs.influxdata.com#660]
###### URL
https://docs.influxdata.com/kapacitor/v1.0/tick/expr/#conditional-functions

I want a more complex lambda expressions using AND condition. Looks like conditional functions will fit to the need, but need more info on it.

**Comment by beckettsean** [comment]
@sarathj can you provide an example calculation or pseudo-code to describe what you would like to do?

**Comment by sarathj** [comment]
@beckettsean 
Your documentation is solid and is the reason for me to choose TICK stack. 

I am using a tickscript with a GROUP BY clause. What I want is two lambda expressions with AND condition.
`var condition = lambda: field > threshold AND field != 0`
ref: [#259](https://github.com/influxdata/kapacitor/issues/259)


There is no much documentation on Continuous Functions.
- an example
- what is `any`
- how should be the condition

**Comment by beckettsean** [comment]
@rossmcdonald @nathanielc can you assist?

**Comment by nathanielc** [comment]
@sarathj Can you share your complete TICKscript?

This example is valid:

`var condition = lambda: field > threshold AND field != 0`

The `if` function returns the second or third argument based on whether the first argument evaluates to true:

For example:

```
|eval(lambda: if("field" > threshold AND "field" != 0, 0, 1))
    .as('field')
```

The value of the field `field` will be 0 if the condition is true or 1 otherwise.

**Comment by sarathj** [comment]
Here is my tickscript. I am not using a complex lambda expression yet. Thanks for the info on Conditional Function.

```
batch
    |query('''
    		SELECT mean(field) as avgfield,sum(AIR) as sumAIR,
    		sum(UAA) as sumUAA, sum(NC) as sumNC, sum(AINB) as sumAINB, sum(CNTA) as sumCNTA
    		FROM "fieldMonitor"."autogen"."field"
    ''')
        .period(5m)
        .every(5m)
        .groupBy(time(5m), 'cxxxId', 'cxxxName', 'txxxId')
    |alert()
        .id('{{ index .Tags "txxxId" }}/{{ index .Tags "cxxxId" }}-{{index .Tags "cxxxName"}}')
        .message('{{ .ID }} is {{ .Level }} field:{{ index .Fields "avgfield" }}
         AIR:{{ index .Fields "sumAIR" }}
         UAA:{{ index .Fields "sumUAA" }}
         NC:{{ index .Fields "sumNC" }}
         AINB:{{ index .Fields "sumAINB" }}
         CNTA:{{ index .Fields "sumCNTA" }}')
        .crit(lambda: "avgfield" < 0.7)
        .hipChat()
            .room('RTEDev')
            .token('xxxxxxxxxxxxxxxxxx')
        .log('/Users/sarath/Documents/RTEDev/alerts.log')
```
