### ISSUE TITLE
update code block styling for InfluxQL

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#67]
Originally: https://github.com/influxdb/influxdb.com/issues/193

Currently the `sql` blocks get SQL styling, which doesn't recognize many InfluxQL tokens. Let's update the parser/highlighter as appropriate so we can show InfluxQL without artifacts from SQL.

**Comment by beckettsean** [comment]
a good idea but more complexity than we need, probably.
