### ISSUE TITLE
brew install chronograf Error: No available formula with the name "chronograf"

### ISSUE THREAD

**Issue by ryanmcgarvey** [influxdata/docs.influxdata.com#673]
###### URL for relevant page?
https://www.influxdata.com/downloads/

###### What products and version are you using?
chronograf 1.0.0

###### Where did you look before opening the issue?
https://github.com/influxdata/influxdb.com/blob/master/content/site/download.md

The instructions there say:
brew update
brew install homebrew/binary/chronograf

Which points to 0.13.0

**Comment by beckettsean** [comment]
@gunnaraasen @toddboom it looks like the Homebrew recipe for Chronograf hasn't been updated: https://github.com/Homebrew/homebrew-binary/blob/master/chronograf.rb

@ryanmcgarvey the [code is the same](https://docs.influxdata.com/chronograf/v1.0/administration/upgrading/) between Chronograf 0.13 and Chronograf 1.0.

**Comment by gunnaraasen** [comment]
The `homebrew-binary`was deprecated recently and replaced with `homebrew-cask` so it's been taking awhile to update Homebrew.

I have an [open PR](https://github.com/caskroom/homebrew-cask/pull/24444) on `homebrew-cask`, which should be merged soon.

**Comment by gunnaraasen** [comment]
@ryanmcgarvey Chronograf PR has been accepted. Running `brew cask install chronograf` should work now. I'll get a PR together to update the installation page soon.

**Comment by gunnaraasen** [comment]
The install instruction for Chronograf should be up to date now.

**Comment by halt-hammerzeit** [comment]
Ok, so it installs but doesn't run:

```sh
➜  webpack-react-redux-isomorphic-render-example git:(master) ✗ brew cask install chronograf
==> Downloading https://dl.influxdata.com/chronograf/releases/chronograf-1.0.0-darwin_amd64.tar.gz
######################################################################## 100.0%
==> Verifying checksum for Cask chronograf
==> Symlinking Binary 'chronograf-1.0.0-darwin_amd64' to '/usr/local/bin/chronograf'
🍺  chronograf was successfully installed!
➜  webpack-react-redux-isomorphic-render-example git:(master) ✗ chronograf
[chronograf] 2017/01/22 04:13:27 Starting Chronograf (version 1.0.0)
[chronograf] 2017/01/22 04:13:27 config file could not be found in default locations and -config flag not provided; will use sensible defaults
[chronograf] 2017/01/22 04:13:27 Bind address not set: falling back to 127.0.0.1:10000
[chronograf] 2017/01/22 04:13:27 Local database path not set: falling back to chronograf.db
[chronograf] 2017/01/22 04:13:27 Query response size limit not set: falling back to limit of 2500000 bytes
[chronograf] 2017/01/22 04:13:27 Server binding to http://127.0.0.1:10000
[chronograf] 2017/01/22 04:13:27 listen tcp 127.0.0.1:10000: bind: address already in use
```

And there's no `/usr/local/etc/chronograf.conf` or anything like that.

**Comment by halt-hammerzeit** [comment]
* Found the conf on the internets, that will probably work:
https://github.com/newsdev/docker-influx/blob/master/chronograf/chronograf.conf
