### ISSUE TITLE
Document modifications to SHOW commands

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#674]
Document the modification to the SHOW commands listed in influxdata/influxdb#7295. Some commands that previous required `ON` no longer require `ON` (and will use the default database instead). Some commands now support using `ON` instead of specifying the database.

**Comment by rkuchan** [comment]
Thanks, @jsternberg!

**Comment by rkuchan** [comment]
Pages to update: InfluxQL reference, Schema Exploration.

New syntax:
```
SHOW SERIES ON <database_name>

SHOW MEASUREMENTS ON <measurement_name>

SHOW RETENTION POLICIES

SHOW TAG KEYS ON <database_name>

SHOW TAG VALUES ON <database_name>

SHOW FIELD KEYS ON <database_name>
```

**Comment by rkuchan** [comment]
Opened an issue about SHOW TAG VALUES`: https://github.com/influxdata/influxdb/issues/7552
