### ISSUE TITLE
lost the docs about using INTO to backfill for CQs

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#677]
###### URL for relevant page?
The equivalent of https://docs.influxdata.com/influxdb/v0.13/query_language/continuous_queries/#backfilling doesn't exist in the 1.0 docs.

**Comment by rkuchan** [comment]
That was me - that section technically covered plain `INTO` queries instead of CQs. I can put it back in if you'd like.

**Comment by beckettsean** [comment]
I think it's important to answer, just to address the question of how to recreate the results of a CQ if the cluster is down for a while, for instance. (Just had that question on the mailing list)

Maybe it goes into Troubleshooting? Like a "Recover from Downtime" page?

@gunnaraasen @rossmcdonald @kostasb @jackzampolin thoughts?

**Comment by gunnaraasen** [comment]
I agree with @beckettsean that it's important to mention. The CQ page should include a note about backfilling and a link to the `INTO` queries section since that's a common issue.

Another blurb on the Troubleshooting page about backfilling CQs with a link to the `INTO` query page would also be a nice-to-have.

**Comment by kostasb** [comment]
I believe it would be fine to just add the backfiling section back where it was initially with the Continuous Queries. It actually covers the parts that the continuous query won't work on (past data) so it is supplemental and makes sense for me to be there.

We could add a link for it to the FAQ page or the Troubleshooting page as well.

My opinion is that a "Recover from Downtime" section could be misleading: if there's downtime there won't be data for the CQ to backfill. The "Downtime" this can handle is "the CQ wasn't working at that period of time for whatever reason, but data ingestion was".
