### ISSUE TITLE
Enterprise Web backup

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#679]
###### URL for relevant page?

http://docs.influxdata.com/enterprise/v1.0/guides/backup-and-restore/

No mention of how to backup and restore the InfluxEnterprise Web database. is this the right order for restoring?
1. cluster metadata
2. cluster data
3. InfluxEnterprise database

What style of Postgres backup do we recommend? What about SQLite backups?

**Comment by beckettsean** [comment]
@toddboom @timraymond what is the responsible way to backup and restore the Enterprise Web database?

**Comment by timraymond** [comment]
@beckettsean If users are doing this manually, I usually use this one-liner from Heroku's import/export advice:

```
PGPASSWORD=mypassword pg_dump -Fc --no-acl --no-owner -h localhost -U myuser mydb > mydb.dump
```

Those switches prevent problems with ownership and ACLs and compresses the output. This is the corresponding `pg_restore`:

```
pg_restore --verbose --clean --no-acl --no-owner -h localhost -U myuser -d mydb latest.dump
```

Both of these were taken verbatim from here: https://devcenter.heroku.com/articles/heroku-postgres-import-export .

I wouldn't recommend doing this manually unless you're about to upgrade or something, or if you're taking these and putting them in a script to automate with cron. Many of the popular hosted Postgres services have automated backup, which is far better:

- RDS: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html
- Heroku Postgres: https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups
