### ISSUE TITLE
Documentation InfluxDB 1.0: "401 Authorization"  changed to "403 Forbidden"

### ISSUE THREAD

**Issue by PaulKuiper** [influxdata/docs.influxdata.com#680]
https://docs.influxdata.com/influxdb/v1.0/query_language/authentication_and_authorization/#authentication-and-authorization-http-errors

Al the way at the bottom in the section: Authentication and authorization HTTP errors

It states that a "HTTP 401 authorization" error is returned. 
However in https://github.com/influxdata/influxdb/pull/6978  this was changed to "403 Forbidden"

**Comment by rkuchan** [comment]
Thank you, @PaulKuiper!
