### ISSUE TITLE
document HA for Kapacitor, pre-clustering

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#689]
https://github.com/influxdata/kapacitor/issues/277#issuecomment-213692227

**Comment by thuey** [comment]
Are there any updates on Kapacitor HA? Are [these suggestions](https://github.com/influxdata/kapacitor/issues/277#issuecomment-192492608) still the go-to options for HA?

**Comment by timhallinflux** [comment]
Kapacitor Enterprise Edition is now GA.  It is a commercial offering.
