### ISSUE TITLE
Incorrect version warning

### ISSUE THREAD

**Issue by mvadu** [influxdata/docs.influxdata.com#694]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.0/write_protocols/write_syntax/

The URL is already for v1.0, but the warning says `"Warning! This page documents InfluxDB version 1.0-beta. InfluxDB v0.13 is the most recent stable version of InfluxDB."`

![image](https://cloud.githubusercontent.com/assets/8618235/18628707/2001c1dc-7e7f-11e6-8939-d4e4ed0a4626.png)

**Comment by rkuchan** [comment]
Thanks, @mvadu!

@kostasb, I'm at a loss for why `write_syntax` is showing up - that doc doesn't exist in the 1.0 docs. Do you have any ideas?

**Comment by kostasb** [comment]
@rkuchan fixed via commit to the publish process
The issue's URL now returns a 404, same as with any other URL that shouldn't exist with v1.0 but is there in previous versions.

**Comment by rkuchan** [comment]
Looks good! Thanks, @kostasb!

**Comment by mvadu** [comment]
this is an example of "doing the things right" and "doing the right thing". Previously the v1.0 documentation was kind of complete, as `Line Protocol` is still valid. Now https://docs.influxdata.com/influxdb/v1.0/write_protocols/ has very lame documentation which does not look 1.0 level. @pauldix please take a look at this situation.
![image](https://cloud.githubusercontent.com/assets/8618235/18678968/6305d962-7f7b-11e6-93bb-a4bf40827d90.png)

**Comment by beckettsean** [comment]
@mvadu @pauldix doesn't own the docs, my team does. If you want to yell at someone, yell at @beckettsean. That said, your comments are not currently constructive. If you would like to open an issue with specific criticisms or suggestions, please do so. The refactor of this page was done to make it simpler for each audience to find the right doc for them. I don't understand or agree with your vehement dislike for it. Try again in a constructive manner and leave Paul out of it.

**Comment by beckettsean** [comment]
@mvadu I think perhaps you are just confused about the docs. This old page: https://docs.influxdata.com/influxdb/v0.13/write_protocols/write_syntax/ has been replaced by two new ones: https://docs.influxdata.com/influxdb/v1.0/write_protocols/line_protocol_tutorial/ and https://docs.influxdata.com/influxdb/v1.0/write_protocols/line_protocol_reference/. The intermediary page that you show in your screenshot is just the parent page of the latter two. 

There is more content, and it is more appropriately written for each audience. That's an improvement in my book, do you not agree?

**Comment by mvadu** [comment]
@beckettsean Okay, I think I overreacted. Some of these protocol level things (which do not change frequently) gets linked up from various places, and when you visit the old pages we get an warning. The warning itself states that v1 is the latest version. However the hyperlink in the warning will not necessarily take you to correct version of the documentation. For example, v9 is the widely popular version of InfluxDB, and https://docs.influxdata.com/influxdb/v0.9/write_protocols/line/ currently does not link back to correct version, https://docs.influxdata.com/influxdb/v0.13/write_protocols/line/ does. 

So when I read the throwing the 404 part I initially (at the time of yelling, before calming down) I though we broke the whole page. Having two new version of the documents makes sense. Only quirk will be to fix the links in the warning in old versions to point to right version of the latest tutorial. Sorry again for losing control. My apologies.

**Comment by kostasb** [comment]
Older versions like 0.9 link to the homepage of 1.0, because the structure has changed since then and the links don't directly map to the same URL in 1.0.

**Comment by mvadu** [comment]
@kostasb okay.. so anything in 0.9 docs just points to v1 homepage? This specific example (of line protocol) not much has been changed since 0.9. But as a practice if we are redirecting to homepage then I agree.

**Comment by beckettsean** [comment]
@mvadu thanks for the update. @rkuchan is working on a mapping function for our docs so that the warning note on old versions will link to the most relevant current page.
