### ISSUE TITLE
Link to authentication is broken

### ISSUE THREAD

**Issue by jameswnl** [influxdata/docs.influxdata.com#703]
This link https://docs.influxdata.com/influxdb/v1.0/administration/authentication_and_authorization/ is broken

###### URL for relevant page?
That link is in https://docs.influxdata.com/influxdb/v1.0/guides/querying_data/

**Comment by beckettsean** [comment]
The page moved to the query language section: https://docs.influxdata.com/influxdb/v1.0/query_language/authentication_and_authorization/

The https://docs.influxdata.com/influxdb/v1.0/administration/ page also still lists auth/auth as being a child page.

**Comment by dandv** [comment]
All the links to CREATE, GRANT, REVOKE, SHOW at https://docs.influxdata.com/influxdb/v1.0/query_language/authentication_and_authorization/ have also been broken.

Fix please?

**Comment by rkuchan** [comment]
Fixed by https://github.com/influxdata/docs.influxdata.com/pull/719. Thank you for pointing this out, @jameswnl and @dandv.
