### ISSUE TITLE
document the importance of clients.json

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#704]
Enterprise data nodes need the `/var/lib/influxdb/meta` folder and the single JSON file that lives in it.

```
root@sean-cluster-data-1:/var/lib/influxdb/meta# cat client.json 
{"MetaServers":["sean-cluster-meta-01:8091","sean-cluster-meta-02:8091","sean-cluster-meta-03:8091"]}
```

**Comment by beckettsean** [comment]
unclear to me where in the docs this should go

**Comment by kelseiv** [comment]
added this requirement to the "Clustering in InfluxDB Enterprise" topic
