### ISSUE TITLE
Document the integration with LetsEncrypt

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#705]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.0/administration/config#https-certificate-etc-ssl-influxdb-pem

###### Where did you look before opening the issue?

https://github.com/influxdata/influxdb/issues/7283

###### TL;DR

Something like this could be added to the docs:

To reuse `.pem` files created by [Let's Encrypt](https://letsencrypt.org/), set the following in `/etc/influxdb/influxdb/conf` for the `[http]` section:

    https-certificate = "/etc/letsencrypt/live/yourdomain.com/fullchain.pem"
    ### Use a separate private key location.
    https-private-key = "/etc/letsencrypt/live/yourdomain.com/privkey.pem"

In the `[admin]` section, `https-certificate` should point to a file that concatenates `fullchain.pem` and `privkey.pem`. Note though https://github.com/influxdata/influxdb/issues/7284.

**Comment by beckettsean** [comment]
Thanks for the suggestions, @dandv. We're going to avoid the whole can of worms that gets opened by giving advice on how to set up SSL. Frankly it's not in our wheelhouse (too many distros, cert formats, etc.), so I'd rather folks get educated elsewhere on that.
