### ISSUE TITLE
administration/index.md: Typo in Section title

### ISSUE THREAD

**Issue by chsa** [influxdata/docs.influxdata.com#708]
Hi,
please find patch attached.
thank you
ChSa

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.0/administration/

src in https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.0/administration/index.md

[index.md.patch.txt](https://github.com/influxdata/docs.influxdata.com/files/486624/index.md.patch.txt)

###### Where did you look before opening the issue?
https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.0/administration/index.md

**Comment by rkuchan** [comment]
Thank you for catching this, @chsa!
