### ISSUE TITLE
update all docs pages with committer and commit timestamp

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#71]
Originally: https://github.com/influxdb/influxdb.com/issues/111

This will make it more clear what pages are going stale. In or near the footer let's print in a small font the last committer and the last commit time for that page. E.g.

"Last updated at 2015-07-08 15:32 by mjdesa"

**Comment by beckettsean** [comment]
Would be great, but this is old and not happened yet so closing.
