### ISSUE TITLE
Docs are missing max-series-per-database setting

### ISSUE THREAD

**Issue by reshujain4u** [influxdata/docs.influxdata.com#710]
{"error":"max series per database exceeded: Metrics,App=Saks,MetricName=average_dom_content_load_time,Metric_Type=EndUser/RB/UserAgent/Mobile/Browser"}

This is what I'm getting, I am pretty new to influx db and Time series database, requirnment is to have mutiple tags like App,Metrics_Type to be feeded into influx db, with Metrics (in case content load time) with value.

It is currnetly auto generating Timeseries, I tried to take configuration using influxd config > /etc/influxdb/influxdb.conf.generated

then updated Max-Series DB filed and saved the file, then passon command 

influxd -config /etc/influxdb.conf.generated

restarted Influx as port 8086 was used by gafana to query influx db.

Still nothing happens.. Please provide a clear command to disable max series and let infux make unlimited entry... Because this is going to used for atleast 2 years.

###### Where did you look before opening the issue?

**Comment by beckettsean** [comment]
Set `max-series-per-database` to 0 for unlimited series.

Please read the docs about [schema design](http://docs.influxdata.com/influxdb/v1.0/concepts/schema_and_data_layout/#discouraged-schema-design) to make sure you are using series responsibly.

**Comment by beckettsean** [comment]
need to add

```
[data]
 ...
 max-series-per-database = 1000000
 ...
```

to http://docs.influxdata.com/influxdb/v1.0/administration/config/

**Comment by rkuchan** [comment]
Thank you for pointing that out, @reshujain4u. Fixed by https://github.com/influxdata/docs.influxdata.com/pull/734.
