### ISSUE TITLE
404 on Line Protocol Link

### ISSUE THREAD

**Issue by azilber** [influxdata/docs.influxdata.com#712]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.0/write_protocols/line/

From this page:
https://docs.influxdata.com/influxdb/v1.0/tools/shell/#import-data-from-a-file-with-import

**Comment by mvadu** [comment]
Even from glossary page : https://docs.influxdata.com/influxdb/v1.0/concepts/glossary/#line-protocol

**Comment by rkuchan** [comment]
Thank you, @azilber and @mvadu. All links to the line protocol pages were fixed in  https://github.com/influxdata/docs.influxdata.com/pull/720.
