### ISSUE TITLE
Fix the nbsp;s in https://www.influxdata.com/get-started/influxdb-command-line-basics/

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#716]
At https://www.influxdata.com/get-started/influxdb-command-line-basics/ there's a bunch of `nbsp;`s in a <pre> under `Step 7: Query data`.

**Comment by rkuchan** [comment]
Thank you, @dandv. That's on the primary website - I've let the team know and they're working on getting it fixed.
