### ISSUE TITLE
Add information about how to handle write errors

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/docs.influxdata.com#72]
Originally: https://github.com/influxdb/influxdb.com/issues/100

See this thread: https://twitter.com/tisba/status/618416895272845312

**Comment by beckettsean** [comment]
A good thing to revisit for 1.0, but no one seems to be needing it lately.

**Comment by andrewthad** [comment]
The lack of documentation concerning idempotence of writes is still confusing. Googling something like "influxdb write idempotent" gives no helpful results. If I write the same exact data point (with the same timestamp) twice, what happens? Does influxdb make any guarantee about this?
