### ISSUE TITLE
remove issue mention from create RP, issue is solved

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#723]
###### URL for relevant page?

http://docs.influxdata.com/influxdb/v1.0/query_language/database_management/#create-retention-policies-with-create-retention-policy

https://github.com/influxdata/influxdb/issues/3634 has been closed, so the text needs updating (although the fix should be confirmed, first)

**Comment by rkuchan** [comment]
I believe this is a dup of https://github.com/influxdata/docs.influxdata.com/issues/573, and it's fixed in 1.1.0: https://github.com/influxdata/influxdb/pull/6597.
