### ISSUE TITLE
Typo in influxdb/v1.0/concepts/storage_engine/

### ISSUE THREAD

**Issue by movhr** [influxdata/docs.influxdata.com#727]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.0/concepts/storage_engine/#compactions

In Compactions > Index Optimization I came across the following sentences:

> Before an index **iptimization**, each TSM file contained points for most or all series, and thus each contains the same series index. After an index **optimzation**, each TSM file contains points from a minimum of series and there is little series overlap between files.

**Comment by beckettsean** [comment]
fixed by https://github.com/influxdata/docs.influxdata.com/pull/725
