### ISSUE TITLE
Link for NSQ Output Plugins in Telegraf 1.0 documentation is wrong

### ISSUE THREAD

**Issue by albundy83** [influxdata/docs.influxdata.com#729]
###### URL for relevant page?
https://docs.influxdata.com/telegraf/v1.0/

It's just that in section Output Plugins, link for NSQ is not correct : 
- it points to https://docs.influxdata.com/telegraf/v1.0/#ZgotmplZ
and it should point to 
https://github.com/influxdata/telegraf/tree/master/plugins/outputs/nsq

Very good product :) 
Thanks a lot.

**Comment by rkuchan** [comment]
Thank you, @albundy83!
