### ISSUE TITLE
new page: query engine guide

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#731]
Similar to clustering and storage engine guides in depth and length.

**Comment by beckettsean** [comment]
@jsternberg. @jwilder mentioned you would be a good person to help us with the query engine guide, similar to the [clustering](http://docs.influxdata.com/enterprise/v1.0/concepts/clustering/) and [storage engine](http://docs.influxdata.com/influxdb/v1.0/concepts/storage_engine/) guides. We really just need an outline of the topics and some bullet points or sentence fragments. Anything beyond that is gravy.

**Comment by beckettsean** [comment]
Just drop the notes on https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.0/concepts/query_engine.md, they won't be discoverable on the docs site until we hook up the Hugo syntax.

**Comment by timhallinflux** [comment]
Does EXPLAIN PLAN address the general need for a deep dive here?  We can also put this on the list for the IFQL engine.
