### ISSUE TITLE
Broken Link (404) in the primary website - influxdata.com - get-started - configuring alerts with kapacitor

### ISSUE THREAD

**Issue by peeyush-tm** [influxdata/docs.influxdata.com#735]
[](url)
###### URL for relevant page?
https://www.influxdata.com/get-started/configuring-alerts-with-kapacitor/

###### What products and version are you using?
None yet

###### Where did you look before opening the issue?
https://github.com/influxdata/docs.influxdata.com/issues/

In the section - 
## Step 3: Startup Kapacitor

We can boot up Kapacitor by invoking the daemon and passing it the toml configuration file we just created
```
$ kapacitord -config kapacitor.conf
```
Since InfluxDB is running on `http://localhost:8086` Kapacitor finds it during start up and creates several 
~~[subscriptions](https://github.com/influxdata/influxdb/blob/master/influxql/INFLUXQL.md#create-subscription) on InfluxDB.~~ 
_(is giving 404, needs to be changed to)_
[subscriptions](https://github.com/influxdata/influxdb/blob/master/influxql/README.md#create-subscription) on InfluxDB.
These subscriptions tell InfluxDB to send all the data it receives to Kapacitor.

...contd.

**Comment by rkuchan** [comment]
@peeyush-tm, thank you for pointing that out! 

As you noted, that is on the primary website.  I've let the team know about this issue and they're working on getting in fixed. In the meantime, I recommend checking out the Getting Started guide in the Kapacitor documentation: https://docs.influxdata.com/kapacitor/v1.0/introduction/getting_started/.
