### ISSUE TITLE
document where to find old releases

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#737]
more and more questions about where to find 0.13 binaries and older. Let's put a page in the docs or on influxdata.com/downloads about older versions

**Comment by rkuchan** [comment]
Also add how to get nightlies. Probably on installation for now until the downloads page gets updated.

**Comment by beckettsean** [comment]
Agreed. The downloads page is undergoing a design refresh, but it's a good idea to let users know about the nightlies and older versions on the installation pages.

**Comment by stevebang** [comment]
We haven't been getting lots of questions lately on where to find old releases -- closing.
