### ISSUE TITLE
[feature request] Link error messages to docs

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#741]
## Proposal

Link query-related error messages to further documentation. 

Specifically, an error (like `error parsing query: time dimension must have duration argument`) would link to an external document with more information about that error as well as links to any relevant documentation.
## Possible solution

Purchase a short domain name and put a small shortening/redirect service behind it for specific errors. For example, the link in `error parsing query: time dimension must have duration argument (https://<blah>/time-dim)` would redirect to the relevant doc section.

The link could be updated if error names/details change and we could specify the version number if the error is version-specific. 

(Props to @joelegasse for coming up with this solution)

**Comment by rkuchan** [comment]
The documentation part of this is underway: https://docs.influxdata.com/influxdb/v1.0/troubleshooting/errors/

**Comment by rw** [comment]
Rust does this to great effect:

https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html
