### ISSUE TITLE
Monitoring InfluxDB with Kapacitor - example to add

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#743]
From ZD ticket #3858

Below are a few recommendations for monitoring InfluxDB instances with Kapacitor:

Install and configure Telegraf on the cluster locally to use dual-InfluxDB outputs, one back to the cluster and another directly to Kapacitor (or just one directly to Kapacitor if that works better for you). That way you can create multiple alerts based on the data directly from Telegraf independent of any InfluxDB issues.

Configure Telegraf on each data node to use the influxdb plugin for collecting in-depth diagnostic information which can be used for alerting. I'd also recommend using the procstat plugin for tracking process-level metrics (memory, cpu, file handles) about the InfluxDB process.

Use a deadman node to detect lack of throughput on specific measurements, primarily any task that uses data from the influxdb input plugin, as that could be a sign of performance issues.
As far as measurements to alert on:

`influxdb_hh_processor` - Any upward sustained movement in queueDepth is a sign of the hinted-handoff queue filling up. We usually take the derivative of the incoming queueDepth over a window and then alert if it exceeds a certain threshold (for example, it's been growing at a rate greater than 1 per minute for the last 10 minutes). Example TICK script:

```
var period = 10m
var every = 1m
var queue_delta = stream
|from()
.database('telegraf')
.retentionPolicy('default')
    .measurement('influxdb_hh_processor')
|groupBy('host')
|window()
.period(period)
.every(every)
|default()
.field('queueDepth', 0)
|derivative('queueDepth')
.nonNegative()
.as('derivative')
.unit(period)
```

`influxdb_httpd` - Calculating the error percentage of HTTP requests is also a good sign that something is going wrong. I've attached a tick script that alerts based on the error percentage.
Apart from those two, alerting on the typical system-level metrics (memory, cpu, system load, etc) is also very helpful in identifying errors. We have a set of examples [here](https://github.com/influxdata/kapacitor/tree/master/examples/telegraf) on how to alert on the more generic system-level metrics.

**Comment by rkuchan** [comment]
Part of: https://github.com/influxdata/docs.influxdata.com/issues/752

**Comment by noramullen1** [comment]
@stevebang Going through old issues and wondering if this is one we can close now that the operations guide is out.

**Comment by stevebang** [comment]
This looks like this might be a good example for 1.x -- maybe a developer advocate (@rawkode) or someone else can write up the full example as a blog and we can add it to the docs.

**Comment by rawkode** [comment]
@influxdata/devrel Any takers?
