### ISSUE TITLE
Headings don't appear clickable

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#747]
At https://docs.influxdata.com/influxdb/v1.0/write_protocols/, do any of the headings look clickable?

![image](https://cloud.githubusercontent.com/assets/33569/19026606/b7f16e72-88dc-11e6-8b7f-db238af58fdc.png)

**Comment by beckettsean** [comment]
@dandv the headings are clickable and work fine. Are you raising a design objection, that they should appear more like links?

**Comment by dandv** [comment]
Correct, I think the styling should indicate they are links.

The first time I landed on that page, I though it was a blank/placeholder page.

**Comment by dandv** [comment]
A better example: headings differ from text only in font size. Nothing suggests they are links.

https://docs.influxdata.com/kapacitor/v1.0/examples/

![image](https://cloud.githubusercontent.com/assets/33569/19339056/ea11a498-90d5-11e6-9c49-75fb3cb26488.png)
