### ISSUE TITLE
Open source documentation for /write endpoint should mention consistency

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#749]
https://docs.influxdata.com/influxdb/v1.0/tools/api/#write

Even though the `consistency` parameter is ignored in OSS, I expected to see documentation for it under the OSS docs. It's okay with me if it doesn't explain what consistency does - I mainly want to see:

* The name `consistency` (as opposed to some shorthand)
* The default value is `one` if not specified otherwise
* Probably link to https://docs.influxdata.com/enterprise/v1.0/concepts/clustering#write-consistency

**Comment by rkuchan** [comment]
Thanks, @mark-rushakoff. Fixed!
