### ISSUE TITLE
Add documentation for fill(linear)

### ISSUE THREAD

**Issue by desa** [influxdata/docs.influxdata.com#764]
After PR https://github.com/influxdata/influxdb/pull/7403 it is now possible to fill missing group by buckets linearly.
## Example Usage

```
SELECT mean(value) FROM cpu WHERE time > now() - 1m GROUP BY time(10s) fill(linear)
```

**Comment by beckettsean** [comment]
Do https://github.com/influxdata/docs.influxdata.com/issues/522 at the same time

**Comment by beckettsean** [comment]
data exploration page and influxql spec page
