### ISSUE TITLE
add some repo READMEs to telegraf docs 

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#769]
https://github.com/influxdata/telegraf/blob/master/docs/ has a lot of good detail that should probably be added to the docs site. We also should include a link back to that directory for any new, experimental, or fast-moving READMEs that we don't yet want to add to the docs site.

**Comment by beckettsean** [comment]
@jackzampolin @sparrc are any of those READMEs not appropriate for the docs site?

**Comment by jackzampolin** [comment]
I would say the dependencies licence isn't docs appropriate, but the other 4 are links I regularly send to customers. 👍
