### ISSUE TITLE
purge incompatible API libraries

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#771]
https://github.com/influxdata/docs.influxdata.com/pull/770 purges those that are obviously inactive.

I opened issues on the following projects to see if 1.0 compatibility is planned:
https://github.com/maoe/influxdb-haskell/issues/31
https://github.com/mmaul/cl-influxdb/issues/5
https://github.com/MikaelGRA/InfluxDB.Client/issues/6
https://github.com/raphaelthomas/InfluxDB-HTTP/issues/1
https://github.com/gobwas/influent.rs/issues/11
https://github.com/paulstuart/influxsnmp/issues/28
https://github.com/ajgb/anyevent-influxdb/issues/4

I will remove them mid-October unless the maintainers let us know they plan to be 1.0 compatible.

**Comment by beckettsean** [comment]
https://github.com/ajgb/anyevent-influxdb/issues/4#issuecomment-252102740 is still active.

**Comment by beckettsean** [comment]
https://github.com/maoe/influxdb-haskell/issues/31#issuecomment-252104188 is still active

**Comment by dandv** [comment]
See also https://github.com/gobwas/influent/issues/19

**Comment by beckettsean** [comment]
https://github.com/mmaul/cl-influxdb/issues/5#issuecomment-252280320 is still active

**Comment by beckettsean** [comment]
Fixed in https://github.com/influxdata/docs.influxdata.com/commit/7c610db169c9eebaecd95cfd45ce41246169ca57.

Removed gobwas/influent.rs and paulstuart/influxsnmp as there were no responses to the issues opened.
