### ISSUE TITLE
Kapacitor tasks define command needs to fix with retention policy as 'autogen'

### ISSUE THREAD

**Issue by manojgour** [influxdata/docs.influxdata.com#772]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.0/introduction/getting_started/

###### What products and version are you using?
Kapacitor V1.0
###### Where did you look before opening the issue?
Checked few previous posts here on Github; got some clue with dbrp is missing then I did 'SHOW SUBSCRIPTION' that's where I found retention policy is no longer "default"

Kapacitor command for defining tasks is not working as described in document.

Below command was working fine for earlier version i.e v0.13:
kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp kapacitor_example.default

With Kapacitor new version, when I changed the retention policy to 'autogen' it worked fine:
kapacitor define cpu_alert -type stream -tick cpu_alert.tick -dbrp kapacitor_example.autogen

**Comment by rkuchan** [comment]
Thank you for catching that, @manojgour!
