### ISSUE TITLE
"abvove" in stateChangesOnly 

### ISSUE THREAD

**Issue by zargex** [influxdata/docs.influxdata.com#782]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.0/nodes/alert_node/#statechangesonly

###### What products and version are you using?
Kapacitor v1.0

###### Where did you look before opening the issue?
https://github.com/influxdata/docs.influxdata.com/issues

In the explanation of `stateChangesOnly` you can read `abvove` instead of `above`.

**Comment by rkuchan** [comment]
Thank you for pointing this out, @zargex!
