### ISSUE TITLE
Broken link on CQ page

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#791]
On page https://docs.influxdata.com/influxdb/v1.0/query_language/continuous_queries/#basic-syntax : 

 "CQs default to the relevant basic syntax behavior if the EVERY interval or FOR interval is not provided (see the first issue in Common Issues with Advanced Syntax for an anomalistic case)." links to https://docs.influxdata.com/influxdb/v1.0/query_language/cq_revised/#description-of-basic-syntax which does not exist.

**Comment by rkuchan** [comment]
On it - there are probably a couple of those.

**Comment by rkuchan** [comment]
Also thank you, @mark-rushakoff.
