### ISSUE TITLE
Documentation Theme Toggling Broken

### ISSUE THREAD

**Issue by mingraham** [influxdata/docs.influxdata.com#795]
When you navigate to https://docs.influxdata.com/ with Dark Mode toggled on (the default, meaning that in the upper right corner you see a sun icon), click any of the options (Telegraf, InfluxDB, Chronograf, Kapacitor, Enterprise), and then toggle to light mode (click the sun icon), CSS discovers entropy.

(Originally https://github.com/influxdata/influxdb/issues/7452).

**Comment by rkuchan** [comment]
Thank you, @mingraham. @alexpaxton, could you check this out when you get a chance? I'm able to repro on my machine.
