### ISSUE TITLE
need a mention of <db>.<rp>.<meas> syntax

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#796]
Maybe something on the FAQ, but definitely a specific mention on the data exploration page.

Mostly I need some place to link to to explain the syntax.

**Comment by rkuchan** [comment]
It's here: https://docs.influxdata.com/influxdb/v1.0/query_language/data_exploration/#the-basic-select-statement but it's not an easy thing to see. I'll think about how to make it clearer/easier to spot on the exploration page.
