### ISSUE TITLE
landing page can obscure links at some resolutions

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#797]
###### URL for relevant page?

http://docs.influxdata.com/

With width > 1200 pixels and height < ~600 pixels, links in the landing page are obscured:

<img width="1220" alt="screen shot 2016-10-12 at 15 24 29" src="https://cloud.githubusercontent.com/assets/6537329/19328342/74d06402-9090-11e6-8207-ca78aebc9907.png">

At widths less than 1200 pixels, the format seems okay. 
<img width="1178" alt="screen shot 2016-10-12 at 15 24 38" src="https://cloud.githubusercontent.com/assets/6537329/19328355/7dcb4c70-9090-11e6-90a4-77bd9bdfa636.png">

At heights larger than 700 pixels, the format seems okay. 
![screen shot 2016-10-12 at 15 24 53](https://cloud.githubusercontent.com/assets/6537329/19328361/82dbba92-9090-11e6-9ef1-149bfe96207c.png)

**Comment by stevebang** [comment]
@sanderson -- See if this is still an issue and worth fixing?
