### ISSUE TITLE
Broken survey / can't get stickers 😭

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#802]
###### URL for relevant page?

https://www.influxdata.com/downloads/

![image](https://cloud.githubusercontent.com/assets/33569/19338760/f1167a72-90d3-11e6-9e80-9daf13369393.png)

**Comment by beckettsean** [comment]
Thanks for the report, @dandv. This is on the wordpress site so I've forwarded it to the marketing team.
