### ISSUE TITLE
Incorrect description of syntax in example authentication using HTTP API

### ISSUE THREAD

**Issue by hsundararaja** [influxdata/docs.influxdata.com#808]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.0/query_language/authentication_and_authorization/#authenticate-using-the-http-api
###### What products and version are you using?

influxDB 
###### Where did you look before opening the issue?

https://docs.influxdata.com/influxdb/v1.0/query_language/authentication_and_authorization/#authenticate-using-the-http-api

There's a message saying -

Authenticate by providing query parameters in the URL. Set u as the username and p as the password.

`curl -G http://localhost:8086/query --data-urlencode "u=todd" --data-urlencode "p=influxdb4ever" --data-urlencode "q=SHOW DATABASES"`

If you do --data-urlencode, it becomes part of the request body. If it should be part of the request parameters, it should be mentioned the following way -

`curl -G 'http://localhost:8086/query?u=todd&p=influxdb4ever' --data-urlencode "q=SHOW DATABASES"
`

**Comment by beckettsean** [comment]
@hsundararaja the credentials are not Basic Auth, they are being passed to the database. It works perfectly well for them to be part of the request body.


```
curl -G http://<redacted>:8086/query --data-urlencode "u=åß∂ƒ" --data-urlencode "p=<redacted>" --data-urlencode "q=SHOW DATABASES"
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["mydb"],["_internal"],["foo"]]}]}]}
```

**Comment by hsundararaja** [comment]
I know, I didn't say they don't work. I just meant the documentation is wrong when it says "query parameters in the URL". 

Query parameters - 
http://localhost:8086/query?u=todd&p=influxdb4ever 

Body of request - 
--data-urlencode "u=todd" ---data-urlencode "p=influxdb4ever"

The document says "query parameters", but the example is as "body of request". 

Both work though,.

**Comment by beckettsean** [comment]
Thanks for the clarification, @hsundararaja. The curl command is not wrong, just the text describing it.

**Comment by hsundararaja** [comment]
Oops yeah,sorry, thanks for changing the title. That's what I meant.
