### ISSUE TITLE
Search deficiencies

### ISSUE THREAD

**Issue by MatMeredith** [influxdata/docs.influxdata.com#811]
See this issue here: https://github.com/influxdata/influxdb/issues/7465

One of the reasons that I hadn't found the API document was that it doesn't come up in the list of search results when searching the docs for e.g. "retention policy".

**Comment by beckettsean** [comment]
@gunnaraasen is there anything we can tweak with Algolia to show more complete results?

**Comment by timhallinflux** [comment]
We've overhauled the search as part of the 1.5 InfluxDB releases.  Review...and close?

**Comment by stevebang** [comment]
Closing, but working with Algolia on product/version filtering issue.
