### ISSUE TITLE
Continuous Query example range clarification

### ISSUE THREAD

**Issue by stevenh** [influxdata/docs.influxdata.com#821]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.0/query_language/continuous_queries/
###### What products and version are you using?

Influxdb
###### Where did you look before opening the issue?

The rest of the documentation
###### What is the issue?

The following statement in the continuous querys docs is inaccurate:

> When the CQ executes, it runs a single query for the time range between now() and now() minus the GROUP BY time() interval. If the GROUP BY time() interval is one hour and the current time is 17:00, the query’s time range is between 16:00 and 16:59.

This states that the last minutes worth of data for each hour would never be included, which is not the case.

Instead something like the following would be better:

> When the CQ executes, it runs a single query for the time range between now() and now() minus the GROUP BY time() interval. If the GROUP BY time() interval is one hour and the current time is 17:00, the query’s time range is >= 16:00 and < 17:00.

**Comment by rkuchan** [comment]
Thank you, @stevenh. Agreed - that does make is seem like some data would be left out. This is fixed by #891.
