### ISSUE TITLE
Update cluster join docs/syntax

### ISSUE THREAD

**Issue by jwilder** [influxdata/docs.influxdata.com#827]
The `influxd-ctl join` syntax is changing in an incompatible way with 1.1.  To use the old functionality and join procedure as documented for 1.0, you would need to use `influxd-ctl add-meta`.

The updated `influxd-ctl join` now handles adding meta and data node processes using the same command.  We need to update the docs for data nodes that you must also install the `meta` package in order to have access to `influxd-ctl`.
###### URL for relevant page?

https://github.com/influxdata/plutonium/pull/665
https://github.com/influxdata/plutonium/pull/712
###### What products and version are you using?

Enterprise 1.1

**Comment by beckettsean** [comment]
Make this experimental only, since it requires both binaries on the server and that will definitely confuse people. Not sure we should document at launch.

**Comment by ILMostro** [comment]
Is this still experimental?
Trying to figure out safe failover method if/when meta or data node needs to be added or replaced.
