### ISSUE TITLE
Document mixed units

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#836]
(Could have sworn there was an open issue for this but I can't find it)

Pages to update: InfluxQL reference (duration literals), Database Management (retention policies)

Looks like this affects everything - retention policy durations, cq every and for intervals, and doing math on timestamps.

**Comment by beckettsean** [comment]
https://github.com/influxdata/docs.influxdata.com/issues/573 is the original issue. Closed because it doesn't work everywhere, so feels weird to bother documenting it in only some places.

**Comment by rkuchan** [comment]
I think this is only in 1.1. I tried out the query you mentioned in #573 on the nightly and it worked:
```
> create retention policy blah on mydb duration 3d4h replication 1

> show retention policies on mydb
name	duration	shardGroupDuration	replicaN	default
----	--------	------------------	--------	-------
autogen	0s		168h0m0s		1		true
blah	76h0m0s		24h0m0s			1		false
```

I remember it being talked about for 1.0 but I think it got pushed to 1.1.
