### ISSUE TITLE
chronograf docs

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#852]
new product
no upgrade path
link to repo
link to old docs
link to blog post (get URL)

**Comment by rkuchan** [comment]
Keep only GS, Upgrading (can't upgrade)
Include `deprecated` in version list above 1.0 that links to page in docs

**Comment by rkuchan** [comment]
Relevant branch: https://github.com/influxdata/docs.influxdata.com/pull/853

**Comment by beckettsean** [comment]
Checked in changes to Getting Started and Upgrading pages, which include links to the repo, the blog post, and to old docs.

**Comment by beckettsean** [comment]
fixed by eb28b36 and bbfe530
