### ISSUE TITLE
[InfluxDB] Create Retention Policy - Default Scenarios

### ISSUE THREAD

**Issue by corylanou** [influxdata/docs.influxdata.com#856]
We need to review the documentation for retention policies to be specific about when the statements are idempotent, and when they create a conflict.  Based on https://github.com/influxdata/influxdb/issues/7448

###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.0/query_language/database_management/#retention-policy-management

**Comment by beckettsean** [comment]
This is for 1.2, right?

**Comment by corylanou** [comment]
yes, 1.2
