### ISSUE TITLE
Telegraf docs do not mention the -config-directory flag

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#857]
`-config-directory` flag is [here in the code](https://github.com/influxdata/telegraf/blob/61269c3500cbec0cd3f61871f17f1b876805d196/cmd/telegraf/telegraf.go#L31-L32) and is referenced in [the service file](https://github.com/influxdata/telegraf/blob/61269c3500cbec0cd3f61871f17f1b876805d196/scripts/telegraf.service#L9) which is used by packaging in 1.0.

**Comment by sanderson** [comment]
Resolved by  6e78108e99c45d18c030db68a234df0c44e79ce0
