### ISSUE TITLE
document how time works in Kapacitor

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#864]
inspired by https://github.com/influxdata/docs.influxdata.com/issues/542#issuecomment-252279812

@nathanielc can you elaborate a bit more on what you want to cover with this? Seems to me like a "Concepts" section doc.

**Comment by nathanielc** [comment]
@beckettsean Yeah, it would fit best in a `Concepts` section.

Basically `time` in the context of Kapacitor is not the same thing as system time or wall clock time. Time is relative and independent for each task and driven by the data it processes. While one can glean this information from various different docs, a nice concepts page that explains how time works in Kapacitor would be great.
