### ISSUE TITLE
Y-axis range selector not working

### ISSUE THREAD

**Issue by xcanchal-uz** [influxdata/docs.influxdata.com#868]
Using Cronograph v1.0 in the visualization page, when trying to type a number in any of the the y-axis range inputs, validation says it does not match the valid pattern and thus it's impossible to specify any value.

**Comment by rkuchan** [comment]
Hi @xcanchal-uz, we've [recently released](https://www.influxdata.com/announcing-the-new-chronograf-a-ui-for-the-tick-stack-and-a-complete-open-source-monitoring-solution/) Chronograf v1.1. This new open source version is not a continuation of the closed source product that you're using. We will not be developing or making any changes to that closed source product. We recommend checking out the [new Chronograf](https://github.com/influxdata/chronograf) - it's currently an alpha release and we'd welcome any feedback.
