### ISSUE TITLE
Kapacitor: Alert conditions are ingored

### ISSUE THREAD

**Issue by jayannah** [influxdata/docs.influxdata.com#875]
Hi

I have written the TICK script to query the data from InfluxDB, calculate tablespace_used and I want to write back to InfluxDB if the tablespace_used is > 0.6 in this example.

The below  TICK is able to query the data and write the data back to InfluxDB successfully. 

However, it is writing the entry into Database (Oracle_Intellix_TableSpace_Alerts meansurement) and to /tmp/batch_alerts.log even if the value of tablespace used is less than 0.6. I do see the entries in the DB and also in File /tmp/batch_alerts.log  with tablespace_used value  as 0.02, 0.5, 0.8, 0.9..etc.

1. Why the script is writing the entries for the tablespace_used values less than 0.6??? 
2. How to pass USED_MB, TOTAL_MB and other parameters of Oracle_Intellix_TableSpace measurement like serverName back into InfluxDB measurement created for alert (i.e Oracle_Intellix_TableSpace_Alerts)?

var tablespace_errors = batch
    |query('''
       SELECT *  FROM "comm_qa"."default"."Oracle_Intellix_TableSpace"
    ''')
      .period(15m)
      .every(10m)

tablespace_errors
   |eval(lambda: "USED_MB" / "TOTAL_MB")
          .as('tablespace_used')
   |alert()
        .crit(lambda: "tablespace_used" >  0.6)
        // Whenever we get an alert write it to a file.
        .log('/tmp/batch_alerts.log')
   |influxDBOut()
        .cluster('emmo_relays')
        .database('comm_qa')
        .measurement('Oracle_Intellix_TableSpace_Alerts')

====

Kapacitor 1.1
InfluxDB 1.0

**Comment by beckettsean** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the [influxdb@googlegroups.com](mailto:influxdb@googlegroups.com) mailing list

**Comment by jayannah** [comment]
I would consider this as a bug as 
1. The simple condition is ignored here
2. The documentation is so poor, it doesn't have example which can brief on the combination of conditions.

**Comment by beckettsean** [comment]
We haven't yet determined that your script is correct. Therefore it might be a bug or it might be a misconfiguration. We will determine that on the mailing list, not on the documentation repository issues.

To put it simply, there's nothing actionable about this for the docs. If you want to open a docs issue requesting more information, be specific about what you want. 

If you think it's a bug, open that on the Kapacitor repo.

Meanwhile, please take it to the mailing list until we determine where the fault lies.

**Comment by jayannah** [comment]
Thank you.
