### ISSUE TITLE
Default precision on getting_started doesn't match example

### ISSUE THREAD

**Issue by GeoffNicholls** [influxdata/docs.influxdata.com#890]
I'm going through and using the getting started page and influxdb for the first time (new set of eyes). I noticed that the first select example (`SELECT "host", "region", "value" FROM "cpu"`) returns the time as rfc3339, but when I did it on my Mac with the latest and greatest, I got ms. I had to enter `precision rfc3339` to get it to match the example

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.1/introduction/getting_started/

###### What products and version are you using?
Influx 1.1 for MacOS 10.11.6

###### Where did you look before opening the issue?
Nowhere

**Comment by rkuchan** [comment]
Thank you for pointing this out, @GeoffNicholls! We've added how to get that precision to the Getting Started.
