### ISSUE TITLE
Additional Operating System Support information

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#897]
Add supported Operating System information to the documentation.

Include OS support by versions, constrained by Go.

OS examples:
https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux
https://en.wikipedia.org/wiki/Ubuntu_version_history

Go support:
https://golang.org/doc/install

See https://help.pentaho.com/Documentation/7.0/0D0/160/000 as an example.

**Comment by rkuchan** [comment]
@rossmcdonald

**Comment by stevebang** [comment]
No plans to change this for 1.x. Supported versions and OS info will be better documented in 2.0 Closing.
