### ISSUE TITLE
update config page with WAL logging syntax

### ISSUE THREAD

**Issue by beckettsean** [influxdata/docs.influxdata.com#90]
See https://github.com/influxdb/influxdb.com/issues/550.

Apparently in 0.9.5 the syntax is different than 0.9.6, although I can't explain why from looking at the code.

**Comment by beckettsean** [comment]
@gunnaraasen can you figure out why we have a mismatch here? I can't find any record of `wal-enable-logging` in the repo, but that's absolutely what my 0.9.5 config shows:

```
[data]
  dir = "/Users/sean/.influxdb/data"
  max-wal-size = 104857600
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-dir = "/Users/sean/.influxdb/wal"
  wal-enable-logging = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5m0s"
  wal-partition-size-threshold = 20971520
```

**Comment by jademcgough** [comment]
I think he might be confused; it's always been `wal-enable-logging` in the config file.

**Comment by beckettsean** [comment]
@jademcgough I just looked at a config file on @jackzampolin's 0.9.6 box and it was `wal-logging-enabled`. Not sure what's the truth yet.

**Comment by hervenicol** [comment]
If you look at source code:
tsdb/config.go:90:	WALLoggingEnabled         bool          `toml:"wal-logging-enabled"`

**Comment by jademcgough** [comment]
oh, I'm completely wrong: https://github.com/influxdb/influxdb/commit/6592dcc69948190c19b8ec73a6c37a8bae9d486d

**Comment by gunnaraasen** [comment]
Looks like the config option was changed to `wal-enable-logging` back in 0.9.4 via https://github.com/influxdb/influxdb/commit/6592dcc69948190c19b8ec73a6c37a8bae9d486d and the sample config had `wal-enable-logging` up until this commit https://github.com/influxdb/influxdb/commit/4281da6688261f4675e21da850839a941268e56a.

On 0.9.5.1 and 0.9.6.1, the generated config is `wal-logging-enabled`.

I'm updating the config page now. There's some other stuff on there which needs to be updated as well.
