### ISSUE TITLE
General remark for Windows users

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/docs.influxdata.com#900]
###### URL for relevant page?
All

###### What products and version are you using?
InfluxDB V1.1

###### Where did you look before opening the issue?
At the documentation "getting started" and "documentation"

Hi,

I am trying to get InfluxDB running on my Windows System. While reading the documentation I noticed that the documentation is almost completely focussed on Linux users. While I'm quite proficient using Windows I don't know anything about Linux (Sorry) ;-). 
I hope that the documentation will focus a bit more on Windows users in the future.

**Comment by stevebang** [comment]
No plans to add new Windows documentation in 1.x.  For 2.0, platform support and documentation will be more consistent. Closing
