### ISSUE TITLE
[Suggestion] add deb link for arm

### ISSUE THREAD

**Issue by fg2it** [influxdata/docs.influxdata.com#902]
###### influxdb

I would find handy to have reference for arm .deb package on the download page (they already are on https://dl.influxdata.com/influxdb/releases/ ...). This also holds for Telegraph.
I didn't check for Kapacitor, but since influxdata provides them on the debian repo, I guess this could be included too.

**Comment by timhallinflux** [comment]
@gunnaraasen -- let's update the downloads page to include the ARM releases such as:
influxdb_1.3.6-1_arm64.deb
influxdb_1.3.6-1_armel.deb
influxdb_1.3.6-1_armhf.deb

**Comment by stevebang** [comment]
ARM binaries appear in downloads -- closing.
