### ISSUE TITLE
unable to send POST request to InfluxDB REST Api

### ISSUE THREAD

**Issue by sameerbetageri** [influxdata/docs.influxdata.com#906]
i am trying to create a InfluxDB database by sending the POST request and url to which i am sending POST query is 
http://localhost:8086/write?db=hamlet' --data-binary 'tobeornottobe booleanonly=true

iam getting reponse as
![src3](https://cloud.githubusercontent.com/assets/19279489/20783885/b5b1abb8-b7bc-11e6-82c4-843ad1b14719.jpg)

Any help in this regard is very much appreciated. Thank you

**Comment by rossmcdonald** [comment]
We try to reserve GitHub Issues for actionable bug reports or feature requests. Please send general questions to the influxdb@googlegroups.com mailing list
