### ISSUE TITLE
[InfluxDB] Document truncated HTTP responses

### ISSUE THREAD

**Issue by kostasb** [influxdata/docs.influxdata.com#909]
Need to document the effect of max-row-limit with the new partial tag introduced with PR  https://github.com/influxdata/influxdb/pull/7368

If you don’t use chunking, the server will automatically truncate at `max-row-limit` entries and will append a `"partial":true` tag in the response body.

The update needs to go here:
https://docs.influxdata.com/influxdb/v1.1/guides/querying_data/#maximum-row-limit

**Comment by kostasb** [comment]
Code comment:

```
Limit the number of rows that can be returned in a non-chunked
response.  This is to prevent the server from going OOM when
returning a large response.  If you want to return more than the
default chunk size, then use chunking to process multiple blobs.
Iterate through the series in this result to count the rows and
truncate any rows we shouldn't return.
```

**Comment by rkuchan** [comment]
Update:
* [ ] Querying data guide
* [ ] API reference
