### ISSUE TITLE
Typo and Error maybe??

### ISSUE THREAD

**Issue by MrD2** [influxdata/docs.influxdata.com#917]
###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.1/guides/writing_data/

###### What products and version are you using?
influxdb 1.1.1

###### Where did you look before opening the issue?
Writing a float to a field that previously accepted booleans:

---> It should be "Writing a float to a..."

And also, 200 OK isent supposed to be success? why is 204 the one considered OK and the 200 the one with an error?

**Comment by rkuchan** [comment]
@MrD2, thank you for pointing this out! It's actually not possible to get a `200 OK` with a write so we've removed that very outdated part of the guide. `204 No Content` is the response for a successful write.

Could you elaborate on the typo you mentioned? I'm having trouble identifying the typo in "Writing a float to a". Again, we really appreciate your feedback.

**Comment by rkuchan** [comment]
Closing this but feel free to reopen if there's still an issue!
