### ISSUE TITLE
[InfluxDB] Clarify that specifying the epoch query parameter always returns whole numbers

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/docs.influxdata.com#919]
Page: https://docs.influxdata.com/influxdb/v1.1/guides/querying_data/

In issue https://github.com/influxdata/influxdb/issues/7734, a user had a timestamp `1970-01-01T00:00:00.000051Z` and queried back for it with `epoch=ms`, and the result was time `0`. In that case, someone may expect the time `0.051`, but we currently (and probably always will) round the time to the nearest _whole_ unit.

**Comment by stevebang** [comment]
Closed -- addressed in #1694.
