### ISSUE TITLE
Problem with Chronograf and Kapacitor

### ISSUE THREAD

**Issue by gmajlis** [influxdata/docs.influxdata.com#921]
I Installed the ultimate versions (Telegraf, Influx, Chronograf and Kapacitor)
All of them are running on a personal VM.... up to here everything is working ok.

When creating alerts with Chronograf. It says is cannot save the alert.

I checked every signle log file, and there is no data regarding the issue.

I wanted to know if kapacitor and chronograf permissions need to be set to a specific user to solve this issue.

Again.....I am unable to create alerts form Chronograf (without it ......Kapacitor works perfect when I create the tick files)

**Comment by rkuchan** [comment]
@gmajlis, we generally try to reserve this repo for docs-specific issues. Would you mind re-opening this issue on the [Chronograf repo](https://github.com/influxdata/chronograf/issues/new)? You should be able to get the help you need there. Thank you!
