### ISSUE TITLE
[InfluxDB] Documentation on default ports no longer list 8088

### ISSUE THREAD

**Issue by hraftery** [influxdata/docs.influxdata.com#924]
The Installation documentation page lists 8083 and 8086 as the default ports in use by InfluxDB. The default influxdb.conf backs this up (though also suggests 8089 for UDP line protocol data).

However, the backup_and_restore documentation page uses port 8088 in its example for getting a backup from a remote host. This works just fine on a default install.

https://github.com/influxdata/influxdb/issues/6286 reveals that the port used to be explicit, but was removed because the open source version does not support clustering. However the use of the port remains, as does the backup functionality.

It seems less confusion would result from including 8088 in the list of default ports, and perhaps mentioning that its use in the open source product is restricted to remote backups (if that's true).

###### URL for relevant page?
https://docs.influxdata.com/influxdb/v1.1/introduction/installation/

###### What products and version are you using?
InfluxDB 1.1.1

###### Where did you look before opening the issue?
https://docs.influxdata.com/influxdb/v1.1/introduction/installation/
https://docs.influxdata.com/influxdb/v1.1/administration/backup_and_restore/
/etc/influxdb/influxdb.conf
https://docs.influxdata.com/influxdb/v1.1/tools/api/
Various Google searches on "influxdb" "port" "8088" and "8086"

**Comment by rkuchan** [comment]
@hraftery, thank you for pointing this out. Our documentation on ports was lacking. We've updated the docs for the 1.2 release with more information. Again, really appreciate the feedback!
