### ISSUE TITLE
Not possible to record a stream for use with union or join nodes

### ISSUE THREAD

**Issue by hraftery** [influxdata/docs.influxdata.com#925]
The "Calculate Rates across joined series + Backfill" example for Kapacitor describes how to use a join to combine series from two different measurements. It then shows how to use Kapacitor to record some historical data to pass to the script. Being able to repeatedly pass a set of existing data is extremely useful while developing the script.

The page then ends with a hint for doing the same with a stream instead of a batch. While the script works, the recording does not. The three methods of recording fail for the following reasons:

1. batch: batch recordings cannot be replayed to stream scripts
2. stream: stream recordings do not accept the stop, start and past arguments for recording historical data.
3. query: the query syntax only supports selecting from one measurement (as discussed in https://github.com/influxdata/influxdb/issues/3860). The replay works, but it will only have the points from which ever measurement was in the query and not the other one.

If it is indeed not possible to provide historical data to stream scripts that process multiple measurements, then (1) can this feature be added, (2) can the documentation point this out?

Example script:

```
var one = stream
    |from()
        .measurement('one')

var two = stream
    |from()
        .measurement('two')

one
    |union(two)
    @myUDF()
    |log()
```

Example recordings:

```
kapacitor record query -query $'select * from "database_name"."autogen"."one" where time > \'2016-12-21T07:49:00Z\' and time < \'2016-12-21T08:21:00Z\'' -type stream
kapacitor record query -query $'select * from "database_name"."autogen"."two" where time > \'2016-12-21T07:49:00Z\' and time < \'2016-12-21T08:21:00Z\'' -type stream
kapacitor replay -task my_script -recording $rid -rec-time
```

###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.1//examples/join_backfill/

###### What products and version are you using?
InfluxDB 1.1.1
Kapacitor 1.1.1

###### Where did you look before opening the issue?
https://docs.influxdata.com/kapacitor/v1.1//examples/join_backfill/
https://docs.influxdata.com/kapacitor/v1.1/nodes/union_node/
https://docs.influxdata.com/kapacitor/v1.1/nodes/join_node/
https://github.com/influxdata/influxdb/issues/3860

**Comment by hraftery** [comment]
Solved it a few hours later using [Multiple Statements](https://docs.influxdata.com/influxdb/v1.1/query_language/data_exploration/#multiple-statements-in-queries)

```
rid=$(kapacitor record query -query $'select * from "database_name"."autogen"."one" where time > \'2016-12-21T07:49:00Z\' and time < \'2016-12-21T08:21:00Z\'; select * from "database_name"."autogen"."two" where time > \'2016-12-21T07:49:00Z\' and time < \'2016-12-21T08:21:00Z\'' -type stream
kapacitor replay -task my_script -recording $rid -rec-time
```

Verbose, but works a treat.

**Comment by hraftery** [comment]
For those playing along at home, note that in order to:

1. Retain the tags as tags (instead of converting to fields)
2. Return all the fields, not just the first one (I assume this is a bug, since executing the `*` query at the command line returns all fields, but I can't be sure at this stage)

your query needs to be:

`rid=$(kapacitor record query -query $'select field1,field2,field3 from "database_name"."autogen"."one" where time > \'2016-12-21T07:49:00Z\' and time < \'2016-12-21T08:21:00Z\' GROUP BY *; select field1,field2,field3 from "database_name"."autogen"."two" where time > \'2016-12-21T07:49:00Z\' and time < \'2016-12-21T08:21:00Z\' GROUP BY *' -type stream`

which just rolls of the tongue. Note the two changes: (1) `GROUP BY *` added, and (2) fields listed explicitly instead of using `*`.

**Comment by hraftery** [comment]
I don't believe the fix addresses the issue. Still outstanding:

1. The trailing `)` seems to be getting cut off the `record query` statement, so as it appears in the documentation the statement doesn't even execute.
1. The recording still converts tags into fields. The `GROUP BY *` I mentioned on [30 Dec 2016](https://github.com/influxdata/docs.influxdata.com/issues/925#issuecomment-269715096) still seems to be necessary.

It seems this fix wasn't even tried before applying... I'm happy to do the testing on issues I raise in the future if that helps.

The "only returning the first field" bug does seem to have been fixed though.

**Comment by ivankudibal** [comment]
I'd propose to continue in Closed status and ask to decouple the issue from join backfill and split in more issues.

As for the article context:
ad 1/ the issue described above seems to be relevant to bash
ad 2/ "group by clause has to be present"
* retaining the tags as tags is shown -- you can group results by tags, as shown in the picture

![image](https://user-images.githubusercontent.com/8028110/40649567-8f8396d2-6331-11e8-8552-b9af2af6a692.png)

Chronograf charts:
1/ SELECT mean("error_percent") AS "mean_ep" FROM "pages"."autogen"."error_percent" WHERE time > :dashboardTime: GROUP BY time(:interval:),page FILL(null)
2/ SELECT mean("value") AS "mean_value" FROM "pages"."autogen"."error_percent_batch" WHERE time > :dashboardTime: GROUP BY time(:interval:),page FILL(null)

The join_backfill article shows how to join two measurements and store the processed data into new calculated field. More, the article does not describe how to record stream. The stream worked for me from the real data..

In addition I also recorded stream. Pls note the documentation does not allow -past option for recording  stream-typed tasks. Eg this works
```
$ kapacitor record stream -task error_percent_stream -duration 1m
$ kapacitor replay -task error_percent_stream -recording c37c3a41-126e-4dfe-aa9a-8e935e646147

```

**Comment by hraftery** [comment]
I think the issue (which is just that the documentation is wrong) is small enough just to resolve and move on. To be abundantly clear (because it wasn't obvious to @ivankudibal so probably isn't to others) this is the issue:

The bottom of https://docs.influxdata.com/kapacitor/v1.5/guides/join_backfill/ says:

> To provide historical data to stream scripts that process multiple measurements, use multiple statements when recording the data.
> 
> `rid=$(kapacitor record query -query $'SELECT * FROM "pages"."autogen"."errors" WHERE time > \'2016-12-21T07:49:00Z\' AND time < \'2016-12-21T08:21:00Z\'; SELECT * FROM "pages"."autogen"."views" WHERE time > \'2016-12-21T07:49:00Z\' AND time < \'2016-12-21T08:21:00Z\'' -type stream`
> `kapacitor replay -task error-percent -recording $rid -rec-time`

Which doesn't work for two reasons:

1. The `)` is missing from the end of the first statement (note this is not a bashism and will work in `sh`-compatible shells).
1. The tags get converted to fields in the replay.

The solution is already in this issue, posted by me on [30 Dec 2016](https://github.com/influxdata/docs.influxdata.com/issues/925#issuecomment-269715096). Perhaps there is a reason it has not been used and incorrect documentation has been used instead, but I don't know it. I do know that these sorts of bum-steers lead to many, many hours of frustration for newbies to TICK. I guess I'm starting to see why they exist.

**Comment by stevebang** [comment]
Thanks, @hraftery -- minimizing head-banging by newbies (or any user) is important.  I reopened this and we'll resolve this properly.

**Comment by sanderson** [comment]
@hraftery this issue was automatically close with the merge of some changes that @karel-rehor made. Do you want to take a look? If adjustments still need to be made, I'll reopen the issue and would love to work through them with you.

**Comment by hraftery** [comment]
Sorry for the delay, had some email dramas. Yep, all looks good now.
