### ISSUE TITLE
[InfluxDB] Please explain how to have Influx start at system boot

### ISSUE THREAD

**Issue by dandv** [influxdata/docs.influxdata.com#965]
###### URL for relevant page?

https://docs.influxdata.com/influxdb/v1.1/introduction/installation/

###### Where did you look before opening the issue?

https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.1/introduction/installation.md mentions "To have InfluxDB start at system boot", but that file doesn't seem to be the source for the Installation page I've linked above.

On Ubuntu, I tried `systemctl enable influxd` but [got](https://github.com/influxdata/influxdb/issues/7850)

> Failed to execute operation: Too many levels of symbolic links

**Comment by LendLord** [comment]
+1

**Comment by Robirt55** [comment]
+1
This seems to still be an issue. Will post the workaround once I found it.

**Comment by jonol** [comment]
`sudo systemctl enable influxdb.service` worked for me :)

**Comment by vasilgerman** [comment]
> ###### URL for relevant page?
> https://docs.influxdata.com/influxdb/v1.1/introduction/installation/
> 
> ###### Where did you look before opening the issue?
> https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.1/introduction/installation.md mentions "To have InfluxDB start at system boot", but that file doesn't seem to be the source for the Installation page I've linked above.
> 
> On Ubuntu, I tried `systemctl enable influxd` but [got](https://github.com/influxdata/influxdb/issues/7850)
> 
> > Failed to execute operation: Too many levels of symbolic links

Hi, bro! Try to create a user chronograf before localinstall chronograf-1.7.11.x86_64.rpm
