### ISSUE TITLE
Document "no such table: products" and 500 error

### ISSUE THREAD

**Issue by kostasb** [influxdata/docs.influxdata.com#967]
Let's document this error in the enterprise FAQ:

```
Jan 19 10:49:41 enterprise-centos7 influx-enterprise[15148]: 2017/01/19 10:49:41 Starting on port :3000...
Jan 19 10:49:41 enterprise-centos7 influx-enterprise[15148]: 2017/01/19 10:49:41 Fetching and validating license: XYZ
Jan 19 10:49:41 enterprise-centos7 influx-enterprise[15148]: [metamaster] 2017/01/19 10:49:41 DB connection err: no such table: products
Jan 19 10:49:41 enterprise-centos7 influx-enterprise[15148]: Saving license locally to: /tmp/influx-enterprise.key.json
Jan 19 10:49:41 enterprise-centos7 influx-enterprise[15148]: 2017/01/19 10:49:41 License XYZ is valid.
Jan 19 10:49:54 enterprise-centos7 influx-enterprise[15148]: Started POST "/api/v1/products" for IP 2017-01-19 10:49:54.404432769 +0000 UTC
Jan 19 10:49:54 enterprise-centos7 influx-enterprise[15148]: ERROR        2017-01-19T10:49:54Z /home/ubuntu/.go_workspace/src/github.com/influxdata/enterprise/actions/api/v1/products.go:29 : no such table: products
Jan 19 10:49:54 enterprise-centos7 influx-enterprise[15148]: Completed 500 in 1.092018ms (Size: 35B | POP: 607.146µs)
```

This is an indication that the migrate command wasn't issued and the enterprise console database schema is not initialized.

Here are the steps to resolve this error:

```
systemctl stop influx-enterprise.service
rm /var/lib/influx-enterprise/*
sudo -u influx-enterprise influx-enterprise migrate --config /etc/influx-enterprise/influx-enterprise.conf
systemctl start influx-enterprise.service
```

**NOTE**: the steps to fix this demand purging the enterprise database so all changes will be lost. However the user wouldn't normally have been able to save anything in the enterprise database at this point because it doesn't work.

**Comment by kgmiles** [comment]
There were 5 shards that I found errors for across the 8 data nodes so I tried to remove them with the commands below.  After this, errors continue with different shard numbers.

Removed shard 75 from 172.18.212.108:8088
Removed shard 75 from 172.18.211.157:8088
Removed shard 77 from 172.18.214.141:8088
Removed shard 77 from 172.18.214.73:8088
Removed shard 78 from 172.18.212.141:8088
Removed shard 78 from 172.18.212.157:8088
Removed shard 79 from 172.18.211.157:8088
Removed shard 79 from 172.18.212.189:8088
Removed shard 83 from 172.18.212.189:8088
Removed shard 83 from 172.18.211.126:8088

**Comment by kgmiles** [comment]
We have several DBs on these nodes but the shards I removed per my last update and the new set I am seeing are all for the same DB.  Barring another idea, I will try dropping that DB, issuing remove-shard on any shards that remain for that DB and recreating the DB.

**Comment by stevebang** [comment]
Discussed with support. The migrate command and console are older functionality and deprecated, so closing this issue.
