### ISSUE TITLE
[Kapacitor] Typo in documents

### ISSUE THREAD

**Issue by gcyre** [influxdata/docs.influxdata.com#968]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.1/nodes/alert_node/#email

###### What products and version are you using?
Kapacitor 
###### Where did you look before opening the issue?

There is a typo in the email example/code snippets

    |alert()
       .id('{{ .Name }}')
       // Email subject
       .meassage('{{ .ID }}:{{ .Level }}') <-- message is spelled wrong
       //Email body as HTML
       .details('''
<h1>{{ .ID }}</h1>
<b>{{ .Message }}</b>
Value: {{ index .Fields "value" }}
''')
       .email()

**Comment by rkuchan** [comment]
Thanks,  @gcyre!  Fixed in https://github.com/influxdata/docs.influxdata.com/pull/982.
