### ISSUE TITLE
mouse wheel scrolling is very slow

### ISSUE THREAD

**Issue by hervenicol** [influxdata/docs.influxdata.com#97]
The main panel is very slow to scroll with the mouse wheel.
On my desktop, one wheel action usually scrolls 1/2 to 1 text page, but on this website it only scrolls 3 to 6 lines of text.

Tested with Firefox 39 / Windows and Firefox 40 / Ubuntu.

**Comment by alexpaxton** [comment]
I'm using this CSS property: `-webkit-overflow-scrolling: touch;` which enables "momentum" scrolling on mobile devices. Haven't tested this in non-webkit browsers but haven't run into this issue before. Might not even be related to the above scrolling property

**Comment by alexpaxton** [comment]
Was able to reproduce slow scrolling in Firefox 41

**Comment by beckettsean** [comment]
@hervenicol we just released an updated design with new CSS. Is scrolling still slow?

**Comment by hervenicol** [comment]
@beckettsean the scrolling is now OK for the docs page.
If you can use the same css for the main page that will be perfect. ;)

**Comment by beckettsean** [comment]
We'll let the marketing team know. The main site is Wordpress, not built from the markdown here.
