### ISSUE TITLE
Update docs link in portal.influxdata.com to v1.2

### ISSUE THREAD

**Issue by sebito91** [influxdata/docs.influxdata.com#977]
###### WTF?
The Docs link on portal.influxdata.com defaults to v1.0 documentation at the above link:
http://docs.influxdata.com/enterprise/v1.0/

Not a biggie, just needs update to v1.2.

**Comment by rkuchan** [comment]
Oh no - thank you, @sebito91. We'll get that fixed now. Keeping this open until it's done.

**Comment by rkuchan** [comment]
Fixed. Thanks again!
