### ISSUE TITLE
not all logstash patterns are supported

### ISSUE THREAD

**Issue by thermionic** [influxdata/docs.influxdata.com#991]
###### URL for relevant page?
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/logparser
"as well as supporting logstash's builtin patterns."
should be "as well as supporting most/many/some of logstash's builtin patterns."

###### What products and version are you using?
Telegraf v1.1.2 (git: release-1.1.0 3da3a2279108d02c2158782794532de7cd7deacd)

###### Where did you look before opening the issue?
https://github.com/influxdata/telegraf/issues/2302

**Comment by timhallinflux** [comment]
Let's add what the limitation is related to lookahead/lookbehind into the logparser plugin.

**Comment by sanderson** [comment]
Resolved by influxdata/telegraf@a50acadc44bbab42d2952d44b2a6ed2f127b346d
