### ISSUE TITLE
Document importance of NTP for source data

### ISSUE THREAD

**Issue by kostasb** [influxdata/docs.influxdata.com#993]
NTP is important for source timestamp precision.
The source will not provide reliable timestamps if it isn’t synchronised with NTP.

Collection agents like Telegraf and servers running applications that produce timestamped data should be synchronized with a reliable NTP server.

**Comment by rkuchan** [comment]
Relevant docs: 

* InfluxDB's FAQ, API reference, both write protocol docs
* Telegraf's input and output data formats (I think) and the troubleshooting page
* Cloud's FAQ page

**Comment by kostasb** [comment]
@rkuchan Agreed, about Telegraf I'd say that input data format is enough since timestamps are assigned at input time.
