### ISSUE TITLE
add-data: operation exited with error: open /tmp/influx-enterprise.key.json: no such file or directory

### ISSUE THREAD

**Issue by Knappek** [influxdata/docs.influxdata.com#997]
###### URL for relevant page?
https://docs.influxdata.com/enterprise/v1.2/production_installation/data_node_installation/ 

###### What products and version are you using?
InfluxDB Enterprise v1.2

###### Where did you look before opening the issue?
google, didn't find anything ;).

###### Issue
I am about to install InfluxDB Enterprise v1.2. I already installed the Meta Nodes, joined them and started them. Now I am trying to to step 2: Data Node Installation. 

When I try to join the Data Nodes to the Cluster with 
`influxd-ctl add-data <fqdn>:8088`
I get the error:

```
add-data: operation exited with error: open /tmp/influx-enterprise.key.json: no such file or directory
```

I don't use the `license-path` but the `license-key` and have it correctly configured in `/etc/influxdb/influxdb-meta.conf`. Though the Data Nodes want to have the json. How can I tell them to use the `license-key`?

**Comment by rkuchan** [comment]
Hi @Knappek, we try to reserve this repo for docs-specific issues. Please contact support at the email provided to you when you signed up for InfluxEnterprise - I know they'll be able to help you!
