### ISSUE TITLE
Note that "time" is a reserved word and should not be used as tag or field key

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/docs.influxdata.com#998]
The keyword "time" will be dropped on any incoming points, which should be noted in the documentation.

**Comment by rkuchan** [comment]
@rossmcdonald - `time` seems to be treated differently from other key words: I can use it as a measurement name without a problem but when I write it as a field or tag key, its data are silently dropped (like you said).

```
# Measurement treatment: time vs. all

> insert time value=1
> select * from time
name: time
time                value
----                -----
1486403076637310944 1

> insert all value=1
> select * from all
ERR: error parsing query: found ALL, expected identifier at line 1, char 15

# Field key treatment: time vs. all

> INSERT whatever all=1
> INSERT whatever time=1
> SELECT * FROM whatever
name: whatever
time                all
----                ---
1486403430399284559 1
```

Is this more of a bug with the database?

**Comment by rossmcdonald** [comment]
@rkuchan The "time" drops should be logged server-side, so they are only silently dropped from the client's perspective. From my perspective the database is operating as intended, as a "time" field/tag key would be indistinguishable from the "time" timestamp when querying (and the database is purposefully stripping the "time" component out before writing the points to disk).

We can also open a feature request to have a message sent back to the client, if you think that would help.

**Comment by rkuchan** [comment]
No, that's fine. I was just curious. I'll get this added!
