### ISSUE TITLE
[Kapacitor] How to doc

### ISSUE THREAD

**Issue by rkuchan** [influxdata/docs.influxdata.com#999]
Start a how-to document.

Some ideas:

* Automate successive queries with Kapacitor (https://www.influxdata.com/tldr-influxdb-tech-tips-june-30-2016/)
* Compare data by changing timestamps (https://www.influxdata.com/tldr-influxdb-tech-tips-june-9-2016/)
* Issues with using multiple-level filters in a TICK-script (https://www.influxdata.com/tldr-influxdb-tech-tips-may-19-2016/)
* When to stream and when to batch (https://www.influxdata.com/tldr-influxdb-tech-tips-may-26-2016/)

Also check out the discussions in Google Groups.

**Comment by nathanielc** [comment]
- How to use alert templates and available vars within the templates. Or possibly a more step by step walk through of the features of the alert node.

**Comment by rkuchan** [comment]
Batch vs. Stream: https://community.influxdata.com/t/batch-versus-stream-processing-combine/792
